engines/python/build.gradle

[ci] Clean up temporary changes in __init__.py

---

serving/docker/deepspeed.Dockerfile

https://github.com/deepjavalibrary/djl-serving/actions/runs/6618217285

Update datasets version in deepspeed.Dockerfile

---

.github/workflows/docker-nightly-publish.yml
serving/docker/docker-compose.yml
serving/docker/scripts/pull_and_retag.sh
serving/docker/tensorrt-llm.Dockerfile

add trtllm container initial commit

add trtllm container build

---

serving/docker/scripts/install_tensorrt.sh
serving/docker/tensorrt-llm.Dockerfile

resolving nccl version mismatch problems

Add TRTLLM TRT build from our managed source

---

engines/python/setup/djl_python/huggingface.py
serving/docker/tensorrt-llm.Dockerfile

install s5cmd to trtllm

---

engines/python/src/main/java/ai/djl/python/engine/Connection.java

Add options:
--bind-to none
-x MKL_DYNAMIC=FALSE

Update mpirun options

---

serving/src/test/java/ai/djl/serving/ModelServerTest.java

Adds this as a required behavior. See #1209

Adds a test for unencoded urls during registration

---

serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/src/main/java/ai/djl/serving/http/Session.java
serving/src/main/java/ai/djl/serving/util/NettyUtils.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Cancel request if client disconnect

---

engines/python/src/main/java/ai/djl/python/engine/PyProcess.java

[python] Update PyProcess to support trtllm

---

engines/python/setup/djl_python/huggingface.py
engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java

[python] Fixes batch error handling.

---

engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java

[python] Make parse_input() backward compatible

---

serving/docs/modes.md

[docs] Fixes serving document

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

Do warmup in multiple requests

---

engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
plugins/cache/src/test/java/ai/djl/serving/cache/CacheEngineTest.java

[python] Update PublisherBytesSupplier API

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

remove unused components

---

serving/docker/deepspeed.Dockerfile
serving/docker/scripts/install_aitemplate.sh

Break the layer build to speedup downloading
Checked with pip dependencies diff, all matching

[DeepSpeed DLC] separate container build with multi-layers

---

.github/workflows/client-test.yml
.github/workflows/continuous.yml
.github/workflows/integration.yml
.github/workflows/pyunit.yml
engines/python/setup/djl_python/transformers_neuronx.py
serving/docker/pytorch-inf2.Dockerfile
serving/docker/scripts/install_inferentia2.sh

Adding 2.15 and it associated handler to 0.24.0 dlc's 

[feat] Add inf2 2.15 sdk and handler to 0.24.0 dlc

---

engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java
serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java

[serving] Adds token latency metric

---

serving/docker/tensorrt-llm.Dockerfile

Add trtllm toolkit in the container

install trtllm toolkit

---

serving/docker/tensorrt-llm.Dockerfile

[TRTLLM] use tensorrt wheel

---

engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
engines/python/setup/djl_python/tensorrt_llm.py
serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-cu118.Dockerfile
serving/docker/pytorch-inf2.Dockerfile
serving/docker/tensorrt-llm.Dockerfile

This begins adding the versions to dockerfiles so they can later be picked up by the DLC pipeline.

Adds versions as labels in dockerfiles

---

serving/docker/tensorrt-llm.Dockerfile

Remove dependencies asked by TRTLLM

[TRTLLM] add trtllm with no deps

---

engines/python/src/main/java/ai/djl/python/engine/TrtLlmUtils.java

Use realtime stream reader for the running process

[TRT partition] add realtime stream reader for the conversion script

---

engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py

[TRTLLM] always setting request output length

---

tests/integration/llm/unmerged_lora.py

update lora model id in correctness test

---

engines/python/src/main/java/ai/djl/python/engine/TrtLlmUtils.java
serving/docker/partition/trt_llm_partition.py

Allowing GPU to be detected with Java parsing

allow gpu detection

---

serving/docker/dockerd-entrypoint-with-cuda-compat.sh
serving/docker/tensorrt-llm.Dockerfile

Add Cudacompat 12.2 to the current container

add trtllm cuda-compat

---

engines/python/setup/djl_python/transformers_neuronx.py

Adding capability to serving.properties for accepting an s3 URI or a relative path directory to a precompiled graph of the model for faster loading.

[feat] Add serving.properties parameter for compiled graph path inf2

---

.github/workflows/llm_inf2_integration.yml
engines/python/setup/djl_python/properties_manager/properties.py
engines/python/setup/djl_python/properties_manager/tnx_properties.py
engines/python/setup/djl_python/tests/test_properties_manager.py
engines/python/setup/djl_python/transformers_neuronx.py
engines/python/setup/setup.py
serving/docker/partition/trt_llm_partition.py
serving/docker/pytorch-inf2.Dockerfile
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Using Pydantic library, to assign the configurations for the handlers. So installed in inf2 containers. And also added unit test cases, so added for python tests requirement.
Todo:
Define a model using pydantic for DJLServing configurations, which makes easy to deprecate configurations. Will do in the next PR.
Test:
Build inf2 container and ran inf2 integration test cases.  https://github.com/deepjavalibrary/djl-serving/actions/runs/6740207548
Added unit test case for pydantic

Inf2 properties refactoring using pydantic

---

serving/docker/tensorrt-llm.Dockerfile

datasets is required for smoothquant calibration

install datasets in trtllm container

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

Add tokenizer check for triton repo

---

engines/python/setup/djl_python/properties_manager/properties.py
engines/python/setup/djl_python/properties_manager/trt_properties.py
engines/python/setup/djl_python/tensorrt_llm.py
engines/python/setup/djl_python/tests/test_properties_manager.py
serving/docker/tensorrt-llm.Dockerfile
wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

TensorRrt Configs refactoring

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

[wlm] Supports model_id point to a local directory

---

engines/python/setup/djl_python/sagemaker.py
serving/src/main/java/ai/djl/serving/ModelServer.java
wlm/build.gradle
wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
wlm/src/main/java/ai/djl/serving/wlm/SageMakerUtils.java
wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java
wlm/src/test/resources/sagemaker/invalid_inference_spec/metadata.yaml
wlm/src/test/resources/sagemaker/invalid_pytorch_model/metadata.yaml
wlm/src/test/resources/sagemaker/pytorch_model/metadata.yaml
wlm/src/test/resources/sagemaker/xgb_model/metadata.yaml

1. Load model and infer engine for SageMaker model format
2. Customized entry point in python engine for SageMaker model format

[SageMaker Galactus developer experience] model load integration to DJL serving

---

serving/docker/tensorrt-llm.Dockerfile

fix pydantic install bug

---

.github/workflows/llm_integration.yml

Add SmoothQuant option in the CI test

add smoothquant as options

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

Testing:
Build a trt container and tested it locally with falcon 7b and passing empty env variables.

Check whether env variable value is empty

---

tests/integration/llm/prepare.py

update smoothquant arg

---

engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py

[python] Adds do_sample support for trtllm

---

serving/docker/partition/utils.py

[partition] extract properties files

---

.github/workflows/llm_inf2_integration.yml
engines/python/setup/djl_python/transformers_neuronx.py
tests/integration/llm/client.py
tests/integration/llm/prepare.py

[CI] TnX load split model llama2 test and fix handler

---

engines/python/setup/djl_python/properties_manager/ds_properties.py
engines/python/setup/djl_python/tests/test_properties_manager.py

Testing:
In Ec2, manually tested AOT with opt 6.7b model

add checkpoint to ds properties

---

serving/docker/tensorrt-llm.Dockerfile

Build with more layers to speed up downloading

[TRTLLM] split further for container layers

---

engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java

[pyton] Recover from python process crash

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py

Improve logging and reduce crashes

[TRTLLM] format better for logging

---

.github/workflows/rolling_batch_integration.yml

[CI] Adding option to run only test we need

---

gradle.properties

[serving] Upgrades AWSSDK version to 2.21.19

---

engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py

Changes the default settings in TRTLLM rolling batch (top_k from 2 to 5 and the temperature from 0.7 to 0.8) to produce higher quality, less repetitive output. Also added default setting for top_p.

Change default top_k and temperature parameters in TRTLLM rolling batch

---

serving/docker/scripts/security_patch.sh
serving/docker/tensorrt-llm.Dockerfile

upgrade some system dependencies

[TRTLLM] CVE fixes

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

This fixes local path issues with TRTLLM

[TRTLLM] fix corner case that model_id point to local path

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
tests/integration/llm/client.py

Calculate max_seq_length in warmup dynamically

---

tests/integration/llm/client.py

Increase memory limit for rolling batch integration octocoder model

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

Allow user to pass in max_batch_prefill_tokens

---

engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py

[TRTLLM] remove default repetition penalty

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

Fix rolling batch properties

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

[0.25.0] Fix rolling batch properties

---

serving/docs/lmi/lmi_environment_variable_instruction.md

[doc] LMI environment variable instruction

---

serving/docs/lmi/tutorials/trtllm_aot_tutorial.md

Adding AOT tutorial to replace placeholder

Add AOT Tutorial

---

serving/docs/lmi/tuning_guides/tnx_tuning_guide.md

[doc] TransformerNeuronX tuning guide

---

serving/docs/lmi/tuning_guides/trtllm_tuning_guide.md

[doc] TensorRt-Llm tuning guide

---

serving/docs/lmi/tuning_guides/deepspeed_tuning_guide.md

[doc] DeepSpeed tuning guide

---

serving/docs/lmi/tuning_guides/lmi_dist_tuning_guide.md

[doc] LMI dist tuning guide

---

serving/docs/large_model_inference.md

[doc] large model inference document

---

engines/python/setup/djl_python/fastertransformer.py

[0.24.0-dlc] Fix for beam width with dynamic batching

---

engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/rolling_batch/deepspeed_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/neuron_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
tools/gradle/python-formatter.gradle

Support `details:true` in the payload to extract log probability, token id and finish reason
```
curl -X POST http://127.0.0.1:8080/invocations -N   -H "Content-typat got Oscar this year","parameters":{"max_new_tokens":50, "do_sample":true, "details":true}}'
{"generated_text": "? I don't understand a single word of it. Lepython knows nothing about movies that don't have subs.
In terms of knowledge, he is a bit like a caged bird. He has a lot of knowledge,", "details": {"finish_reason": "length", "tokens": [{"id": 29973, "text": "?", "log_prob": -4.198227405548096, "special_token": null}, {"id": 306, "text": " I", "log_prob": -6.91507625579834, "special_token": null}, {"id": 1016, "text": " don", "log_prob": -9.707087516784668, "special_token": null}, {"id": 29915, "text": "'", "log_prob": …
```

[UX][RollingBatch] add details function to the rolling batch

---

serving/docker/deepspeed.Dockerfile

[fix] datasets dependency fix for smoothquant

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
engines/python/src/main/java/ai/djl/python/engine/PyModel.java

[python] Sets mpi_model property for python to consume

---

gradle.properties

Bump up DJL version to 0.26.0

---

serving/docker/deepspeed.Dockerfile
serving/docker/tensorrt-llm.Dockerfile

[docker] Avoid JVM consume GPU memory

---

engines/python/src/main/java/ai/djl/python/engine/PyModel.java

[python] Fixes mpi_mode properties

---

engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
serving/docker/tensorrt-llm.Dockerfile

Add TRTLLM details function
Upgrade container as well

[TRTLLM][UX] add trtllm changes to support stop reason and also log prob

---

.github/workflows/docker-nightly-publish.yml
.github/workflows/integration.yml
serving/docker/Dockerfile
serving/docker/README.md
serving/docker/docker-compose.yml
serving/docker/pytorch-gpu.Dockerfile
serving/docker/scripts/pull_and_retag.sh
serving/docker/scripts/security_patch.sh
tests/integration/download_models.sh

Rename GPU container to pytorch-gpu and upgrade cuda

[Docker] upgrade cuda 12.1 support for DJLServing

---

tests/integration/llm/client.py

remove invalid test for streaming

remove invalid test

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[wlm] Fixes get maxWorkers bug for python engine

---

tests/integration/launch_container.sh

[ci] Fixes nightly gpu integration test

---

.github/workflows/lmi-dist-deps-build.yml

fix the lmi-dist deps build pipeline

allow git permission to aws assumed role

---

tests/integration/test_client.sh

[test] Increases curl timeout for test client

---

.github/workflows/llm_inf2_integration.yml
engines/python/setup/djl_python/neuron_utils/__init__.py
engines/python/setup/djl_python/neuron_utils/model_loader.py
engines/python/setup/djl_python/neuron_utils/utils.py
engines/python/setup/djl_python/properties_manager/tnx_properties.py
engines/python/setup/djl_python/stable_diffusion_inf2.py
engines/python/setup/djl_python/tests/test_properties_manager.py
engines/python/setup/djl_python/tests/test_transformers_neuronx.py
engines/python/setup/djl_python/tests/utils.py
engines/python/setup/djl_python/transformers_neuronx.py
serving/docker/partition/partition.py
serving/docker/partition/properties_manager.py
serving/docker/partition/utils.py
serving/docker/pytorch-inf2.Dockerfile
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Updated the NeuronX docker image to 2.15.2 SDK (Moved to https://github.com/deepjavalibrary/djl-serving/pull/1363)
Added new dependency for the DLC [optimum, optimum-neuron]
Added AOT model compilation for neuronx
Added CI/CD testing for transformers neuronx handler
Added Python unit tests for transformers neuronx handler

[feat] optimum handler creation

---

.github/workflows/lmi-dist-deps-build.yml

Fix build source of the content

[LMI-Deps] fix build source

---

.github/workflows/lmi-dist-deps-build.yml

Build megablocks from pipeline

also build megablocks by default

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-inf2.Dockerfile
serving/docker/tensorrt-llm.Dockerfile

[docker] Updates version to 0.26.0

---

engines/python/setup/djl_python/properties_manager/hf_properties.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

[Fix] fix the lmi dist device

---

tests/integration/llm/prepare.py

[CI] update the model to fp16

---

engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
engines/python/setup/djl_python/tests/test_properties_manager.py
serving/docs/lmi/configurations_large_model_inference_containers.md

Support load format for mixtral model on pt checkpoints

[vLLM] add load_format to support for mixtral model

---

.github/workflows/llm_inf2_integration.yml
engines/python/setup/djl_python/neuron_utils/model_loader.py
engines/python/setup/djl_python/properties_manager/sd_inf2_properties.py
engines/python/setup/djl_python/stable_diffusion_inf2.py
engines/python/setup/djl_python/tests/test_properties_manager.py
engines/python/setup/djl_python/tests/test_stable_diffusion_inf2.py
engines/python/setup/djl_python/transformers_neuronx.py
serving/docker/partition/utils.py
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Refactor INF2 stable diffusion handler to use optimum model loader.
Adds stable diffusion 1.5, 2.1, and XL base as both loadable from compiled, and runtime compilation available through handler.
Updates integration testing to test SD 1.5, 2.1, and XL.
Adds unit testing for stable diffusion inf2 handler.

[DLC][TNX] inf2 stable diffusion handler refactor

---

serving/docker/tensorrt-llm.Dockerfile

Build with Ammo for extra dependencies

[TRTLLM] install ammo dependencies for quantization

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

Add config passing in lmi-dist

---

serving/docker/scripts/patch_oss_dlc.sh
serving/docker/tensorrt-llm.Dockerfile

add ammo installation for TRTLLM

[TRTLLM][DLC] install ammo with TRTLLM for runtime compilation

---

awscurl/build.gradle
awscurl/src/main/java/ai/djl/awscurl/AwsCurl.java
awscurl/src/main/java/ai/djl/awscurl/HttpClient.java
awscurl/src/main/java/ai/djl/awscurl/NullOutputStream.java

[awscurl] Removes commons-io and commons-codec dependency

---

.github/workflows/instant_benchmark.yml
tests/integration/record_benchmark.py

This updates the record benchmark script to work better for uploading manual benchmark results.

Record benchmarks for manual

---

serving/docs/large_model_inference.md
serving/docs/lmi/tutorials/trtllm_manual_convert_tutorial.md

Add TRTLLM conversion tutorial manual

[Tutorials] add tensorrt llm manual

---

.github/workflows/client-test.yml
.github/workflows/continuous.yml
.github/workflows/docker-nightly-publish.yml
.github/workflows/integration.yml

[ci] Upgrades CI to use JDK 17

---

serving/docker/pytorch-inf2.Dockerfile

Version bump for optimum neuronx to current release

[DLC][TNX] optimum version bump

---

.github/workflows/rolling_batch_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Add mistral model tests for lmi-dist and vllm

[CI] add mistral model tests

---

engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
engines/python/setup/djl_python/properties_manager/properties.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/tests/test_properties_manager.py

Extracted the properties of lmi-dist rolling batch. 
Testing 
- Tested them in my EC2 machine. 
- Tested in CI using my local branch https://github.com/deepjavalibrary/djl-serving/actions/runs/7279838457

[Refactor] lmi dist rolling batch properties

---

plugins/cache/src/test/java/ai/djl/serving/cache/CacheEngineTest.java
serving/build.gradle
serving/docker/Dockerfile
serving/docs/configurations_global.md
serving/docs/management_api.md
serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
serving/src/test/resources/config.properties
serving/src/test/resources/workflow.config.properties
serving/src/test/resources/workflows/basic.json
serving/src/test/resources/workflows/basic.yaml
serving/src/test/resources/workflows/ensemble.json
serving/src/test/resources/workflows/functions.json
serving/src/test/resources/workflows/localPerf.json
wlm/build.gradle
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

1. Use PyTorch engine for all test
2. No longer install MXNet in docker
3. Makes MXNet a runtime dependencies

[ci] Fixes build issues on aarch64 machine

---

build.gradle

[ci] Suppress javadoc warnings.

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Add two new set of models for support

[TRTLLM][CI] add baichuan and internlm model to the ci for trtllm

---

.github/workflows/continuous.yml
serving/src/test/java/ai/djl/serving/ModelServerTest.java

[ci] Fixes flaky async token test

---

serving/src/test/java/ai/djl/serving/ModelServerTest.java

[ci] Fixes merge conflict issue

---

serving/docker/tensorrt-llm.Dockerfile
tests/integration/llm/prepare.py

[TRTLLM] bump up trtllm to 0.7.0

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Adds TRTLLM ChatGLM to integration testing

[TRTLLM] [CI] Add ChatGLM to trtllm ci

---

engines/python/setup/djl_python/properties_manager/README.md

[doc] instruction on adding new properties to default handlers

---

.github/workflows/llm_integration.yml
tests/integration/llm/prepare.py

[TRTLLM] build with tp1

---

engines/python/setup/djl_python/properties_manager/scheduler_rb_properties.py
engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
engines/python/setup/djl_python/tests/test_properties_manager.py

Testing
- tested rolling_batch_integration.yml in my ec2 machine 
- Added a unit test case for scheduler rolling batch

[Refactor] scheduler rolling batch refactor

---

.github/workflows/lmi-dist-deps-build.yml
.github/workflows/rolling_batch_integration.yml
engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/tests/test_properties_manager.py
serving/docker/deepspeed.Dockerfile
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Support AWQ quantization in LMI Dist

---

.github/workflows/llm_integration.yml
serving/docs/lmi/tutorials/trtllm_aot_tutorial.md
tests/integration/llm/client.py
tests/integration/llm/prepare.py

[TRTLLM] add qwen model to CI

---

tests/integration/llm/prepare.py

Add trust remote code for qwen

[TRTLLM] trust remote code for qwen

---

serving/docker/deepspeed.Dockerfile

Install flash attn v1 and v2 in order

---

engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/tests/test_properties_manager.py
serving/docs/configurations_model.md
serving/docs/lmi/configurations_large_model_inference_containers.md

Remove old flash models in LMI Dist

---

awscurl/src/main/java/ai/djl/awscurl/AwsCurl.java
awscurl/src/main/java/ai/djl/awscurl/HttpClient.java
awscurl/src/main/java/ai/djl/awscurl/JsonUtils.java
awscurl/src/test/java/ai/djl/awscurl/AwsCurlTest.java

[awscurl] Allows search nested json key

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/tests/test_rolling_batch.py

change the output also have generated text

make jsonline outputs generated tokens

---

tests/integration/llm/client.py

Start running batch inference and report benchmark results

[CI] use awscurl for rollingbatch tests

---

.github/workflows/llm_integration_p4d.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

[CI] add trtllm P4D tests

---

serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java

[serving] Loads model zoo and engine from deps folder on startup

---

tests/integration/llm/prepare.py

Patch for failing test - https://github.com/deepjavalibrary/djl-serving/actions/runs/7424437590/job/20204116124
Filed issue upstream - https://github.com/NVIDIA/TensorRT-LLM/issues/825

disable mixtral custom all reduce flag

---

engines/python/build.gradle

[python] Excludes test code from jar

---

.github/workflows/lmi-dist-deps-build.yml

Kill megablocks from the build pipeline

remove megablocks from the list

---

.github/workflows/lmi-dist-deps-build.yml
serving/docker/deepspeed.Dockerfile
serving/docker/scripts/install_python.sh
serving/docker/scripts/security_patch.sh

Upgrade all dependencies to 12.1

[DLC][DeepSpeed] upgrade DeepSpeed container to 12.1

---

.github/workflows/llm_integration_p4d.yml

Fix P4D name builder to use deepspeed container

[CI] fix name builder

---

serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Adds llama.cpp support

---

serving/docker/deepspeed.Dockerfile
tests/integration/llm/prepare.py

Allow trust remote code to PHI

[CI] add trust remote code to phi

---

.github/workflows/instant_benchmark.yml
tests/integration/instant_benchmark.py
tests/integration/record_benchmark.py

This adds more possible source locations for a template besides http, specifically local files and s3://bucketName/key.
This can be used for several purposes. First, it can support debugging and template locally. Afterwards, it can allow more hidden or secure templates.

[CI][IB] Parses template from S3 and local dir

---

.github/workflows/llm_inf2_integration.yml
engines/python/setup/djl_python/neuron_utils/model_loader.py
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Support full rolling batch integration tests for INF2

[CI] add 2 inf2 rolling batch tests

---

.github/workflows/llm_inf2_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

[TNX][CI] setup java for tnx models

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/tests/test_rolling_batch.py
engines/python/setup/djl_python_engine.py

Support customized rollingbatch function

[RollingBatch] add customized rollingbatch

---

gradle.properties
serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/src/main/java/ai/djl/serving/util/NettyUtils.java

[serving] Updates dependencies to latest version

---

serving/src/test/java/ai/djl/serving/ModelServerTest.java
serving/src/test/java/ai/djl/serving/plugins/DependencyManagerTest.java

[serving] Adds logs to ModelServerTest.

---

tests/integration/llm/client.py

update the memory range of a certain model

[CI] update the memory range

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/tests/test_rolling_batch.py

Add request ID fixed in the rolling batch

[RollingBatch] fix request id in rolling batch

---

serving/docker/deepspeed.Dockerfile

[docker] Add lmi_vllm wheel and environment variables

---

serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-inf2.Dockerfile
serving/docker/tensorrt-llm.Dockerfile

Support use case like: https://huggingface.co/docs/transformers/chat_templating for chat template autofilling

add jinja2 for chat completion use case

---

tests/integration/llm/client.py

Fixes the issue with gpt4all-lora mem usage, and refactors the memory checking into a single method with better logging and error details.
Run in progress here https://github.com/deepjavalibrary/djl-serving/actions/runs/7508500077/job/20444097774

[ci] add information to memory assert in lmi integ tests

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

[LMIDist] Allow passing in ignore_eos_token param

---

serving/docker/deepspeed.Dockerfile

[docker] Upgrade aiccl version to 1.1

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

[LMIDist] Make ignore_eos_token default to false

---

gradle.properties
serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-gpu.Dockerfile
serving/docker/pytorch-inf2.Dockerfile
serving/docker/tensorrt-llm.Dockerfile

Updates DJL version to 0.27.0

---

engines/python/src/main/java/ai/djl/python/engine/Connection.java

Makes netty buffer size configurable

---

plugins/management-console/webapp/package.json

[console] Updates axios to 1.6.5

---

engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
serving/docs/lmi/lmi_input_output_schema.md

Translating a few params in vLLM and TRTLLM handlers into HuggingFace format. https://huggingface.co/docs/transformers/v4.37.0/en/main_classes/text_generation#transformers.GenerationConfig

translate few vllm and trtllm params to HF format

---

tests/integration/llm/prepare.py

Test different possible options for rolling batch for trt-llm backend to catch issues like - https://github.com/deepjavalibrary/djl-serving/pull/1501

test different options of rolling batch option for trt-llm

---

serving/src/test/java/ai/djl/serving/ModelServerTest.java

[test] print http message when assertion fail

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

Cherry-pick #1501 to release branch

Fix trtllm check logic (

---

serving/src/test/java/ai/djl/serving/ModelServerTest.java

[serving] Fixes flaky unittest

---

engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java

check for rolling batch "disable" value

---

.github/workflows/instant_benchmark.yml
serving/src/test/java/ai/djl/serving/ModelServerTest.java
tests/integration/record_benchmark.py

This enables support to save the results of a benchmark to cloudwatch. It can be enabled to add a test for regressions

[CI][IB] Supports cloudwatch saving

---

serving/docs/lmi/configurations_large_model_inference_containers.md

[doc] fix vllm engine

---

.github/workflows/client-test.yml
.github/workflows/codeql-analysis-java.yml
.github/workflows/continuous.yml
.github/workflows/docker-nightly-publish.yml
.github/workflows/instant_benchmark.yml
.github/workflows/integration.yml
.github/workflows/llm_inf2_integration.yml
.github/workflows/llm_integration.yml
.github/workflows/llm_integration_p4d.yml
.github/workflows/lmi-dist-deps-build.yml
.github/workflows/lmic_performance.yml
.github/workflows/nightly-docker-ecr-sync.yml
.github/workflows/pyunit.yml
.github/workflows/rolling_batch_integration.yml
.github/workflows/sagemaker-integration.yml

[ci] Upgrade github actions nodejs 16 to nodejs 2

---

build.gradle
serving/src/test/java/ai/djl/serving/ModelServerTest.java

[test] Fixes model server flaky test

---

engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_neuron_scheduler.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/token_selector.py
tests/integration/llm/README.md

Fix Neuron log probs calculation

[Neuron][WIP] add log probs calulation in Neuron

---

.github/workflows/publish-job-success.yml
.github/workflows/sagemaker-integration.yml

[ci] Upgrade aws-actions/configure-aws-credentials to v4

---

serving/src/test/java/ai/djl/serving/ModelServerTest.java

[serving] Fixes testThrottle() flaky test

---

engines/python/setup/djl_python/properties_manager/sd_inf2_properties.py
engines/python/setup/djl_python/properties_manager/tnx_properties.py
engines/python/setup/djl_python/tests/test_transformers_neuronx.py
engines/python/setup/djl_python/transformers_neuronx.py

This PR fixes the integration for NeuronRollingBatch and the jsonlines output formatter.

[fix] NeuronRollingBatch jsonlines integration

---

.github/workflows/lmi-dist-deps-build.yml

Support the new speculative decoding feature with vLLM and 0.3.1 versions.
@zachgk @ymwangg

[CI] add vllm 0.3.1 into deps build

---

engines/python/setup/djl_python/inputs.py
engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/test_model.py
engines/python/setup/djl_python/tests/rolling_batch/__init__.py
engines/python/setup/djl_python/tests/rolling_batch/fake_rolling_batch.py
engines/python/setup/djl_python/tests/test_input_output.py
engines/python/setup/djl_python/tests/test_test_model.py
engines/python/setup/setup.py
serving/docker/partition/trt_llm_partition.py

Create an engine that everyone can simply iterate with and playing around without using model server

[Test] build test handler

---

serving/docs/lmi_new/README.md
serving/docs/lmi_new/deployment_guide/model-artifacts.md
serving/docs/lmi_new/user_guides/vllm_user_guide.md

Add vLLM docs following the doc structure

[Docs] vllm docs

---

.github/workflows/lmi-dist-deps-build.yml

change the order of build to make vllm all the way to the end.

[CI][Deps build] upgrade torch to 2.1.2

---

serving/docker/pytorch-inf2.Dockerfile
serving/docker/scripts/install_inferentia2.sh

Upgrade TNX container to 2.17.0 SDK

[docker][TNX] Upgrade to 2.17.0 SDK

---

awscurl/src/main/java/ai/djl/awscurl/AwsCurl.java
awscurl/src/main/java/ai/djl/awscurl/HttpClient.java
awscurl/src/main/java/ai/djl/awscurl/JsonUtils.java
awscurl/src/main/java/ai/djl/awscurl/Result.java

[awscurl] Refactor time to first byte calculation

---

serving/docs/lmi_new/deployment_guide/model-artifacts.md
serving/docs/lmi_new/user_guides/trt_llm_user_guide.md

TRT-LLM docs following the new doc structure

[Docs]TRT-LLM user guide

---

serving/docs/lmi_new/user_guides/deepspeed_user_guide.md

[docs] add deepspeed user guide

---

serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java

This should hopefully resolve a flaky failure in testAsyncInference()

Stream returns only after putting placeholder finishes

---

serving/docker/deepspeed.Dockerfile

[CVE] patch datasets package

---

serving/docs/lmi_new/user_guides/lmi-dist_user_guide.md

[docs] Add lmi-dist user guide

---

serving/src/main/java/ai/djl/serving/ModelServer.java

[serving] Fixes HF_REVISION env variable

---

serving/docs/lmi_new/deployment_guide/model-artifacts.md
serving/docs/lmi_new/user_guides/tnx_user_guide.md

Add the user guid for TransformersNeuronX LMI containers

[docs] TNX user guide

---

serving/src/test/java/ai/djl/serving/ModelServerTest.java
wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
wlm/src/main/java/ai/djl/serving/wlm/util/EventManager.java
wlm/src/main/java/ai/djl/serving/wlm/util/ModelServerListener.java
wlm/src/main/java/ai/djl/serving/wlm/util/ModelServerListenerAdapter.java

[serving] Adds model event listener

---

serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/models/ModelManager.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Add model loading metrics

---

engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py

Adds type hints and comments for scheduler rolling batch.

type hints for scheduler rolling batch

---

serving/docs/lmi_new/README.md
serving/docs/lmi_new/user_guides/README.md
serving/docs/lmi_new/user_guides/tensorrt-llm_user_guide.md
serving/docs/lmi_new/user_guides/transformers-neuronx_user_guide.md

Adding a README for the user guides to provide an overview of the information covered. Also deleted unused user guides

[docs] add readme for user guides, remove unused user guides

---

serving/docker/deepspeed.Dockerfile
serving/docker/tensorrt-llm.Dockerfile

[docker] Fixes typo in java properties

---

.github/workflows/lmi-dist-deps-build.yml
serving/docker/deepspeed.Dockerfile

update vllm to 0.3.2

---

engines/python/src/main/java/ai/djl/python/engine/PyModel.java
engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Uses model.intProperty() api

---

.github/workflows/rolling_batch_integration.yml

Test is failing after transformers upgrade
https://github.com/deepjavalibrary/djl-serving/actions/runs/8044419773/job/21968040041. (transformers [PR](https://github.com/huggingface/transformers/pull/27931/files)).
We should add test after the model is updated or find a new model. Removing for now to unblock testing

Remove test as the model is incompatible with transformers upgrade

---

engines/python/setup/djl_python/test_model.py
engines/python/setup/djl_python/tests/test_input_output.py
serving/docs/lmi_new/deployment_guide/testing-custom-script.md

add test model tutorials

---

engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java
serving/docs/configurations_model.md
serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/src/main/java/ai/djl/serving/models/ModelManager.java
serving/src/test/resources/identity/serving.properties
wlm/src/main/java/ai/djl/serving/wlm/BatchAggregator.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Uses dimension for model metric

---

engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
engines/python/setup/djl_python/tests/test_properties_manager.py

Fix AWQ OOM problems through turning on Eager mode

[vLLM] fix awq OOM issue due to CUDA compat

---

engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
tests/integration/llm/prepare.py

Record acceptance rate for Speculative decoding

[SD][vLLM] record acceptance

---

build.gradle
engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
serving/docs/configurations.md

[docs] Updates offline mode document

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/tests/test_rolling_batch.py

Adds generated token count to the output when details are requested

[lmi] add generated token count to details

---

awscurl/README.md

[awscurl] add download steps to README.md

---

serving/docs/lmi/lmi_environment_variable_instruction.md
serving/docs/lmi/tutorials/trtllm_aot_tutorial.md
serving/docs/lmi_new/deployment_guide/configurations.md
serving/docs/lmi_new/deployment_guide/deploying-your-endpoint.md
serving/docs/lmi_new/deployment_guide/testing-custom-script.md
serving/docs/lmi_new/user_guides/deepspeed_user_guide.md
serving/docs/lmi_new/user_guides/lmi-dist_user_guide.md
serving/docs/lmi_new/user_guides/tnx_user_guide.md
serving/docs/lmi_new/user_guides/trt_llm_user_guide.md
serving/docs/lmi_new/user_guides/vllm_user_guide.md

[docs] Update OPTION_MODEL_ID usage

---

serving/docs/workflow_templates.md
serving/src/main/java/ai/djl/serving/workflow/WorkflowDefinition.java
serving/src/main/resources/workflowTemplates/adapter.json
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

Also switches workflow templates form $var to {var}.

Use workflow template for workflow model_dir

---

serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-gpu.Dockerfile
serving/docker/tensorrt-llm.Dockerfile

Support with 535 driver per sagemaker requirement

support cuda driver on sagemaker

---

serving/docker/scripts/security_patch.sh

Add pytorch-gpu for security patching

---

engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
engines/python/setup/djl_python/tests/test_properties_manager.py
tests/integration/llm/prepare.py

With CUDA driver upgrade, we no longer need this hack

remove checker for awq with enforce eager

---

serving/docker/tensorrt-llm.Dockerfile

Brief description of what this PR is about: Updates dockerfile to build 0.27.0 version container with TRT-LLM v0.8.0.

Update TRT-LLM Dockerfile for v0.8.0

---

tests/integration/llm/prepare.py

Reduce the GPU memory util for draft model impact

[vLLM] reduce speculative decoding gpu util to leave room for draft model

---

engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java

[python] Encode error in single line for jsonlines case.

---

.github/workflows/lmi-dist-deps-build.yml
serving/docker/deepspeed.Dockerfile

Update the vLLM branch and build

Update the build script to use vLLM 0.3.3

---

engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_v2_rolling_batch.py

Update lmi-dist rolling batch to use rubikon engine

Update lmi-dist rolling batch to use rubikon engine

---

.github/workflows/llm_integration.yml

[ci][fix] remove no code test from stop runner condition

---

tools/gradle/publish.gradle

[ci] Publish prometheus to maven

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_v2_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/neuron_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
engines/python/setup/djl_python/tests/test_rolling_batch.py

Sending all details information to output formatter just for further processing. Making tokenizer reachable from rollingbatch class.
@sindhuvahinis @siddvenk

add customer required field

---

.github/workflows/lmi-no-code.yml
tests/integration/llm/client.py

Adding new no-code test suite. Right now, the tests only run against the lmi container.
I will add trt container to the tests as well, but i'm currently working through some issues there in the toolkit level. Not exactly sure what is happening with trt (worked in 0.7, now something is wrong with 0.8).
Test run https://github.com/deepjavalibrary/djl-serving/actions/runs/8363073653/job/22895293922

[ci][lmi] add new no code tests

---

engines/python/setup/djl_python/neuron_utils/model_loader.py
engines/python/setup/djl_python/neuron_utils/utils.py
engines/python/setup/djl_python/tests/test_stable_diffusion_inf2.py
engines/python/setup/djl_python/tests/test_transformers_neuronx.py
engines/python/setup/djl_python/tests/utils.py
engines/python/setup/djl_python/transformers_neuronx.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_modeling.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_neuron_scheduler.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/token_selector.py
serving/docker/partition/utils.py
serving/docker/pytorch-inf2.Dockerfile

Update optimum to v0.0.20 and separate our generation model code from optimums. This matches the behavior from 0.0.16 optimum and allows us to use the same adapter for TNX and Optimum loaded models.

[tnx] bump optimum version

---

.github/workflows/codeql-analysis-java.yml
plugins/cache/.gitignore
plugins/cache/build.gradle

[cache] Updates DynamoDBLocal to 2.3.0

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_v2_rolling_batch.py

* Update lmi_dist handler to account for engine's `Request` api change
* Adds `adapters` as an arg to `LmiDistRollingBatch.inference()`
* Fixes bug in `temperature` param which was setting it to either 0 or 1 and overriding user-provided value
```
$ ./gradlew dockerDeb
$ docker cp build/distributions/djl-serving_0.27.0\~SNAPSHOT-1_all.deb `docker ps -q`:/tmp
$ dpkg -i /tmp/djl-serving_0.27.0~SNAPSHOT-1_all.deb
$ cat /tmp/model_dir/serving.properties
option.model_id=TheBloke/Llama-2-13B-fp16
option.task=text-generation
option.dtype=fp16
option.tensor_parallel_degree=2
option.rolling_batch=lmi-dist
option.max_rolling_batch_size=32
$ CUDA_VISIBLE_DEVICES=0,1 djl-serving -m /tmp/model_dir/
$ docker exec -it `docker ps -q` curl -X POST http://127.0.0.1:8080/invocations -H "Content-type: …
```

[fix] Update lmi_dist handler to account for engine's Request api change, adapters fix and temperature param fix

---

.github/workflows/lmi-dist-deps-build.yml
serving/docker/deepspeed.Dockerfile

Updated the dependencies to use LMI-Dist as default

updated dependencies for LMI

---

plugins/cache/build.gradle

[cache] Remove gson from fatjar of cache

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/rolling_batch/deepspeed_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_v2_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/neuron_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
engines/python/setup/djl_python/tensorrt_llm.py
engines/python/setup/djl_python/tests/rolling_batch/fake_rolling_batch.py
engines/python/setup/djl_python/tests/rolling_batch_test_scripts/lmi-specdec.py
engines/python/setup/djl_python/tests/rolling_batch_test_scripts/lmi_runner.py
engines/python/setup/djl_python/tests/test_lmi_dist.py
engines/python/setup/djl_python/tests/test_rolling_batch.py
engines/python/setup/djl_python/transformers_neuronx.py
engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java

[python] Move output formatter to request level

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

[wlm] Makes generateHuggingFaceConfigUri public

---

engines/python/setup/djl_python/transformers_neuronx.py

Fix for output formatter to params feature for inferentia

[tnx] fix output formatter as param implementation

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/tests/test_rolling_batch.py
serving/docker/scripts/install_djl_serving.sh

Make parameter accessible for output formatter

add parameters to part of the field

---

engines/python/setup/djl_python/deepspeed.py

output_formatter bug fix

---

engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_neuron_scheduler.py
serving/docs/lmi/user_guides/lmi_input_output_schema.md

[Optimum] Change the default value of temperature

---

.github/workflows/rolling_batch_integration.yml
engines/python/setup/djl_python/properties_manager/hf_properties.py
engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
engines/python/setup/djl_python/properties_manager/properties.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
tests/integration/llm/prepare.py

Add lora support in lmi-dist. Necessary changes on the engine side have been made.
Was waiting for https://github.com/deepjavalibrary/djl-serving/pull/1651 to be merged to create this PR to avoid merge conflicts for either PR, so got little late.

Add lora support in lmi-dist

---

serving/docker/partition/utils.py

Extract all djl_python files for partition. The list has grown to the point where i don't think it makes sense to restrict which files are extracted.
Alternatively, we could use a deny-list to exclude certain files from being extracted rather than an allow list

[fix][partition] fix partition script due to missing python files

---

.github/workflows/rolling_batch_integration.yml

Fixes - https://github.com/deepjavalibrary/djl-serving/actions/runs/8456124722/job/23165231351

install huggingface_hub for lmi-dist lora test

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Allows use OPTION_ENGINE env var

---

serving/docker/partition/trt_llm_partition.py

fix a bug in partition

---

engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py

[lmi-dist]validate usage lora and speculative together

---

tests/integration/launch_container.sh

1. `total_retries` was not being assigned correctly, fixing that

Fix incorrect assignment in shell script

---

serving/docker/partition/sm_neo_trt_llm_partition.py
serving/docker/tensorrt-llm.Dockerfile

This PR is adding an additional environment variable to be recognized by the SageMaker Neo partition script, and passed into the toolkit. It also adds `graphviz` to the TRT-LLM Dockerfile.

[TRTLLM] Add env var for Neo cache

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Separate download draft model from downloadS3()

---

benchmark/README.md
benchmark/snapcraft/snapcraft.yaml
engines/python/README.md
serving/docker/README.md
serving/src/test/java/ai/djl/serving/plugins/DependencyManagerTest.java
wlm/README.md

Upgrade to DJL 0.27.0

---

engines/python/setup/djl_python/rolling_batch/deepspeed_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py

rolling batch with details=True is broken for these two backends without this functionality

add get_tokenizer for ds and scheduler rolling batch

---

.github/workflows/llm_integration.yml
.github/workflows/rolling_batch_integration.yml
engines/python/setup/djl_python/huggingface.py
tests/integration/llm/client.py
tests/integration/llm/prepare.py

This adds some additional testing for more unmerged adapter cases in both vllm and lmi_dist. It also makes the handler return an error on invalid or removed adapters rather than falling back to the base model.

Adds additional adapter tests

---

engines/python/setup/djl_python/deepspeed.py

Tested on ec2 for gpt4all-lora model, it works now.

fix typo in ds handler for lora models

---

.github/workflows/rolling_batch_integration.yml

Fixes https://github.com/deepjavalibrary/djl-serving/actions/runs/8487695743/job/23255835248

[fix] install huggingface_hub for vllm lora test

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-gpu.Dockerfile
serving/docker/pytorch-inf2.Dockerfile

[docker] Updates version to 0.27.0

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/tests/test_rolling_batch.py

[python] Fix chat completions logprobs output

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py
tests/integration/llm/client.py

[fix] Fix logprobs format in chat completions

---

.github/workflows/lmi-no-code.yml

[ci][lcnc] do not skip jobs if previous job fails

---

engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_neuron_scheduler.py

[python] Set repetition_penalty from presence_penalty in chat completions

---

engines/python/setup/djl_python/tensorrt_llm.py
engines/python/setup/djl_python/tensorrt_llm_python.py
engines/python/setup/djl_python/utils.py

To support log_probs in TensorRT-LLM in details for T5.

[TRTLLM] T5 python backend log_probs support

---

engines/python/setup/djl_python/inputs.py
engines/python/setup/djl_python/outputs.py
engines/python/setup/djl_python/test_model.py
engines/python/src/main/java/ai/djl/python/engine/CodecUtils.java

[python] Allows send more than 32k utf-8 string

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

Create logic to check machine type from given cuda information

[WIP][Do Not Merge]check for machine type from given information

---

engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py

Do not translate presence_penalty in TRTLLM because presence_penalty is supported.

[trtllm] Do not translate presence_penalty in TRTLLM

---

tests/integration/llm/client.py

[fix] Fix integration test for chat completions

---

engines/python/setup/djl_python/neuron_utils/model_loader.py
engines/python/setup/djl_python/properties_manager/tnx_properties.py
engines/python/setup/djl_python/rolling_batch/neuron_rolling_batch.py
engines/python/setup/djl_python/tests/test_properties_manager.py
engines/python/setup/djl_python/tests/test_transformers_neuronx.py
engines/python/setup/djl_python/transformers_neuronx.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_modeling.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_neuron_scheduler.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/slot.py
serving/docker/pytorch-inf2.Dockerfile
serving/docker/scripts/install_inferentia2.sh
tests/integration/llm/prepare.py

Update Neuron SDK to 2.18.0, fix integration with updated artifacts.
Added safetensor model loading support
The NeuronGenerator has been moved to an abstract class that implements continuous batching, and niave rolling batch (recalculating prefill for all models every time) for models that don't fully support continuous batching. This also allows for speculative decodings generator to fit into this structure better.

[neuron] Update to 2.18.0 SDK

---

engines/python/setup/djl_python/tensorrt_llm_python.py
engines/python/setup/djl_python/utils.py

Keeping all the handler's parse_input signature to be the same. 
Testing:
Tested manually with t5 model

fix parse_input signature for backward compatibility

---

serving/docs/lmi/conceptual_guide/lmi_engine.md

[docs] Update LMI conceptual guide

---

serving/docs/lmi/deployment_guide/model-artifacts.md

Update model-artifacts doc with snapshot download

[doc] Add snapshot download to storing models in s3 doc

---

awscurl/src/main/java/ai/djl/awscurl/AwsCurl.java
awscurl/src/main/java/ai/djl/awscurl/Result.java

[awscurl] Add p50 to TTFB

---

serving/docs/lmi/user_guides/lmi_input_output_schema.md

[docs][lmi] update input/output schema doc

---

serving/docs/lmi/deployment_guide/testing-custom-script.md

Tested the example in my g5.12x machine. Could not run lmi-dist testing standalone, because getting particular version of glibc not present, even after installing the wheel manually. 
Todo:
In the future, we could add another `extras_require` in out setup.py which installs the necessary wheels to test these default handlers. But that might not solve the glibc version problem.

[doc] update testing_custom_script.md

---

.github/workflows/llm_integration.yml
.github/workflows/lmi-no-code.yml
engines/python/setup/djl_python/tensorrt_llm_python.py
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Added integration test cases for python backend of TRTLLM. For both pre-compiled model and JIT compilation.

[T5] Add integration test cases

---

.github/workflows/lmi-no-code.yml

Add g6 in the matrix selection

test lcnc on g6

---

serving/docs/lmi/deployment_guide/benchmarking-your-endpoint.md

[Docs]Add link to configuration in benchmarking doc

---

engines/python/setup/djl_python/neuron_utils/model_loader.py
engines/python/setup/djl_python/neuron_utils/utils.py
engines/python/setup/djl_python/properties_manager/tnx_properties.py
engines/python/setup/djl_python/rolling_batch/neuron_rolling_batch.py
engines/python/setup/djl_python/tests/test_properties_manager.py
engines/python/setup/djl_python/tests/test_transformers_neuronx.py
engines/python/setup/djl_python/transformers_neuronx.py
serving/docker/pytorch-inf2.Dockerfile

Add in the support for safetensors loading to the aot partition methods, add a compile only option for just creating neff files, and add model artifacts schema selection to configuration properties.

[tnx] add safetensor loading for aot compilation

---

.github/workflows/lmi-no-code.yml

We are testing flan-t5-xxl in Large model integration test.

Test t5-xl for lcnc

---

awscurl/src/main/java/ai/djl/awscurl/JsonUtils.java
awscurl/src/test/java/ai/djl/awscurl/AwsCurlTest.java

[awscurl] Support OpenAI style response

---

serving/docs/lmi/README.md
serving/docs/lmi/user_guides/README.md
serving/docs/lmi/user_guides/hf_accelerate.md

Adds the HuggingFace Accelerate backend user guide.

[docs][lmi] add huggingface accelerate user guide

---

serving/docs/lmi/README.md
serving/docs/lmi/deployment_guide/README.md
serving/docs/lmi/deployment_guide/deploying-your-endpoint.md
serving/docs/lmi/user_guides/starting-guide.md

Adds the lcnc guide, which I have called the starting guide.

[docs][lcnc] update documentation with lcnc user journey

---

engines/python/setup/djl_python/transformers_neuronx.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_neuron_scheduler.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/slot.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/token_selector.py

Move parse inputs to global input parser and support seed for token selection.

[tnx] support parse input func and seed param

---

serving/docker/deepspeed.Dockerfile
serving/docker/tensorrt-llm.Dockerfile

Add blobfile as tiktoken dependency

add blobfile as dependency

---

tests/integration/llm/prepare.py

[CI] add extra wait time for TRTLLM conversion

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py

[chat] Add role for the first token in the chat completions streaming response

---

serving/docker/pytorch-inf2.Dockerfile

Add Tiktoken and blobfile support

[DLC] installing tiktoken and blobfile for TNX

---

serving/docs/lmi/user_guides/chat_input_output_schema.md

[doc] Add chat completions input output schema doc

---

engines/python/setup/djl_python/transformers_neuronx.py
serving/docker/pytorch-inf2.Dockerfile

[tnx] upgrade neuron sdk to 2.18.1

---

tests/integration/llm/client.py
tests/integration/llm/prepare.py

Improving lora test coverage
* test tp > 1
* test variable input lengths

update lora test to tp=max and variable prompt lengths

---

awscurl/src/main/java/ai/djl/awscurl/HttpClient.java
awscurl/src/test/java/ai/djl/awscurl/AwsCurlTest.java
awscurl/src/test/java/ai/djl/awscurl/TestHttpHandler.java

[awscurl] Support TGI response with coral streaming

---

.github/workflows/continuous.yml
engines/python/build.gradle

[python] Exclude kv_cache*.pt from release

---

awscurl/src/test/java/ai/djl/awscurl/AwsCredentialsTest.java
benchmark/src/main/java/ai/djl/benchmark/AbstractBenchmark.java
serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
serving/src/test/resources/emptyStore.config.properties
serving/src/test/resources/model_id.config.properties
serving/src/test/resources/zoomodel2/serving.properties
wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java

[serving] Fixes HF_MODEL_ID conflict with djl:// URL issue

---

gradle.properties
serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-gpu.Dockerfile
serving/docker/tensorrt-llm.Dockerfile

Updates DJL version to 0.28.0

---

engines/python/setup/djl_python/neuron_utils/model_loader.py
engines/python/setup/djl_python/properties_manager/tnx_properties.py
engines/python/setup/djl_python/tests/test_properties_manager.py

Enable passthrough access to more neuron config options.

[tnx] adding additional neuron config options

---

serving/docker/pytorch-inf2.Dockerfile
wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java

[serving] Refactor rolling batch detection logic

---

engines/python/setup/djl_python/neuron_utils/model_loader.py
engines/python/setup/djl_python/properties_manager/tnx_properties.py
engines/python/setup/djl_python/tests/test_properties_manager.py

(cherry picked from commit f535d4597692d17818d4c91fc8f43756ce603c02)
Cherry pick adding support for neuron config parameters

[tnx] adding additional neuron config options (#1777)

---

awscurl/src/main/java/ai/djl/awscurl/HttpClient.java

[awscurl] Fix output for server sent event content-type

---

engines/python/setup/djl_python/tests/test_properties_manager.py

Refactoring to parameterized test cases for the error cases, as it reduces the duplicate code and also makes it more readable. 
For other test cases, making it parameterized test cases does not make it more readable.

Refactor properties error test cases to parameterized

---

serving/docker/pytorch-inf2.Dockerfile

Add a neuron compatible vllm 4.0 wheel to the Neuron LMI container.

[tnx] add vllm to container

---

wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java

[wlm] Avoid using gated model for testing

---

serving/docker/scripts/install_djl_serving.sh
serving/src/main/java/ai/djl/serving/plugins/FolderScanPluginManager.java
serving/src/main/java/ai/djl/serving/util/ConfigManager.java

[serving] Avoid unecessary copy plugin jars.

---

.github/workflows/trtllm-deps-build.yml

[CI] add trtllm workflow pipeline

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

Override user-agent for hf config requests. I'll need a separate PR for the 0.27.0 patch since this code has been refactored since then

set user-agent for hf requests

---

serving/build.gradle
serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-gpu.Dockerfile
serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java
serving/src/test/java/ai/djl/serving/plugins/DependencyManagerTest.java

[docker] Install onnxruntime in docker

---

.github/workflows/trtllm-deps-build.yml

Granting permission to the trtllm build pipeline

[CI][TRTLLM] setting up permission to retrieve from repo

---

tests/integration/llm/client.py

Fix the CI with more recognition of files

add fixes for huggingface accelerate CI

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

[trt][lmi] always set mpi mode for trt container

---

serving/docker/partition/sm_neo_neuron_partition.py
serving/docker/partition/sm_neo_utils.py

Adds some additional logging for the Neo partition scripts. logging.debug lines are currently inaccessible; the ability to change the log level will be added in the future.

[Neo] Add more logging to Neo Neuron partition script

---

engines/python/src/main/java/ai/djl/python/engine/PyModel.java
plugins/static-file-plugin/src/main/java/ai/djl/serving/plugins/staticfile/StaticFileHandler.java
serving/src/main/java/ai/djl/serving/plugins/PropertyFilePluginMetaDataReader.java
serving/src/main/java/ai/djl/serving/workflow/WorkflowDefinition.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
serving/src/test/java/ai/djl/serving/WorkflowTest.java
wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java
wlm/src/test/java/ai/djl/serving/wlm/WorkLoadManagerTest.java

[serving] Uses Utils.openUrl() to download files

---

serving/docker/docker-compose.yml
serving/docker/lmi.Dockerfile

[CI] fix CI in LMI container build

---

tests/integration/llm/prepare.py

[CI] Disable rolling batch for hf acc tests

---

engines/python/setup/djl_python/chat_completions/chat_properties.py
engines/python/setup/djl_python/properties_manager/hf_properties.py
engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
engines/python/setup/djl_python/properties_manager/properties.py
engines/python/setup/djl_python/properties_manager/sd_inf2_properties.py
engines/python/setup/djl_python/properties_manager/tnx_properties.py
engines/python/setup/djl_python/properties_manager/trt_properties.py
engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
engines/python/setup/djl_python/tests/test_properties_manager.py

Migrating to pydantic v2 from v1 for all of our properties manager.

Migrate to pydantic v2

---

serving/docker/lmi.Dockerfile
serving/docker/tensorrt-llm.Dockerfile

replace peft with open source version

---

serving/docker/pytorch-inf2.Dockerfile

Fixing the pip install in the inf2 container to properly retrieve the version for torchvision

[fix] inf2 container fix torchvision install

---

.github/workflows/llm_integration.yml
serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/lmi.Dockerfile
serving/docker/pytorch-gpu.Dockerfile
serving/docker/pytorch-inf2.Dockerfile
serving/docker/scripts/install_djl_serving.sh
serving/docker/tensorrt-llm.Dockerfile
tests/integration/llm/client.py
tests/integration/llm/prepare.py

change the CI to use corretto Java 17

use corretto java

---

tests/integration/benchmark/nightly/g5-2xl.txt
tests/integration/instant_benchmark.py

[CI][IB] fix tests

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

Java model may package config.json as well

[wlm] Fixed engine detection logic

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Support set arguments via env var

---

tests/integration/instant_benchmark.py

Let error message popping out instead of continue execution

[CI][IB] fail instance benchmark if a single command failed

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

fix test profiles

---

engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/slot.py

[chat] Remove unused parameters

---

serving/docker/scripts/docker_name_builder.sh
tests/integration/llm/client.py
tests/integration/llm/prepare.py
tests/integration/rb_client.py
tests/integration/tests.py

This creates a new container test runner system through pytest. The intention is that it will be merged into usage as part of the github actions testing in later PRs

Creates container test runner

---

.github/workflows/rolling_batch_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

remove open llama lmi test

---

.github/workflows/instant_benchmark.yml

Update the running script and use latest awscurl

[IB] fixing bugs and update awscurl

---

engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/tensorrt_llm.py
engines/python/setup/djl_python/tensorrt_llm_python.py
engines/python/setup/djl_python/transformers_neuronx.py
engines/python/setup/djl_python/utils.py

- DeepSpeed handler is not refactored, since it is going to be deprecated. 
Tested vllm, huggingface and tensorrt llm handlers with gpt2 model.

Refactor parse_input for handlers

---

awscurl/src/main/java/ai/djl/awscurl/AwsCurl.java
awscurl/src/test/java/ai/djl/awscurl/AwsCurlTest.java

[awscurl] Adds seed and test duration

---

engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_neuron_scheduler.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/slot.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/token_selector.py

Add in last fix for chat completions, additionally adds stop token ids support and ignore eos tokens.

[0.27.0-DLC][cherrypick][tnx] 0.27.0 dlc chat completions fix (#1848)

---

benchmark/src/main/java/ai/djl/benchmark/Arguments.java
benchmark/src/main/java/ai/djl/benchmark/NDListGenerator.java

[djl-bench] Uses Shape.parseShapes()

---

awscurl/src/main/java/ai/djl/awscurl/AwsCurl.java

Update the description of duration

fix the comments in awscurl

---

tests/integration/llm/prepare.py

Updated the Falcon compiled model

[CI] update the falcon model for TRTLLM

---

serving/docs/configurations_global.md
serving/docs/configurations_model.md

[docs] Updates model server configuration document

---

serving/docker/partition/partition.py
serving/docker/partition/sm_neo_neuron_partition.py
serving/docker/partition/sm_neo_utils.py

Cherrypick the latest neo update for the final 0.27.0 inf2 container release.

[0.27.0-DLC][cherrypick][tnx] 0.27.0 neo script update (#1854)

---

serving/docker/lmi.Dockerfile

Bump up dependencies version and release with new vLLM.
@davidthomas426

update container for LMI

---

tests/integration/benchmark/nightly/g5-12xl.txt
tests/integration/benchmark/nightly/g5-2xl.txt

[CI] Fixes too many TOKENIZER in nightly bench llama

---

awscurl/src/main/java/ai/djl/awscurl/AwsCurl.java
awscurl/src/test/java/ai/djl/awscurl/AwsCurlTest.java
awscurl/src/test/resources/prompts/prompt2.txt

[awscurl] Adds extra parameters to dataset

---

awscurl/src/main/java/ai/djl/awscurl/AwsCurl.java
awscurl/src/main/java/ai/djl/awscurl/Result.java
awscurl/src/test/java/ai/djl/awscurl/AwsCurlTest.java

Write the benchmark result to a json file

[awscurl] allow write to json file

---

engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
serving/src/main/java/ai/djl/serving/ModelServer.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
wlm/src/main/java/ai/djl/serving/wlm/SageMakerUtils.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java

[serving] Fixes logging invoke convention

---

serving/docker/lmi.Dockerfile

Revert PyTorch + update vLLM url

[DLC] update deps and wheel

---

engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/util/MutableClassLoader.java
serving/src/test/java/ai/djl/serving/ConfigManagerTest.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
tools/gradle/java-formatter.gradle

[serving] Fixes java21 compile error

---

.github/workflows/llm_integration_p4d.yml

[CI] restart docker service if general container kill doesn't work

---

.github/workflows/llm_integration_p4d.yml

Try to restart service if a container cannot be killed

Fix P4D docker issues

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Avoid using tab in logging

---

.github/workflows/run-max-num-tokens.yml

Adding a placeholder workflow into master so that the following message will display under GitHub Actions:
`This workflow has a workflow_dispatch event trigger.` (allows workflows from branches to be manually launched)

Add placeholder workflow

---

.github/workflows/run-max-num-tokens.yml

emergency fix

---

.github/workflows/llm_integration_p4d.yml

1. Attempt to restart docker daemon in the beginning of every run, as sometimes, a previous `docker rm -f` command leaves docker daemon in a bad state. (may revert this change in case we find a better solution)

[CI] Update p4d CI workflow

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/test_model.py
engines/python/setup/djl_python/tests/rolling_batch/fake_rolling_batch.py
engines/python/setup/djl_python/tests/test_test_model.py
tests/integration/llm/client.py

Reach better handling at problematic points

Add better token handling under hazardous condition

---

gradle.properties

[ci] Updates dependencies version

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/tests/test_rolling_batch.py

[RollingBatch] allow appending for token

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py

not supporting pending requests

[RollingBatch] remove pending requests

---

serving/docker/scripts/install_djl_serving.sh

This PR patches an issue with the 0.27.0 DJL api.

[0.27.0-DLC][patch] Patches security issue in 0.27.0 DJL lib

---

tests/integration/llm/client.py

Update the tokenizer for benchmarks

[CI] update benchmark tokenizer

---

serving/docs/adapters.md
serving/docs/lmi/README.md
serving/docs/lmi/conceptual_guide/lmi_engine.md
serving/docs/lmi/user_guides/lmi-dist_user_guide.md
serving/docs/lmi/user_guides/vllm_user_guide.md

[Doc] Update LoRA docs

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/tests/test_rolling_batch.py

Fix TGI compat with format on token ids

allow TGI compat to work with output token ids

---

.github/workflows/run-max-num-tokens.yml
tests/integration/llm/run_max_num_tokens.py

Add max num tokens workflow

---

tests/integration/llm/client.py

[CI] fix tokenizers

---

.github/workflows/lmi-no-code.yml
serving/docker/tensorrt-llm.Dockerfile

[TRTLLM] add gemma model support

---

serving/src/main/java/ai/djl/serving/util/ConfigManager.java

[serving] Avoid tab in logging

---

serving/docker/lmi.Dockerfile

[LMI] not sharing container info

---

.github/workflows/instant_benchmark.yml

Add repository support for remote branch

[IB] fix with master branch if come from external repo

---

prometheus/build.gradle

[prometheus] Avoid missing class warning

---

tests/integration/llm/README.md
tests/integration/llm/dataset_prep.py

[Benchmark] dataset preparation

---

.github/workflows/instant_benchmark.yml

[IB] increase benchmark time out time

---

.github/workflows/instant_benchmark.yml
tests/integration/llm/client.py
wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java

- setting a max_new_tokens for TRTLLM
- Extending benchmark our to 2

update default for TRTLLM with max_new_tokens

---

.github/workflows/lmi-no-code.yml
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/tensorrt_llm.py
engines/python/setup/djl_python/tests/rolling_batch_test_scripts/generator.py
engines/python/setup/djl_python/tests/test_rolling_batch.py
engines/python/setup/djl_python/transformers_neuronx.py
tests/integration/llm/tgi_client.py

- Generally supporting SSE data format
- Change token id back into integer
- remove step token in the settings
- Adding content type to each formatter and return to the host

[UX] Fix a few code to get closer to TGI UX

---

.github/workflows/lmi-no-code.yml
engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/tests/test_rolling_batch.py
engines/python/setup/djl_python/tests/test_test_model.py

[CI] improve lcnc

---

engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py

[trtllm] translate tgi stop to stop_sequences

---

.github/workflows/text_embedding_integration.yml
tests/integration/embedding/client.py
tests/integration/embedding/prepare.py

[ci] Add text embedding integration test

---

.github/workflows/lmi-no-code.yml

fix bug on p4d machine closure

---

tests/integration/llm/dataset_prep.py

add open orca conversion

---

engines/python/setup/djl_python/request.py
engines/python/setup/djl_python/tests/test_rolling_batch.py
engines/python/setup/djl_python/utils.py

[fix] Refactor extra parameters and added unit tests cases

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java

Search for onnx file with folder name. This is the same logic with DJL:
https://github.com/deepjavalibrary/djl/blob/master/engines/onnxruntime/onnxruntime-engine/src/main/java/ai/djl/onnxruntime/engine/OrtModel.java#L77-L78

[onnx] Search for onnx file with folder name

---

engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_modeling.py

Fix application of stopping criteria to align with optimum-neuron 0.0.22

[tnx] fix optimum 0.0.22 integration

---

engines/python/setup/djl_python/neuron_utils/model_loader.py

Updates AOT partitioning to use safetensors format for weight checkpoints aligning with optimum-neuron 0.0.22

[tnx] add new optimum safetensors model loading and partition support

---

.github/workflows/download_llm_to_gamma.yml
tests/integration/llm/download_llm.py

Simple download model workflow

download model workflow

---

plugins/cache/build.gradle
plugins/cache/src/test/java/ai/djl/serving/cache/CacheEngineTest.java

[cache] Update DDBLocal to 2.4.0

---

.github/workflows/download_llm_to_gamma.yml

Fix Download workflow

---

engines/python/setup/djl_python/neuron_utils/model_loader.py
engines/python/setup/djl_python/properties_manager/tnx_properties.py
engines/python/setup/djl_python/tests/test_properties_manager.py

Adds passthrough support for generation config for on device embedding.

[tnx] add on device generation params support

---

engines/python/setup/djl_python/tests/rolling_batch/fake_rolling_batch.py
engines/python/setup/djl_python/tests/test_test_model.py
engines/python/setup/djl_python/tests/utils.py
engines/python/setup/djl_python/utils.py
engines/python/setup/setup.py

Simple module to print the leakage

add profiling utils to check object leakage

---

awscurl/src/test/java/ai/djl/awscurl/package-info.java
gradle/wrapper/gradle-wrapper.properties
plugins/cache/src/test/java/ai/djl/serving/cache/package-info.java
plugins/kserve/src/test/java/ai/djl/serving/kserve/package-info.java
serving/src/main/java/ai/djl/serving/http/list/ListAdaptersResponse.java
tools/conf/checkstyle.xml
tools/conf/suppressions.xml
tools/gradle/check.gradle

[ci] Updates gradle to 8.7

---

.github/workflows/lmi-no-code.yml

Update the model list to test latest

[CI] update model list

---

tests/integration/llm/client.py

Fail if return code is not 200

[CI] track for code not 200 errored response

---

serving/docker/dockerd-entrypoint-with-cuda-compat.sh
serving/docker/lmi.Dockerfile
tests/integration/llm/prepare.py

~~Depends on https://github.com/deepjavalibrary/djl-serving/pull/1934~~
Adding `max_model_len` param to ci tests [vllm-project/vllm/issues/2418]
* Nightly build: https://github.com/deepjavalibrary/djl-serving/actions/runs/9215590750
* Large model integration: https://github.com/deepjavalibrary/djl-serving/actions/runs/9214783969
* P4D integ tests: https://github.com/deepjavalibrary/djl-serving/actions/runs/9214819854

[dep] Updgrades dependencies for lmi-dist engine

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py

Change the logprobs to 1 as the logprobs of top candidate

[vLLM/LMI-Dist]change the default logprobs to 1

---

serving/docker/tensorrt-llm.Dockerfile

Upgrade pybind together with triton core

[TRTLLM] fix memory issue with pybind and triton core version upgrade

---

engines/python/setup/djl_python_engine.py

[python] Avoid nested logging exception

---

tests/integration/llm/client.py

add a failed log check for jsonlines

---

wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java

Update the list of supported model in LMI
@davidthomas426

[0.4.2] update the list of supported model

---

.github/workflows/llm_integration.yml
serving/docker/lmi.Dockerfile
tests/integration/llm/client.py
tests/integration/llm/prepare.py

[dep] Bump up transformers version to support falcon2

---

serving/docker/lmi.Dockerfile

[dep] Update optimum version to resolve conflict with transformers

---

engines/python/setup/djl_python/request_io.py

fix default values in request io

---

serving/docker/lmi.Dockerfile

[0.28.0-dlc] [docker] Install onnxruntime custom built wheel

---

serving/docker/lmi.Dockerfile

Install onnxruntime wheel built for cudnn 9 and cublast 12

[docker] Install onnxruntime custom built wheel

---

engines/python/setup/djl_python/request_io.py

[cherry-pick][0.28.0-dlc] fix default values in request io (#1975)

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
tests/integration/llm/client.py

add some fixes and fine print the error message

---

.github/workflows/lmi-no-code.yml
tests/integration/llm/prepare.py

skip for code llama

---

serving/docker/lmi.Dockerfile

[dep] Update optimum to latest version

---

serving/docker/lmi.Dockerfile

[0.28.0-dlc][dep] Update optimum to latest version #1981

---

.github/workflows/llm_integration.yml

Fixing ci for release branch while falcon model config gets updated

[0.28.0-dlc] removing falcon-7b ci due to config.json missing attr

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[0.28.0-dlc] [fix] Fix arguments null pointer

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[fix] Fix arguments null pointer

---

tests/integration/llm/prepare.py

[ci] Remove remote code and use latest transformers for falcon

---

engines/python/setup/djl_python/properties_manager/hf_properties.py
engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py

[vLLM] support future arctic model FP8 quantization

---

engines/python/setup/djl_python/request_io.py

fix typo in finish_reason default. 

---

serving/docker/pytorch-inf2.Dockerfile

Freeze versions for 0.28.0 release

[0.28.0-dlc][tnx] freeze versions for LMI Neuron

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/pytorch-gpu.Dockerfile

CPU / GPU / arm container tags update

[0.28.0-dlc][dlc] Update tag versions for containers

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

[serving] Fixes onnx model conversion bug

---

serving/docker/lmi.Dockerfile

Update vllm config path for sm

Sm vllm config

---

serving/docker/lmi.Dockerfile

[fix] Update vllm config path for sm

---

serving/docker/lmi.Dockerfile
serving/docker/pytorch-inf2.Dockerfile

[docker] Install missing pytorch jni package

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py

Use G6 machines for publishing

[Post 0.28.0] update pipeline machine to g6

---

tests/integration/llm/client.py

[CI] use split by '\n' to solve the issue

---

tests/integration/llm/client.py

[0.28.0-dlc][cherry-pick][CI] use split by '\n' to solve the issue (#2020)

---

.github/workflows/instant_benchmark.yml

Add ecr login credentials
- If this change is a backward incompatible change, why must this change be made? This is backward compatible

Add ecr login credentials

---

serving/docs/lmi/user_guides/lmi-dist_user_guide.md
serving/docs/lmi/user_guides/trt_llm_user_guide.md

[docs] Fix broken links in user guide

---

tests/integration/llm/dataset_prep.py

[CI] fix a bug in dataset prep

---

gradle/libs.versions.toml

Updates DJL version to 0.29.0-SNAPSHOT

---

tests/java-client/build.gradle.kts

[test] Fixes java-client test dependency

---

engines/python/setup/djl_python/session_manager.py

[python] Fixes typing issue with py3.8

---

engines/python/setup/djl_python/request_io.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
engines/python/setup/djl_python/tests/rolling_batch_test_scripts/test_rb_vllm_utils.py

Refactor lmi_dist and vllm to support best_of with RequestOutput

---

.github/workflows/docker-nightly-publish.yml
serving/docker/README.md

[docker] Fixes docker build script for version detection

---

engines/python/build.gradle.kts
prometheus/build.gradle.kts
serving/build.gradle.kts
wlm/build.gradle.kts

[ci] Add back missing publish task in gradle

---

prometheus/src/main/java/ai/djl/prometheus/PrometheusAppender.java
prometheus/src/test/java/ai/djl/preometheus/MetricExporterTest.java
wlm/src/main/java/ai/djl/serving/wlm/BatchAggregator.java

[metrics] Improve prometheus metric type handling

---

serving/docs/lmi/user_guides/lmi_input_output_schema.md

[doc] SSE jsonline document

---

serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/src/main/java/ai/djl/serving/util/ConfigManager.java
serving/src/main/java/ai/djl/serving/util/RateLimiter.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
serving/src/test/resources/config.properties

[serving] Fail ping if error rate exceed

---

.github/workflows/instant_benchmark.yml
tests/integration/instant_benchmark.py

To solve the file getting too big problems

[IB] use a file to pass to the output

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Update default max worker to 1 for GPU

---

tests/integration/record_benchmark.py

Add suzuka model to message reporting

[IB] support suzuka model

---

serving/docs/lmi/user_guides/embedding-user-guide.md

[docs] Updates embedding user guide

---

benchmark/build.gradle.kts

This should fix
https://github.com/deepjavalibrary/djl-serving/actions/workflows/integration.yml

Fix benchmark deb build

---

serving/docker/dockerd-entrypoint-with-cuda-compat.sh
serving/docker/lmi.Dockerfile
serving/docker/partition/partition.py
serving/docker/partition/properties_manager.py
serving/docker/partition/run_partition.py
serving/docker/partition/sm_neo_neuron_partition.py
serving/docker/partition/sm_neo_quantize.py
serving/docker/partition/sm_neo_utils.py
serving/docker/partition/trt_llm_partition.py
serving/docker/partition/utils.py

[0.28.0-dlc][cherry-pick] AutoAWQ Integration Script (#2038)

---

serving/build.gradle.kts

[plugin] Fixes plugin scaning bug

---

jacoco/build.gradle
plugins/secure-mode/src/main/java/ai/djl/serving/plugins/securemode/SecureModeModelServerListener.java
plugins/secure-mode/src/main/java/ai/djl/serving/plugins/securemode/SecureModeUtils.java
plugins/secure-mode/src/test/java/ai/djl/serving/plugins/securemode/SecureModePluginTest.java
serving/src/main/java/ai/djl/serving/http/IllegalConfigurationException.java
serving/src/main/java/ai/djl/serving/util/NettyUtils.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[secure-mode] Refactor secure mode plugin (#2058)

---

.github/workflows/llm_integration.yml
.github/workflows/lmi-no-code.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Removing this till, triton support in 0.10.0 is supported.

[test] remove trtllm flan t5 integration test

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Added integration test for AutoAwq. 
Verified by running the integration test https://github.com/deepjavalibrary/djl-serving/actions/runs/9507687861/job/26207665808#step:8:24

[ci] Adding integration test for AutoAwq

---

.github/workflows/continuous.yml
.github/workflows/llm_inf2_integration.yml
.github/workflows/llm_integration.yml
.github/workflows/llm_integration_p4d.yml
.github/workflows/lmi-dist-deps-build.yml
.github/workflows/lmi-no-code.yml
.github/workflows/lmic_performance.yml
.github/workflows/rolling_batch_integration.yml
engines/python/setup/setup.py
engines/python/src/test/resources/accumulate/requirements.txt
serving/docker/pytorch-gpu.Dockerfile
serving/docker/scripts/install_python.sh

pin numpy to <2 in ci/docker

---

.github/workflows/continuous.yml
.github/workflows/llm_inf2_integration.yml
.github/workflows/llm_integration.yml
.github/workflows/llm_integration_p4d.yml
.github/workflows/lmi-dist-deps-build.yml
.github/workflows/lmi-no-code.yml
.github/workflows/lmic_performance.yml
engines/python/setup/setup.py
engines/python/src/test/resources/accumulate/requirements.txt
serving/docker/pytorch-gpu.Dockerfile
serving/docker/scripts/install_python.sh

pin numpy to <2 in ci/docker (#2071)

---

.github/workflows/continuous.yml
.github/workflows/llm_inf2_integration.yml
.github/workflows/llm_integration.yml
.github/workflows/llm_integration_p4d.yml
.github/workflows/lmi-dist-deps-build.yml
.github/workflows/lmi-no-code.yml
.github/workflows/lmic_performance.yml
engines/python/setup/setup.py
engines/python/src/test/resources/accumulate/requirements.txt
serving/docker/partition/sm_neo_quantize.py
serving/docker/partition/sm_neo_trt_llm_partition.py
serving/docker/partition/sm_neo_utils.py
serving/docker/pytorch-gpu.Dockerfile
serving/docker/scripts/install_python.sh

[0.28.0 dlc][cherry-pick] AOT fix and pin numpy

---

tests/integration/tests.py

[CI] Fix post autoAwq cleanup

---

engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
engines/python/setup/djl_python/sm_log_filter.py
engines/python/setup/djl_python/telemetry.py
engines/python/src/main/java/ai/djl/python/engine/PyProcess.java

This is a minimal change to add acceptance rate telemetry recording

Record telemetry including acceptance rate

---

engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
engines/python/setup/djl_python/sm_log_filter.py
engines/python/setup/djl_python/telemetry.py
engines/python/src/main/java/ai/djl/python/engine/PyProcess.java

[0.28.0-dlc] Record telemetry including acceptance rate

---

engines/python/setup/djl_python/tests/neuron_test_scripts/test_neuron_vllm_rolling_batch.py

Revert string ground truth for assert in neuron unit test.

[ci] fix ground truth for neuron unit test

---

serving/docker/tensorrt-llm.Dockerfile

Update wheel naming for trtllm toolkit

[ci] fix trtllm nightly wheel pip installs

---

serving/docker/pytorch-inf2.Dockerfile

fix numpy version error in dockerfile

[ci] fix pinning numpy inf2 error

---

engines/python/setup/djl_python/tensorrt_llm.py
engines/python/setup/djl_python/tensorrt_llm_python.py

[0.28.0-dlc][cherry-pick][fix] Set tokenizer on output_formatter for TRT-LLM Handlers (#2100)

---

tests/integration/llm/client.py
tests/integration/llm/prepare.py
tests/integration/tests.py

[ci] add trtllm chat test

---

serving/docker/tensorrt-llm.Dockerfile

[dockerfile] pin datasets to 2.19.1 in trtllm

---

tests/integration/tests.py

Fix gpt2 integ test failure
[Test run](https://github.com/deepjavalibrary/djl-serving/actions/runs/9671820800)

[ci] Fix gpt2 integ test failure

---

serving/docker/tensorrt-llm.Dockerfile

[0.26.0-dlc] pin datasets version in tensorrt llm

---

serving/docker/tensorrt-llm.Dockerfile

[0.27.0-dlc] pin datasets version in tensorrt llm

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

[0.28.0] fix telemetry tracking for Speculative Decoding

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/lmi.Dockerfile
serving/docker/pytorch-gpu.Dockerfile
serving/docker/pytorch-inf2.Dockerfile
serving/docker/tensorrt-llm.Dockerfile

[docker] Update DJL to 0.29.0-SNAPSHOT

---

awscurl/src/main/java/ai/djl/awscurl/AwsCurl.java
awscurl/src/main/java/ai/djl/awscurl/SignableRequest.java

[awscurl] Handles Bedrock special url case

---

wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java

…(#2116)
(cherry picked from commit a215752ab91fa5313687e7909e771f2842005ef1)

[cherrypick][0.28.0 dlc] fix default behavior for rb in neuron (#2116)

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Fixes snake case pattern

---

serving/docs/lmi/README.md

Added a bullet point for new Text Embedding Feature

[docs]Update DJL-Serving Read Me

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Fixes snake case pattern (#2123)

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
engines/python/setup/setup.py

[0.28.0-dlc] spec decoding cache dirty fix

---

plugins/secure-mode/src/main/java/ai/djl/serving/plugins/securemode/SecureModeAllowList.java
plugins/secure-mode/src/main/java/ai/djl/serving/plugins/securemode/SecureModeUtils.java
plugins/secure-mode/src/test/java/ai/djl/serving/plugins/securemode/SecureModePluginTest.java

[secure-mode] Add properties allowlist validation (#2129)

---

awscurl/src/main/java/ai/djl/awscurl/JsonUtils.java
awscurl/src/test/java/ai/djl/awscurl/AwsCurlTest.java

[awscurl] Fixes missing \"text\" case in jsonlines output

---

serving/docker/Dockerfile

[docker] remove tensorflow native from cpu-full image

---

serving/docker/Dockerfile

[docker] Fixes cpu-full docker build script

---

serving/docker/pytorch-gpu.Dockerfile

[docker] Fixes pytorch-gpu docker build script

---

.github/workflows/docker-nightly-publish.yml
serving/docker/Dockerfile
serving/docker/pytorch-gpu.Dockerfile
serving/docker/scripts/install_djl_serving.sh

[docker] Fixes docker -SNAPSHOT version build issue

---

build.gradle.kts
buildSrc/src/main/kotlin/ai/djl/shellFormatter.gradle.kts
serving/docker/dockerd-entrypoint-with-cuda-compat.sh
serving/docker/dockerd-entrypoint.sh
serving/docker/scripts/docker_name_builder.sh
serving/docker/scripts/install_inferentia2.sh
serving/docker/scripts/pull_and_retag.sh
serving/docker/scripts/security_patch.sh
tests/integration/cpu_memory_monitor.sh
tests/integration/launch_container.sh
tests/integration/remove_container.sh
tests/integration/test_client.sh
tests/integration/test_telemetry.sh

[ci] Adds formatShell gradle tasks

---

engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/input_parser.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/neuron_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
engines/python/setup/djl_python/tensorrt_llm.py
engines/python/setup/djl_python/tensorrt_llm_python.py
engines/python/setup/djl_python/tests/rolling_batch/fake_rolling_batch.py

This use case is only for rolling batch

[python] parse input only when new requests are received

---

engines/python/setup/djl_python/chat_completions/chat_properties.py
engines/python/setup/djl_python/chat_completions/chat_utils.py
engines/python/setup/djl_python/tests/test_chat_completions.py
engines/python/setup/djl_python/tests/test_properties_manager.py

This refactor introduces stronger typing on the ChatCompletions use-case. It creates a Message type, as well as ImageInput and TextInput types to facilitate better handling of multi-modal use-cases.
As part of these new types, some of the parsing/converting logic has been moved from utility methods to instance methods, which is cleaner and more understandable in my opinion. 
This also allows us to do better payload validation via pydantic.

Add stronger typing for chat completions use-cases

---

awscurl/build.gradle.kts
awscurl/src/main/java/ai/djl/awscurl/AwsCurl.java
awscurl/src/main/java/ai/djl/awscurl/HttpClient.java
awscurl/src/main/java/ai/djl/awscurl/JsonUtils.java
awscurl/src/main/java/ai/djl/awscurl/TokenUtils.java
awscurl/src/test/java/ai/djl/awscurl/AwsCurlTest.java
gradle/libs.versions.toml

[awscurl] Supports full jsonquery syntax

---

awscurl/src/main/java/ai/djl/awscurl/TokenUtils.java

[awscurl] Fixes tokenizer cache directory

---

tests/integration/llm/download_llm.py
tests/integration/llm/prepare.py
wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java

Add vLLM 0.5.1 supported models

add 0.5.1 supported models

---

engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py

Kindly merge this only after vllm is upgraded to 0.5.1

[python] update max_logprobs default for vllm 0.5.1

---

serving/docker/lmi.Dockerfile

fix the cache miss issue

---

tests/integration/test_client.py
tests/python/model.py

Validate Json error is correctly built

add json error testing

---

tests/integration/llm/prepare.py

Create new versions of SD compiled models based on new optimum version.

[fix] optimum update stable diffusion support

---

.github/workflows/continuous.yml
.github/workflows/docker-nightly-publish.yml
.github/workflows/integration.yml
.github/workflows/integration_execute.yml
.github/workflows/llm_integration_p4d.yml
.github/workflows/lmi-no-code.yml
.github/workflows/run-max-num-tokens.yml
.github/workflows/text_embedding_integration.yml
.github/workflows/trtllm-deps-build.yml

[CI] upgrade deps version

---

awscurl/src/main/java/ai/djl/awscurl/HttpClient.java

[awscurl] Includes input data in output file

---

tests/integration/llm/README.md
tests/integration/llm/dataset/README.md
tests/integration/llm/dataset/dataset_prep.py
tests/integration/llm/dataset/mmlu_generator.py

add mmlu dataset

---

.github/workflows/trtllm-deps-build.yml

[CI] update cuda version and the pipeline

---

tests/integration/llm/client.py

Now that response codes are coming back with non-200 values the `send_json` functions error handling is now occurring prior to and outside of the adapters test handler. Refactored to allow `send_json` to throw errors, and handle catches appropriately.

[ci] fix adapters client testing

---

serving/docs/lmi/user_guides/chat_input_output_schema.md
serving/docs/lmi/user_guides/vision_language_models.md

[lmi][doc] update docs for vision language model support

---

benchmark/README.md
benchmark/snapcraft/snapcraft.yaml

bump up bench to 0.29.0

---

.github/workflows/correctness.yml
tests/integration/llm/client.py
tests/integration/llm/correctness/execution.py
tests/integration/llm/prepare.py
tests/integration/pytest.ini
tests/integration/tests.py

[ci] Add correctness testing

---

.github/workflows/integration.yml
tests/integration/llm/client.py
tests/integration/tests.py

Aimed to fetch all client logs together with serving logs

[CI] add client logger to output logs

---

serving/docker/lmi.Dockerfile

[lmi] Dependencies upgrade for 0.29.0

---

tests/integration/llm/client.py
tests/integration/llm/prepare.py

fix the handler

---

engines/python/setup/djl_python/output_formatter.py

[chat-completions] fix minor issues with response schema

---

tests/integration/tests.py

[CI] update the test

---

tests/integration/llm/prepare.py

Reverts deepjavalibrary/djl-serving#2205
Given the model fix

Revert "Update max_model_len for llama-3 lora test"

---

.github/workflows/llm_integration_p4d.yml

[CI] add P4D test missing deps

---

.github/workflows/correctness.yml
tests/integration/llm/client.py
tests/integration/llm/correctness/execution.py
tests/integration/llm/prepare.py
tests/integration/tests.py

[ci] Add mmlu dataset to correctness testing

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

[wlm] Fixes retrieve config.json error

---

.github/workflows/lmi-no-code.yml
tests/integration/llm/client.py

[CI] fix no code pipeline issues

---

.github/workflows/docker-nightly-publish.yml
serving/docker/lmi.Dockerfile

Make LMI container build use default runner

[CI] use default github runner

---

tests/integration/tests.py

fix typo in test name

---

.github/workflows/correctness.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py
tests/integration/tests.py

[ci] Update correctness testing

---

engines/python/setup/djl_python/transformers_neuronx_scheduler/slot.py
serving/docker/pytorch-inf2.Dockerfile

Update dependencies to support LLama3.1

[docker] neuron bump transformers for llama3.1

---

.github/workflows/lmi-dist-deps-build.yml

[ci][hotfix] changes to build new vllm wheel with hanging fix

---

serving/docker/lmi.Dockerfile

This will solve the Rope issue on LLAMA 2-32k @ydm-amazon

update the transformers version

---

serving/docker/lmi.Dockerfile

[0.29.0] use vllm wheel with hanging patch

---

serving/docker/lmi.Dockerfile

[lmi] use vllm wheel with hanging patch

---

engines/python/src/main/java/ai/djl/python/engine/Connection.java
wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving][post 7/24] Fixes tensor_parallel_degree detection on CPU

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

Convert model_id to rust artifacts

---

tests/integration/llm/client.py
tests/integration/llm/prepare.py
tests/integration/tests.py
wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

[python] remove flan-t5 python backend in recommender and add test cases

---

awscurl/src/main/java/ai/djl/awscurl/HttpClient.java
awscurl/src/test/java/ai/djl/awscurl/AwsCurlTest.java

Fix the logic for content parsing
```
< Content-Type: application/vnd.amazon.eventstream
< X-Amzn-SageMaker-Content-Type: text/event-stream; charset=utf-8
```

[AWSCurl] fix the logic on content parsing

---

tests/integration/llm/client.py
tests/integration/llm/prepare.py
tests/integration/tests.py

[ci] Fix correctness testing pipeline

---

serving/docs/lmi/user_guides/input_formatter_schema.md
serving/docs/lmi/user_guides/output_formatter_schema.md

[doc] add input_formatter schema doc

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/lmi.Dockerfile
serving/docker/pytorch-gpu.Dockerfile
serving/docker/pytorch-inf2.Dockerfile
serving/docker/tensorrt-llm.Dockerfile

[docker] Update DJL to 0.30.0

---

gradle/libs.versions.toml

Update DJL version to 0.30.0

---

engines/python/setup/djl_python/output_formatter.py
engines/python/setup/djl_python/service_loader.py
engines/python/setup/djl_python_engine.py
serving/docs/lmi/user_guides/output_formatter_schema.md

[python] add annotation for output formatter

---

serving/docker/lmi.Dockerfile

[docker] Update djl_converter version to 0.30.0

---

awscurl/src/main/java/ai/djl/awscurl/HttpClient.java

[awscurl] Fixes TTFB for SageMaker SSE response

---

tests/integration/llm/client.py

[ci] Update chat batch generation messages

---

engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
engines/python/setup/djl_python/utils.py

[python] fix beam search garbage issue

---

serving/docs/lmi/user_guides/lmi_input_output_schema.md

Updated best_of_sequences in the output schema and also best_of, n, num_beams in generation parameters of vllm and lmi-dist.

[doc] update beam search parameters in io schema

---

serving/docs/lmi/tutorials/tnx_aot_tutorial.md
serving/docs/lmi/user_guides/tnx_user_guide.md

Currency update for LMI Neuron docs

[docs] Update tnx docs to current

---

.github/workflows/lmi-no-code.yml
wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

Rewrite properties to the right path for model compilation

Fix TRTLLM partition issue

---

engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py

[python] fix mismatch tokens error

---

engines/python/setup/djl_python/utils.py

[python] fix dynamic batch input parse

---

tests/integration/llm/client.py

Fixing the jsonlines parsing on lora tests

[ci] fix lora test failures

---

.github/workflows/lmi-no-code.yml

Update Phi LCNC config

---

serving/docker/partition/sm_neo_quantize.py

In initial PR, quantization will default to awq if customer passes through serving.properties. This fix allows customer to either use envvar or serving.properties to use quantization type, while still properly defaulting to awq.

[neo] FP8 quantization fix

---

.github/workflows/lmi-no-code.yml

[CI] use s3 url for stability

---

serving/docker/lmi.Dockerfile
serving/docker/pytorch-inf2.Dockerfile
serving/docker/tensorrt-llm.Dockerfile

Set versions for wheels in dockerfile to non nightly
Do not merge until I am able to make sure all wheels are available

dockerfile versions non nightly

---

.github/workflows/sagemaker-integration.yml
tests/integration/llm/sagemaker-endpoint-tests.py

1. Fix issue with phi-2 + tensorrtllm. Using TP1
2. Add multimodal ci test for llava-v1.6

[ci] add multimodal tests for sagemaker

---

engines/python/setup/djl_python/chat_completions/chat_properties.py
serving/docs/lmi/user_guides/chat_input_output_schema.md

https://github.com/deepjavalibrary/djl/issues/3387

add ignore_eos support in chat completions schema

---

serving/docker/Dockerfile
serving/docker/pytorch-gpu.Dockerfile

[docker] Update PyTorch to 2.4.0

---

serving/docker/tensorrt-llm.Dockerfile

Cherry-pick the change to 0.29.0

[Cherry-pick][TRTLLM] take out cudnn (#2286)

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[onnx] Fixes detect need convert model logic for onnx

---

engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
engines/python/setup/setup.py

[python] fix the NoneType error when decoded_token is empty

---

engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
engines/python/setup/setup.py

Cherrypick the change to 0.29.0

[Cherrypick][python] fix the NoneType error when decoded_token is empty (#2289)

---

serving/docker/partition/partition.py
tests/integration/llm/client.py
tests/integration/llm/prepare.py
tests/integration/tests.py

[Cherrypick][ci] fix hf hub flakiness remove unused prepare (#2278)

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[onnx] Fixes detect need convert model logic for onnx (#2287)

---

serving/docker/tensorrt-llm.Dockerfile

Critical dependencies missing issues

[TRTLLM] fix the wrong libnvinfer issues

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

[serving] Adds error message for download config.json

---

serving/docker/tensorrt-llm.Dockerfile

Allow python mode to run normally

[CherryPick][TRTLLM] fix the wrong libnvinfer issues (#2298)

---

serving/docker/dockerd-entrypoint.sh
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[wlm] fail fast if one of the workers dies

---

serving/docker/dockerd-entrypoint.sh
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[wlm] fail fast if one of the workers dies (#2305)

---

.github/workflows/integration.yml

[0.28.0-dlc] fix the integration test to build on staging

---

wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

[wlm] Minor refactor to remove unused parameter

---

engines/python/setup/djl_python/chat_completions/chat_utils.py
engines/python/setup/djl_python/input_parser.py
engines/python/setup/djl_python/properties_manager/hf_properties.py
engines/python/setup/djl_python/tests/test_properties_manager.py

fix: allow chat template for non batch

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Change default retry_threshold to 0

---

tests/integration/benchmark/nightly/g5-2xl.txt

[ci] fix benchmark nightly concurrency

---

awscurl/src/main/java/ai/djl/awscurl/AwsCredentials.java

[awscurl] Loads AWS creadentials from EKS metadata

---

plugins/secure-mode/src/main/java/ai/djl/serving/plugins/securemode/SecureModeAllowList.java

Add enable streaming and tgi compat to allowlist

[cherry-pick] allow list enable streaming

---

serving/docs/lmi/user_guides/release_notes.md

Waiting to confirm (add) or remove a current Known Issue so WIP do not merge

LMI release notes

---

awscurl/src/main/java/ai/djl/awscurl/TokenUtils.java

[awscurl] Allows set max length by env var

---

.github/workflows/integration.yml

[0.28.0-dlc] fix the integration test to build on staging for gpu

---

engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java

[lmi][rolling-batch] deprecate backwards compat input formatter support

---

.github/workflows/llm_integration.yml

[ci] use g6 for llm integration due to capacity issues with g5

---

plugins/management-console/src/main/java/ai/djl/serving/console/ConsoleRequestHandler.java
serving/src/main/java/ai/djl/serving/http/RequestParser.java

[serving] Removes form data size limit

---

wlm/src/main/java/ai/djl/serving/wlm/NeuronSmartDefaultUtils.java
wlm/src/test/java/ai/djl/serving/wlm/NeuronSmartDefaultUtilsTest.java
wlm/src/test/resources/smart-default-model/gpt2/config.json

Fix for gpt2 models, test added for gpt2 config, and cap on max concurrency loop iterations.

[test][neuron] Add gpt2 test case and infinite loop guard

---

engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
serving/src/main/java/ai/djl/serving/util/MutableClassLoader.java
serving/src/main/java/ai/djl/serving/util/ServerGroups.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Minor code improvement

---

serving/src/main/java/ai/djl/serving/util/ConfigManager.java

[serving] Print PIPELINE_PARALLEL_DEGREE env var

---

tests/integration/launch_container.sh

[ci] Reformat shell script with shfmt

---

.github/workflows/lmi-no-code.yml

[ci] Neuron LCNC tests small models

---

.github/workflows/lmi-no-code.yml

Fixes the accelerator count from incorrectly being pulling in as part of the image name

[ci][fix] LCNC model tagging and accelerator count

---

awscurl/src/main/java/ai/djl/awscurl/AwsCurl.java
awscurl/src/main/java/ai/djl/awscurl/Result.java

[awscurl] Prints inter token latency

---

engines/python/setup/djl_python/output_formatter.py

[python] check whether last token is generated for json_output_formatter

---

engines/python/setup/djl_python/tests/test_rolling_batch.py

Python unittest would be passing after #2372 is merged.

[unittest] add spec decoding multiple tokens generation unit tests

---

serving/docker/partition/partition.py
serving/docker/partition/sm_neo_quantize.py

replacing https://github.com/deepjavalibrary/djl-serving/pull/2383

[cherry-pick] [Neo][vLLM] Accept quant options for awq, fp8 (#2382)

---

gradle/libs.versions.toml

[serving] Updates dependencies version to latest

---

gradle/wrapper/gradle-wrapper.properties

[ci] Updates gradle to 8.10.1

---

serving/docker/lmi.Dockerfile

[docker] Update vllm to 0.5.5

---

serving/docker/partition/partition.py

[cherry-pick] [neo] Fix calib_size dtype bug (#2397)

---

engines/python/setup/djl_python/chat_completions/chat_properties.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/properties_manager/hf_properties.py
engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
serving/docs/lmi/user_guides/vision_language_models.md
tests/integration/llm/client.py
tests/integration/llm/prepare.py

[multimodal] Support multi-image input for vision language models

---

tests/integration/llm/prepare.py

Accidentally committed the experiments

[vllm] Fix speculative_model in vllm integration test

---

engines/python/setup/djl_python/output_formatter.py

[python] fix token lookup when token is null

---

serving/docker/scripts/install_djl_serving.sh

[docker] Fixes ImageFactory visualization error

---

serving/docs/lmi/user_guides/release_notes.md

[docs] fix typo in release notes

---

.github/workflows/serving_publish.yml

adding serving_publish workflow

Serving publish brndyng

---

serving/docker/lmi.Dockerfile
serving/docker/scripts/install_python.sh

Updating python dependency versions for lmi container.
I've tested a few of the integration test suites locally and they are passing (TestLmiDist1, TestLmiDistLora, TestScheduler)
We will still need another update here for vllm and lmi-dist once ready

[docker] update dependencies in lmi dockerfile

---

awscurl/src/main/java/ai/djl/awscurl/AwsCurl.java

awscurl's --delay option did not actually work, for a couple of different reasons.

Fix awscurl --delay option

---

serving/docker/lmi.Dockerfile

[lmi][docker] use index url instead of extra index url, cu124 for torch

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

lmi_dist offers a batched add_requests call. Moving forward, it will probably have better performance. It does not yet, but this sets up for likely better performance in the near future.

[lmi][lmi-dist] Use batched add_requests call.

---

serving/docker/pytorch-inf2.Dockerfile

Pin hugging-face hub to fix stable diffusion optimum failures.

[neuron] pin huggingface hub

---

.github/workflows/integration.yml

Forgot this in the previous PR https://github.com/deepjavalibrary/djl-serving/pull/2467

[ci][lmi] add pipeline parallel tests to ci workflow

---

tests/integration/tests.py

Fix model name for aot lcnc test

[fix] neuron unit test aot lcnc test script

---

tests/integration/llm/client.py
tests/integration/llm/prepare.py
tests/integration/tests.py

[ci][trt] add llama3-1 test for trtllm

---

gradle/libs.versions.toml
serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/lmi.Dockerfile
serving/docker/pytorch-gpu.Dockerfile
serving/docker/pytorch-inf2.Dockerfile
serving/docker/tensorrt-llm.Dockerfile

[serving] Bump up DJL version to 0.31.0-SNAPSHOT

---

engines/python/setup/djl_python/input_parser.py
engines/python/setup/djl_python/request.py
engines/python/setup/djl_python/request_io.py
engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/utils.py

[lmi] add minimal requestId logging for new requests, and exceptions/errors

---

engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/input_parser.py
engines/python/setup/djl_python/request.py
engines/python/setup/djl_python/request_io.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
engines/python/setup/djl_python/tests/rolling_batch/fake_rolling_batch.py
engines/python/setup/djl_python/utils.py

Couple more cherry-picks for v12. 
- fix issues with hf model config in rolling batch for non pixtral multimodal models
- request id logging in a few places

0.30.0 dlc - cherry picks

---

serving/docker/lmi.Dockerfile

[lmi][v12] pin lmi version to release nightly wheel

---

.github/workflows/docker-nightly-publish.yml

[ci] add snapshot for nightly and temp builds

---

.github/workflows/integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py
tests/integration/tests.py

t5 was broken in lmi-dist. David fixed it, and i validated it locally with the new lmi wheel

[lmi] add t5 integration test for lmi-dist

---

.github/workflows/integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py
tests/integration/tests.py

[lmi] add t5 integration test for lmi-dist (#2482)

---

tests/integration/tests.py

[fix] fix typo in t5 integration test (#2487)

---

engines/python/setup/djl_python/neuron_utils/model_loader.py
engines/python/setup/djl_python/neuron_utils/utils.py
engines/python/setup/djl_python/properties_manager/tnx_properties.py
engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
engines/python/setup/djl_python/tests/test_properties_manager.py
engines/python/setup/djl_python/transformers_neuronx.py

This is initial PR for neuron speculative decoding support. There are still few things to do, which will be done in next PRs.
- Adding smart defaults for spec decoding 
- Adding unit tests for new configurations. 
- Adding integration tests
- Adding correction tests.

[python] neuron speculative decoding support

---

serving/docker/lmi.Dockerfile

[lmi][v12] pin lmi version to release nightly wheel (#2483)

---

engines/python/setup/djl_python/neuron_utils/model_loader.py

[python] fix typo in fuse_qkv

---

tests/integration/llm/prepare.py

[fix] fix speculative decoding draft model param name in test

---

tests/integration/llm/prepare.py

[fix] fix speculative decoding draft model param name in test (#2493)

---

.github/workflows/text_embedding_integration.yml

[ci] Increase text embedding integration timeout

---

serving/docker/lmi.Dockerfile
serving/docker/pytorch-gpu.Dockerfile

[docker] Update dependencies in dockerfile

---

engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
engines/python/src/test/resources/adaptecho/model.py
engines/python/src/test/resources/adaptecho/serving.properties
serving/docs/adapters_api.md
serving/src/main/java/ai/djl/serving/http/AdapterManagementRequestHandler.java
serving/src/main/java/ai/djl/serving/http/DescribeAdapterResponse.java
serving/src/main/java/ai/djl/serving/http/list/ListAdaptersResponse.java
serving/src/main/java/ai/djl/serving/util/NettyUtils.java
serving/src/main/java/ai/djl/serving/workflow/function/AdapterWorkflowFunction.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
wlm/src/main/java/ai/djl/serving/wlm/Adapter.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
wlm/src/main/java/ai/djl/serving/wlm/PyAdapter.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java
wlm/src/main/java/ai/djl/serving/wlm/util/EventManager.java
wlm/src/main/java/ai/djl/serving/wlm/util/ModelServerListener.java
wlm/src/main/java/ai/djl/serving/wlm/util/ModelServerListenerAdapter.java

[lora] Support pin adapter API

---

engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/input_parser.py
serving/docs/adapters.md
serving/src/main/java/ai/djl/serving/http/AdapterManagementRequestHandler.java
serving/src/main/java/ai/djl/serving/workflow/function/AdapterWorkflowFunction.java
wlm/src/main/java/ai/djl/serving/wlm/Adapter.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
wlm/src/main/java/ai/djl/serving/wlm/PyAdapter.java

[lora] Support SageMaker adapter header

---

serving/docker/lmi.Dockerfile

This PR updates lmi docker to PT 2.5.1, including a custom vllm build on 0.6.3.post1. This unblocks some testing for various folks.
Additionally, we need to evaluate what vllm wheel we use. It makes sense to use a nightly/recent commit, but i need to figure that out with lmi-dist as well.
This also consolidates the pip installs into fewer installs to ensure we catch conflicts.

[lmi][docker] updating lmi docker file dependencies

---

serving/docker/dockerd-entrypoint-with-cuda-compat.sh
serving/docker/dockerd-entrypoint.sh
serving/docker/lmi.Dockerfile
serving/docker/partition/sm_neo_dispatcher.py
serving/docker/partition/sm_neo_shard.py

Introducing SageMaker Fast Model Loader and the associated scripts for Model Sharding

Introducing SageMaker Fast Model Loader

---

serving/docker/lmi.Dockerfile
tests/integration/llm/prepare.py

SageMaker FML: Fix Build Path & add integ test dependency

---

engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/input_parser.py
engines/python/src/test/resources/adaptecho/model.py
serving/src/main/java/ai/djl/serving/http/AdapterManagementRequestHandler.java
serving/src/main/java/ai/djl/serving/workflow/function/AdapterWorkflowFunction.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
wlm/src/main/java/ai/djl/serving/wlm/Adapter.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[lora] Update adapters list after backend job succeed and added tests

---

engines/python/setup/djl_python/huggingface.py
serving/src/main/java/ai/djl/serving/http/AdapterManagementRequestHandler.java
serving/src/main/java/ai/djl/serving/workflow/function/AdapterWorkflowFunction.java
wlm/src/main/java/ai/djl/serving/wlm/Adapter.java
wlm/src/main/java/ai/djl/serving/wlm/PyAdapter.java

Currently we have a optional pin parameter in Adapter, but it's also in the options map. So raise this PR to avoid duplication.

[lora] Move pin to options

---

serving/docker/pytorch-inf2.Dockerfile

This will fix a failing regression test for that patch release
https://github.com/deepjavalibrary/djl-serving/actions/runs/11748525861/job/32732832900

[docker][inf2] pin huf hub python dependency

---

engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
serving/docker/lmi.Dockerfile
serving/docker/partition/sm_neo_dispatcher.py
serving/docker/partition/sm_neo_shard.py
tests/integration/llm/client.py
tests/integration/llm/prepare.py

did a format based on https://github.com/deepjavalibrary/djl-serving/pull/2530

++ #2530 Fixing Neo integ tests & adding more input validations 

---

serving/docs/adapters.md

[lora] Update LoRA adapter doc

---

serving/docker/README.md
serving/docker/partition/sm_neo_shard.py

- Fix bug in Neo sharding script
- Update docker README for decoupled versions

[neo] Fix sharding script bug

---

engines/python/src/test/resources/adaptecho/model.py
serving/src/test/java/ai/djl/serving/ModelServerTest.java

[lora] Add adapter OOM unit tests

---

engines/python/setup/djl_python/tests/neuron_test_scripts/test_neuron_tnx_rolling_batch.py

[cherry-pick][0.30.0-dlc][test] fix transformers neuronx integration test failure (#2539)

---

engines/python/setup/djl_python/neuron_utils/model_loader.py
engines/python/setup/djl_python/neuron_utils/neuron_smart_default_utils.py
engines/python/setup/djl_python/properties_manager/tnx_properties.py
engines/python/setup/djl_python/tests/test_properties_manager.py
engines/python/setup/djl_python/transformers_neuronx.py

[0.30.0 dlc][cherry-pick] legacy partition removal and add on_device_embedding true

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/pytorch-gpu.Dockerfile
serving/docker/tensorrt-llm.Dockerfile

[docker] Update torch to 2.5.1 in docker

---

gradle/libs.versions.toml
serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/lmi.Dockerfile
serving/docker/pytorch-gpu.Dockerfile
serving/docker/pytorch-inf2.Dockerfile
serving/docker/tensorrt-llm.Dockerfile

Bump DJL version to 0.32.0-SNAPSHOT

---

engines/python/setup/djl_python/neuron_utils/model_loader.py

[python] remove huggingface load and save for tnx (#2499)

---

engines/python/setup/djl_python/input_parser.py

Fix input request adapter parsing, I will add proper validation later.

[0.31.0-dlc] [fix] Fix input request adapter parsing

---

engines/python/setup/djl_python/input_parser.py

Fix input request adapter parsing, I will add proper validation later.

[fix] Fix input request adapter parsing

---

engines/python/setup/djl_python/input_parser.py

[lora] Log adapter name in inference

---

tests/integration/llm/prepare.py

[0.31.0-dlc] Fix lora integration test

---

tests/integration/llm/prepare.py

[lora] Fix lora integration test

---

tests/integration/benchmark/ir-llm/config/lmi-dist/config.yml
tests/integration/benchmark/ir-llm/config/trtllm/config.yml

Enable llama instruct models test cases in benchmark testing

---

engines/python/setup/djl_python/input_parser.py

[0.31.0-dlc] Fix parsing adapters list in inference request

---

engines/python/setup/djl_python/input_parser.py

[lora] Fix parsing adapters list in inference request

---

serving/docker/lmi.Dockerfile

This change reduces the number of layers in the lmi dockerfile by combining some pieces that didn't need to be separated. It brings down the image size to 18GB. for reference
- nightly is currently 22.3gb
- 0.30.0 is 22gb (before any refactors)
- 0.29.0 is 19.8gb (before any refactors)
The largest contributor to our image size are the python dependencies (9GB, of which PT is like 5GB). I don't know if we can get around that at the moment.
The DJL serving components, and patching/os updates are still left at the bottom since those are the most likely to change. If a change happens at either of these layers, it only requires pulling layers of about ~1GB. Before these series of changes, a change to the djl serving deb/jars would result in also needing to pull the python deps again.
We still …

[docker][lmi] reduce number of layers by consolidating some commands

---

engines/python/setup/djl_python/input_parser.py
engines/python/setup/djl_python/properties_manager/properties.py

[lora] Parse adapters iff enable_lora is true

---

engines/python/setup/djl_python/tests/test_input_parser.py

[lora] Add adapter parsing unit test

---

serving/docker/requirements-lmi.txt

Fix typo in requirements-lmi.txt

---

engines/python/setup/djl_python/huggingface.py
serving/docs/adapters_api.md
serving/src/main/java/ai/djl/serving/http/AdapterManagementRequestHandler.java
serving/src/main/java/ai/djl/serving/http/DescribeAdapterResponse.java
serving/src/main/java/ai/djl/serving/http/list/ListAdaptersResponse.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
wlm/src/main/java/ai/djl/serving/wlm/Adapter.java

[0.31.0-dlc][lora] Update load option to preload

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

Fixes https://github.com/deepjavalibrary/djl-serving/issues/2630

Enable to set custom batchifier

---

engines/python/setup/djl_python/huggingface.py
serving/docker/partition/utils.py

@a-ys 
- [ X] Bug fix (non-breaking change which fixes an issue)

[python] fix the padding_size typo

---

.github/workflows/nightly.yml

[fix][ci] default to nightly when mode is not specified via cron trigger

---

.github/PULL_REQUEST_TEMPLATE.md

add  integ tests executor link in PR template checklist 
Doc update 

add integ tests executor link in PR template

---

engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py

[fix] return prompt from get_prompt_inputs utility method (#2635)

---

serving/src/test/java/ai/djl/serving/translator/EchoTranslator.java

[fix][test] ensure EchoTranslator.processInput does not return null

---

engines/python/setup/djl_python/seq_scheduler/lm_block.py
engines/python/setup/djl_python/tests/test_scheduler_bloom.py

[fix] Fix seq scheduler legacy cache format

---

serving/docs/lmi/user_guides/lmi-dist_user_guide.md
serving/docs/lmi/user_guides/vllm_user_guide.md

There was a section missing regarding ahead-of-time quantization on the vllm user guide.

[lmi][doc] minor updates to lmi-dist/vllm quantization docs

---

serving/src/main/java/ai/djl/serving/models/ModelManager.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

This is a forward port of the following two commits that enabled SERVING_HEALTH_CHECK_OVERRIDE in 0.28.0.
- https://github.com/deepjavalibrary/djl-serving/commit/0aab4c2ef39afdbe928e6e61b035574cc76a013c
- https://github.com/deepjavalibrary/djl-serving/commit/ab701655d768488759162b47061f93b4f2025de0

[patch][port] forward port of SERVING_HEALTH_CHECK_OVERRIDE from 0.28.0

---

awscurl/build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

[ci] Upgrade gradle to 8.12

---

serving/docker/pytorch-inf2.Dockerfile

[docker] pin tokenizers version in neuronx

---

engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/slot.py
engines/python/setup/djl_python/utils.py

https://github.com/deepjavalibrary/djl-serving/pull/2676 -> Removing .keys() reference in other handlers, since it is redundant. 

[python]remove keys to check param dict

---

.github/workflows/docker-nightly-publish.yml
.github/workflows/integration_execute.yml
.github/workflows/nightly-docker-ecr-sync.yml

[fix][ci] install awscli via pip due to issues with using apt

---

.github/workflows/docker-nightly-publish.yml
.github/workflows/integration_execute.yml
.github/workflows/nightly-docker-ecr-sync.yml

[ci][fix] install awscli via pip instead of apt

---

serving/docker/pytorch-inf2.Dockerfile

This PR updates the wheel to neuron vllm. https://github.com/aws-neuron/upstreaming-to-vllm. Built a wheel using internal wheel with vllm forked inside. 

[docker] update vllm wheel in neuronx container

---

wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java

[python] fix venv for neuron vllm

---

tests/integration/llm/client.py
tests/integration/llm/prepare.py
tests/integration/tests.py

Fixing Correctness Testing for neuron. Verified in my inf2 machine. 
- TP Degree for inf2 can be either 1 , 2, 4, 8, 24. Not sure, how tp degree 12 was working. 
- Changed the model to latest smaller model - llama 3.2 1B

[ci] fix correctness testing for neuronx

---

serving/docker/Dockerfile
serving/docker/lmi.Dockerfile
serving/docker/pytorch-gpu.Dockerfile

[docker] Updates docker file

---

engines/python/setup/djl_python/output_formatter.py
tests/integration/llm/client.py

[python] Update reasoning integration test

---

serving/docker/partition/partition.py
tests/integration/llm/client.py
tests/integration/tests.py

```
for line in proc.stdout:
partition_stdout += line
print(line, end='')
for line in proc.stderr:
partition_stderr = line
```
Here the output and errors are buffered and read synchronously one by one. For NXDI, some of the warning messages are comes in standard error stream. So errors filled out the buffers. But we are reading the standard output first, but there wont be any standard output in the buffer since the buffer is full with error messages. So it becomes a deadlock and that's why the process was stuck.
So, in the PR, we are redirecting stderr to stdout, which dumps everything in the stdout. Same is done in https://github.com/deepjavalibrary/djl-serving/blob/master/serving/docker/partition/sm_neo_dispatcher.py#L113 
Since, AOT issue is fixed, added back the integration tests. …

[python] fix aot buffered print

---

.github/workflows/docker-nightly-publish.yml
.github/workflows/docker_publish.yml
.github/workflows/integration.yml
.github/workflows/nightly.yml
serving/docker/docker-compose.yml
serving/docker/partition/partition.py
serving/docker/scripts/push_image_from_ECR.sh
tests/integration/tests.py

This PR updates the nightly pipeline workflow across a few places to fix issues with running release builds/tests. 
For internal staging builds, I have prepended the DJL version for nightly builds as well (e.g. previously we would have `lmi-nightly`, now we will have `0.32.0-lmi-nightly`. 
Test run for release pipeline: https://github.com/deepjavalibrary/djl-serving/actions/runs/13320792063
Previous release attempt before these changes: https://github.com/deepjavalibrary/djl-serving/actions/runs/13252982975
There are unrelated formatting errors that were fixed in this PR in  serving/docker/partition/partition.py
Please describe the Unit or Integration tests that you ran to verify your changes and relevant result summary. Provide instructions so …

[ci] update docker build of temp images to properly build release images

---

serving/docker/pytorch-inf2.Dockerfile
serving/docker/scripts/install_inferentia2.sh

[docker] Bump up neuron to 2.21.1 (#2734)

---

serving/docker/partition/partition.py
tests/integration/llm/client.py
tests/integration/tests.py

[python] fix aot buffered print (#2738)

---

.github/workflows/integration.yml
.github/workflows/nightly.yml
.github/workflows/optimization_integration.yml
tests/integration/llm/prepare.py

[IntegTest]add sharding optimization integ tests (#2742)

---

serving/docker/tensorrt-llm.Dockerfile

Make scripts executable in TRT-LLM build

[docker] Make scripts executable in TRT-LLM build

---

.github/workflows/optimization_integration.yml
gradle/libs.versions.toml
tests/integration/tests.py

Bump Version from 0.32.0 to 0.33.0

bump djl and djl serving version

---

engines/python/setup/djl_python/output_formatter.py

[0.32.0-dlc][tool] Fix tool calling output

---

engines/python/setup/djl_python/output_formatter.py

[tool] Fix tool calling output

---

serving/docker/requirements-vllm.txt

Install ninja to fix the error below when running name tool calling.
```
INFO  PyProcess W-194-8d7f663aaab4e5d-stdout: Traceback (most recent call last):
INFO  PyProcess W-194-8d7f663aaab4e5d-stdout:   File "/tmp/.djl.ai/python/0.33.0-SNAPSHOT/djl_python/rolling_batch/rolling_batch.py", line 47, in try_catch_handling
INFO  PyProcess W-194-8d7f663aaab4e5d-stdout:     return func(self, *args, **kwargs)
INFO  PyProcess W-194-8d7f663aaab4e5d-stdout:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
INFO  PyProcess W-194-8d7f663aaab4e5d-stdout:   File "/tmp/.djl.ai/python/0.33.0-SNAPSHOT/djl_python/rolling_batch/vllm_rolling_batch.py", line 185, in inference
INFO  PyProcess W-194-8d7f663aaab4e5d-stdout:     self.engine.add_request(request_id=request_id,
INFO …
```

[0.32.0-dlc][docker] Install ninja in lmi container

---

serving/docker/README.md

[doc] Update aarch64 docker documentation

---

.github/workflows/docker-nightly-publish.yml

[ci] Fix DJL version for release docker build

---

.github/workflows/docker-nightly-publish.yml

[0.32.0-dlc][ci] Fix DJL version for release docker build

---

benchmark/build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
jacoco/build.gradle.kts
serving/build.gradle.kts

[ci] Upgrade gradle to 8.13

---

serving/docker/lmi-container-requirements-common.txt
serving/docker/requirements-vllm.txt
serving/docker/scripts/install_s5cmd.sh

0.32.0 CVE fixes

---

tests/integration/tests.py

[0.32.0] remove async test since it is not supported in 0.32.0

---

.github/workflows/integration.yml

[fix] make the role credential timeout 7200 seconds to reflect 2 hours

---

serving/docs/lmi/README.md
serving/docs/lmi/user_guides/README.md
serving/docs/lmi/user_guides/chat_input_output_schema.md
serving/docs/lmi/user_guides/lmi-dist_user_guide.md
serving/docs/lmi/user_guides/release_notes.md
serving/docs/lmi/user_guides/starting-guide.md
serving/docs/lmi/user_guides/tool_calling.md
serving/docs/lmi/user_guides/vllm_user_guide.md

Updating the docs for LMI v14. I'll cherry-pick this to the DLC branch as well.

[lmi][docs] update lmi docs for v14

---

serving/docs/lmi/README.md
serving/docs/lmi/user_guides/README.md
serving/docs/lmi/user_guides/chat_input_output_schema.md
serving/docs/lmi/user_guides/lmi-dist_user_guide.md
serving/docs/lmi/user_guides/release_notes.md
serving/docs/lmi/user_guides/starting-guide.md
serving/docs/lmi/user_guides/tool_calling.md
serving/docs/lmi/user_guides/vllm_user_guide.md

[lmi][docs] update lmi docs for v14 (#2787)

---

engines/python/setup/djl_python/chat_completions/vllm_chat_utils.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
serving/docker/lmi.Dockerfile
serving/docker/requirements-vllm.txt

Upgrading vLLM to 0.8.2. I tested this locally for the following functionality across both rolling batch and async, stream/non-stream:
- lmi text payload
- chat text payload
- chat image payload
- chat tool payload

[vllm] update to vllm 0.8.2

---

engines/python/setup/djl_python/python_async_engine.py
engines/python/src/main/java/ai/djl/python/engine/AsyncRequestManager.java

This fixes an issue where the response returned from python in certain error scenarios (handler failures) were not being parsed properly by the frontend. This PR pulls logic from the RollingBatch Implementation that did the same thing, in order to maintain backwards compatibility.

[python][async] parse error responses when handler has exceptions

---

serving/docs/lmi/user_guides/tool_calling.md

[doc][lmi] fix tool calling doc payload

---

serving/docker/requirements-vllm.txt

[vllm] update to vllm 0.8.3

---

engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
tests/integration/tests.py

[vllm][ci] fix ci issues with vllm upgrade and v1 engine

---

serving/docker/lmi-container-requirements-common.txt
serving/docker/requirements-lmi.txt
serving/docker/requirements-vllm.txt
serving/docker/scripts/install_s5cmd.sh

This PR updates some container dependencies to address CVEs. 
- s5cmd to address GO CVEs
- python dep updates for various CVEs

[lmi][docker] update python dependency versions for lmi container

---

tests/integration/llm/prepare.py
tests/integration/tests.py

Fixing issues with the VLLM Lora tests, where a few of the tests are being run with the LMI-Dist configs

[fix][vllm][lora] fix issues with vllm lora tests using lmi-dist

---

.github/workflows/integration.yml

[ci] use self-hosted cpu instances in integ tests (#2801)

---

serving/docker/requirements-vllm.txt

[vllm] update to vllm 0.8.4

---

.github/workflows/integration.yml
tests/integration/tests.py

[ci] remove missed lmi-dist test from integ pipeline

---

engines/python/setup/djl_python/async_utils.py
engines/python/setup/djl_python/lmi_trtllm/request_response_utils.py
engines/python/setup/djl_python/lmi_trtllm/trtllm_async_service.py
engines/python/setup/djl_python/lmi_vllm/request_response_utils.py
engines/python/setup/djl_python/lmi_vllm/vllm_async_service.py
engines/python/setup/djl_python/outputs.py
engines/python/setup/djl_python/properties_manager/trt_properties.py
engines/python/setup/djl_python/tests/test_properties_manager.py
engines/python/setup/setup.py
engines/python/src/main/java/ai/djl/python/engine/PyModel.java
serving/docker/lmi.Dockerfile
serving/docker/partition/trt_llm_partition.py
serving/docker/tensorrt-llm.Dockerfile
tests/integration/llm/client.py
tests/integration/llm/prepare.py
wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

This PR updates TRTLLM to 0.20.0rc0 by leveraging the LLM API and async mode. It handles both AOT/compilation/quantization and inference implementations.
For AOT, we implement
- Build Config parsing
- Quant Config parsing
- Calib Config parsing
This allows full model conversion + quantization in a single step. Note that PyTorch backend of TRTLLM does not seem to support saving a compiled model. If the pytorch backend is specified, we then skip AOT and let the entrypoint handle the conversion/pytorch setup.
For inference, the default handler expects the model to be compiled ahead of time and does not expose Build/Quant/Config settings since those are expected to be handled by the AOT script, or by the user if bringing a compiled TRT model. …

[python][async] adding async tensorrt-llm handler

---

awscurl/src/main/java/ai/djl/awscurl/AwsCurl.java
awscurl/src/test/java/ai/djl/awscurl/AwsCurlTest.java

[awscurl] properly handle missing -jq case

---

serving/src/main/java/ai/djl/serving/models/ModelManager.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

Port https://github.com/deepjavalibrary/djl-serving/pull/2768 to 0.33.0 DLC

[patch][port] forward port of SERVING_HEALTH_CHECK_OVERRIDE

---

serving/src/main/java/ai/djl/serving/models/ModelManager.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

Promote https://github.com/deepjavalibrary/djl-serving/pull/2768 to master so future DLCs will not require a separate port

Promote SERVING_HEALTH_CHECK_OVERRIDE to mainline

---

README.md
awscurl/README.md
benchmark/README.md
benchmark/snapcraft/snapcraft.yaml
engines/python/README.md
serving/docker/README.md
serving/docs/lmi/deployment_guide/deploying-your-endpoint.md
serving/docs/lmi/user_guides/chat_input_output_schema.md
wlm/README.md

[docs] Update docs to 0.33.0

---

engines/python/setup/djl_python/async_utils.py
engines/python/setup/djl_python/lmi_trtllm/request_response_utils.py
engines/python/setup/djl_python/lmi_trtllm/trtllm_async_service.py
engines/python/setup/djl_python/lmi_vllm/vllm_async_service.py
engines/python/setup/djl_python/outputs.py
engines/python/setup/djl_python/properties_manager/trt_properties.py
engines/python/setup/djl_python/tests/test_properties_manager.py
engines/python/setup/setup.py
engines/python/src/main/java/ai/djl/python/engine/PyModel.java
serving/docker/lmi.Dockerfile
serving/docker/partition/trt_llm_partition.py
serving/docker/tensorrt-llm.Dockerfile
tests/integration/llm/client.py
tests/integration/llm/prepare.py
tests/integration/tests.py
wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

[trtllm] Upgrade TRT-LLM to version 0.21.0rc1 for djl-serving 0.33.0

---

buildSrc/src/main/kotlin/ai/djl/javaBase.gradle.kts
jacoco/build.gradle.kts
tests/java-client/build.gradle.kts

Update oss sonatype snapshot repository url

---

serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java

Update snapshot download URL

---

serving/build.gradle.kts
serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

This PR fixes the following error:
```
java.lang.VerifyError: Bad access to protected data in getfield
Exception Details:
Location:
com/sun/jna/PointerProxy.<init>(Lcom/sun/jna/Pointer;)V @2: getfield
Reason:
Type 'com/sun/jna/Pointer' (current frame, stack[1]) is not assignable to 'com/sun/jna/PointerProxy'
```
This is because xgboost jar is downloaded to deps folder. jar files in /deps are loaded in child classloader, however JNA jar is loaded in system class loader, causing JNA jar not able to access xgboost jar.
Therefore, this PR put the xgbost jar file in `lib` folder, in order to fix the class loading problem.
Please describe the Unit or Integration tests that you ran to verify your changes and …

Fix XGBoost model loading

---

engines/python/setup/djl_python/custom_formatter_handling.py
engines/python/setup/djl_python/lmi_vllm/vllm_async_service.py
engines/python/setup/djl_python/service_loader.py
serving/docs/lmi/user_guides/input_formatter_schema.md
serving/docs/lmi/user_guides/output_formatter_schema.md
tests/integration/examples/custom_formatters/input_formatter_failed.py
tests/integration/examples/custom_formatters/integration_script.py
tests/integration/examples/custom_formatters/load_formatter_failed.py
tests/integration/examples/custom_formatters/model.py
tests/integration/examples/custom_formatters/output_formatter_failed.py
tests/integration/llm/client.py
tests/integration/llm/prepare.py
tests/integration/tests.py

[lmiv16-vllm] Apply custom formatters to vLLM Async Handlers

---

.github/workflows/integration.yml
tests/integration/tests.py

Add TestVllmCustomHandlers to integration tests workflow

---

buildSrc/src/main/kotlin/ai/djl/pythonFormatter.gradle.kts
tests/integration/examples/custom_formatters/output_formatter_failed.py

Exclude syntax error example file from pythonFormatter

---

serving/docker/lmi-container-requirements.txt
serving/docker/lmi.Dockerfile

- Use official vLLM wheel
- Update deps for CVE patching

[0.34.0-dlc] CVE patching and use official vLLM wheel
