- engines/python/build.gradle
- wlm/build.gradle
> Add maven publish task to python engine

- engines/python/src/main/resources/ai/djl/python/scripts/inputs.py
- engines/python/src/main/resources/ai/djl/python/scripts/np_util.py
> [python] remove type hint to be compatible with lower version of python

- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
- serving/src/main/java/ai/djl/serving/models/ModelManager.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
> Refactor model manager inference api

- serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
- serving/src/main/java/ai/djl/serving/models/ModelManager.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
This removes some of the data from the ModelInfo to the wlm. Specifically, it
moves tracking of the min and max number of workers.
It also starts turning the wlm.WorkerPool into a public representation of the
management of a single model while the main wlm has all models. As part of this,
some functionality is moved from the main wlm to the pool. In general, we should
eventually not have part of the API be wlm.doSomething(model, ...) and some of
it be wlm.model(model).doSomething(...). I favor the latter approach.
Lastly, this also removes the concept of updating the model and then triggering
model changed. I noticed the change only really affects the scaleModel, so it is
simpler to just move those effects under scaleModel directly.
> Refactors minMaxWorkers from ModelInfo to WorkerPool

- serving/src/main/java/ai/djl/serving/models/ModelManager.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
This replaces the use of scaling a worker to 0 to unregister it. The dedicated
method should make the behavior more transparent.
> Add WorkLoadManager.unregisterModel

- serving/src/main/java/ai/djl/serving/ModelServer.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
- serving/src/test/resources/config.properties
> [serving] detect engine for local model store

- gradle.properties
> Upgrade log4j to 2.15.0

- gradle.properties
> Upgrade log4j to 2.16.0

- gradle.properties
> Upgrade log4j to 2.17.0

- gradle.properties
> Upgrade log4j to 2.17.1

- serving/src/main/java/ai/djl/serving/ModelServer.java
- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
- serving/src/main/java/ai/djl/serving/http/ListModelsResponse.java
- serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
- serving/src/main/java/ai/djl/serving/models/ModelManager.java
- serving/src/main/java/ai/djl/serving/util/ConfigManager.java
- serving/src/main/java/ai/djl/serving/workflow/Workflow.java
- serving/src/main/java/ai/djl/serving/workflow/WorkflowDefinition.java
- serving/src/main/java/ai/djl/serving/workflow/function/ModelWorkflowFunction.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
- serving/src/test/java/ai/djl/serving/WorkflowTest.java
- serving/src/test/resources/workflows/criteria.json
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java
- wlm/src/main/java/ai/djl/serving/wlm/util/WlmCapacityException.java
- wlm/src/main/java/ai/djl/serving/wlm/util/WlmShutdownException.java
- wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java
> [serving] Refactor ModelDefinition class

- serving/src/main/java/ai/djl/serving/ModelServer.java
- serving/src/main/java/ai/djl/serving/util/ConfigManager.java
> [serving] Make startup model default devices configurable

- serving/docs/management_api.md
- serving/src/main/java/ai/djl/serving/http/DescribeWorkflowResponse.java
- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
- serving/src/main/java/ai/djl/serving/http/ListWorkflowsResponse.java
- serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
- serving/src/main/java/ai/djl/serving/models/ModelManager.java
- serving/src/main/java/ai/djl/serving/util/ConfigManager.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
This updates the management request handler to add a control plane for
workflows. It shares a number of routes between the old models and workflows,
while some routes have different behaviors for each.
Specifically, there is a separate register and list command for both models and
workflows, while all other commands including describe, unregister, and scale
only work on workflows but will still accept "/models/..." routes. The precise
behavior is documented in management_api.md.
There are also a few refactors for ModelServerTest including cleaning up test
client connections, a shared list reader, a shared model registration checking function.
Finally, it also fixes a bug with the WorkLoadManager close not closing the
threadpool. This can result in the tests hanging.
> Create control plane for workflows

- serving/src/main/java/ai/djl/serving/ModelServer.java
- serving/src/main/java/ai/djl/serving/http/DescribeWorkflowResponse.java
- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
- serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
- serving/src/main/java/ai/djl/serving/models/ModelManager.java
- serving/src/main/java/ai/djl/serving/workflow/Workflow.java
- serving/src/test/java/ai/djl/serving/WorkflowTest.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java
- wlm/src/main/java/ai/djl/serving/wlm/util/WlmConfigManager.java
This modifies server to support models with workers on multiple devices rather
than using the previous system of having it as multiple models with versions
indicating the device. The models then share a single work queue. I tested it
with a queue per each device and found this way had slightly better performance.
As part of this, it also tries to replace ad-hoc device usages with actual
device. This includes systematically converting device names into Device and
storing device rather than device name or gpu boolean.
It also makes some changes to model loading. This moves the model loading to a
part of the workflow scaling. Because loading is device dependent, and you can
scale a model on multiple devices, the loading should occur during the scaling
for each device.
The remaining part of …
> Multi-device model support

- engines/python/setup/djl_python/inputs.py
- engines/python/setup/djl_python/outputs.py
- engines/python/setup/djl_python/test_model.py
Add test methods for handle functions and support more python use cases for output extractions. Support incoming inputs decoding. Sample request from client can send as:
```
def create_npz_request(list, key: str = None) -> Input:
request = Input()
request.properties["device_id"] = "-1"
request.properties["content-type"] = "tensor/npz"
memory_file = io.BytesIO()
np.savez(memory_file, *list)
memory_file.seek(0)
request.content.add(key=key, value=memory_file.read(-1))
return request
```
Customer can also construct the data on their own to build the client
> support more python use cases

- .github/workflows/nightly-publish.yml
Made a success run with current config: https://github.com/deepjavalibrary/djl-serving/actions/runs/2491303619
Currently the action runner registration API access requires Admin of DJL repo. I just offered mine one there.
> fix workflow jobs

- wlm/build.gradle
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
- wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java
Adds a new constructor for ModelInfo based on a Criteria. This can be used when
using the WLM as a standalone tool to create jobs to run.
> ModelInfo from Criteria

- serving/src/main/java/ai/djl/serving/models/ModelManager.java
- serving/src/test/java/ai/djl/serving/WorkflowTest.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
This modifies the WLM to require explicit registration. This makes a clearer
picture with the explicit unregister as well as the management APIcalls to
register both models and workflows.
> Add model registration to WLM

- serving/src/main/java/ai/djl/serving/ModelServer.java
- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
- serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
- serving/src/main/java/ai/djl/serving/util/ConfigManager.java
- serving/src/main/java/ai/djl/serving/workflow/WorkflowDefinition.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
- wlm/src/main/java/ai/djl/serving/wlm/util/WlmConfigManager.java
- wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java
- wlm/src/test/java/ai/djl/serving/wlm/WorkLoadManagerTest.java
This also moves some of the default model settings from ConfigManager to
WlmConfigManager. These settings are used in the standalone WLM so they need to
be available from it.
> Create test of standalone WLM

- serving/docker/scripts/install_python.sh
> [docker] numpy is required by djl python engine by default

- README.md
- benchmark/README.md
- benchmark/snapcraft/snapcraft.yaml
- engines/python/README.md
- serving/docker/Dockerfile
- serving/docker/README.md
- serving/docker/deepspeed.Dockerfile
- serving/src/test/java/ai/djl/serving/plugins/DependencyManagerTest.java
- wlm/README.md
Update to DJL 0.18.0 - this should be the last change needed before the serving 0.18.0 release.
Currently the Dockerfiles are using the SNAPSHOT djl repo by default - I updated deepspeed to do the same. The github action we're using overrides this default value with the one from gradle.properties, so I think this is ok.
> Upgrade to DJL  0.18.0

- .github/workflows/docker-nightly-publish.yml
- serving/docker/docker-compose.yml
When running the docker nightly publish action for 'release', there's currently a bug where the base image gets tagged as 'vX.X.X-' rather than 'vX.X.X'. This is causing failures in the 'Retag image for release' step. 
I think we want the base image for a given version to not have the trailing hyphen ('-'), so I've updated the image name as such.
This change should fix that issue
I tried running the Build and push docker nightly action for release to publish the 0.18.0* images to dockerhub.
For release, we set RELEASE_VERSION like `export RELEASE_VERSION="${DJL_VERSION}-"`. In this case it would be `0.18.0-`. 
When we build the cpu image for release, the resulting tag would be `0.18.0-` instead of `0.18.0` based on the logic for naming the image in the compose file …
> Fix issue with cpu image tag for docker release image

- gradle.properties
- serving/docker/Dockerfile
- serving/docker/aarch64.Dockerfile
- serving/docker/deepspeed.Dockerfile
- serving/docker/pytorch-cu113.Dockerfile
- serving/docker/pytorch-inf1.Dockerfile
bump djl version so nightly image builds use latest snapshot. 
It's expected that some of the checks fail due to not having the 0.19.0-SNAPSHOT serving artifacts in maven. We need to run the "serving publish" action from djl after this has been merged, and then run the actions in this repo to verify. 
Alternatively I could push this change to a different branch, modify the workflow in djl on a separate branch to checkout the corresponding serving branch and run the action that way to validate before merging this to master.
> bump to latest djl snapshot version

- benchmark/build.gradle
- gradle.properties
This fixes the gradle detection of hardware to enable onnxruntime to run on GPU
that was lost in the move of djl-bench from DJL to DJL Serving.
> Fix OnnxRuntime Benchmark on GPU

- serving/docker/deepspeed.Dockerfile
Upgrade DeepSpeed version to its latest.
This solves GPT-J-6B model inference issues
> update deepspeed version

- benchmark/snapcraft/snapcraft.yaml
Publishing to snapcraft failed due to dangling symlink. After some research, it seems like the solution described here works and might be the best solution. 
Open to other ideas as well.
> update snapcraft file to use correct repo and remove dangling symlink

- benchmark/README.md
since djl-bench has been removed from homebrew-cask, update the instructions for macOS to use zip file for djl-bench
> Update macOS instructions to download from zip

- benchmark/src/main/java/ai/djl/benchmark/WlmBenchmark.java
- serving/src/main/java/ai/djl/serving/ModelServer.java
- serving/src/main/java/ai/djl/serving/http/DescribeWorkflowResponse.java
- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
- serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
- serving/src/main/java/ai/djl/serving/models/ModelManager.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
- serving/src/test/java/ai/djl/serving/WorkflowTest.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkerGroup.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkerPool.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java
- wlm/src/main/java/ai/djl/serving/wlm/util/WlmConfigManager.java
- wlm/src/test/java/ai/djl/serving/wlm/WorkLoadManagerTest.java
1. If engine name is not specified, currently use MXNet to detect default device. We should differ to scale worker time, so we can use correct engine to find default device.
2. When unregister to model, if model is loaded on non-default device, we always load the model on default device and then unregister. This causing confusion.
3. Scale worker API is broken for workflow, new behavior will scale per device, if device is not provided, scale for all loaded devices.
4. Scale worker API now allow you to scale worker for a new device which model was not loaded on.
5. Auto scaling now is per device configuration (GPU and CPU has different default maxWorkers)
6. Fixes describeWorkflow API, it shows Unhealthy due to mis-calcuated minWorkers
7. DescribeWorkerflow API will show WorkGroup …
> [serving] Change scale worker per device

- benchmark/src/main/java/ai/djl/benchmark/WlmBenchmark.java
- serving/src/main/java/ai/djl/serving/ModelServer.java
- serving/src/main/java/ai/djl/serving/models/Endpoint.java
- serving/src/main/java/ai/djl/serving/models/ModelManager.java
- serving/src/main/java/ai/djl/serving/workflow/Workflow.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
- serving/src/test/java/ai/djl/serving/WorkflowTest.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkerPool.java
- wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java
- wlm/src/test/java/ai/djl/serving/wlm/WorkLoadManagerTest.java
1. We are only using try-with-resource in our unit test code
2. AutoClosable suppose to be closed with try-catch on every reference, but it is not fessible in most cases
3. The close() function is very hard to find usage in IDE
4. IDE gave a lot of warning due to the class is not used with try-with-resource style
> [wlm] Removes AutoClosable for ModelServer, Endpoint and Workflow

- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
Fixes #184
Uses workaround described in https://github.com/diffplug/spotless/issues/834
and found in
https://github.com/diffplug/spotless/tree/main/plugin-gradle#google-java-format.
> Updates to gradle 7.5 and fix formatter

- plugins/management-console/build.gradle
> [ci] fix npmInstall in case nodejs is not installed

- serving/docker/deepspeed.Dockerfile
> [deepspeed] Update default timeout for deepspeed docker

- engines/python/setup/djl_python/deepspeed.py
- engines/python/src/test/resources/gpt2/README.md
- engines/python/src/test/resources/gpt2/model.py
- engines/python/src/test/resources/gpt2/serving.properties
> [python] Adds built-in DeepSpeed handler

- README.md
- serving/docs/architecture.md
- serving/docs/starting.md
Reorganizes the docs to separate the starting and architecture pages. This gives them more room to grow and can be cleaner from the new docs section.
Related to https://github.com/deepjavalibrary/djl/pull/2100
> Reorganize docs

- serving/docker/scripts/security_patch.sh
- tests/integration/launch_container.sh
6 min is the default DJL model loading timeout, just make it consistent with test. 2 min seemed to be too tight
> [Integration] make 6 min timeout per model

- benchmark/src/main/java/ai/djl/benchmark/Benchmark.java
- serving/src/main/java/ai/djl/serving/util/ConfigManager.java
> [serving] Sets default ONNXRuntime OMP threads to 1

- .github/workflows/client-test.yml
- gradle.properties
- serving/src/main/java/ai/djl/serving/workflow/Workflow.java
- serving/src/main/java/ai/djl/serving/workflow/WorkflowExpression.java
- serving/src/main/java/ai/djl/serving/workflow/function/EnsembleMerge.java
- serving/src/main/java/ai/djl/serving/workflow/function/FunctionsApply.java
- serving/src/main/java/ai/djl/serving/workflow/function/IdentityWF.java
- serving/src/main/java/ai/djl/serving/workflow/function/ModelWorkflowFunction.java
- serving/src/main/java/ai/djl/serving/workflow/function/WorkflowFunction.java
- serving/src/test/java/ai/djl/serving/WorkflowTest.java
- serving/src/test/resources/workflows/ensemble.json
This creates a test for an ensemble workflow. As part of it, it also modifies the workflow expression evaluation to return an Item instead of an Input. This is primarily so that a list can be returned. It is useful for more logical or control flow functions like map, filter, functionsApply, etc.
It also creates two new built-ins: ensemble and functionsApply.
Lastly, the dependency on Ensembleable means that the current version of DJL Serving must depend on DJL 0.20.0 (including as snapshot).
> Create an ensemble workflow

- .github/workflows/client-test.yml
- .github/workflows/codeql-analysis-java.yml
- .github/workflows/continuous.yml
- .github/workflows/integration.yml
- .github/workflows/pyunit.yml
1. Upgrade checkout@v3
2. Upgrade codeql-action@v2
3. Upgrade cache@v3
4. Upgrade setup-python@v4
5. Upgarde upload-artifact@v3
> [ci] Upgrade deprecated github actions

- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
> fix typo in Pymodel mpi log

- engines/python/setup/djl_python_engine.py
In python mode, the TP passed from the property is always None given this is not passed from parameters.
> [Python] fix potential None on TP degree

- serving/docker/deepspeed.Dockerfile
- serving/docker/deepspeed.config.properties
- serving/src/main/java/ai/djl/serving/ModelServer.java
> [serving] Avoid using special config.properties for DeepSpeed

- engines/python/setup/djl_python/deepspeed.py
- engines/python/setup/djl_python/stable-diffusion.py
- serving/docker/deepspeed.Dockerfile
This PR adds support for built in handlers to serve models using the DeepSpeed engine.
2 handlers are added/modified:
- Stable Diffusion handler
- Transformer/LLM handler
Testing for Stable Diffusion and most language models except bloom have been tested. Things left to be done:
- Stable Diffusion is a separate handler as I felt it was cleaner this way. It is different enough that implementing it within a generic deepspeed handler felt messy. But, right now it's tied to DS so we may want to modify it so it can work with accelerate or deepspeed
- Currently I have only tested the text2image task from HF. Others should be easy to add, but might require additional input/output processing
- In the deepspeed handler
- Support user supplied injection policy 
- Support user provided MPU
- Better …
> [WIP] Updating deepspeed handler for more models

- engines/python/setup/djl_python/inputs.py
- engines/python/setup/djl_python/outputs.py
- engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
- engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
- engines/python/src/test/resources/echo/model.py
- engines/python/src/test/resources/resnet18/model.py
- serving/src/main/conf/config.properties
> [python] Add dynamic batching feature to python engine

- serving/docker/Dockerfile
- serving/docker/aarch64.Dockerfile
- serving/docker/deepspeed.Dockerfile
- serving/docker/paddle-cu112.Dockerfile
- serving/docker/pytorch-cu117.Dockerfile
- serving/docker/pytorch-inf1.Dockerfile
Allows user run DJL docker image as non-root user
> [docker] Adds non-root user to docker

- serving/docker/Dockerfile
- serving/docker/aarch64.Dockerfile
- serving/docker/deepspeed.Dockerfile
- serving/docker/paddle-cu112.Dockerfile
- serving/docker/pytorch-cu117.Dockerfile
- serving/docker/pytorch-inf1.Dockerfile
- serving/docker/scripts/install_djl_serving.sh
1. Upgrades PyTorch to 1.13.0
2. Upgrades TensorFlow to 2.7.4
3. Removes dandling logs in docker
4. Removes 0.19.0 workaround
5. Fixes /opt/djl folder permission
> [docker] Update PyTorch/TensorFlow version

- engines/python/setup/djl_python/np_util.py
- engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
- engines/python/src/test/resources/resnet18/model.py
> [python] Adds .npz input support for Python engine

- .github/workflows/integration.yml
- tests/integration/.gitignore
- tests/integration/download_models.sh
- tests/integration/launch_container.sh
- tests/integration/test_client.sh
1. Adds dynamic batching test for Python model
2. Adds npz/ndlist test fro Python model
3. Adds PyTorch binary model tests
4. Adds dynamic batching test for PyTorch model
> [serving] Adds a few more integration tests

- engines/python/setup/djl_python/stable-diffusion.py
It seems like the type check used for self.data_type to determine kwargs was incorrect, leading to pipeline being initialized as one data type, and ds inference trying to use another data type (always defaults to fp32). This should fix that issue and use the data type the user provides.
Before this change, model would start fine, but during inference there is an issue with invoking a triton op due to mismatched data type. Tested this change on g5 and it should work as expected.
> fix issue in sd handler with data type

- .github/workflows/llm_integration.yml
- engines/python/setup/djl_python/stable-diffusion.py
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
1. Fix issues with fp32 dtype for stable diffusion via deepspeed. There are 2 things that get fixed:
- If dtype is not specified (i.e. None) when passed to ds init inference and `replace_with_kernel_inject=True` and `replace_method='auto'`, then ds will invoke fp16 layers and fused kernels. If fp32 is specified with the same configurations otherwise, there will be an error due to not having fused kernels/layers to replace with (fp32 kernels for stable-diffusion layers are not implemented in ds 0.7.5)
- In our fork with bf16, due to some logic changes about replacing layers, there is an error in the case dtype=None rather than silently failing and using fp16 like the original deepspeed behavior
- Stable diffusion kernels for fp32, as well as some ops not being set for layer replacement …
> Fix fp32 issues with DS fork wheel for stable diffusion, fix llm tests

- serving/build.gradle
- serving/src/main/java/ai/djl/serving/workflow/WorkflowDefinition.java
- serving/src/test/java/ai/djl/serving/WorkflowTest.java
> [serving] Make yaml support optional

- README.md
- benchmark/snapcraft/snapcraft.yaml
- engines/java/README.md
- engines/python/README.md
- gradle.properties
- serving/docker/Dockerfile
- serving/docker/README.md
- serving/docker/aarch64.Dockerfile
- serving/docker/deepspeed.Dockerfile
- serving/docker/paddle-cu112.Dockerfile
- serving/docker/pytorch-cu117.Dockerfile
- serving/docker/pytorch-inf1.Dockerfile
- serving/src/test/java/ai/djl/serving/plugins/DependencyManagerTest.java
- wlm/README.md
> Bump up on repository versions

- serving/src/main/java/ai/djl/serving/workflow/WorkflowDefinition.java
This provides a better error message for the requirements to parse yaml files that clearly indicate what to change in order to support it.
Improves on the error message given in #393.
> Improve snakeyaml error message

- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
Workaround on SageMaker readonly disk
> add fix to workaround SageMaker changes

- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
Minor improvements to s5cmd process execution. Unfortunately, s5cmd does not return non-zero exit codes for every failure (like no credentials found). Alternatively we could process stdout and stderr separately, and if stderr is nonempty we assume ERROR and throw an exception. 
For now, all output will be logged and when s5cmd returns non-zero exit code we'll fail.
> Add better logging and error handling for s5cmd process execution

- gradle.properties
> [ci] Upgrades testng version to 7.7.0 to fix CVE

- serving/docker/Dockerfile
- serving/docker/aarch64.Dockerfile
- serving/docker/pytorch-cu117.Dockerfile
DeepSpeed and inf1 is still on 1.12.1
> [docker] Upgrade PyTorch to 1.13.1

- serving/docker/fastertransformer.Dockerfile
Copy gemm config binaries generated during build to system directory.
FasterTransformer suggests to run these binaries like for e.g
`./bin/t5_gemm 8 4 32 512 8 64 2048 512 8 64 2048 32128 0 2 1` to
generate the best GEMM configuration for a given model config and record the configuration into the gemm_config.in file. This change packages these binaries in the container to give users option to run these optimization.
Without running this, FT throws a warning: `[WARNING] gemm_config.in is not found; using default GEMM algo`
> copy gemm config computation binaries to sys directory

- README.md
- benchmark/README.md
- benchmark/build.gradle
- benchmark/snapcraft/snapcraft.yaml
- benchmark/src/main/java/ai/djl/benchmark/Benchmark.java
- plugins/management-console/webapp/src/view/Dependency.vue
- serving/docs/configurations.md
- serving/src/main/java/ai/djl/serving/ModelServer.java
- serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java
- serving/src/main/puml/architecture.puml
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
> [docs] Remove DLR from documents

- engines/python/src/main/java/ai/djl/python/engine/Connection.java
- serving/src/main/java/ai/djl/serving/util/NettyUtils.java
> [serving] Print better stacktrace if channel is closed

- engines/python/setup/djl_python/deepspeed.py
- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/stable-diffusion.py
- serving/docker/deepspeed.Dockerfile
Updating the deepspeed handlers for 0.8.0. Minimal changes are required to support the current functionality.
So far I have tested gptj-6b with fp16, fp32, bf16 with no issues.
In 0.8.0, Deepspeed has changed how the replacement of layers works. Only 1 of replace_method and injection_policy will be honored. Auto replacement seems to be working as expected now (previously it was broken for some model classes like opt), so we defer to that.
Remaining work pending wheel updates:
- int8 integration and corresponding testing
- Model loading from partitioned checkpoints
- Adding support for new ds configs related to quantization
Remaining enhancements:
- Support user provided injection policy
- Dynamic batching support (applies to all python handlers)
> Update python handlers for deepspeed 0.8.0

- .github/workflows/llm_integration.yml
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
stable-diffusion-2-1-base tests. Replaces the test for stable-diffusion-1-4 which is covered pretty much by the stable-diffusion-1-5. 
test files have been updated as well to reflect the new diffusers api changes (steps -> num_inference_steps)
> Add tests for stable-diffusion-2-1-base model

- engines/python/setup/djl_python/deepspeed.py
Tested the handler with opt-2.7b using both user supplied dtype in serving properties, and inferred dtype from model (not specified in serving.properties)
> Read dtype from hf model when not supplied in config

- serving/docker/deepspeed.Dockerfile
- serving/docker/scripts/install_aitemplate.sh
- tests/integration/llm/client.py
Build AI template package into the container
> add AI template package

- engines/python/setup/djl_python/deepspeed.py
- serving/docker/deepspeed.Dockerfile
- serving/docker/dockerd-entrypoint.sh
- serving/docker/partition/partition.py
- serving/docker/partition/properties_manager.py
- serving/docker/partition/run_partition.py
- tests/integration/llm/deepspeed-model.py
> Deepspeed AOT Partition in DLC

- serving/docker/partition/partition.py
- serving/docker/partition/properties_manager.py
- `engine` in serving.properties was written as `option.engine`. Removed the option config. 
- No need to specify `option.entryPoint` if the user provide their own model.py. So removed it.
> Generated serving.properties fix for AOT partition

- serving/docker/fastertransformer.Dockerfile
- serving/docker/scripts/security_patch.sh
Adds security patching to fastertransformer image - we need this in master as well as dlc branch so 2 prs are raised
It seems like we're doing the same set of patches for all of fastertransformer, deepspeed, pytorch-cu117 so i combined them into a single block (this makes sense to me since they all derive from the same base image, and we're patching the os libs- maybe we update the security patching to operate based on the base image?)
Same PR is raised for the dlc branch https://github.com/deepjavalibrary/djl-serving/pull/510
> Add security patching for fastertransformers image

- .github/workflows/docker-nightly-publish.yml
- .github/workflows/llm_inf2_integration.yml
- serving/docker/docker-compose.yml
- serving/docker/pytorch-inf2.Dockerfile
- serving/docker/scripts/install_inferentia2.sh
- tests/integration/launch_container.sh
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/llm/transformers-neuronx-gpt2-model.py
Adding inf2 container with support for LLMs available as part of [transformers-neuronx](https://github.com/aws-neuron/transformers-neuronx#currently-supported-models) module
- If this change is a backward incompatible change, why must this change be made? *N/A*
- Interesting edge cases to note here *N/A*
```
git clone https://github.com/maaquib/djl-serving/
cd djl-serving && git checkout inf2 && cd serving/docker
docker compose build pytorch-inf2
cd ../../tests/integration
python3 llm/prepare.py transformers_neuronx gpt2
./launch_container.sh deepjavalibrary/djl-serving:pytorch-inf2 `pwd`/models inf2 serve
python3 llm/client.py transformers_neuronx gpt2
```
```
docker pull deepjavalibrary/djl-serving:pytorch-inf2-nightly
git clone https://github.com/maaquib/djl-serving/
cd djl-serving && …
```
> Inf2 container with transformers-neuronx LLM support

- .github/workflows/llm_integration.yml
> [fix] requirements.txt install check testcase

- serving/docker/deepspeed.Dockerfile
min python version for https://github.com/huggingface/text-generation-inference is 3.9.
> update deepspeed container python version to 3.9

- .github/workflows/llm_inf2_integration.yml
- engines/python/setup/djl_python/transformer-neuronx.py
- engines/python/setup/djl_python/transformers-neuronx.py
- serving/docker/pytorch-inf2.Dockerfile
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
Adding `gptj` to transformers handler
- If this change is a backward incompatible change, why must this change be made? *N/A*
- Interesting edge cases to note here *N/A*
```
$ docker pull deepjavalibrary/djl-serving:pytorch-inf2-nightly
$ mkdir models
$ tee models/serving.properties > /dev/null <<EOF
option.s3url=s3://djl-llm/gpt-j-6b/
option.batch_size=4
option.tensor_parallel_degree=8
option.n_positions=512
option.dtype=fp32
option.model_loading_timeout=720
engine=Python
option.entryPoint=djl_python.transformer-neuronx
EOF
$ docker run -it --rm --network=host -v `pwd`/models:/opt/ml/model -v /home/ubuntu/djl-serving/tests/integration/logs:/opt/djl/logs -v /home/ubuntu/.aws:/home/djl/.aws -e TEST_TELEMETRY_COLLECTION=true -e MODEL_LOADING_TIMEOUT=7200 -e PREDICT_TIMEOUT=360 -u djl …
```
> [inf2] Adding gptj to transformers handler

- serving/docker/scripts/install_aitemplate.sh
- serving/docker/scripts/install_python.sh
This will help the installation of git-based python dependencies:
```
git+https://github.com/facebookincubator/AITemplate
git+https://github.com/huggingface/transformers
```
> install git by default for all python releases

- engines/python/src/main/java/ai/djl/python/engine/DsNDManager.java
- engines/python/src/main/java/ai/djl/python/engine/PyNDManager.java
- engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
> [serving] Removes 0.21.0 workaround.

- engines/python/setup/djl_python_engine.py
> [python] flush logging output before process end

- engines/python/setup/djl_python/service_loader.py
- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
- engines/python/src/test/resources/huggingface/serving.properties
- tests/integration/llm/prepare.py
> [serving] support load entryPoint with url

- engines/python/setup/djl_python/deepspeed.py
- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/stable-diffusion.py
- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
- serving/docker/partition/partition.py
- serving/docker/partition/properties_manager.py
- tests/integration/llm/prepare.py
- [serving] support load entryPoint with url
- [serving] deprecate s3Url and replace it with model_id
> [serving] deprecate s3Url and replace it with model_id

- engines/python/setup/djl_python/streaming_utils.py
In the [handler](https://github.com/deepjavalibrary/djl-serving/blob/master/engines/python/setup/djl_python/transformers-neuronx.py#L180) `seq_length` is set.
> Fix typo in streaming utils

- engines/python/src/main/java/ai/djl/python/engine/Connection.java
- engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
This fixes serving for changes from
https://github.com/deepjavalibrary/djl/pull/2470. Some more extensive changes should follow including using the servingPredict and PublisherBytesSupplier. To fix CI, they will be part of a separate PR.
> Minimal followup for BytesSupplier changes

- plugins/kserve/src/main/java/ai/djl/serving/kserve/KServeTensor.java
- plugins/kserve/src/test/java/ai/djl/serving/kserve/KServeTensorTest.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
Kserve data conversion to bytes was faulty. Fixed by conversion to bytes according to datatype. 
Renamed dataType -> datatype (lowercase T), as this was the requirement in v2 protocol. (https://kserve.github.io/website/0.8/modelserving/inference_api/#model-metadata-response-json-object)
> KServe data to bytes fix

- serving/src/main/java/ai/djl/serving/cache/CacheManager.java
- serving/src/main/java/ai/djl/serving/cache/package-info.java
- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
- serving/src/test/java/ai/djl/serving/translator/EchoTranslator.java
- serving/src/test/resources/echo/serving.properties
> Adds async inference API

- engines/python/setup/djl_python/deepspeed.py
- engines/python/setup/djl_python/huggingface.py
- tests/integration/llm/client.py
TLDR: Implements actual batch inference for text generation use cases
In our handlers we currently use the transformers `pipeline` interface to handle tokenization and generation. This abstraction is slow. When passing in a batch of inputs, the inputs get executed sequentially (the run_multi method is just a for loop of single forward passes) https://github.com/huggingface/transformers/blob/main/src/transformers/pipelines/base.py#L1085-L1112.
This PR changes the generation implementation only for text generation tasks to use the tokenizer encode/decode and model.generate methods directly. Doing so achieves true batch processing. This is compatible with both accelerate and deepspeed.
Follow up:
- I need to see whether we can apply this same implementation for other tasks. In particular, …
> Optimize batch inference for text generation

- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
- engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
Also avoid download the file into fixed location
> [python] Makes download entryPoint atomic

- serving/src/main/java/ai/djl/serving/cache/CacheEngine.java
- serving/src/main/java/ai/djl/serving/cache/CacheManager.java
- serving/src/main/java/ai/djl/serving/cache/MemoryCacheEngine.java
- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
- serving/src/main/java/ai/djl/serving/workflow/Workflow.java
- serving/src/main/java/ai/djl/serving/workflow/WorkflowDefinition.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
Splits the CacheManager into a CacheEngine interface along with a manager to manage a global cache. This then modifies the CacheEngine to also include a few additional pieces. It has a way to create a cache key before needing to store it which is used by the async and streaming sections. There is also some tentative features for multiTenant online caches.
It also modifies the InferenceRequestHandler's handling of async. Before, it wasn't actually asynchronous as it had to wait for the result to send the response. This sends the response before the computation is started.
Additionally, this PR also contains some changes adding a config to the Workflow system.
> Refactor CacheManager, Working Async

- serving/docker/deepspeed.Dockerfile
Updating the DeepSpeed version for the 0.21.0 dlc.
> [ci] bump up deepspeed version

- tests/integration/llm/client.py
https://github.com/deepjavalibrary/djl-serving/pull/586 introduced different behavior for processing batches of inputs for text generation. One impact this has on the llm tests is that the existing memory checks break for larger batch sizes.
This PR does 2 things to adjust the expected memory usage:
- we analyze memory usage based on the batch size (i.e. batch size directly impacts gpu usage)
- update expected memory usage numbers based on testing the models with updated handlers on g5.12xl
Only DS and HF tests are changed - ft, inf2 tests are not touched.
> Adjust expected mem usage by batch size for transformers and deepspeed

- engines/python/setup/djl_python/streaming_utils.py
Adds support for batch size > 1. If one sequence reaches end of sentence before others in the batch, pad_token is returned for that sequence for subsequent iterations. Working fine for bloom and opt models. Seems to be producing inaccurate output for gpt2 with unequal input lengths.
Next steps:
1. Add integration tests.
> Add support for streaming batch size > 1

- tests/integration/llm/client.py
Seq length 32 test case is hanging for unknown reason and the test job gets cancelled - https://github.com/deepjavalibrary/djl-serving/actions/runs/4679798912/jobs/8290368439
Same case works locally though.
Removing the test for now to unblock the tests.
> Remove hanging streaming test case

- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
- wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java
This PR adds support for inferring the specific Python engine to use. This logic should only be called when users don't specify engine in `serving.properties`, and we can reasonably assume the model is intended to be run with a Python backend.
Use Cases covered:
- User only specifies HF_MODEL_ID environment variable (no serving properties, model artifacts, or user code)
- User provides serving properties with model id (either hf hub id or s3 url), but does not specify engine
- model_id is not provided in any form, but model artifacts are present in model_dir
This does not support the use case where users provide their own code that is expected to be invoked via the hugging face inference toolkit. There's no special error handling for that now, it will just fail when the PyProcess tries to …
> Infer lmi engine

- wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
> [wlm] Moves LmiUtils.inferLmiEngine() into separate class

- serving/docker/pytorch-inf2.Dockerfile
- serving/docker/scripts/install_inferentia2.sh
Pinning `aws-neuronx-*` packages to 2.8 for Inf2 containers
- If this change is a backward incompatible change, why must this change be made? N/A
- Interesting edge cases to note here N/A
> Pinning aws-neuronx-* packages for Inf2 containers

- serving/docker/deepspeed.Dockerfile
DeepSpeed container failing on stable diffusion ci due to an error from triton 2.0 flash attention, pinning to 2.0.0.dev20221202 while we resolve.
> [fix] pin triton due to SD triton flash failing for deepspeed

- serving/docker/deepspeed.Dockerfile
The xformers package was added to improve SD performance, but requires torch 2.0.0 due to pip limitation. Since we downgraded and because we having added the SD performance optimization I want to remove the package for now, so that it no longer installs torch 2.0.0 and triton 2.0.0 when installed.
> [fix] removing xformers due to torch 2.0.0 deps

- tests/integration/llm/client.py
The no-code test client should not expect streaming output. With no code, we don't provide any serving.properties which means by default streaming is disabled. client should not try to read response in streaming fashion.
> Remove streaming from no-code test

- engines/python/setup/djl_python/huggingface.py
- tests/integration/llm/client.py
Two issues:
- memory expectations for the dollyv2 model were off. updated those based on testing
- no code experience for huggingface accelerate backend is broken. the huggingface handler expects that task is provided, or the model config is available locally. It didn't support just huggingface model id. Fixed that issue as well
other changes from ./gradlew formatPython
> Fix issues with no code default handlers and tests

- serving/src/main/java/ai/djl/serving/models/ModelManager.java
- serving/src/main/java/ai/djl/serving/workflow/Workflow.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
- serving/src/test/java/ai/djl/serving/WorkflowTest.java
- serving/src/test/resources/workflow.config.properties
- wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkerPool.java
- [serving] Adds workflow model loading for SageMaker
- Refactor workflow parsing
- [workflow] Allows model being shared between workflows
> [workflow] Allows model being shared between workflows

- serving/docker/dockerd-entrypoint.sh
- serving/docker/partition/partition.py
- serving/docker/partition/properties_manager.py
By default, Sagemaker training job, 
- invokes the docker container with entrypoint command `train`
- downloads the input model to `/opt/ml/input/data/` with the channel name `training`. So input model will be downloaded to `/opt/ml/input/data/training`
-  SM looks for the files in `/opt/ml/model` and upload it to s3 output url provided. 
AOT in SM using Estimator
```
from sagemaker.estimator import Estimator
algo = Estimator(
image_uri='125045733377.dkr.ecr.us-east-1.amazonaws.com/sm-test:smtrain_ft',
role='AmazonSageMaker-ExecutionRole-djl',
instance_count=1,
instance_type='ml.g5.12xlarge')
algo.fit('s3://djl-sm-test/models/opt-1.3b-ft/')
```
AOT using DJLModel
```
from sagemaker.djl_inference import DJLModel
djl_model = DJLModel(
"facebook/opt-1.3b", …
```
> SM Training job changes for AOT

- serving/docker/Dockerfile
- serving/docker/aarch64.Dockerfile
- serving/docker/deepspeed.Dockerfile
- serving/docker/fastertransformer.Dockerfile
- serving/docker/pytorch-cu118.Dockerfile
- serving/docker/pytorch-inf1.Dockerfile
- serving/docker/pytorch-inf2.Dockerfile
will push to dlc branch  as well once approved
> Create model dir to prevent issues with no code experience in SageMaker

- .github/workflows/llm_integration.yml
- tests/integration/launch_container.sh
Test run https://github.com/deepjavalibrary/djl-serving/actions/runs/4834079393/jobs/8614905302. 
Although it failed, the issue was with the model name when it was registered (default is model, we expect test). I updated the workflow to match the expected model name on the client side.
Functionally, the test run showed these changes worked.
> Don't mount model dir for no code tests

- .github/workflows/llm_integration.yml
- tests/integration/launch_container.sh
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
Adding tests cases for some for SM Training Job.
- Test AOT with and without passing any model_dir argument 
- Invoke AOT by using the command `train`
- Test cases for upload the partitioned checkpoints to S3
- Adding a few testcases for DeepSpeed with Default handler
> AOT upload checkpoints tests

- serving/docker/pytorch-inf2.Dockerfile
Unset OMP thread to prevent CLIP model delay issue on Stable Diffusion
> unset omp thread to prevent CLIP model delay

- .github/workflows/llm_inf2_integration.yml
- engines/python/setup/djl_python/stable_diffusion_inf2.py
- engines/python/setup/djl_python/transformers-neuronx.py
- serving/docker/pytorch-inf2.Dockerfile
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
port the Stable Diffusion support to INF2 release on 0.22.1
> add stable diffusion support on INF2 (#683)

- .github/workflows/lmic_performance.yml
- tests/integration/launch_container.sh
- tests/integration/lmic_test_builder.py
Update the performance pipeline to run all tests in parallel, uses 4 instances total, 3x g5.12x and 1x g5.48x. Additionally, shortened the llm container setup timeout, since some models are ready earlier than the original 5 minute timer.
> [ci] make performance tests run in parallel

- .github/workflows/hf_tgi_integration.yml
> [tgi] Add more models to TGI test pipeline

- .github/workflows/llm_inf2_integration.yml
- engines/python/setup/djl_python/stable_diffusion_inf2.py
- tests/integration/llm/prepare.py
Add BF16 supporting to Stable Diffusion
> [INF2] add bf16 support to SD

- serving/src/main/java/ai/djl/serving/ModelServer.java
- wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
- wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java
Will move out of draft once tested.
This PR fixes a couple issues:
- Right now, MME is broken through the docker containers due to creation of /opt/ml/model path (model store). The startup of the model server fails when no models are present
- LMI Engine Selection is also incomplete. We should support auto detection of engine when either HF_MODEL_ID env var provided, or option.model_id is present in serving.properties.
To fix these issues, we create model properties when HF_MODEL_ID is present in a tmp model store, and remove the creation of model store from the docker container.
> Refactor logic for supporting HF_MODEL_ID to support MME use case

- .github/workflows/lmic_performance.yml
Changing the start time to no longer conflict with other tests using the g5.48x from the capacity reservation, and adding opt to the large instance rather than the g5.12x
> [ci] reconfigure performance test time and machines

- .github/workflows/llm_integration.yml
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
> Add seq2seq streaming integ test

- gradle/wrapper/gradle-wrapper.properties
- tools/gradle/check.gradle
> [ci] Upgrade jacoco to 0.8.8 to support JDK17+

- serving/docs/architecture.md
Documentation only. Adding a link to the high-level documentation including module, library, dependency and other diagrams (https://sourcespy.com/github/deepjavalibrarydjlserving/). Intended to simplify new developer's introduction to the project.
In the spirit of transparency - I am the author of the generated diagrams. Hope contributors find it useful.
> Adding project diagrams link to architecture.md

- engines/python/src/main/java/ai/djl/python/engine/Connection.java
- engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
- serving/src/main/java/ai/djl/serving/cache/BaseCacheEngine.java
- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
This adds support for the PublisherBytesSuppllier in addition to the ChunkedBytesSupplier for asynchronous support in model outputs and in the BaseCacheEngine. The advantage of using it is that it avoid having to wait on the thread. Therefore, this further switches the PyEngine to using the new PublisherBytesSupplier.
> Asynchronous with PublisherBytesSupplier

- .github/workflows/sagemaker-integration.yml
- tests/integration/llm/sagemaker-endpoint-tests.py
The main change is adding single gpu MME test case with DeepSpeed image.
I also refactored the script slightly to do the following:
- cleanup any dangling resources from the tests at the end of the workflow
- cleanup s3 model artifacts during the tests. Deleting a sagemaker model still leaves the artifacts in S3
- standardize naming of resources so that the cleanup is simple
Testing:
- MME tests are successful in this run, but I want to do one more full run with all the changes to make sure i didn't break anything else. https://github.com/deepjavalibrary/djl-serving/actions/runs/5083982768/jobs/9135696386
Follow Up:
- I'll raise another PR that better supports running the nightly images from alpha ecr
> Add mme tests to sagemaker tests

- tests/integration/llm/sagemaker-endpoint-tests.py
Fix couple issues with using session object of pysdk. 
Also remove check on number of models registered with mme - this can be flaky if multiple runs are happening in parallel, or during personal testing some artifacts are not cleaned up.
> fix typos with get default bucket prefix for sm session

- wlm/src/main/java/ai/djl/serving/wlm/util/WlmConfigManager.java
> [wlm] Sets default maxWorkers based on OMP_NUM_THREADS

- .github/workflows/sagemaker-integration.yml
- tests/integration/llm/sagemaker-endpoint-tests.py
> Upload SM benchmark metrics to cloudwatch

- tests/integration/llm/client.py
- tests/integration/llm/sagemaker-endpoint-tests.py
> Fixes integration test

- engines/python/setup/djl_python/streaming_utils.py
- engines/python/setup/djl_python/transformers-neuronx.py
Add TNX streaming generation for HuggingFace No-KV interface
> [Stream] use huggingface standard generation for tnx

- engines/python/setup/djl_python/deepspeed.py
- engines/python/setup/djl_python/huggingface.py
> add trust remote code option

- .github/workflows/sagemaker-integration.yml
- engines/python/setup/djl_python/transformers-neuronx.py
- tests/integration/llm/sagemaker-endpoint-tests.py
This adds nightly image testing to sagemaker endpoints. With this we now have most permutations covered for testing our changes with sagemaker:
- Testing changes in DLCs via nightly/release images. nightly images are from alpha ecr, release images are the publically available ones in DLC accounts
- Testing changes in SageMaker Python SDK dev forks. Any changes we introduce to the sagemaker python sdk can now be fully tested before PRs
> Add support for testing nightly images in sagemaker endpoint tests

- wlm/src/main/java/ai/djl/serving/wlm/util/WlmConfigManager.java
> [wlm] Sets default maxWorkers the same as earlier version

- .github/workflows/llm_integration.yml
Scheduler does not have the options to get inputs. Inputs are only seems to be available in worflow_dispatch. 
So, made the default value of run_test to be empty. Even if input is not even provided, github seems to set the input param name empty by default.  
Testing:
I removed the whole run_test input for yaml and ran the workflow,  github.event.inputs.run_test env variable is validated to be empty. So the tests were not skipped.
https://github.com/deepjavalibrary/djl-serving/actions/runs/5158317906
> [Fix] [CI/CD] Check if input is empty

- .github/workflows/sagemaker-integration.yml
Typo in default value of mode was causing issues starting the python script. This should fix that, I kicked off a run here with the changes and it seems to be working so far https://github.com/deepjavalibrary/djl-serving/actions/runs/5191566105
> fix typo in sm workflow inputs

- engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
- engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkerPool.java
For python worker, PyProcess is recreated for each worker, restart count is lost.
which lead the model is never marked as failure, and PING will alwasy report healthy.
> [python] Fixes retry_threshold bug

- serving/docker/deepspeed.Dockerfile
- serving/docker/fastertransformer.Dockerfile
- serving/docker/pytorch-cu118.Dockerfile
- serving/docker/pytorch-inf2.Dockerfile
Add PT kernel cache to prevent
```
WARN  PyProcess [1,2]<stderr>:/usr/local/lib/python3.9/dist-packages/transformers/generation/utils.py:2667: UserWarning: Specified kernel cache directory could not be created! This disables kernel caching. Specified directory is /root/.cache/torch/kernels. This warning will appear only once per process. (Triggered internally at ../aten/src/ATen/native/cuda/jit_utils.cpp:1442.)
WARN  PyProcess [1,2]<stderr>:  next_tokens.tile(eos_token_id_tensor.shape[0], 1).ne(eos_token_id_tensor.unsqueeze(1)).prod(dim=0)
WARN  PyProcess [1,0]<stderr>:/usr/local/lib/python3.9/dist-packages/transformers/generation/utils.py:2667: UserWarning: Specified kernel cache directory could not be created! This disables kernel caching. Specified directory is …
```
> add pytorch kernel cache default directory

- serving/docker/partition/partition.py
- serving/docker/partition/properties_manager.py
- serving/docker/partition/utils.py
In the last PR, 'option' keyword was not removed until the control is passed to model.py. Looking up every keyword with option keyword. 
This should also fix the actions failure. Tested it manually.
> [partition] keep 'option' in properties

- .github/workflows/llm_integration.yml
Flan T5 is replaced with nomic-ai/gpt4all-j recently. And this model is already tested in `ft-aot-raw-test`. So removing it here.
> Remove flan-t5-xxl

- engines/python/setup/djl_python/fastertransformer.py
- tests/integration/llm/fastertransformer-model.py
- tests/integration/llm/prepare.py
- wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
> [python] Makes gpt-j model use triton mode

- .github/workflows/sagemaker-integration.yml
- tests/integration/llm/sagemaker-endpoint-tests.py
This change migrates the sagemaker endpoint tests to us-west-2 due to instance availability issues in us-east-1. 
The changes for this test are working as expected, but there are other unrelated failures due to some issues with ahead of time partitioning, and some safetensors issues with fastertransformer.
https://github.com/deepjavalibrary/djl-serving/actions/workflows/sagemaker-integration.yml
The actual failures will be investigated an triaged with separate prs
> Migrate sagemaker endpoint tests to us-west-2

- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
- tests/integration/llm/prepare.py
- wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
- wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java
This changes moves the default tensor parallel number detection from LmiUtils to PyModel. As a result, we now fix an issue where a model defined like this would not work.
```
engine=DeepSpeed
option.model_id=<model_id>
```
I've modified the integration tests to test this case across the 3 engines.
One thing to note for this change, is that we default to maximizing the gpus for both mpi mode and non mpi mode. For non mpi mode, the value of tensor parallel doesn't matter. We just use the fact that tp > 0 to determine which device map to set (if a device map is not specified by the user). 
This change does break the above example when using gpt2-xl. While that's technically a regression, this model is so small that I would argue it should only be used on a single gpu. To fix this (and make …
> Move tp detection logic to PyModel from LmiUtils

- .github/workflows/llm_integration.yml
- engines/python/setup/djl_python/deepspeed.py
- serving/docker/deepspeed.Dockerfile
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
Update to deepspeed container, adds and pins protobuf 3.20.3 as a dependency for conversion of the fast llama tokenizer. Adds integration tests for llama using HF accelerate and DS.
--Edit: Now uses fused kernels
> [docker] add llama support and integration tests

- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/__init__.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
- engines/python/setup/djl_python/scheduler/__init__.py
- engines/python/setup/djl_python/scheduler/lm_block.py
- engines/python/setup/djl_python/scheduler/search_config.py
- engines/python/setup/djl_python/scheduler/seq_batch_scheduler.py
- engines/python/setup/djl_python/tests/test_scheduler.py
- engines/python/setup/djl_python/tests/test_scheduler_bloom.py
- engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java
- serving/docker/partition/properties_manager.py
> Rolling batch for huggingface handler

- engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
- engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
- engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
- engines/python/src/test/resources/venv/requirements.txt
- engines/python/src/test/resources/venv/serving.properties
- serving/docker/scripts/install_python.sh
- serving/docs/modes.md
Create model-specific virtualenv. I discussed with Frank about two options:
1. Option 1: Create a virtual environment on the fly for each model.
2. Option 2: Pre-create a pool of n virtual environments and allocate one to each model.
In my experiment, the time creating the venv on the fly is not noticeable. So I had this PR for option 1.
> [python] Create model level virtualenv

- engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
- engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
- engines/python/src/test/java/ai/djl/python/engine/PyEnvTest.java
- engines/python/src/test/resources/venv/requirements.txt
- engines/python/src/test/resources/venv/serving.properties
> Refactor createVirtualEnv()

- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/rolling_batch/__init__.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
- engines/python/src/test/resources/rolling_batch/serving.properties
> [python] Rolling batch support for flash models

- engines/python/src/main/java/ai/djl/python/engine/MpiEngineProvider.java
- engines/python/src/main/resources/META-INF/services/ai.djl.engine.EngineProvider
Use MPI Engine for generic Distributed environment name
> add MPI Engine as generic name for distributed environment

- .github/workflows/llm_integration.yml
- engines/python/setup/djl_python/deepspeed.py
- engines/python/setup/djl_python/huggingface.py
- serving/docker/deepspeed.Dockerfile
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
This PR adds support for single adapter Lora models. Support is added for both huggingface accelerate, and deepspeed. 
This is achieved by leveraging the merge_and_unload() method of PeftModel, which adds the lora checkpoints into the base model, and unwraps it out of the peft context so it can be used/understood by deepspeed. It becomes a regular model in the sense that DeepSpeed (and FT in theory) can understand it.
To add support for FasterTransformer, I have to check that code to see whether this is feasible. It's not doable from the handler.
There are no changes or additional configurations that need to be set to use a peft model with djl serving. It's the same UX as any other model, just pass in your peft_model_id as option.model_id and everything should work.
> Add peft support to default deepspeed and huggingface handlers

- serving/docker/fastertransformer.Dockerfile
- tests/integration/llm/client.py
> add peft to fastertransformer container

- engines/python/setup/djl_python/scheduler/lm_block.py
- engines/python/setup/djl_python/tests/test_scheduler_bloom.py
- engines/python/setup/setup.py
The falcon models tiiuae/falcon-40b tiiuae/falcon-7b require special handling of the kv_cache, done in FalconBlock.
```
```
Note:
The tokenizer of falcon models have bug. It cannot tokenize two strings with different lengths.
> Falcon support

- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
Add vLLM rolling batch implementation
> [VLLM] add vllm rolling batch and add hazard handling

- engines/python/src/main/java/ai/djl/python/engine/Connection.java
- engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
> [serving] Fixes invalid CUDA_VISIBLE_DEVICE bug

- plugins/cache/src/test/java/ai/djl/serving/cache/CacheEngineTest.java
- serving/src/main/java/ai/djl/serving/cache/BaseCacheEngine.java
Fixes a bug that occur when streaming with the PublisherBytesSupplier and adds additional testing.
> Fix PublisherBytesSupplier

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
> Fix skip special tokens in lmi-dist

- serving/docker/deepspeed.Dockerfile
Update deepspeed dockerfile to target the nightly ds wheel, and bump transformers to 4.30.2, diffusers to 0.16.0 (17+ fails for deepspeed stable diffusion), accelerate 0.20.3.
> [docker] Update deepspeed docker to nightly wheel

- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
> [python] Refactor output formatter for rolling batch

- engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
do_sample comes from each request from the user like below. It should be expected as a bool.
```
'{"inputs": "The new movie that got Oscar this year", 
"parameters":{"max_new_tokens" : 256, "do_sample": true}}
```
Todo: Need to add validations for these input parameters of each request.
> Fix do sample type

- engines/python/setup/djl_python/huggingface.py
Current HF handler sets self.device to None when running on multiple GPU's, but our wrapped pipeline uses self.device for moving the input tokens to the device. Since this is None we needed another control path for getting the input tokens onto the GPU. The current implementation leaves the input tokens on CPU, degrading the performance.
> [fix] add current device for tp > 1 scenario on huggingface handler

- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
> [python] Only override minWorkers when tp > 1

- tests/integration/profiles/opt_30b.json
Removing the 512 token performance test due to oom on gpu 0 using accelerate.
> [ci] remove oom tests for hf accelerate performance

- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
> [serving] Disconnect client when streaming timed out

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
> [python] Fix the default value for rolling batch request parameters

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
Allows overriding the default 1000 value for truncation in the request parameters
> Allow overriding truncate parameter in request

- .github/workflows/llm_inf2_integration.yml
- engines/python/setup/djl_python/transformers-neuronx.py
- serving/docker/pytorch-inf2.Dockerfile
- tests/integration/launch_container.sh
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
* [tnx] Update handler for 2.12 supported models
* [tnx] rewrite handler for 2.12.0 upgrade
* [docker] bump tnx image to 2.12.0
* [ci/cd] Add newly supported tnx models to ci/cd
* [fix] add use_sample from spec in handler test
(cherry picked from commit 6d42f75386cd870c1a3266418a054243d44ea92e)
> [serving] Update tnx handler for 2.12 supported models

- tests/integration/llm/client.py
- tests/integration/profiles/opt_30b.json
> [ci] Update client for llama inf2 and move hf testing off for opt performance testing

- serving/build.gradle
- serving/src/main/conf/log4j2-console.xml
- serving/src/main/conf/log4j2-plain.xml
1. disable color highlight with log4j-plain.xml
2. enable log server and model metrics to console
> [serving] Adds more built-in logging options

- .github/workflows/llm_inf2_integration.yml
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
Fix inf2 bloom test to single worker for timeout issues.
> [ci] Use smaller instance for inf2 bloom test

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- serving/docker/deepspeed.Dockerfile
- serving/docker/scripts/install_flash_attn.sh
- serving/docker/scripts/install_flash_attn_v2.sh
> [python] Update lmi-dist

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
> [python] Make paged attention configurable

- .github/workflows/llm_integration.yml
Changing name of integration test to no-code-test to better represent the system under test. HF models have also been moved to s3 so that we do not get flakiness due to downloading models from hf_hub.
> [ci] move no-code models to s3 to avoid hub download failure

- .github/workflows/client-test.yml
- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/inputs.py
> [python] validate each request in the batch

- engines/python/setup/djl_python/streaming_utils.py
Batch decode sometimes trimmed the output spaces, this will prevent that
> [HF Streaming] use decode instead batch decode for streaming

- serving/docker/pytorch-cu118.Dockerfile
> [docker] disable TORCH_CUDNN_V8_API_DISABLED for PyTorch 2.0.1

- serving/src/main/java/ai/djl/serving/models/ModelManager.java
- serving/src/test/java/ai/djl/serving/WorkflowTest.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkerGroup.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkerPool.java
- wlm/src/main/java/ai/djl/serving/wlm/util/WlmConfigManager.java
This unifies the handling of min/max workers into the two pieces of WorkerGroup and ModelInfo. The source becomes clearly sourced from modelInfo unless a default is passed during a WorkerGroup creation through a scaling call. Before, there were more layers of passed in data and defaults in ways that were difficult to track.
> Simplify handling of min/max workers

- serving/docs/configurations.md
> [docs] Adds log4j configuration document

- engines/python/setup/djl_python/tests/run_rolling_batch_alone.py
- tests/integration/llm/prepare.py
> add data collection and some inf2 bug fixes

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
This reverts commit 7f9b9a8cb0e141f7b147fd265550184e552571ee.
> Revert "Change rolling batch generations order (#1046)"

- benchmark/src/main/java/ai/djl/benchmark/WlmBenchmark.java
- plugins/kserve/src/main/java/ai/djl/serving/kserve/KServeRequestHandler.java
- serving/docs/architecture.md
- serving/src/main/java/ai/djl/serving/http/DescribeWorkflowResponse.java
- serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
- serving/src/main/java/ai/djl/serving/models/ModelManager.java
- serving/src/main/java/ai/djl/serving/workflow/Workflow.java
- serving/src/main/java/ai/djl/serving/workflow/WorkflowDefinition.java
- serving/src/main/java/ai/djl/serving/workflow/function/WlmWorkflowFunction.java
- serving/src/main/puml/frontend.puml
- serving/src/main/puml/wlm.puml
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
- serving/src/test/java/ai/djl/serving/WorkflowTest.java
- wlm/src/main/java/ai/djl/serving/wlm/BatchAggregator.java
- wlm/src/main/java/ai/djl/serving/wlm/Job.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
- wlm/src/main/java/ai/djl/serving/wlm/PermanentBatchAggregator.java
- wlm/src/main/java/ai/djl/serving/wlm/TemporaryBatchAggregator.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkerGroup.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkerPool.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkerPoolConfig.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java
- wlm/src/test/java/ai/djl/serving/wlm/WorkLoadManagerTest.java
This is a decent change I wanted to get some early feedback on. It still needs a
bit of clean up, and I am not quite happy with the name of "workerType" (let me
know if anyone has any better ideas).
The basic idea is that I replaced the `ModelInfo` inside of the WLM with an
abstraction called `WorkerType`. The WorkerType corresponds to a WorkerPool and
determines what data is saved and work is done within a `WorkerThread`. The main
WorkerType is still the ModelInfo which extends it. I also added a
LambdaWorkerType that can be used for other processing. Unlike a
WorkflowFunction, it runs in a dedicated worker thread rather than on the common
CompleteableFuture pool.
I think this also helps clean up the abstractions a bit. Within the ModelInfo,
it essentially removed all of the pieces which …
> Worker type

- serving/src/main/java/ai/djl/serving/http/DescribeWorkflowResponse.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
This is an update to fix the changes to the workflow response from https://github.com/deepjavalibrary/djl-serving/pull/1022. Before, we had no test that checks the response components decided by the names of Java response object properties (workflows, models, etc.). This adds some new JSON testing to help ensure that these are not accidentally changed, fixing this issue and hopefully avoiding future breakages.
> Fixes API responses

- serving/docker/scripts/install_inferentia2.sh
Remove linux headers installation. The cross system header mismatch cause building bugs
> [INF2] don't install linux headers

- engines/python/setup/djl_python/rolling_batch/neuron_rolling_batch.py
- engines/python/setup/djl_python/tests/rolling_batch_test_scripts/run_rolling_batch_alone.py
- engines/python/setup/djl_python/transformers_neuronx.py
- engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_neuron_scheduler.py
- engines/python/setup/djl_python/transformers_neuronx_scheduler/token_selector.py
- engines/python/setup/djl_python/transformers_neuronx_scheduler/utils.py
- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
- tests/integration/llm/prepare.py
Support rolling batch using inefficient mechanism. Inspired from Optimum Neuron repo: https://github.com/huggingface/optimum-neuron/tree/main/text-generation-inference/server/text_generation_server
[BREAKING Change]: we are renaming transformers-neuronx.py to transformers_neuronx.py for better importing and regulate the python file naming.
Simulator testing with rolling batch
```
python3 run.py facebook/opt-1.3b -rb neuron
```
```
properties = {
"tensor_parallel_degree": 2,
"trust_remote_code": "true",
"batch_size": 4,
"dtype":"fp16",
"n_positions": 512,
"engine": "Python"
}
if args.rollingbatch == "lmi-dist":
dist.init_process_group("nccl")
properties["engine"] = "MPI"
batcher = init_rolling_batch(args.rollingbatch, args.model_id, properties)
simulator(batcher, "The president of United …
```
> add Neuron RollingBatch implementation

- engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
This is a PR for a bit of discussion. To give context, every time the Python engine spins up a PyProcess it also spins up two reader threads (stdout and stderr) that will read the output of the process and echo it back to the main stdout.
Before, we would shortcut the end of the reader threads by indicating that the ReaderThread should shut down and it cutting off checking for future or current output. The result of this is that the Python process output may be cut off. This is an especially concerning problem if the python process crashes and it cuts off the python error and stack trace. Running with and without this change can already show, even in just the gradle tests, several instances of messages being cut off. More customers may also be having issues understanding their Python …
> Removes quick abort of python reader threads

- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/neuron_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
This PR introduced a new concept called `active_requests`. It means the active serving requests with scheduler. In the meantime, the old `pending_requests` will be used to preseve requests that before the skip tokens. The pseudo process looks like below:
```
Step 1: requests enter into pending requests.
If waiting tokens not meeting:
return [] and just run step
if waiting tokens met:
merge all requests
return all pending requests
```
All 3 GPU engines passed
```
python run.py TheBloke/Llama-2-13B-Chat-fp16 -rb scheduler
```
```
python run.py TheBloke/Llama-2-13B-Chat-fp16 -rb vllm
```
```
torchrun --standalone --nnodes=1 --nproc-per-node=4  run.py TheBloke/Llama-2-13B-Chat-fp16 -rb lmi-dist
```
Inferentia testing
```
properties = {
"tensor_parallel_degree": 2,
"trust_remote_code": "true", …
```
> [RollingBatch] add active requests and pending requests for skip tokens

- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
Make rolling batch output not escape unicode characters. This will make output not have unicode characters escaped like: `\u201c`, `\u0080`, `\u0099`
> [python] Make rolling batch output not escape unicode characters

- engines/python/setup/djl_python/huggingface.py
This adds support for stopwords (also known as stop sequences) to the HuggingFace handler.
> Add support for stopwords in huggingface handler

- engines/python/setup/djl_python/deepspeed.py
- tests/integration/launch_container.sh
Add fast loading for partition testing.
> [fix] add fast loading to partition test

- engines/python/setup/djl_python/transformers_neuronx.py
This PR improves the latency of transferring model weights from the HF representation to the INF2 representation by doing it in-memory as opposed to using the disk as a buffer.  For OPT-66B on inf2.48xl, this improves the latency of weight transfer from 840s to 5s. 
Splitting the model into small pieces on the disk and then loading it, reduces CPU memory requirements. However, this operation demands high IOPS from the disk. Typical EBS volumes used by EC2 (gp3) and SageMaker (gp2) do not provide high IOPS by default. This leads to EBS throttling, which manifests as a massive latency to transfer model weights (upto 1400 secs).
However, Large Language Models are typically used with large instances with large CPU memory. As a result, for instances like inf2.24xl, inf2.48xl, trn1.32xl, …
> Faster in-memory weight transfer for transformers-neuronx

- engines/python/build.gradle
- engines/python/setup/djl_python/sm_log_filter.py
- engines/python/setup/djl_python/tests/test_sm_log_filter.py
- engines/python/setup/djl_python/transformers_neuronx.py
- engines/python/setup/djl_python_engine.py
- engines/python/setup/setup.py
We want to start tracking the compilation latency for INF2 when using the transformers-neuronx service across SageMaker
1. Python log messages with the tag `SysHealth:` will get reformatted in a manner consistent with what SageMaker expects and copied to an additional log file visible to SageMaker. 
2. Mechanism is only enabled when executing within the context of SageMaker Hosting.
3. Log collection by SageMaker can be disabled by following https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/logging-and-monitoring.html
1. Set djl_python version to djl version (required for reporting metrics)
> Adding INF2 (transformers-neuronx) compilation latencies to SageMaker Health Metrics

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
> [python] Do not set default value for truncate

- engines/python/setup/djl_python/transformers_neuronx.py
Updating the way that the context estimate is passed to the *ForSampling classes, so that it is only used for Llama models.
No
No
> [fix] update context estimate interface

- .github/workflows/client-test.yml
- .github/workflows/continuous.yml
- build.gradle
- engines/python/build.gradle
- engines/python/setup/setup.py
- tools/gradle/python-formatter.gradle
PR looks to add a test in the continuous workflow, so that when the build test is done on the ubuntu image we will also test to see if running ./gradlew formatPython changes any files. If it does then we fail with an error informing the PR author to run the command and recommit to pass the pipeline.
> [feat] fail continuous test if python is not formatted in CI

- engines/python/setup/djl_python/deepspeed.py
- engines/python/setup/djl_python/stable-diffusion.py
DeepSpeed Stable diffusion, does not have default datatype. Not it is set as 'fp16'
In DeepSpeed, bf16 with SmoothQuant could cause some issues. So changing that in default_dtype.
> Setting default datatype for deepspeed handlers

- plugins/management-console/src/main/java/ai/djl/serving/console/ConsoleRequestHandler.java
- plugins/management-console/webapp/src/store.js
> [console] Fixes bug for docker port mapping case

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
> [python] Remove generation_dict in lmi_dist_rolling_batch

- .github/workflows/pyunit.yml
- engines/python/setup/djl_python/transformers_neuronx.py
Updating the default sample strategy to use the neuron models implementation for improved performance. Additionally, adding the alias "fast_sample" to the "use_sample" parameter as use_sample is unclear as it really means "use neuronx model's sample implementation".
> [fix] use fast sample as default sample method for inf2

- engines/python/setup/djl_python/encode_decode.py
- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/inputs.py
- engines/python/setup/djl_python/outputs.py
- engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
- engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java
- engines/python/src/test/resources/rolling_batch/model.py
> [python] Optimize batch serialization

- engines/python/setup/djl_python/huggingface.py
This removes the changes to the parse_input signature for adapters for users who override it.
The fix is a bit of a hack using the obj to pass it instead of the return value. However, moving the adapter parsing logic outside of the main parse_input would require redoing much of the decoding work and would therefore increase the parsing costs.
@frankfliu
> Fixes changes to hf parse_input signature

- serving/docker/pytorch-inf2.Dockerfile
- serving/docker/scripts/install_inferentia2.sh
Update the tnx container to 2.15 sdk
> [neuronx] bump to 2.15 for tnx container and scripts

- engines/python/setup/djl_python/transformers_neuronx.py
Remove compiled_artifacts methods for gpt2, they are broken by the 2.15 neff changes
> [fix] gpt2 neuron support handler and ci

- .github/workflows/docker-nightly-publish.yml
- serving/.gitignore
- serving/build.gradle
- serving/docker/Dockerfile
- serving/docker/aarch64.Dockerfile
- serving/docker/deepspeed.Dockerfile
- serving/docker/fastertransformer.Dockerfile
- serving/docker/pytorch-cu118.Dockerfile
- serving/docker/pytorch-inf2.Dockerfile
- serving/docker/scripts/install_djl_serving.sh
- serving/docker/tensorrt-llm.Dockerfile
Before, we only supported docker builds that depend on the DJL global djl-serving.deb for the release. This PR begins by updating the Dockerfiles to search for `serving/docker/distributions/*.deb` and copy it to the container if it exists. This can then be used for the build instead of downloading. It enables easier local testing with a custom version of DJL Serving.
As part of this, it also creates a new gradle task `dockerDeb` that will move the build into the docker building context directory. It will be git ignored and cleaned through gradle.
Finally, it also modifies the nightly CI to no longer rely on the global build. This means that the nightly publish job does not require running the serving publish in the DJL repo first.
> Supports docker build with local .deb

- engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
- engines/python/setup/djl_python/trtllm.py
Adds TensorRT-LLM handler and rolling batch class.
Both tested, working with g5.12xlarge
Note: option.rolling_batch is still needed in serving.properties. Buggy output when removing option.rolling_batch due to Java side dependency (PyPredictor.java or PyProcess.java)
Recommended serving.properties:
```
engine=Python
option.entryPoint=djl_python.trtllm
option.model_id=/opt/djl/llama-2-7b-hf
option.tensor_parallel_degree=1
option.max_rolling_batch_size=32
option.task=text-generation
option.rolling_batch=trtllm
option.tensor_parallel_degree=4
```
To test:
- Install tensorrt-llm-toolkit
- Clone djl-serving
- Run:
```
cd djl-serving/serving
./gradlew clean createDeb
dpkg -i build/distributions/*.deb
pip install https://publish.djl.ai/peft/peft-0.5.0alpha-py3-none-any.whl
pip install …
```
> New PR for tensorrt llm

- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
- engines/python/src/main/java/ai/djl/python/engine/TrtLLMUtils.java
- serving/docker/partition/trt_llm_partition.py
- serving/docker/tensorrt-llm.Dockerfile
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
Add TRT-LLM engine build step during model initialization
TODO: Tests
> Add trt-llm engine build step during model initialization

- engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
- engines/python/setup/djl_python/tensorrt_llm.py
- serving/docker/tensorrt-llm.Dockerfile
> [TRTLLM] some clean up on trtllm handler

- engines/python/setup/djl_python/properties_manager/tnx_properties.py
- engines/python/setup/djl_python/tests/test_properties_manager.py
- engines/python/setup/djl_python/transformers_neuronx.py
Adding compiled_graph_path to the pydantic refactor, and adding unit tests to the config
> [ci] Update tnx_config with new property and unit tests

- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
- serving/src/main/java/ai/djl/serving/ModelServer.java
> MME - deviceId while creating workers

- engines/python/setup/djl_python/properties_manager/properties.py
- engines/python/setup/djl_python/properties_manager/tnx_properties.py
- engines/python/setup/setup.py
- serving/docker/pytorch-inf2.Dockerfile
Discussed with @tosterberg. He pointed out DeepSpeed is also using pydantic, checking their version it is 1.10.13. So downgrading from 2.4 to 1.10.13 as it has breaking changes. 
Testing:
Build a inf2 container and their integration test
https://github.com/deepjavalibrary/djl-serving/actions/runs/6757166039
> Downgrade to pydantic version 1.10.13

- .github/workflows/docker-nightly-publish.yml
This creates a new mode to docker_nightly_publish that will create temporary instances tagged with the commit hash such as `185921645874.dkr.ecr.us-east-1.amazonaws.com/djl-ci-temp:cpu-99f92ba11ef38e2b94d4df73b9b20480d9515cc8`. They are stored in an ECR repository with a lifecycle that will autoclean after 7 days as currently configured.
Right now, this PR only enables the mode for creating these. In a followup PR, I will also use this as a basis for the DJL Serving infrastructure. Specifically, here is the plan. I will modify the temp build so it will be the only docker build (keeping a temp/release option). The integration tests will all read from temp. Then, I will make a sync action that will take a temp instance and copy it to nightly, release, and/or ECR. To put these all together, …
> Creates docker temporary instances

- engines/python/src/main/java/ai/djl/python/engine/Connection.java
- engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
> [python] Workaround bug in PublisherBytesSupplier

- serving/docker/dockerd-entrypoint-with-cuda-compat.sh
Use CUDA compat with old drivers, not new ones
```
% verlt() {
[ "$1" = "$2" ] && return 1 || [  "$1" = "`echo -e "$1\n$2" | sort -V | head -n1`" ]
}
% verlte 2.5.7 2.5.6 && echo "yes" || echo "no"
no
% verlte 535.129.03 515.65.01 && echo "yes" || echo "no"
no
% verlte 515.65.01 535.129.03 && echo "yes" || echo "no"
yes
% verlte 470.129.03 555.68.01 && echo "yes" || echo "no"
yes
```
> fix the bug in the cuda compat settings

- serving/docker/dockerd-entrypoint-with-cuda-compat.sh
Some more changes to the script
```
root@10607c153a8a:/opt/djl# bash test.sh
CUDA compat package requires Nvidia driver ⩽535.129.03
Current installed Nvidia driver version is 535.104.12
Setup CUDA compatibility libs path to LD_LIBRARY_PATH
/usr/local/cuda/compat:/opt/tritonserver/lib:/usr/local/lib/python3.10/dist-packages/tensorrt_libs:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
```
> [CUDA Compat] fix the verlte settings on the script

- engines/python/setup/djl_python/deepspeed.py
- engines/python/setup/djl_python/properties_manager/ds_properties.py
- engines/python/setup/djl_python/properties_manager/properties.py
- engines/python/setup/djl_python/tests/test_properties_manager.py
- tests/integration/llm/prepare.py
Added pydantic refactoring to DeepSpeed handler. 
Added unit test cases. 
CI passes
https://github.com/deepjavalibrary/djl-serving/actions/runs/6779335757 - ds smoothquant handler test
https://github.com/deepjavalibrary/djl-serving/actions/runs/6779004237 - ds handler
> Deepspeed configurations refactoring

- wlm/src/main/java/ai/djl/serving/wlm/SageMakerUtils.java
- wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java
- use python backend when schema is customized
> [SageMaker Galactus developer experience] use python backend when schema is customized

- engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
remove max_new_tokens when passing down
> [TRTLLM] remove max_new_tokens since backend does not recognize it

- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/properties_manager/hf_properties.py
- engines/python/setup/djl_python/properties_manager/properties.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/tests/test_properties_manager.py
Tests:
Added unit test cases.
Tested CI test cases manually in ec2. And also ran in github actions
HF https://github.com/deepjavalibrary/djl-serving/actions/runs/6790943108/job/18461535915
HF lora https://github.com/deepjavalibrary/djl-serving/actions/runs/6791093901/job/18462088800
Rolling batch changes https://github.com/deepjavalibrary/djl-serving/actions/runs/6790720395/job/18460807680
> Huggingface configurations refactoring

- engines/python/setup/djl_python/properties_manager/ds_properties.py
- engines/python/setup/djl_python/properties_manager/properties.py
- engines/python/setup/djl_python/tests/test_properties_manager.py
Issue:
Pydantic does auto conversion, but we do validate batch_size before assigning, so manually need to type cast them. 
Test case:
These were not caught in unit test case before because, tested it as int not str. Changed all input to Properties as str and added more test cases.
> fix batch_size type conversion

- .github/workflows/rolling_batch_integration.yml
- tests/integration/llm/prepare.py
> [CI] Add awq test case for vllm

- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
> [vllm] standardize input parameters

- .github/workflows/llm_inf2_integration.yml
Adding one more machine for inf2 integration tests. Since we have 13 test cases now. Adding one more machine should reduce the runtime from 1 hour to 30 mins.
> [CI] Adding one more machine for inf2 integration test

- serving/src/main/java/ai/djl/serving/cache/BaseCacheEngine.java
- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
- serving/src/main/java/ai/djl/serving/util/ConfigManager.java
> [serving] Uses seconds for ChunkedBytesSupplier timeout

- engines/python/setup/djl_python/tests/test_properties_manager.py
> [UnitTest] adding more properties testing

- .github/workflows/instant_benchmark.yml
- engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
- tests/integration/instant_benchmark.py
- tests/integration/record_benchmark.py
This improves the instant benchmark action with support to record the data in a DynamoDB table. It saves the input, serving.properties, and all accessible outputs as well. The table with some existing data can be seen [here](https://us-east-1.console.aws.amazon.com/dynamodbv2/home?region=us-east-1#item-explorer?operation=SCAN&table=RubikonBenchmarks) from this [input](https://gist.githubusercontent.com/zachgk/c0090ab15c00a3fda06b63f7a61a370a/raw/867f9b4db107b225b4993e8328f6c8bbf608e107/gistfile1.txt).
> [CI] Adds instance benchmark tabular recording

- engines/python/setup/djl_python/properties_manager/hf_properties.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
Found a bug while testing quantization with new properties for HF Accelerate and lmi-dist
LMI Dist rolling batch takes in the parsed properties instead of pydantic, so new bitsandbytes8 needs to be handled in rolling batch handler. 
Testing:
Tested HF and LMI Dist in my machine with bitsandbytes option
Tested TnX quantization in my machine , works 
vllm, deepseed, trtllm has no changes for quantization
> [fix] quantization properties for lmi dist and hf acc

- .github/workflows/rolling_batch_integration.yml
- engines/python/setup/djl_python/deepspeed.py
- engines/python/setup/djl_python/properties_manager/ds_properties.py
- engines/python/setup/djl_python/properties_manager/properties.py
- engines/python/setup/djl_python/rolling_batch/deepspeed_rolling_batch.py
- serving/docker/deepspeed.Dockerfile
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
> [DS] Deepspeed rolling batch support

- serving/docs/lmi/tutorials/seq_scheduler_tutorial.md
> [doc] seq_scheduler_document

- serving/docs/lmi/tutorials/trtllm_aot_tutorial.md
> [doc] fix docker image uri for trtllm tutorial

- serving/docs/configurations_model.md
> [docs] Adds option.max_output_size document

- tests/integration/instant_benchmark.py
- tests/integration/record_benchmark.py
This adds support for a new section on variables in the IB configurations. They are specified by
```
[test_name]
test
[vars]
CONCURRENCY={1,16,32}
RANGE=[1..5]
```
This will then produce a template result for each combination of vars (note ranges are following python semantics of inclusive start and exclusive end).
It can be used to support larger configurations with variations.
I also added a small update to the record benchmarks script to also pre-compute throughput.
Successful run at https://github.com/deepjavalibrary/djl-serving/actions/runs/7067209325
> [CI][IB] Support variables

- serving/docker/pytorch-inf2.Dockerfile
Updating the inf2 DLC to 2.15.2 SDK
> [tnx] version bump to 2.15.2

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
> [python] Update lmi_dist warmup logic

- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
> [RollingBatch] optimize rolling batch result

- engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
If there is non-daemon thread is running, JVM cannot exit normally (when we programaticall call ModelServer.stop(), or model load failed on startup and trying to stop model server)
> [python] Sets rolling batch threads as daemon thread

- engines/python/setup/djl_python/properties_manager/hf_properties.py
- engines/python/setup/djl_python/properties_manager/properties.py
- engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
- engines/python/setup/djl_python/rolling_batch/deepspeed_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/neuron_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- engines/python/setup/djl_python/tests/test_properties_manager.py
Refactoring the rolling batch handlers to extract out the properties and maintain it in pydantic. Will be doing it for all rolling batch handlers. 
Right now, for easier review, will raise PR for each handler at a time. After this, all the rolling batch based if conditions in huggingface_properties can be removed. Right now, added TODOs, to prevent our CI from breaking. Once all the rolling batch handlers are refactored, will address these TODOs. 
- Added unit test cases for vllm properties
- Ran vllm rolling batch integration test in my local machine.
> [Refactor][UX] Refactoring vllm rolling batch properties

- .github/workflows/sagemaker-integration.yml
- tests/integration/llm/sagemaker-endpoint-tests.py
Sagemaker metrics were not uploaded to cloud watch, because the github action inputs will be empty when the workflow is dispatched through schedule. 
Changes in this PR:
- Made `run_benchmark` an argument to sagemaker-endpoint-tests script. 
- Uploading metrics for MME also, (before it was only for SME)
- Metric name format will be `{name}-{engine_name}-{num_partitions}p-{instance_type}-metric`, for example `opt-1-3-b-deepspeed-2p-ml.g5.8xlarge-throughput`
Test:
- Tested MME and SME 1 test case in my ec2 machine.
> [CI][fix] Sagemaker integration test cloudwatch metrics fix

- .github/workflows/llm_inf2_integration.yml
Fix early failure on the CI inf2 AOT integration test, check for compiled neff files for verification of successful compilation.
> [CI][fix] Inf2 AOT integration test fix

- serving/docker/scripts/install_inferentia2.sh
Freeze the aws-neuronx dependencies down to the patch version. Collectives and runtime have hashes on the end of their version so I am taking the end of the collectives and runtimes as a *glob to get the correct hash.
> [DLC][TNX] Freeze all aws-neuronx deps

- serving/docker/tensorrt-llm.Dockerfile
Reverts deepjavalibrary/djl-serving#1394
Ammo required much more dependencies to install, will address in a different PR
> Revert "[TRTLLM] install ammo dependencies for quantization"

- engines/python/setup/djl_python/properties_manager/tnx_properties.py
- engines/python/setup/djl_python/tests/test_properties_manager.py
- engines/python/setup/djl_python/tests/test_transformers_neuronx.py
- engines/python/setup/djl_python/transformers_neuronx.py
- serving/docs/lmi/tuning_guides/tnx_tuning_guide.md
- tests/integration/llm/prepare.py
This PR specifies the use of `batch_size` and `max_rolling_batch_size` in TNX properties. Specifically, this removes the need for `option.batch_size` for all but one case (batch size > 1 and streaming enabled). Tests and docs are updated to reflect the change.
One additional constraint was added to the properties, which is if `batch_size` > 1 and `rolling_batch` is enabled will now throw an error. This behavior should have existed previously, but due to being unable to differentiate `batch_size` and `option.batch_size` when setting properties, it was not detectable.
One warning that was previously thrown, was removed. Originally, a warning was thrown when `batch_size` > 1 and `enable_streaming` was enabled. Due to our inability to differentiate dynamic batching `batch_size` and …
> [TNX][config] update rolling batch batch size behavior and docs

- .github/workflows/lmic_performance.yml
- tests/integration/llm/prepare.py
- tests/integration/profiles/bloom_7b1.json
- tests/integration/profiles/gpt_j_6b.json
- tests/integration/profiles/gpt_neox_20b.json
- tests/integration/profiles/llama_13b.json
- tests/integration/profiles/opt_30b.json
- Removed the g5xl and removed huggingface testing. 
- Replaced huggingface testing with lmi dist test. 
Tested through running in our CI 
https://github.com/deepjavalibrary/djl-serving/actions/runs/7266944676 
Note that gptj failed because of lmi dist gptj is not supported in the above runner. `sharded is not supported for AutoModel` Lmidist work with non shared version though. So removed the gpt-j-lmi-dist for now.
> [CI][fix] remove g5xl and introduce rolling batch in lmic

- README.md
- benchmark/README.md
- engines/python/README.md
- serving/docker/README.md
- wlm/README.md
some of the docs were outdated - updating them to the correct djl versions
> [docs] update docs to use djl 0.25.0

- build.gradle
- serving/docker/Dockerfile
- serving/docker/aarch64.Dockerfile
- serving/docker/deepspeed.Dockerfile
- serving/docker/pytorch-gpu.Dockerfile
- serving/docker/pytorch-inf2.Dockerfile
- serving/docker/scripts/install_djl_serving.sh
- serving/docker/tensorrt-llm.Dockerfile
> [docker] Upgrades JDK 17 for docker images

- serving/src/main/java/ai/djl/serving/ServerInitializer.java
> [serving] Allows plugin to override default HTTP handler

- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
> [wlm] enable max workers env var for MPI mode

- .github/workflows/llm_inf2_integration.yml
- engines/python/setup/djl_python/neuron_utils/model_loader.py
- engines/python/setup/djl_python/neuron_utils/utils.py
- engines/python/setup/djl_python/rolling_batch/neuron_rolling_batch.py
- engines/python/setup/djl_python/tests/test_stable_diffusion_inf2.py
- engines/python/setup/djl_python/tests/test_transformers_neuronx.py
- engines/python/setup/djl_python/transformers_neuronx.py
- engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_neuron_scheduler.py
- serving/docker/pytorch-inf2.Dockerfile
- serving/docker/scripts/install_inferentia2.sh
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
Updates TNX container to 2.16.0
Adds mistral-7b test replacing redundant llama2-7b test
Adds continuous batching integration
Removed workaround functions that were fixed in TNX update and have been reimported `save_pretrained_split` as an example
Updated TNX unit tests for new model loader determinations when supporting continuous batching
Further needs:
- continuous batching CI tests
- future updates when optimum is compatible with 2.16.0
- GQA and Llama2-70b testing and integration
**Note**: The change will break some precompiled models so downstream users of nightly builds should be informed
> [TNX] version update to 2.16.0 sdk and continuous batching

- serving/docker/tensorrt-llm.Dockerfile
- tests/integration/llm/prepare.py
Fix TRTLLM issue on GPTJ model
> [TRTLLM][CI] reduce memory for GPTJ

- engines/python/setup/djl_python/tensorrt_llm.py
Fixes bug in TensorRT-LLM handler that prevents some error messages from being displayed to user
> [TRTLLM] Fix bug in handler

- engines/python/src/main/java/ai/djl/python/engine/PyEngineProvider.java
- serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java
This updates DJL Serving to follow the engine initialization standards set in https://github.com/deepjavalibrary/djl/pull/2885. First, it updates the PyEngineProvider to follow the EngineProvider conventions.
It also updates the DependencyManager, fixing some bugs that inspired https://github.com/deepjavalibrary/djl/pull/2934. The dependency manager before this change would always re-register the engine with a new provider. Beforehand, the engine was fully static and unable to re-initialize, so this would not accidentally re-initialize engines. After this, it would re-initialize engines that did not support it causing errors. Instead, it should only register new engines rather than all providers to avoid these accidental re-initialization.
> Works with manual initialization

- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- tests/integration/llm/prepare.py
Fixes bug where user supplied revision was not passed to vllm engine.
Pin version of phi2 model in rolling batch test since latest changes in HF require transformers==4.37.0.dev0
> [vllm] pass hf revision to vllm engine, pin phi2 model revision for test

- serving/docs/lmi/lmi_input_output_schema.md
This document added only the rolling batch handlers input schemas. 
DeepSpeed non-rolling-batch handler input schema have a lot of parameters, will gather them all in a single doc and find a better way to present in our markdown files. 
Will add optimum neuron and transformer neuronx options in the upcoming PRs.
> [doc] add lmi input output schema doc

- wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
Fixes a bug introduced by https://github.com/deepjavalibrary/djl-serving/pull/1373 where if `trtllm` is specified as rolling_batch, it returns false for `isTrtLLM` check.
> Fix trtllm check logic

- .github/workflows/codeql-analysis-java.yml
- .github/workflows/docker-nightly-publish.yml
- .github/workflows/integration.yml
- .github/workflows/llm_inf2_integration.yml
- .github/workflows/llm_integration.yml
- .github/workflows/llm_integration_p4d.yml
- .github/workflows/lmic_performance.yml
- .github/workflows/nightly-docker-ecr-sync.yml
- .github/workflows/publish-job-success.yml
- .github/workflows/rolling_batch_integration.yml
- .github/workflows/sagemaker-integration.yml
Adds failure metrics for each of the scheduled workflows. This will allow us to create monitors/ticketing from the cloudwatch metrics. The ticketing helps alert the oncall sooner, and allows for investigations to be captured in the ticket itself.
Notes:
- Only publishes failures for scheduled runs. Manual runs of workflows will not result in metrics being published
- Uses our self-hosted runner because it's convenient for aws credentials
- Metric Names follow `DJLServing-<TestName>-Failure` format
I'll do the same thing for djl/djl-demo if we think it's useful
> [ci] publish scheduled workflow failures to cloudwatch for monitoring

- .github/workflows/codeql-analysis-java.yml
- .github/workflows/docker-nightly-publish.yml
- .github/workflows/integration.yml
- .github/workflows/llm_inf2_integration.yml
- .github/workflows/llm_integration.yml
- .github/workflows/llm_integration_p4d.yml
- .github/workflows/lmic_performance.yml
- .github/workflows/nightly-docker-ecr-sync.yml
- .github/workflows/rolling_batch_integration.yml
- .github/workflows/sagemaker-integration.yml
Failed tests aren't publishing metrics - the calling step needs the `always()` condition even if the called workflow specifies a condition in order to run at all
> [ci] fix action metric publish on failure

- engines/python/setup/djl_python/properties_manager/tnx_properties.py
Change Neuron default compilation dtype
> making default dtype to fp16 for compilation

- engines/python/setup/djl_python/deepspeed.py
The same logic that was added to the huggingface handler for lmi_dist rolling batch in https://github.com/deepjavalibrary/djl-serving/pull/912 is needed in the deepspeed handler, too.
The current buggy behavior is that every request uses seed 0 if none is provided from user. Instead, we should use the server-provided seed when the request params do not include a specific seed.
I verified the fix by running a sequence of requests with the same prompt with concurrency 1, with no explicit seed, with do_sample=true, with and without this fix. Without the fix, all the outputs are exactly the same. After this fix, the outputs are all different, showing that they are now each seeded with a different value. With the fix, if I send the requests with explicit seed 0, I get the same result that I …
> Use server-provided seed if not in request params in deepspeed handler

- tests/integration/llm/sagemaker-endpoint-tests.py
Removing partition testing for DeepSpeed models since we favor the fast loading mechanism for this engine. this should fix the issues we're seeing with the gpt-j-6b partition test (the issue will still exist for bf16, but we're considering it a low priority issue)
> [ci] remove partition steps for deepspeed/hf based models

- .github/workflows/instant_benchmark.yml
- tests/integration/instant_benchmark.py
- tests/integration/record_benchmark.py
This allows including the container in the template. This can be useful for having multiple containers specified in the same template. Following this, only one template per instance type is needed. It is still possible to specify the container through the action, which now acts as an override. It also expands to support containers outside of the deepjavalibrary namespace.
Runs:
- No template container, override in action: https://github.com/deepjavalibrary/djl-serving/actions/runs/7674783679
- Template container, no override: https://github.com/deepjavalibrary/djl-serving/actions/runs/7674943363
> [CI][IB] Specify container through template

- serving/docker/aarch64.Dockerfile
> [docker] Adds performance tuning env var for aarch64

- tests/integration/llm/prepare.py
Right sizing the compilation of the gpt-j model to compile faster for ci test, and expand the range of timeout for observed compilation time variance. Also removing redundant serving properties from our prepare.py script.
> [ci] Fix gpt-j timeout issues in inf2 integration

- engines/python/setup/djl_python/properties_manager/hf_properties.py
Please let me know if it is alright to remove this code now that it's not needed
This PR removes 2 things in hf_properties:
1) the awq value in the HFQuantizeMethods enum
2) LMI_DIST_ADV_MODEL, which has been moved to huggingface handler
> remove a bit of unused code

- engines/python/setup/djl_python/deepspeed.py
- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/rolling_batch/deepspeed_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- engines/python/setup/djl_python/tensorrt_llm.py
- engines/python/setup/djl_python/tests/rolling_batch_test_scripts/run_rolling_batch_alone.py
- engines/python/setup/djl_python/tests/rolling_batch_test_scripts/test_rolling_batch.py
- engines/python/setup/djl_python/tests/test_lmi_dist.py
Really small nit that makes the code very slightly cleaner :)
> Remove unused device parameter from all rolling batch classes

- serving/src/main/java/ai/djl/serving/util/ConfigManager.java
With the LMI changes to support all configs via `OPTION_` env vars, we should write those at startup similar to writing the other relevant environment variables to be consistent.
> dump OPTION_ env vars at startup

- serving/docs/configurations_model.md
vllm backend does not use mpi engine
> change line in documentation examples (vllm serving.properties)

- serving/docs/streaming_config.md
Updates random doc
I chose not to change the part where it says ENGINE in StreamingUtils.get_stream_generator(ENGINE) can be one of DeepSpeed, Accelerate, and transformers-neuronx, since that is actually still true.
> update random doc

- engines/python/setup/djl_python/properties_manager/hf_properties.py
Rolls back part of #1536 temporarily to pass rolling batch integration tests.
To fix the root cause, it's necessary to determine whether we can change all tests involving vllm awq in tests/integration/llm/prepare.py to use Vllm Rolling batch instead.
> roll back enum changes

- serving/docs/lmi_new/README.md
- serving/docs/lmi_new/deployment_guide/README.md
- serving/docs/lmi_new/deployment_guide/backend-selection.md
- serving/docs/lmi_new/deployment_guide/benchmarking-your-endpoint.md
- serving/docs/lmi_new/deployment_guide/configurations.md
- serving/docs/lmi_new/deployment_guide/deploying-your-endpoint.md
- serving/docs/lmi_new/deployment_guide/instance-type-selection.md
- serving/docs/lmi_new/deployment_guide/model-artifacts.md
- serving/docs/lmi_new/user_guides/deepspeed_user_guide.md
- serving/docs/lmi_new/user_guides/lmi-dist_user_guide.md
- serving/docs/lmi_new/user_guides/tensorrt-llm_user_guide.md
- serving/docs/lmi_new/user_guides/transformers-neuronx_user_guide.md
- serving/docs/lmi_new/user_guides/vllm_user_guide.md
This PR addes the structure for the new LMI documentation:
- Top Level ReadMe
- User Guides/
- DeepSpeed, TRTLLM, vLLM, LMI-Dist, TNX
- Conceptual Guides/ 
- Will contain things like quantization, rolling batch, tensor parallelism etc
- Deployment Guide/
- Comprehensive guide intended for "advanced"/"thorough" users
We still need to review the specific content and iterate, but initial reviews have been good. 
This is ready to merge so that others can start adding the respective user-guides
> [docs][lmi] updating structure for lmi docs

- serving/docker/dockerd-entrypoint-with-cuda-compat.sh
This PR adds support for mapping some TGI environment variables to equivalent LMI environment variables.
The set of environment variables may change based on more discussion, but this at least sets it up so we can add/remove from the list.
This change is only added to the deepspeed/trtllm containers, not NeuronX.
---
Tested locally with: ` docker run -it --runtime=nvidia -p 8080:8080 --shm-size=2g -e MODEL_ID=TheBloke/Llama-2-13b-fp16 -e SM_NUM_GPUS=max -e MAX_BATCH_SIZE=32 -e OPTION_MAX_ROLLING_BATCH_SIZE=64 deepjavalibrary/djl-serving:deepspeed`
Logs show:
```
Environment variables:
HF_HUB_ENABLE_HF_TRANSFER: 1
HF_HOME: /tmp/.cache/huggingface
OPTION_MAX_ROLLING_BATCH_SIZE: 64
OMP_NUM_THREADS: 1
HF_MODEL_ID: TheBloke/Llama-2-13b-fp16
OPTION_TENSOR_PARALLEL_DEGREE: max
DJL_CACHE_DIR: …
```
> [docker] map select tgi env vars to lmi env vars

- engines/python/setup/djl_python/tensorrt_llm.py
Trial commit for type hints and code clarity.
Only works for Python 3.9 and newer - older type hints style that is compatible with 3.8 is deprecated soon. Please let me know if compatibility with 3.8 is a must.
> type hints and comments for trtllm handler

- .github/workflows/rolling_batch_integration.yml
- engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
Initial PR to support speculative decoding
> [vLLM] add speculative configs

- serving/docs/lmi/tutorials/tnx_aot_tutorial.md
Adding AOT doc for precompiling TNX models on EC2
> [docs] Add TNX AOT docs for Llama-2-70B

- .github/workflows/llm_integration.yml
- serving/docs/adapters.md
- serving/docs/adapters_api.md
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
- wlm/src/main/java/ai/djl/serving/wlm/Adapter.java
This removes the adapters preview flag. The features still remain subject to change, but no longer require this additional step to enable.
> Remove adapters preview flag

- serving/src/main/java/ai/djl/serving/ModelServer.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
> [serving] Ignore CUDA OOM when collecting metrics

- serving/docs/lmi_new/README.md
- serving/docs/lmi_new/deployment_guide/README.md
- serving/docs/lmi_new/deployment_guide/deploying-your-endpoint.md
Adds guide for deployment (section 4 in deployment guide).
Doing this a bit out of order, but the remaining pieces in the deployment guide are:
- picking your container and backend
- configurations
- benchmarking
> [docs] add deployment guide section for deploying model to endpoint

- engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
- engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
- **Revert "[python] Buffer tokens for rolling batch (#1249)"**
- **[serving] Adds rolling batch metrics**
> [serving] Adds rolling batch metrics

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/neuron_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
Adds more type hints.
Also does the following as I increase my understanding of PEP style guidelines:
- Removes types inside the comments since they are already there in type hints.
- Adds "None" return type to all functions that return None.
> rolling batch type hints part 3

- tests/integration/llm/prepare.py
This may fix the CI error caused by possibly an unfinished download.
> [CI] replace chatglm with s3 model

- serving/docs/adapters.md
- serving/docs/management_api.md
- serving/docs/workflow_templates.md
- serving/src/main/java/ai/djl/serving/http/LoadModelRequest.java
- serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
- serving/src/main/java/ai/djl/serving/workflow/WorkflowDefinition.java
- serving/src/main/java/ai/djl/serving/workflow/WorkflowTemplates.java
- serving/src/main/resources/workflowTemplates/adapter.json
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
This creates a new concept of workflow templates. They are largely the same as existing workflows, but expand the `WorkflowDefinition` to support template replacement fields. The workflow templates can be used to simplify the creation of new workflows, especially ones that follow simple patterns.
As future work, it may be worth considering whether to support:
- Ways to define the templates as a file rather than just through the management API
- Adding templates using a pre-defined folder or the config
> Workflow Templates

- plugins/management-console/src/main/java/ai/djl/serving/console/ConsoleRequestHandler.java
CodeQL has started failing due to using deprecated Charset in ConsoleRequestHandler. Moving to StandardCharset
> [console] use StandardCharset instead of deprecated Charset

- serving/docs/lmi/tutorials/tnx_aot_tutorial.md
Misspelling in s3 copy folder name
> bad folder name

- serving/src/test/java/ai/djl/serving/ModelServerTest.java
> [serving] Skip testPrometheusMetrics when run in IDE

- serving/docker/deepspeed.Dockerfile
Failure during container rebuild: https://github.com/deepjavalibrary/djl-serving/actions/runs/8207124712/job/22447771144#step:12:2588
The following 2 changes fix the dependency issue. Verified that this works locally on branch `0.25.0` by running `docker compose build deepspeed`
* Pinning version of `huggingface-hub` to be the same as the current DLC version
```
$ docker run --rm -it 763104351884.dkr.ecr.us-west-2.amazonaws.com/djl-inference:0.25.0-deepspeed0.11.0-cu118 pip show huggingface-hub
Name: huggingface-hub
Version: 0.17.3
Summary: Client library to download and publish models, datasets and other repos on the huggingface.co hub
Home-page: https://github.com/huggingface/huggingface_hub
Author: Hugging Face, Inc.
Author-email: julien@huggingface.co
License: Apache
Location: …
```
> [CVE][Build] Pins huggingface-hub to fix pip dependency resolution failure

- serving/docs/lmi_new/deployment_guide/benchmarking-your-endpoint.md
Adds benchmarking guide for LMI using awscurl
> [docs] add benchmarking guide for lmi

- serving/docker/deepspeed.Dockerfile
> [Build] Pins datasets version to fix pip dependency resolution failure

- engines/python/setup/djl_python/neuron_utils/model_loader.py
- serving/docker/partition/properties_manager.py
This PR includes 2 changes
1. Removed a redundant call to save_pretrained_split in TNXModelLoader partition(). Previously it was called in partition() and then called again in load_inf2_model_from_disk(). We retain only the call in load_inf2_model_from_disk().
- This was tested with llama-2-7b, reduced partitioning time from 13 min to 9 min (inf2.48xlarge, 6 neuron cores exposed to container, compiler cache populated for both runs)
3. Improved the error handling of the partition PropertiesManager. Previously, this checked if any .bin files existed in the model artifacts, if not, partitioning would fail. Now, we check for .bin OR .safetensors files, allowing users to pass in models that only have .safetensors files without erros.
cc: @tosterberg
> [Partition] Remove redudant model splitting, Improve Input Model Parsing

- serving/docs/lmi_new/user_guides/deepspeed_user_guide.md
- serving/docs/lmi_new/user_guides/lmi-dist_user_guide.md
- serving/docs/lmi_new/user_guides/tnx_user_guide.md
- serving/docs/lmi_new/user_guides/trt_llm_user_guide.md
- serving/docs/lmi_new/user_guides/vllm_user_guide.md
This PR standardizes the backend user guide structure and content.
> [docs][lmi] standardize structure of backend user guides

- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- serving/docs/lmi/user_guides/lmi_input_output_schema.md
This PR 
- Makes greedy the default for vllm, [before this PR random sampling was the default for vllm]
- Introduces num_beams should enable beam search. [Even for the beam search, the generated sequence will be 1. It will be greater than 1 only if `n` > 1. `n` in equivalent to `num_return_sequences` in huggingface] 
- Makes default value of max_new_tokens to be 30. [Before this PR, it was 16]
> [UX] sampling with vllm

- serving/docs/large_model_inference.md
- serving/docs/lmi/README.md
- serving/docs/lmi/deployment_guide/backend-selection.md
- serving/docs/lmi/deployment_guide/configurations.md
- serving/docs/lmi/user_guides/deepspeed_user_guide.md
Fixes some formatting issues that are present on the docs site but not on github
> [docs] fix some links that do not work on mkdocs site

- serving/docs/adapters_api.md
- serving/src/main/java/ai/djl/serving/http/AdapterManagementRequestHandler.java
- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
- serving/src/main/java/ai/djl/serving/models/ModelManager.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
- serving/src/test/resources/smeAdapt.config.properties
This adds a shortcut for the adapter API for single model use case. In addition to being able to call it through `/models/{modelName}/adapters`, it can also be called through `/adapters` if this is unambiguous. This use case may be run into in cases like SageMaker SME.
> Single model adapter API

- serving/docker/partition/properties_manager.py
One-liner change to fix how the partition PropertiesManager checks for input model files.
cc: @tosterberg
> [partition] fix checking for model files

- serving/docker/deepspeed.Dockerfile
Update the build url. trigger a dry run
> [DO NOT MERGE][CAN APPROVE]change flash attn url

- engines/python/setup/djl_python/neuron_utils/model_loader.py
- engines/python/setup/djl_python/properties_manager/tnx_properties.py
- engines/python/setup/djl_python/tests/test_transformers_neuronx.py
- engines/python/setup/djl_python/transformers_neuronx.py
Purpose of this PR is to increase the speed, and reduce the disk requirements when doing aot partitioning using the tnx  model loader.
Additionally, I have added an override property to specify model loader for test purposes. This is not going to be a documented property.
> [tnx] improve model partitioning time

- engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_neuron_scheduler.py
- engines/python/setup/djl_python/transformers_neuronx_scheduler/token_selector.py
Adding the ability to consume fine-tuned tokenizers that utilize multiple EOS tokens as part of their generation strategy. Example artifact https://huggingface.co/codellama/CodeLlama-70b-Instruct-hf/blob/main/generation_config.json#L4.
> [tnx] support codellama 70b instruct tokenizer

- serving/docs/lmi/README.md
Adds notebook links for the completed sample notebooks in the gen ai hosting examples repo.
Not all of the models have been completed yet, but for the ones that have I have included the links here. I have removed models from the list that don't have examples so users don't have bad links that don't take them anywhere.
> [docs][lmi] update landing page sample notebook links

- engines/python/setup/djl_python/rolling_batch/lmi_dist_v2_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- serving/docs/lmi/user_guides/lmi_input_output_schema.md
**Unifying TensorRT-LLM parameters**:
- TensorRT-LLM does not have do_sample parameters, so if top_p=0 and top_k=0, then it automatically does greedy, which are also the default values . So the default values of top_p and top_k has to be different from other optimization engines. 
- Retaining the same numbers for do_sample as before, but clairfied it in our schema doc. 
- In future, this will be changed if TensorRT-LLM's Inference API started supporting all the models, in which they do have `do_sample` parameters and also in python API. 
Ref: https://github.com/NVIDIA/TensorRT-LLM/blob/66ca3378c61efa3154ed34a48cfc362351405eef/docs/source/gpt_runtime.md?plain=1#L385
https://github.com/NVIDIA/TensorRT-LLM/issues/646#issuecomment-1853151562
In their c++ code, I could not find where they set …
> [UX] Changing some default parameters

- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
Fix a bug with output formatter
```
INFO  PyProcess W-1382-test-stdout: [1,0]<stdout>:Rolling batch inference error
INFO  PyProcess W-1382-test-stdout: [1,0]<stdout>:Traceback (most recent call last):
INFO  PyProcess W-1382-test-stdout: [1,0]<stdout>:  File "/tmp/.djl.ai/python/0.27.0-SNAPSHOT/djl_python/rolling_batch/rolling_batch.py", line 249, in try_catch_handling
INFO  PyProcess W-1382-test-stdout: [1,0]<stdout>:    return func(self, *args, **kwargs)
INFO  PyProcess W-1382-test-stdout: [1,0]<stdout>:  File "/tmp/.djl.ai/python/0.27.0-SNAPSHOT/djl_python/rolling_batch/trtllm_rolling_batch.py", line 102, in inference
INFO  PyProcess W-1382-test-stdout: [1,0]<stdout>:    response = self.model.generate(request.input_text, **param)
INFO  PyProcess W-1382-test-stdout: [1,0]<stdout>:  File …
```
> fix a bug with output formatter

- tests/integration/llm/prepare.py
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
Introduce max_dynamic_batch_size (equivalent to batch_size).  
- This changes support only when users provide this property through serving.properties or environment variables. Registering model through API and other ways of setting this property is **not implemented** in this changes. 
- batch_size takes the highest precedence. 
- While printing our properties in logs, batch_size will be printed as **max_dynamic_batch_size**.
> Support max_dynamic_batch_size property name

- engines/python/setup/djl_python/deepspeed.py
- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/tensorrt_llm.py
- engines/python/setup/djl_python/tests/test_rolling_batch.py
- engines/python/setup/djl_python/transformers_neuronx.py
This PR adds support for `stream` as a request configuration. With the change to make output formatter a request level concern, we can now support request level streaming.
The same thing can be achieved now by specifying output formatter as either json (non-streaming), or jsonlines (streaming). However, using a separate stream parameter is what we need for chat completions support. It is also more user friendly than specifying output formatter.
If output_formatter is specified in the request, we use that. 
If output_formatter is not specified, we then use the stream parameter to determine which format to use.
Sample Payload:
```
{
"inputs": <inputs>,
"parameters": {...},
"stream": <bool>
}
```
tested this with both deepspeed-nighlty and tensorrt-llm-nightly. Have not tested in neuronx …
> [lmi] add stream parameter to enable per request streaming config

- serving/docker/dockerd-entrypoint-with-cuda-compat.sh
- serving/docker/partition/sm_neo_trt_llm_partition.py
This PR is introducing an additional path in the entrypoint of the TensorRT-LLM LMI container, which will enable the container to be used in the context of [SageMaker Neo](https://aws.amazon.com/sagemaker/neo/) for AOT compilation. 
- This change only adds an alternate AOT partition script which must be specifically enabled during `docker run`, and thus does not impact serving or any default behavior
> [TRTLLM] Add entrypoint for SM Neo AOT compilation

- wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
I am getting an inf2 machine and testing it. 
Why this fix?
When the user give max_dynamic_batch_size, we set the batchSize of workerpool config, which will do the dynamic batching. But in TNX handler, they check the batch_size in property and validate with the input size. So setting the batch_size property when max_dynamic_batch_size is given. 
Testing:
- Tested with inf2 machine with gpt2 handler (CI test which is failing)
> [Fix] set batch size property for handlers

- engines/python/setup/djl_python/deepspeed.py
- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/transformers_neuronx.py
Fix an issue with "stream" being populated for dynamic batch use-cases.
We support per request streaming only for rolling batch (I think it may be possible with dynamic batching, but only in the case where we serve 1 request at a time, so it's probably not worth it).
> [fix] restrict per request streaming to rolling batch use-cases

- tests/integration/llm/prepare.py
Example: https://github.com/deepjavalibrary/djl-serving/actions/runs/8422220967/job/23061144377
The issue was that the download was through a symlink using the huggingface cache, but that cache was not in the container. This removes the symlink usage
> [CI] Fixes vllm unmerged LoRA tests

- tests/integration/launch_container.sh
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
1. The new compilation workflow for TRT-LLM takes longer to compile due to two-step process: convert_checkpoint and 
trtllm-build.
2. Currently setting the retry value such that it increases wait time by 4-5 min. This is a bit generous. And if this addresses some of the timeout issues, will be reduced later to a more reasonable value.
3. Also changes some tokenizers for models to use llama, since awscurl fails for them due to the absence of `tokenizer.json`
> Increase test timeout for TRT-LLM compilation and tokenizer fix

- engines/python/setup/djl_python/chat_completions/chat_utils.py
Chat completions is only supported by rolling batch due to the details needed in the response.
We can add support for chat completions in dynamic batch at a later point, but it requires a bit more effort to compute the required output details across all the different backends.
> [chat][lmi] restrict chat completions support to rolling batch use-cases

- .github/workflows/lmi-no-code.yml
- tests/integration/launch_container.sh
Adds trt-llm to no code suite.
I've tested portions of the full suite independently, and i'm pretty confident everything will work together.
Struggling with capacity to test the full suite.
This test suite will take a LONG time to run. Couple options:
- add a new input: `run_all` that allows you to run all the tests. The default would be a `$RANDOM` number. This number could be used to run half the tests if even, other half the tests if odd.
- reduce the overall test suite to limit time
> [ci][lcnc] add trt-llm container to no code tests

- .github/workflows/llm_integration.yml
- engines/python/setup/djl_python/properties_manager/properties.py
- engines/python/setup/djl_python/properties_manager/trt_properties.py
- engines/python/setup/djl_python/tensorrt_llm.py
- engines/python/setup/djl_python/tests/test_properties_manager.py
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
JIT compilation and others changes in another PR. Separated them for easy review. https://github.com/deepjavalibrary/djl-serving/pull/1678
Changes in this PR:
- Handler support to handle inference with python backend. tensorrt_llm_toolkit recognizes whether it is a python backend based on "use_python_backend" parameter sent with init_inference. 
- If rolling_batch is disabled, then the handler will automatically assume it is python backend and inits the inference. If the model is not supported by python backend, tensorrt_llm_toolkit will throw the error saying model is not supported.
> [TrtLLM] Python backend support for T5 model

- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
- wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
- wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
T5 handler support is in another PR. Separated my changes into multiple PR for easy reviewing https://github.com/deepjavalibrary/djl-serving/pull/1680
This is for TensorRT-LLM T5 python backend
- Does JIT compilation of T5 models
- Automatically sets dynamic batch if not provided.
- Automatically sets engine=MPI and mpi_mode=True
NOTE: User has to disable rolling_batch in order for us to set dynamic batch and engine=mpi with these changes. We could do disable rolling batch ourselves, but did not do that way because, if TRTLLM release C++ backend support for T5 in between our releases, user could upgrade their TRTLLM in requirements.txt and enable rolling batch and test them. But open to suggestions here.
Testing:
Tested with flan-t5-xl in my EC2 machine.
My serving.properties
``` …
```
> [TrtLLM] Support JIT compilation and dynamic batch for TrtLLM python backend

- .github/workflows/lmi-no-code.yml
- tests/integration/llm/client.py
- wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
lcnc support for dbrx, lcnc integ tests
> [lcnc] support dbrx model

- serving/docker/Dockerfile
- serving/docker/aarch64.Dockerfile
- serving/docker/deepspeed.Dockerfile
- serving/docker/pytorch-gpu.Dockerfile
- serving/docker/pytorch-inf2.Dockerfile
- serving/docker/tensorrt-llm.Dockerfile
Re-raise the PR https://github.com/deepjavalibrary/djl-serving/pull/1681
> [0.27.0-dlc] Use fixed versions in dockerfile

- .github/workflows/lmi-dist-deps-build.yml
Build flash-attn from fork which allows smaller block-sizes for paged-attn. [[branch](https://github.com/ymwangg/flash-attention/tree/specdec_v0.3.3)]
- If this change is a backward incompatible change, why must this change be made? N/A
- Interesting edge cases to note here: N/A
> [feat] Build flash-attn from fork which allows smaller block-sizes for paged-attn

- engines/python/setup/djl_python/deepspeed.py
`from_config` does not accept any kwargs except for attn_implementation. removing all kwargs from calls to from_config, which only occurs in ds handler
> fix params for from_config model instantiation

- engines/python/setup/djl_python/chat_completions/chat_properties.py
- engines/python/setup/djl_python/chat_completions/chat_utils.py
- engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
- engines/python/setup/djl_python/tests/test_properties_manager.py
> [python] Update chat properties

- engines/python/setup/djl_python/chat_completions/chat_utils.py
In chat completions, there's no do_sample parameter. And in rolling batch handlers, if do_sample is not set, temperature will be reset to 0. So set do_sample parameter in chat_completions.
https://github.com/deepjavalibrary/djl-serving/blob/master/engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py#L112
https://github.com/deepjavalibrary/djl-serving/blob/master/engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py#L93
> [python] Set do_sample from temperature in chat completions

- serving/docs/adapters.md
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
- serving/src/test/resources/adaptersInModelDir/config.properties
- serving/src/test/resources/adaptersInModelDir/modelProp/model.py
- serving/src/test/resources/adaptersInModelDir/modelProp/serving.properties
- serving/src/test/resources/adaptersInModelDir/s3AdaptersInModelDir/adapters/a/readme.md
- serving/src/test/resources/adaptersInModelDir/s3AdaptersInModelDir/adapters/b/readme.md
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
This increases the default adapter directory checks to include both the model dir (where the serving.properties is) and the download dir (where the model files are).
> Supports adapters in download dir

- wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
missed this one in the initial model mapping list. tested with both vllm and lmi-dist
> [lcnc] add starcoder2 model type to auto configure list

- engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
The following config does not work with LMI-Dist currently because of how we validate mpi mode:
```
engine=Python
option.mpi_mode=true
option.rolling_batch=lmi-dist
option.model_id=modelid
```
This PR fixes that.
> [lmi-dist] fix validation of mpi in properties validation

- .github/workflows/lmi-no-code.yml
1. Paged_kv_cache not supported by gpt neox
```
assert default_net(
INFO  LmiUtils convert_py: AssertionError: Paged KV cache is not supported for this model yet, will add in future release
```
2. But if disabled, inflight batcher does not work
```
WARN  PyProcess W-449-model-stderr: [1,0]<stderr>:Arguments: (RuntimeError("error: load model: Invalid argument - load failed for model 'fe19578afd651a19e1a73eddc27c47b677ae5410': version 1 is at UNAVAILABLE state: Internal: unexpected error when creating modelInstanceState: TrtGptModelInflightBatching requires GPT attention plugin with packed input and paged KV cache.;\n"),)
```
It seems this will be supported in next version v0.9.0
> [TRTLLM] Remove gptneox from LCNC trtllm tests

- engines/python/setup/djl_python/deepspeed.py
- engines/python/setup/djl_python/properties_manager/hf_properties.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- engines/python/setup/djl_python/tensorrt_llm.py
- engines/python/setup/djl_python/tensorrt_llm_python.py
- engines/python/setup/djl_python/tests/test_properties_manager.py
- engines/python/setup/djl_python/transformers_neuronx.py
Two fixes related to providing custom input/output formatters. While not a fully supported use-case, there are currently users relying on this behavior that we need to maintain support for.
1. custom input formatting for tensorrtllm handlers. Users of previous versions rely on overriding `parse_input` method of the Service object. the static parse_input method no longer works for overriding, so i've made `self.parse_input` accessible again so that users can override this default implementation the same way they do in previous releases.
2. custom output formatting by providing `option.output_formatter` no longer works. We probably missed this when making the changes to per request output_formatter. This also adds back that logic
>  [fix] fix custom input and output formatting

- engines/python/setup/djl_python/tensorrt_llm_python.py
- engines/python/setup/djl_python/utils.py
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
If the user sends, client side batch then the result is json array. If the user sends single input, then we send back json object. 
Examples:
Request : `"inputs":["The new movie that got Oscar this year"]`
Response : 
```
[
{
"generated_text":"The new movie that got Oscar this year is The Shape of Water."
}
]
```
Request: `"inputs":"The new movie that got Oscar this year"`
Response:
```
{
"generated_text":"The new movie that got Oscar this year is The Shape of Water."
}
```
> [TRTLLM Python backend]Fix the output format for client side batching in dynamic batch 

- serving/docs/lmi/deployment_guide/instance-type-selection.md
Minor updates to instance-type-selection doc
> [docs] Minor updates to instance-type-selection doc

- serving/docs/lmi/deployment_guide/deploying-your-endpoint.md
Adds following details to SageMaker endpoint deployment guide:
1. https://docs.aws.amazon.com/sagemaker/latest/dg/large-model-inference-hosting.html
(Option to set VolumeSizeInGB, ModelDataDownloadTimeoutInSeconds, ContainerStartupHealthCheckTimeoutInSeconds)
We could point to AWS docs (ideal) or mention these in our docs itself.
2. Another is to deploy uncompressed model: https://docs.aws.amazon.com/sagemaker/latest/dg/large-model-inference-uncompressed.html
> [Docs] Update Endpoint Deployment guide to specify advanced config options

- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/tests/test_rolling_batch.py
- serving/docs/lmi/user_guides/lmi_input_output_schema.md
2 changes:
1. in details, return "inputs" instead of "input_text" to match the request body "inputs"
2. change generated_tokens -> generated_text in the output formatter method signatures
> fix naming of some inconsistent fields in output formatters

- wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
- wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
This is a workaround to set the default rb size for vllm and lmi-dist to 256. 
I would like to capture this in the LmiConfigRecommender.configure api, but that will rely on https://github.com/deepjavalibrary/djl-serving/pull/1727
> [lcnc] make default rolling batch size 256 for vllm, lmi-dist

- serving/src/main/java/ai/djl/serving/ModelServer.java
This is a quick fix for when user has local model artifacts in /opt/ml/model, and also sets HF_MODEL_ID=/opt/ml/model.
Previously, we attempt to load this model twice, which can cause issues. Now, we will just load it once via HF_MODEL_ID. 
This is a very simple check that probably doesn't address all cases, but should for the common case
> fix issue with duplicate model loading for local hf model on sagemaker

- serving/docker/pytorch-inf2.Dockerfile
Add torchvision to the docker image, this will replace the need for a requirements.txt in the python integration test and allow us to use just one traced model artifact rather than one per version of pytorch.
> [tnx] add torchvision for resnet tests

- tests/integration/llm/prepare.py
We updated the AMI around the same time that this test started failing. This AMI brought in a new cuda driver (old:  535.54.03, new: 535.161.08).
That's the only change during the timeframe where this behavior changed that makes sense as the cause. None of the source changes we have made are relevant to this change in behavior.
> [ci][vllm] reduce max seq len for gemma vllm

- wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
If tnx is available in serving features only use Python mode for now.
> [tnx] update default neuron rolling batch for correct mpi mode config

- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
Adds infer entry point logic to LmiConfigRecommender, and removes the duplicate logic from PyModel.
This will also address a couple of issues:
- this will now infer the correct entrypoint when djl-serving is only provided with raw model files (previously this did not work)
- this will now infer the correct entrypoint when HF_MODEL_ID=<s3_uri>. This did work previously, but some of the previous refactor around HF_MODEL_ID to fix other issues exposed some of the issues in the PyModel entry point logic
> [lmi] infer entry point for lmi models in LmiConfigRecommender

- .github/workflows/benchmark-nightly.yml
- .github/workflows/instant_benchmark.yml
- tests/benchmark/nightly/g5-2xl.txt
- tests/integration/benchmark/nightly/g5-2xl.txt
- tests/integration/record_benchmark.py
This creates a new nightly benchmark action. Right now, it only contains a single mistral test for a POC. Later, this config file can be replaced with a more intentional suite to track.
Sample Run: https://github.com/deepjavalibrary/djl-serving/actions/runs/8792872806/job/24129825770?pr=1787
> [CI] Creates nightly benchmark

- .github/workflows/llm_inf2_integration.yml
- tests/integration/download_models.sh
Update Python mode test to utilize torchvision installed on the container.
> [tnx][ci] add resnet test w/o requirements.txt

- serving/docker/tensorrt-llm.Dockerfile
Updating TRTLLM to 0.9.0.
- We will install cudnn8 manually from apt to get the latest version
> upgrade trtllm to 0.9.0

- serving/docker/tensorrt-llm.Dockerfile
libnccl already ships with libcudnn, explicitly installing it is causing an error - https://github.com/deepjavalibrary/djl-serving/actions/runs/8853249246/job/24313655935#step:10:2048
> Remove libnccl-dev installation in trtllm container

- engines/python/src/main/java/ai/djl/python/engine/Connection.java
- serving/docker/pytorch-inf2.Dockerfile
- serving/docs/lmi/user_guides/tnx_user_guide.md
Bump versions for Neuron SDK and optimum-neuron. Additionally fixed a pip install bug in the dockerfile, and added NO_OMP_NUM_THREADS=true for pytorch based multithreading.
> [tnx] version bump Neuron SDK and Optimum

- .github/workflows/llm_inf2_integration.yml
- tests/integration/llm/prepare.py
Removing redundant test, broken mistral test, and fixed opt streaming config.
> [tnx] fix CI for running on 2.18.1

- .github/workflows/benchmark-nightly.yml
- tests/integration/benchmark/nightly/g5-12xl.txt
- tests/integration/benchmark/nightly/g5-48xl.txt
- tests/integration/record_benchmark.py
> Creates initial benchmark suite

- engines/python/setup/djl_python/properties_manager/properties.py
In Pydantic v2, the default protected namespace is model_, causing warnings in logs when properties like model_id_or_path are used. However, model_id_or_path doesn't conflict with any Pydantic BaseModel configurations.
This issue also suppresses errors when overriding Pydantic configurations like model_validate. The Machine Learning community has raised concerns, suggesting that Pydantic shouldn't restrict users from using model_, hinting at potential changes in Pydantic v3.
Currently, we're addressing this by setting properties_namespaces to an empty tuple, eliminating warnings since model_id_or_path doesn't override any core Pydantic methods.
> Resolve protected_namespaces warning for pydantic

- .github/workflows/lmi-no-code.yml
1. Add gptneox test back as v0.9.0 now supports paged kv cache for gptneox
> Add back LCNC test for gptneox in trtllm

- tests/integration/llm/prepare.py
In peft>=0.6.0 version, they did make a change that breaks the backward compatibility of old adapters. They no longer support `enable_lora` and `merge_weights` configurations` in `adapter_config.json`. 
Issue Link https://github.com/huggingface/peft/issues/1087
I tried the solution that is suggested in the above issue. Manually downloaded the model and removed the `enable_lora` and `merge_weights` configurations. Peft was able to load the adapter weights. Checked the inference output, and it was generated the same outputs as before, no garbage. 
So here, uploaded the adpater model in our s3 bucket and updated the url in our testing. 
Leaving another note here, https://github.com/huggingface/peft/issues/379 - Issue which requries retraining. So if we stick with peft, we might need to …
> Updated s3url gpt4all lora adapter_config.json

- tests/integration/llm/client.py
- tests/integration/rb_client.py
> [CI] Fix test LLM client

- serving/docker/partition/partition.py
- serving/docker/partition/sm_neo_neuron_partition.py
- serving/docker/partition/sm_neo_utils.py
This PR adds additional JumpStart integration in the Neo Neuron partitioning scripts. When a JumpStart model is passed in, the script will output Neuron subgraphs to be consumed by JumpStart. When JumpStart metadata files `__model_info__.json` and `__script_info__.json` files are found & and the environment variable `SM_CACHE_JUMPSTART_FORMAT` is set, the Neo partitioning script will output the Neuron Cache subgraphs for the current model under the directory `PRE_COMPILED_NEURON_GRAPH_INFER`in the partitioning output.
The subgraphs will also be saved to a secondary location in the Neuron cache: e.g:
```
/<cache dir>/JUMPSTART_COMPILED_GRAPHS/neuronxcc-2.13.68.0+6dfecc895/<JumpStart model id>/inference/PRE_COMPILED_NEURON_GRAPH_INFER/neuronxcc-2.13.68.0+6dfecc895/<Module folders>
```
this …
> [Neo] Add JumpStart Integration to SM Neo Neuron AOT compilation flow

- serving/src/main/java/ai/djl/serving/ModelServer.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
If the error occurs at model initialization is failed, we handle the exception at CompletableFuture `exceptionally`, to wait for 3 seconds and then stop the model server. Then we before even checking whether model server is stopped or not, we bind to the 8080 address, and then we check for model server is stopped or not. 
This causes problems with SageMaker, since it receives the ping HTTP Status as 200, they mark the endpoint as `InService`.
> Stop the model server when model download fails

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- engines/python/setup/djl_python/tests/test_rolling_batch.py
- serving/docs/lmi/user_guides/lmi_input_output_schema.md
Support input log_probs in our API. 
If user sends `"decoder_input_details": true` and `details: true`, prefill in details is sent. 
If user sends `decoder_input_details:true` and `details: false`, prefill in details is still sent, but other values would be null. 
Testing:
Tested with vllm gpt2 model, with both  json and jsonline output formatter.
> [vllm, lmi-dist] Support input log_probs

- tests/integration/llm/prepare.py
Tests failing fetching the model from HF - https://github.com/deepjavalibrary/djl-serving/actions/runs/8934805108/job/24542311372.
Use s3 models instead.
> Use s3 models for llama gptq

- tests/integration/llm/prepare.py
- wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
To check whether model is already converted or not for TRTLLM python repo. In TrtLLM 0.10.0, Triton support for T5 is getting released. Once it is released, we will be removing TRTLLM python support in our handlers and toolkit.
> [T5] TRTLLM python repo model check

- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/tests/test_rolling_batch.py
- engines/python/setup/djl_python/tests/test_test_model.py
> add TGI compat feature for rollingbatch

- serving/docker/tensorrt-llm.Dockerfile
1. Update TRT Container to build with Triton 24.04. One of the motivations for this is to check if it addresses a segfault issue.
> Update TRT-LLM Container to build with Triton 24.04

- .github/workflows/llm_integration_p4d.yml
1. Currently, when the command `docker rm -f $(docker ps -aq) ` fails with an error such as `https://github.com/deepjavalibrary/djl-serving/actions/runs/8987762857/job/24687145016#step:11:185` i.e. `Error response from daemon: cannot remove container "/magical_proskuriakova": could not kill: tried to kill container, but did not receive an exit event` - in this case, we do a `|| sudo systemctl restart docker`. However, this second command itself also fails leading to further error - `Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.`. The `||` solution isn't really working. We perhaps need multi-level cleanup in a script such as `terminate_container.sh`
2. Revert change to restart docker …
> Remove docker daemon restarts from p4d workflow

- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/tests/test_rolling_batch.py
- engines/python/setup/djl_python/tests/test_test_model.py
- wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java
Cherrypick TGI compat fix to 0.27.0
> [CherryPick][0.27.0] add TGI compat feature for rollingbatch (#1866)

- serving/src/main/java/ai/djl/serving/ModelServer.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
> [cherry-pick][0.27.0-dlc] Stop the model server when model download fails (#1842)

- awscurl/src/main/java/ai/djl/awscurl/AwsCurl.java
- awscurl/src/test/java/ai/djl/awscurl/AwsCurlTest.java
> [awscurl] Allows override stream parameter for dataset

- engines/python/setup/djl_python/neuron_utils/model_loader.py
- engines/python/setup/djl_python/transformers_neuronx.py
Updates behavior to default to the generation.config eos token list when loading instruct type models. Changing the default loading strategy for llama and mistral to support multiple eos tokens in generation.config. (Llama3 / Instruct fine tuned models)
> [tnx] Default to generation.config generation settings

- engines/python/setup/djl_python/neuron_utils/model_loader.py
This PR adds the following logic: When loading a Neuron model, if the currently set Neuron cache directory is read-only, the model loader will copy the contents of this read-only directory to the default Neuron cache location and use the default Neuron cache location for compiling the model. 
This enables the ability for users to pass in a Neuron cache directory with pre-prepared graphs in the input model location (`/opt/ml/model`) on a SageMaker endpoint, which is read-only.
Currently, if a user attempts to pass a Neuron cache in the input model directory they will encounter an error like:
```
[WARN ] PyProcess - W-100-model-stderr: File "/usr/local/lib/python3.9/dist-packages/libneuronxla/neuron_cc_cache.py", line 118, in __enter__
[WARN ] PyProcess - W-100-model-stderr: self.lock_fd = …
```
> [tnx] Read-only Neuron cache workaround for SM

- plugins/management-console/src/main/java/ai/djl/serving/console/ConsoleRequestHandler.java
- serving/src/main/java/ai/djl/serving/util/ConfigManager.java
This updates the default management port to be 8081 to match the documented behavior in
https://docs.djl.ai/docs/serving/serving/docs/configurations_global.html#configure-listening-port.
> Updates default management port

- .github/workflows/instant_benchmark.yml
- tests/integration/benchmark/nightly/g5-12xl.txt
- tests/integration/benchmark/nightly/g5-2xl.txt
- tests/integration/benchmark/nightly/g5-48xl.txt
- tests/integration/instant_benchmark.py
- tests/integration/record_benchmark.py
Supporting benchmark handle in matrix
> [IB] support benchmark matrix

- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/utils.py
There are two cases where the current implementation is buggy for adapters.
* When unregistered adapter is specified in the inference request
* When incorrect number of adapters is specified for client side batching
In both these cases, input is sent to the backend engine and error is populated for the request as well. As a result the model server will send the error response back to the client while the engine still keeps processing the request.
In this change, when an error occurs, the input request will not be sent to the engine.
> [BugFix] Fix bug when invalid adapters are passed

- tests/integration/instant_benchmark.py
This will fix the replicated parameter in `vars` not applied into `benchmark_vars` replications
> [IB] fix a bug in IB

- engines/python/setup/djl_python/utils.py
Add logic to ensure that when adapters are not supported that parse input still passes
> [fix] inf2 pipeline fix for adapter unsupported

- engines/python/setup/djl_python/properties_manager/properties.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/neuron_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- engines/python/setup/djl_python/tensorrt_llm.py
- engines/python/setup/djl_python/tests/rolling_batch/fake_rolling_batch.py
- engines/python/setup/djl_python/tests/test_rolling_batch.py
- engines/python/setup/djl_python/tests/test_test_model.py
- engines/python/setup/djl_python/transformers_neuronx.py
In this PR:
1. option.tgi_compat in serving.properties and OPTION_TGI_COMPAT env both should work
2. Refactored rolling_batch class to accept Configs(parsed properties) instead of kwargs. 
3. [Breaks backward compatibility] token_id won't be list anymore. Since, now speculative decoding, we are adding multiple tokens. 
Testing:
Tested with scheduler rolling batch with env and serving.properties for bloom-560m model.
> Refactor tgi compat and removed token_id as list

- engines/python/setup/djl_python/request_io.py
- engines/python/setup/djl_python/utils.py
Breaking down the changes of refactoring the output formatter and supporting multiple sequences into multiple PRs. 
Added minimum getters and setters in the PR, will be adding more in the other PRs.
> Add request output dataclasses

- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/properties_manager/hf_properties.py
- engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
- engines/python/setup/djl_python/properties_manager/properties.py
- engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
- engines/python/setup/djl_python/tests/test_properties_manager.py
1. In TensorLLM,  instead of `if not config.mpi_mode`, it was `if config.mpi_mode` 
2. In properties,  we dont need `is_mpi` property, it should be `mpi_mode`. 
Tested with docker env HF_MODEL_ID and OPTION_TGI_COMPAT
> [fix] mpi mode check in trtllm

- engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_neuron_scheduler.py
Fixing CI failures for inferentia integration tests. Slot was being cleared before completing the generation so rolling batch completions resulted in error messages.
> [fix] Fix for neuron rolling batch CI error

- serving/docker/pytorch-inf2.Dockerfile
Moving neuron container to python 3.10, ubuntu 22.04, and bumping versions of optimum in preparation for vllm 0.4.2.
> [tnx] version bumps for the container

- .github/workflows/sagemaker-integration.yml
- tests/integration/install_sagemaker_pysdk.sh
- tests/integration/llm/sagemaker-endpoint-tests.py
Updating the SM PySDK tests that have been failing for a while. I've removed usage of our custom DJLModel implementation for now, since we need to either update those classes or decide what we do with them moving forward.
For now, these tests validate key functionality on SM endpoints, including:
- Uncompressed model artifacts with SM native solution (network isolation use-case)
- LMI and TRT LLM containers with S5cmd and hf hub test-cases
- MME test
I also removed the partitioning test cases. Test run with these changes https://github.com/deepjavalibrary/djl-serving/actions/runs/9179268954.
We have discussed removing this suite entirely, but I think this is needed/useful to validate key SM functionality works with our containers
> fix sagemaker test suite

- .github/workflows/lmi-dist-deps-build.yml
Updates vllm dependency to `v0.4.2`. Built flash-attn from @ymwangg `v0.4.2` fork [here](https://github.com/deepjavalibrary/djl-serving/actions/runs/9161478592/job/25186488317)
> [dep] Update flash-attn dependency build

- serving/docs/lmi/tutorials/tnx_aot_tutorial.md
> [docs] fix wrong hf token env var in doc

- tests/integration/launch_container.sh
1. Noticed during some local runs that, higher MNT value on p4d may cause shm memory OOM, very rare. 
2. This change may help in ruling out role of shm size in intermittent llama2 70b failures we see on p4d for tp8
> Update shm size for trtllm test

- serving/docs/lmi/user_guides/lmi_input_output_schema.md
Adding error response schema details to the lmi docs. **Note: this is the state of 0.28.0**
This should cover the most common error scenarios when using LMI with the different modes (streaming/non-streaming, rolling-batch/dynamic-batch).
I've tested all the scenarios and validated that this is what the responses look like for various scenarios.
I don't think we have docs for the inference api error responses (at least I can't find them). I've left those out of scope for now as it probably deserves its own doc if we want to add those details.
> [docs][lmi] update input/output schema docs with error response details

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
1. In `lmi-dist`, t5 model impl is different from other models and preprocessor's tokenizer attribute contains `tokenizer` directly instead of `TokenizerGroup`
2. skip sending prompt token details for t5 as it does not populate those in request output. Current code errors out as `request_output.prompt_token_ids` is an integer of bos token and fails in the for loop enumeration.
> fix t5 tokenizer and prompt token failures

- .github/workflows/llm_inf2_integration.yml
- engines/python/setup/djl_python/properties_manager/tnx_properties.py
- engines/python/setup/djl_python/tests/neuron_test_scripts/test_neuron_vllm_rolling_batch.py
- engines/python/setup/djl_python/tests/neuron_test_scripts/test_transformers_neuronx.py
This PR is meant to reorganize neuron testing so that we can test unit tests in context as a djl_python wheel + test scripts so that it can be added to other CI tests with different environments.
> [tnx] refactor neuron testing

- engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
vllm changed the PromptLogProbs dataclass in 0.4.2
in vllm 0.3.3
```
PromptLogprobs = List[Optional[Dict[int, float]]]
```
in vllm 0.4.2
```
@dataclass
class Logprob:
logprob: float
rank: Optional[int] = None
decoded_token: Optional[str] = None
PromptLogprobs = List[Optional[Dict[int, Logprob]]]
```
Will test it with vllm 0.4.2, once it is ready.
> [vllm 0.4.2] prompt log probs changes

- serving/docker/tensorrt-llm.Dockerfile
1. Currently, on the container, the `libtriton_tensorrtllm_common.so` is not correctly linked to `libtensorrt_llm.so`:
```
root@1255f90326fc:/opt/tritonserver/backends/tensorrtllm# ldd libtriton_tensorrtllm_common.so
linux-vdso.so.1 (0x00007fff9a34c000)
libtensorrt_llm.so => not found
libtritonserver.so => /opt/tritonserver/lib/libtritonserver.so (0x00007f14ad69f000)
libmpi_cxx.so.40 => /usr/lib/x86_64-linux-gnu/libmpi_cxx.so.40 (0x00007f14ad685000)
....
```
2. Adding the path to tensorrt_llm libs from dist-packages to fix this. After fix:
```
root@1255f90326fc:/opt/tritonserver/backends/tensorrtllm# ldd libtriton_tensorrtllm_common.so
linux-vdso.so.1 (0x00007ffc8d976000)
libtensorrt_llm.so => /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so …
```
> Add tensorrt_llm libs to LD_LIBRARY_PATH

- engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
Seq2Seq model fix for lmi-dist
**Pending build of RE with the corresponding backend fix**
> [fix] Seq2Seq model fix for lmi-dist

- SECURITY.md
Adds a new file to introduce the security policy. The initial version is based off of torchserve: https://github.com/pytorch/serve/blob/master/SECURITY.md.
> Adds SECURITY.md file

- serving/docker/lmi.Dockerfile
Freeze lmi-dist version for lmi container
> [0.28.0-dlc][lmi] freeze versions for LMI Dist

- serving/docs/lmi/user_guides/lmi-dist_user_guide.md
- serving/docs/lmi/user_guides/vllm_user_guide.md
Update lmi-dist and vllm docs for 0.28.0 release
- If this change is a backward incompatible change, why must this change be made? N/A
- Interesting edge cases to note here N/A
> [docs] Update lmi-dist and vllm docs for 0.28.0 release

- engines/python/setup/djl_python/output_formatter.py
- engines/python/setup/djl_python/request.py
- engines/python/setup/djl_python/request_io.py
- engines/python/setup/djl_python/tests/test_rolling_batch.py
- engines/python/setup/djl_python/utils.py
For best_of, we wait for the whole generation is finished, because we would not know which of the multiple sequences has the highest cumulative probability until the end of the generation. This is the reason, TGI supports best_of only during non streaming case. 
This PR, introduces best_of support in json_output_formatter. 
Unit test case:
Added unit test case to validate the output formatter. 
Integration tests:
In order to test this in integration test, vllm/lmi-dist handler should support this. Will create a new PR for this, as the changes are a lot. Meanwhile, this PR changes should not fail any integration tests.
> best_of support in output formatter

- .github/workflows/llm_integration.yml
- tests/integration/launch_container.sh
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
Mount to tmp with NVME disk and also adding model update support
> [CI] add nvme support and update model

- .github/workflows/run-max-num-tokens.yml
- tests/integration/llm/run_max_num_tokens.py
This is the branch I was using to run all the max_num_tokens numbers for 0.28.0; it contains lots of small changes.
- double check cleaning model artifacts directory 
- multiple tries for model downloading
- fallback to aws s3 cp from s5cmd
- error handling for cases of non OOM error
- better logging
- timeout increased
- increase shared memory size
- mount to nvme instead of EBS volume
- add g6.12xlarge
> Update max num tokens workflow, fix multiple bugs

- serving/docs/lmi/user_guides/lmi_input_output_schema.md
Removing `[]` from the token id in token object in schema docs.
> [lmi][docs] fix token format in api schema docs

- serving/docker/lmi.Dockerfile
> [docker] Remove onnxruntime cpu jar in lmi docker

- serving/docs/lmi/user_guides/output_formatter_schema.md
> [doc] custom output formatter schema

- serving/docs/lmi/announcements/deepspeed-deprecation.md
- serving/docs/lmi/user_guides/deepspeed_user_guide.md
add deepspeed deprecation notice
> [lmi][docs] add deepspeed deprecation notice to lmi docs

- .github/workflows/llm_integration.yml
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
Adds llama-3-8b lora test for vllm and lmi-dist.
Tested locally.
> Add llama-3 lora test

- serving/docs/lmi/user_guides/output_formatter_schema.md
Addressing Sid's comments in the previous PR.
> [doc] improve output schema doc

- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/request.py
- engines/python/setup/djl_python/request_io.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/neuron_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- engines/python/setup/djl_python/tensorrt_llm.py
- engines/python/setup/djl_python/tensorrt_llm_python.py
- engines/python/setup/djl_python/transformers_neuronx.py
- engines/python/setup/djl_python/utils.py
Updating typing nomenclature to support py38, python types are not sub-scriptable in py38 and we should instead use the typing class associated with the type. This will avoid build problems for users using ubuntu 20.04 and below.
> [serving] Update python typing to support py38

- .github/workflows/llm_integration.yml
- engines/python/setup/djl_python/test_model.py
- engines/python/setup/djl_python/tests/test_test_model.py
- serving/docs/lmi/deployment_guide/configurations.md
- serving/docs/lmi/deployment_guide/deploying-your-endpoint.md
- serving/docs/lmi/deployment_guide/testing-custom-script.md
- serving/docs/lmi/tutorials/trtllm_aot_tutorial.md
- serving/docs/lmi/tutorials/trtllm_manual_convert_tutorial.md
> remove usage of SERVING_LOAD_MODELS in examples/docs/tests

- serving/docs/lmi/user_guides/lmi_input_output_schema.md
> [doc] add tgi_compat and see details

- serving/src/main/java/ai/djl/serving/ModelServer.java
If customer has mounted model artifacts to /opt/ml/model, and also specified HF_MODEL_ID=/opt/ml/model, then the container fails to startup with
```
ERROR ModelServer Invalid configuration
ai.djl.serving.http.BadRequestException: Workflow model is already registered.
at ai.djl.serving.models.ModelManager.registerWorkflow(ModelManager.java:92) ~[serving-0.28.0.jar:?]
at ai.djl.serving.ModelServer.initModelStore(ModelServer.java:444) ~[serving-0.28.0.jar:?]
at ai.djl.serving.ModelServer.start(ModelServer.java:208) ~[serving-0.28.0.jar:?]
at ai.djl.serving.ModelServer.startAndWait(ModelServer.java:174) ~[serving-0.28.0.jar:?]
at ai.djl.serving.ModelServer.main(ModelServer.java:143) [serving-0.28.0.jar:?]
```
Issue is that when adding to the list or urls, we returned the local path which is …
> fix bug with duplicate models when HF_MODEL_ID points to model store

- jacoco/build.gradle.kts
- plugins/secure-mode/src/main/java/ai/djl/serving/plugins/securemode/SecureModeModelServerListener.java
- plugins/secure-mode/src/main/java/ai/djl/serving/plugins/securemode/SecureModeUtils.java
- plugins/secure-mode/src/test/java/ai/djl/serving/plugins/securemode/SecureModePluginTest.java
- serving/src/main/java/ai/djl/serving/http/IllegalConfigurationException.java
- serving/src/main/java/ai/djl/serving/util/NettyUtils.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
1. Add jacoco report
2. improve code coverage
3. Remove unrelated features
> [secure-mode] Refactor secure mode plugin

- serving/docs/lmi/user_guides/release_notes.md
> [doc] adding release notes for docs.djl.ai

- serving/docker/partition/properties_manager.py
Test case passed : https://github.com/deepjavalibrary/djl-serving/actions/runs/9521520715/job/26249192465
We dont need validate quantization in properties_manager.py. We already do validate in HuggingFaceProperties which is called before quantization.
> [fix] remove validating quantization in properties_manager.py

- serving/docker/partition/properties_manager.py
> [cherry-pick][0.28.0-dlc][fix] remove validating quantization in properties_manager.py

- .github/workflows/continuous.yml
- .github/workflows/llm_inf2_integration.yml
- .github/workflows/llm_integration.yml
- .github/workflows/llm_integration_p4d.yml
- .github/workflows/lmi-dist-deps-build.yml
- .github/workflows/lmi-no-code.yml
- .github/workflows/lmic_performance.yml
- engines/python/setup/setup.py
- engines/python/src/test/resources/accumulate/requirements.txt
- serving/docker/pytorch-gpu.Dockerfile
- serving/docker/scripts/install_python.sh
pinning the numpy version across ci/docker to <2. nump 2.x is released, and causing issues across ci/docker.
I will wait to merge this until reviewing with team on monday
> pin numpy to <2 in ci/docker

- engines/python/setup/djl_python/output_formatter.py
- engines/python/setup/djl_python/request_io.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- engines/python/setup/djl_python/tests/rolling_batch_test_scripts/test_rb_vllm_utils.py
Supported top_n_token for vllm, lmi-dist 
ToDo:
1. Add it chat output_formatter
2. Add parameters in integration test
3. Adding unit test cases with fake rolling batch
> [vllm, lmi-dist] add support for top_n_tokens

- tests/integration/instant_benchmark.py
Fix issue where env variables passed using IB are not being added to the container when running IB.
Current implementation will add the `docker_env` file to `./model/test` relative to the current working directory, however, the `docker_env` needs to be in the same directory as the `./launch_container.sh` when it is run in order to add the env variables to the container. Since the paths were already relative in the script I updated the file right to current working directory `./` rather than `./model/test`
> [ib] fix docker env file write location

- serving/docker/partition/sm_neo_quantize.py
- serving/docker/partition/sm_neo_trt_llm_partition.py
- serving/docker/partition/sm_neo_utils.py
Currently, the Neo Quantization script will always quantize at `tensor_parallel_degree=8` and output `tensor_parallel_degree=8` in serving.properties. This is often not compatible with serving, so we will avoid outputting this value. 
Specifically, with AWQ quantized small models like Llama-2-7b, they can not be served with tp=8. This is because the intermediate_size / tp_degree must be divisible by the quantization group size (128). In this case, intermediate_size after quantization is 5632, so valid tp_degrees are 1,2, and 4.
**New behavior**: Neo still quantizes with `tensor_parallel_degree=8` but the output will depend on customer input to Neo.
- If a customer passes `tensor_parallel_degree` in serving.properties or through the environment variable (but not both):
- The inputted …
> [Neo] Fix Neo Quantization properties output. Add some additional configuration.

- serving/docker/partition/partition.py
Fixes the quantization path when doing AOT partitioning for weight only quantization strategies, since these do not require any AOT model changes.
> [aot] Fix aot quantization for weight only quantization

- tests/integration/instant_benchmark.py
This extends the instant benchmark system to allow environment variables to be referenced from within a config parsing by using $ENV_VAR_NAME. Putting it within an [env] block can forward environment variables into the docker container.
> [IB] Supports forwarding environment variables

- .github/workflows/codeql-analysis-java.yml
Adding codeql for python as well.
Sample wf https://github.com/deepjavalibrary/djl-serving/actions/runs/9569675600.
I can see that it did scan the python, but I don't know where to find the results (there are logs in the wf run).
> codeql for python

- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/tensorrt_llm.py
- engines/python/setup/djl_python/transformers_neuronx.py
- engines/python/setup/djl_python/utils.py
- Our handlers calls the rolling_batch.inference and constructs the output, but our handlers share the same code, so there are some code duplication
- So extracted the duplicated code to utils.py. 
- In huggingface.py, inference method is too long, so modularized them. 
- There are some further more refactor will be done next week, which will clean up these method signatures further better.
> [python] refactor rolling batch inference method

- engines/python/setup/djl_python/neuron_utils/model_loader.py
Fixes Neuron compilation logging. Example logs that were missing:
```
2024-02-21 01:04:37.000772: 246 INFO ||NEURON_CC_WRAPPER||: Using a cached neff at /opt/ml/compilation/cache/neuronxcc-2.12.54.0+f631c2365/MODULE_b135f12bed698159448c+ede6753c/model.neff. Exiting with a successfully compiled graph.
2024-02-21 01:04:37.000823: 247 INFO ||NEURON_CACHE||: Compile cache path: /opt/ml/compilation/cache
2024-02-21 01:04:37.000875: 247 INFO ||NEURON_CC_WRAPPER||: Using a cached neff at /opt/ml/compilation/cache/neuronxcc-2.12.54.0+f631c2365/MODULE_b702d7ddf38e1da4abf8+ede6753c/model.neff. Exiting with a successfully compiled graph.
2024-02-21 01:04:38.000380: 248 INFO ||NEURON_CC_WRAPPER||: Using a cached neff at /opt/ml/compilation/cache/neuronxcc-2.12.54.0+f631c2365/MODULE_02b140725c88b5ccd39 …
```
> [Neuron] Fix Neuron compilation logging

- serving/docker/tensorrt-llm.Dockerfile
- tests/integration/llm/prepare.py
Checklist
Notes: 
- I have found that transformers 4.40 is compatible with the container.
- Running another build on this container after the changes to see if there are any errors (done)
> bump up trtllm to 0.10.0

- serving/docker/lmi.Dockerfile
- serving/docker/pytorch-inf2.Dockerfile
This PR moves our nightly wheels to a new format that is consistent with the newest version of pip. The proposed versioning of our nightly wheels would be as follows:
`package-0.0.0+nightly-py3-none-any.whl`
I am leaving this in draft until we confirm the naming as acceptable.
> [ci] fix nightly wheel pip installs

- engines/python/setup/djl_python/tensorrt_llm.py
- engines/python/setup/djl_python/tensorrt_llm_python.py
> [fix] Set tokenizer on output_formatter for TRT-LLM Handlers

- serving/docker/tensorrt-llm.Dockerfile
> [0.28.0-dlc][cherry-pick][dockerfile] pin datasets to 2.19.1 in trtllm (#2104)

- .github/workflows/llm_integration.yml
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
Fix some error conditions and telemetry tracking
> [CI] fix bugs

- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
- serving/src/main/java/ai/djl/serving/util/ConfigManager.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
Expose configurations to override default http response codes in error situations.
The only one exposed that has not been leveraged is the TimeoutException. That specific case needs some more work that i'll take up in a separate pr.
> [serving] make http response codes configurable for exception cases

- wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
Updating the behavior of LmiConfigRecommender to match the behavior of the default properties when using a serving.properties for NeuronX containers. The recommender currently defaults all models to rolling batch, but this is not the desired behavior for LMI NeuronX due to the limited number of supported models for rolling batch.
This undoes a change that was a altered the default as aa side effect of the recommenders implementation but is not consistent in defaulting between launching with environmental variables and serving.properties for LMI NeuronX.
> [fix] align default neuron behavior between model server and handler

- serving/build.gradle.kts
- serving/docker/Dockerfile
- serving/docker/lmi.Dockerfile
- serving/docker/pytorch-gpu.Dockerfile
- serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java
> [docker] Fixes onnxruntime engine installation

- engines/python/setup/djl_python/huggingface.py
Conversation, and "conversation" task for hf pipelines have been removed in release 4.42.0 https://github.com/huggingface/transformers/releases/tag/v4.42.0. 
Removing usage from our handler.
This use-case is now handled by the text-generation pipeline from hf. I think some updates are needed there to make it work, but for now just removing the usage.
> [lmi][hf]remove usage of HF Conversational pipeline as it is deprecated

- tests/integration/tests.py
- prepare.py has serving.properties, which has `option.model_id=gpt2` 
- and env has HF_MODEL_ID also has gpt2. So it is loading the model again, which leads to OOM. 
https://github.com/deepjavalibrary/djl-serving/actions/runs/9698967044/job/26767133000#step:7:476
> [ci] remove HF_MODEL_ID env for lmi_dist_1 test

- wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
> [onnx] Allows to customize onnxruntime optimization level

- engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
**This bug is only in master, not in 0.28.0. This fixes the LMI no-code low code CI failures.**
Even if we set logprobs=1, sometimes, vLLM sends more than one log probabilities. Here for new log probs, we add all the log probabilities that are return by vLLM to new_logprobs dict. 
But when we determine whether it is last token or not, `i == (len(new_logprobs) -1)` and this fails, because now it has more than one new probs, this case will never be true. So last_token never occurred, so it returned broken json without any details. Hence the CI failed. 
Will add unit test cases for this use-cases as well in the next PR.
> [python] Fix new logprobs computation in vllm_utils

- .github/workflows/integration_execute.yml
This adds an action to allow for running parts of the pytest integration suite. It allows for choosing a single instance and a class or function to run. In a later PR, this should be extended to also support running based on pytest marks.
> [CI] Action for manual pytest runs

- engines/python/setup/djl_python/arg_parser.py
- engines/python/setup/djl_python/service_loader.py
- engines/python/setup/djl_python_engine.py
- engines/python/src/main/java/ai/djl/python/engine/Connection.java
- engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
Existing flow: If model.py exists in the model directory, without explicitly set by the user either in serving.properties or environment variables, then we take that as the entryPoint. 
This PR:
- Still takes model.py as the entryPoint.
- But we also send the inferred built in handler as the recommended_entry_point to the python engine. 
- In the python side, we check whether the given entry point has the `handle` or handler function name. If it does not exist, then we use the recommended_entry_point as the entry point
Tests:
- Manually tested in my ec2 machine.
> [engine] include lmi recommended entrypoint when model.py exists

- engines/python/setup/djl_python/output_formatter.py
- engines/python/setup/djl_python/request_io.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/tests/test_rolling_batch.py
- engines/python/setup/djl_python/three_p/three_p_utils.py
3p Changes:
1. Fix the output formatters to respond with the correct expected payload schema
2. Add metering and error details to the output schema for 3p use-case
3. force do_sample to be true when temperature > 0
General Change:
1. Add exception details to the Token that is set when rolling batch inference occurs. This makes it possible for output formatters to further provide specific error details in the response rather than just saying "error". This is currently only used by the 3p output formatters.
> [3p][python]add metering and error details to 3p outputs

- .github/workflows/docker-nightly-publish.yml
- .github/workflows/integration_execute.yml
- tests/integration/tests.py
This revives the use of the temp repo from #1266 and implements it in the execute job. The job can now be used to automatically test a particular branch through the temp repo. The repo is automatically built as part of the job. So, to test a branch using the pytest suite with actions, these are the only steps required:
1. Push the branch to test to the deepjavalibrary/djl-serving upstream repo
2. Run the integration execute job with the default djl-version "temp"
> [CI] Supports temp repo in execute job

- engines/python/setup/djl_python/arg_parser.py
- engines/python/setup/djl_python/properties_manager/hf_properties.py
- engines/python/setup/djl_python/properties_manager/properties.py
- engines/python/setup/djl_python/tests/test_properties_manager.py
- engines/python/setup/djl_python_engine.py
- engines/python/src/main/java/ai/djl/python/engine/Connection.java
- engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
- engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
> Support multi node for lmi-dist

- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/input_parser.py
- engines/python/setup/djl_python/request.py
- engines/python/setup/djl_python/request_io.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/neuron_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/trtllm_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- engines/python/setup/djl_python/tensorrt_llm.py
- engines/python/setup/djl_python/tensorrt_llm_python.py
- engines/python/setup/djl_python/tests/rolling_batch/fake_rolling_batch.py
- engines/python/setup/djl_python/tests/rolling_batch_test_scripts/test_rb_vllm_utils.py
- engines/python/setup/djl_python/tests/test_input_parser.py
- engines/python/setup/djl_python/tests/test_rolling_batch.py
- engines/python/setup/djl_python/tests/test_test_model.py
- engines/python/setup/djl_python/transformers_neuronx.py
- engines/python/setup/djl_python/utils.py
Refactoring input parser to support Request. Before this PR, we loop through the list of requests to list of input_text, input_size, parameters etc.. and then in rolling batch, we loop through through these parsed list and then convert to list of requests `Request` again. This PR aims to avoid this duplicate work. 
1. Before this PR, we duplicated the parameters for client side batching, which is not needed anymore as we no longer maintain this as list, we maintan this a list of Requests. 
2. In this PR, we assume, if adapter_registry is non empty, then adapters needs to be looked in the requests. If adapter_registry is empty, then we dont look for adapters. 
3. In this PR, we introduced server_parameters => which will have the server modified parameters and the built-in handlers should …
> [python] refactor input parser to support Request

- engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
- engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
> [python] add max_logprobs vllm configuration to EngineArgs

- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/tests/test_test_model.py
There is quite a bit of old/outdated logic scattered throughout djl_python and our default handlers. I'll be raising PRs to slowly clear out this outdated logic.
This change removes the "auto" logic for rolling batch from out python code. This logic has been fully moved to the LmiConfigRecommender on the java side. The logic here is not up to date anymore either.
> [lmi] remove redundant auto logic from python handler

- engines/python/setup/djl_python/neuron_utils/model_loader.py
- engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_modeling.py
- engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_neuron_scheduler.py
- engines/python/setup/djl_python/transformers_neuronx_scheduler/slot.py
- engines/python/setup/djl_python/transformers_neuronx_scheduler/token_selector.py
- serving/docker/pytorch-inf2.Dockerfile
- serving/docker/scripts/install_inferentia2.sh
Updating LMI NeuronX container to 2.19, optimum neuron to 0.0.23, and associated dependencies.
> [docker] bump neuron to 2.19 SDK

- engines/python/setup/djl_python/input_parser.py
- engines/python/setup/djl_python/properties_manager/properties.py
- engines/python/setup/djl_python/request.py
- engines/python/setup/djl_python/request_io.py
- engines/python/setup/djl_python/service_loader.py
- engines/python/setup/djl_python_engine.py
This PR introduces a new decorator `input_formatter`. Users are expected to annotate this in their input_formatter function in `model.py`. 
This PR also expects the user to define their input_formatter with signature 
```
def my_custom_input_formatter(input_item: Input, **kwargs) -> RequestInput:
```
Example of UX for users writing their own input formatter:
```
from djl_python import Input
from djl_python.input_parser import input_formatter
from djl_python.request_io import TextInput
from djl_python.encode_decode import decode
@input_formatter
def custom_input_formatter(input_item: Input, **kwargs):
request_input = TextInput()
content_type = input_item.get_property("Content-Type")
input_map = decode(input_item, content_type)
inputs = input_map.pop("inputs", input_map)
params = …
```
> [python] add input formatter decorator

- awscurl/README.md
> [awscurl] Updates docs for downloading stable version

- engines/python/setup/djl_python/tests/neuron_test_scripts/neuron_rb_generator.py
- engines/python/setup/djl_python/tests/neuron_test_scripts/test_neuron_tnx_rolling_batch.py
- engines/python/setup/djl_python/tests/neuron_test_scripts/test_neuron_vllm_rolling_batch.py
- engines/python/setup/djl_python/tests/neuron_test_scripts/tiny_models.py
- engines/python/setup/djl_python/tests/rolling_batch_test_scripts/run_rolling_batch_alone.py
Create a tnx rb correctness test as well as E2E tests w/o the model server for a variety of model types as tiny random models.
> [tnx] neuron rolling batch test suite

- serving/docker/pytorch-inf2.Dockerfile
Update to the version 0.5.0 wheel for vllm neuron
> [docker] bump neuron vllm to 5.0

- .github/workflows/integration.yml
- engines/python/setup/djl_python/properties_manager/hf_properties.py
- engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
- engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
- serving/docker/lmi.Dockerfile
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/tests.py
CI test: https://github.com/deepjavalibrary/djl-serving/actions/runs/9916087551
> [lmi] Upgrade lmi dockerfile for 0.29.0 release

- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
> [wlm] Trim whitespce for model_id

- serving/docs/configurations.md
> [docs] Adds document for MAX_NETTY_BUFFER_SIZE env var

- .github/workflows/integration_execute.yml
- tests/integration/pytest.ini
- tests/integration/tests.py
This adds marks to the pytest integration suite. They can be used to run suites of tests outside of just the class restrictions. Specifically, it is useful for running tests for a feature, backend, or instance type.
These marks are then integrated into the integration runner test suite. Using it, you can specify both keywords and marks for what tests to run to describe a test suite. We can also grow the marks to include more details and features to run specific components for testing.
Example run: https://github.com/deepjavalibrary/djl-serving/actions/runs/9944892966
@tosterberg
> [CI] Add integration pytest marks

- serving/docs/lmi/deployment_guide/benchmarking-your-endpoint.md
> [docs] Adds benchmark guide for bedrock

- serving/docker/partition/sm_neo_quantize.py
- serving/docker/partition/sm_neo_trt_llm_partition.py
- serving/docker/partition/sm_neo_utils.py
- serving/docker/partition/trt_llm_partition.py
- serving/docker/partition/utils.py
1. Refactor structure of script to be more in line with `sm_neo_neuron_partition.py`
2. Remove code related to deprecated Neo `compiler_flags`
3. Move generation of `serving.properties` file post-compilation from `tensorrt_llm_toolkit` to here
4. Add support for HF dataset cache env var
> [Neo] Refactor Neo TRT-LLM partition script

- serving/docker/partition/utils.py
Changes partition script behavior to only output `option.parallel_loading=true` when handler=DeepSpeed. No longer outputs this field for Neuron & LMI handlers.
> [Partiton] Don't output `option.parallel_loading` when partitioning

- engines/python/setup/djl_python/arg_parser.py
- engines/python/setup/djl_python/properties_manager/hf_properties.py
- engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python_engine.py
- engines/python/src/main/java/ai/djl/python/engine/Connection.java
- engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
- engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
- serving/docker/partition/properties_manager.py
- serving/docker/partition/trt_llm_partition.py
- wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
- wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
> Introduce pipeline parallel degree config

- engines/python/setup/djl_python/neuron_utils/model_loader.py
- serving/docker/partition/sm_neo_neuron_partition.py
- serving/docker/partition/sm_neo_quantize.py
- serving/docker/partition/utils.py
Cherry-pick for the following Neo fixes for v10 containers
587fa2241665cc3702e9a0d2b897a8a0ac01caa2 - [[Link to PR](https://github.com/deepjavalibrary/djl-serving/pull/2189)] - Today's fix of parallel_loading
88f84ba7c127c1e639b3527cae6128d0e9e97730 - [[Link to PR](https://github.com/deepjavalibrary/djl-serving/pull/2115)] - Various Neo script fixes for QuickSilver
ac4acb8b860e45d4138186a9522edc8449c166ad - [[Link to PR](https://github.com/deepjavalibrary/djl-serving/pull/2095/commits)] - vLLM logging fix
> [cherrypick][0.28.0 dlc] Neo fixes (#2189) (#2115) (#2095)

- serving/docker/config.properties
- serving/src/main/java/ai/djl/serving/ModelServer.java
- serving/src/main/java/ai/djl/serving/ServerInitializer.java
- serving/src/main/java/ai/djl/serving/http/ClusterRequestHandler.java
- serving/src/main/java/ai/djl/serving/util/ClusterConfig.java
- serving/src/main/java/ai/djl/serving/util/ConfigManager.java
- serving/src/main/java/ai/djl/serving/util/Connector.java
> [serving] Adds mutliple node cluster configuration support

- serving/docker/partition/partition.py
CI is failing for Neuron for AOT due to pipeline parallel being added to properties_manager.py in partitioning but not in the partion.py parse args. This adds the argument and fixes the CI.
> [aot] fix aot partition args, add pipeline parallel

- serving/src/main/java/ai/djl/serving/ModelServer.java
- serving/src/main/java/ai/djl/serving/http/ClusterRequestHandler.java
- serving/src/main/java/ai/djl/serving/util/ModelStore.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
- wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
> [serving] Download model while initialize multi-node cluster

- README.md
- engines/python/README.md
- serving/docker/README.md
- wlm/README.md
I've been directing people to djl-serving, but there has been confusion since the docs still have links to 0.27.0 instead of 0.28.0.
I didn't touch the LMI area which still has 0.27.0 as I am not so clear on that area, but there are plenty of 0.27.0 references in there.
> Update documentation to latest release 0.28.0.

- engines/python/setup/djl_python/chat_completions/chat_utils.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
This cannot be merged until the lmi-dist changes have been merged + built.
I have tested this with llava and phi3 models. PaliGemma requires vllm 0.5.2, lmi-dist is currently on 0.5.1.
> [lmi] support multimodal in lmi-dist

- tests/integration/llm/prepare.py
Seems like llama3 checkpoint used in the test was updated with `max_model_len` greater than what's supported for lora. Explicitly setting value to maximum supported value for lora.
> Update max_model_len for llama-3 lora test

- tests/integration/llm/prepare.py
Previous to pipeline_parallel being added to hf properties, the base behavior for TP > 0 would initiate device mapping as auto. With the addition of pipeline_parallel it now also requires pipeline_parallel to be set PP > 0. Both of these values default value is -1, so this changed the default behavior.
I have fixed this by specifically adding the device mapping, but we should consider reverting the issue above.
https://github.com/deepjavalibrary/djl-serving/blob/master/engines/python/setup/djl_python/properties_manager/hf_properties.py#L116-L137
> [ci] fix hf lora test for accelerate

- tests/integration/llm/client.py
> [ci] Fix pipeline failures

- .github/workflows/integration.yml
- .github/workflows/integration_execute.yml
- tests/integration/llm/client.py
This adds fixes for a few different CI issues. First, it fixes the pipeline for running execute with non-temp mode such as nightly.
Then, it adds a new check to verify a non-error result from awscurl. This does detect the hidden trtllm errors we have been observing. Here is an [example run](https://github.com/deepjavalibrary/djl-serving/actions/runs/10045418675) detecting it.
Finally, the above trtllm errors stem from using an old version of aws curl. This also updates to using the proper download which fixes those problems. See this [example run](https://github.com/deepjavalibrary/djl-serving/actions/runs/10045610755/job/27763272590)
> [CI] Miscellaneous CI Fixes

- .github/workflows/lmi-no-code.yml
Take out Falcon from supported model list
> take out falcon from the test list

- engines/python/setup/djl_python/chat_completions/chat_utils.py
- engines/python/setup/djl_python/input_parser.py
- engines/python/setup/djl_python/output_formatter.py
- engines/python/setup/djl_python/request.py
- engines/python/setup/djl_python/request_io.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
- engines/python/setup/djl_python/tests/test_rolling_batch.py
- engines/python/setup/djl_python/three_p/three_p_utils.py
Make input ids computation to lazy, not required all the time
>  lazy compute input ids

- engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_modeling.py
- engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_neuron_scheduler.py
- engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_token_selector.py
Fix transformers issue with optimum token selection post 4.43 update. Fix sampling for rolling batch post transformers bump.
OptimumTokenSelector is a copy of optimum-neuron's token selector but upgraded to work with transfomers 4.43, and can be removed and reverted after the dependencies are updated to support llama3.1
> [tnx] fix optimum token selection and sampling

- wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
> [multimodal] add additional vlm architectures to lmi config recommender

- .github/workflows/integration.yml
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/tests.py
> [multimodal][ci] adding multimodal tests

- serving/docker/lmi.Dockerfile
> put back neuron installation

- serving/docker/partition/sm_neo_neuron_partition.py
- serving/docker/partition/sm_neo_quantize.py
Fixes AttributeError caused by new property in PropertiesManager:
https://github.com/deepjavalibrary/djl-serving/blob/1016a233e852d76a3319fb0c3f01de46710fcd90/serving/docker/partition/properties_manager.py#L48-L50
> [neo] Fix AttributeError in Neo partition scripts

- tests/integration/llm/prepare.py
Paligemma has an issue with tensor parallelism in vllm due to some issue in the preprocessing.
I have raise a bug with vllm https://github.com/vllm-project/vllm/issues/6910.
The failure that was occurring with phi3v was due to not including the custom modeling files in s3 - i have fixed that.
> [multimodal][ci] do not use tp for paligemma due to issues in vllm

- .github/workflows/llm_inf2_integration.yml
- .github/workflows/llm_integration.yml
This PR adds fast fail workflows that stand in for manually triggered workflows on release branches. These files should be retained until maintenance windows have passed for 0.28.0-dlc release branch.
> [ci] add files for triggering old workflows

- .github/workflows/benchmark-nightly.yml
- engines/python/setup/djl_python/tests/neuron_test_scripts/tiny_models.py
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/pytest.ini
- tests/integration/tests.py
This PR adds nightly benchmarking for our main GPU handlers (lmi-dist, vllm, trtllm), using tiny-llama it does performance testing for batch size 1 and 128 for both the standard and chat template inference paths. The performance metrics are persisted to cloudwatch for monitoring.
> [ci] add handler performance test

- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/tests.py
With 2.19.1 - Mistral v2 models work with continuous batching, Mistral v1 with windowed context sill does not work and as such the Mixtral rolling batch test was moved to a dynamic batch test until it is resolved.
> [ci] Update neuron tests to mirror observed mistral/mixtral support

- tests/integration/llm/client.py
Previous functionality tested the string output of jsonlines, meaning if the substring "error" appeared in the output rather than just as a response key the test would fail. Now we are explicitly looking for a failure code on a json response, side stepping the parsing of a jsonlines output.
> [ci] fix lora testing to fail on error response code

- tests/integration/tests.py
Fix tests.py typo in handlers used for testing mistral and mixtral.
> [ci] fix neuron rb test failure

- tests/integration/llm/prepare.py
AutoAwq error seems to be happening with 4.43.2 transformers version. https://github.com/casper-hansen/AutoAWQ/issues/558
As suggested in the issue, setting device_map to auto, resolves the error.
> [ci] fix auto awq integration test failure

- serving/docker/partition/partition.py
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/tests.py
This PR cleans up duplication in handler testing functions and should bypass errors coming from hub downloads.
> [ci] fix hf hub flakiness remove unused prepare

- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/tests.py
This PR introduces support for running the Llama-3-8B model with 8-bit (fp8) quantization using TensorRT LLM. The changes include:
1. Adding configuration for the trtllm-meta-llama3-8b-fp8 model in client.py and prepare.py, specifically with option.quantize: "fp8" for 8-bit quantization.
2. Adding a new test case test_llama3_8b_fp8 in tests.py to run the correctness test for the trtllm-meta-llama3-8b-fp8 model with 8-bit quantization.
3. Updating the awscurl_run function in client.py to use os.makedirs with exist_ok=True for creating the dataset directory.
> Add support for Llama-3-8B fp8 quantization with TensorRT LLM

- engines/python/setup/djl_python/chat_completions/chat_properties.py
- serving/docs/lmi/user_guides/chat_input_output_schema.md
> [cherry-pick] add ignore_eos support in chat completions schema (#2281)

- serving/docker/tensorrt-llm.Dockerfile
> [TRTLLM] take out cudnn

- engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
- engines/python/setup/djl_python/request_io.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
- engines/python/setup/djl_python/tests/test_rb_vllm_utils.py
It also caused dummy tokens to be returned to client with `(token_id=-1, text="", logprob=null)`, which is mostly harmless but does cause some tools (including awscurl) to report an incorrect TTFT with chunked prefill, since the TTFB will be after just the first chunk is processed due to the returned dummy token.
Added a couple of tests for the above cases, shown below failing before the change and passing after.
Before:
```
$ time python -m unittest -v djl_python.tests.test_rb_vllm_utils
test_chunked_prefill (djl_python.tests.test_rb_vllm_utils.TestVllmUtils) ... FAIL
test_chunked_prefill_prompt_logprobs (djl_python.tests.test_rb_vllm_utils.TestVllmUtils) ... ERROR
test_multiple_sequences (djl_python.tests.test_rb_vllm_utils.TestVllmUtils) ... ok …
```
> [lmi_dist][vllm] Fix chunked prefill bug that caused error with prompt_logprobs

- plugins/secure-mode/src/main/java/ai/djl/serving/plugins/securemode/SecureModeUtils.java
- plugins/secure-mode/src/test/java/ai/djl/serving/plugins/securemode/SecureModePluginTest.java
In certain valid cases, Hosting platform will pass an empty string as the untrusted channels env var. This PR ensures errors will not be thrown as a result.
> [secure-mode] Allow untrusted channels env var to be empty string

- engines/python/setup/djl_python/properties_manager/tnx_properties.py
- engines/python/setup/djl_python/tests/neuron_test_scripts/test_transformers_neuronx.py
- engines/python/setup/djl_python/transformers_neuronx.py
This PR updates LMI NeuronX's default logic for `n_positions`, updating it from a naive 128 tokens to being based off of the model configs max embeddings, or 4096 - whichever is smaller.
> [feat] lmi neuronx add smart defaults n_positions

- engines/python/setup/djl_python/neuron_utils/model_loader.py
- serving/docker/partition/partition.py
- serving/docker/partition/run_partition.py
- serving/docker/partition/sm_neo_neuron_partition.py
- serving/docker/partition/sm_neo_quantize.py
- serving/docker/partition/sm_neo_trt_llm_partition.py
- serving/docker/partition/sm_neo_utils.py
- serving/docker/partition/utils.py
- Removes unused logic for parsing Neo CompilerOptions.
- Improves error messaging for Neo. The actual error message will be passed to errors.json, rather than just "Partitioning Failed".
- Clarifies the error message for unsupported Neuron models.
- JumpStart cache
- Previously, JS cache is outputted to `output/optimized_model/`
- Now, it will be saved in root dir, and merged with inputted cache if it exists:
- i.e. `output/PRE_COMPILED_NEURON_GRAPH_INFER` 
- Skips duplicating model weights when copying input files to output. Only skips weights in the root directory to preserve draft models. 
- Change error messages for all Neo scripts to OptimizationFatalError from CompilationFatalError
> [Neo] [Neuron] Various CX improvements for Neo Neuron entrypoint

- serving/docker/pytorch-inf2.Dockerfile
Update optimum-neuron version to 2.19.1 Neuron SDK supporting release.
> [docker] LMI Neuron bump optimum-neuron version

- engines/python/setup/djl_python/neuron_utils/model_loader.py
- engines/python/setup/djl_python/neuron_utils/utils.py
- engines/python/setup/djl_python/tests/neuron_test_scripts/test_transformers_neuronx.py
Adds smart defaults for context length estimates when using continuous batching.
> [feat] lmi neuronx add smart defaults context length estimates

- tests/integration/llm/prepare.py
In the previous PR, we decided to set device_map to None, as some models like object detection does not work with pipeline parallelism. Before that, we default device_map = auto always, which is not good. 
Now, we need to enable it whenever we want to use pipeline parallelism. [This will be a breaking change in V12]
> [ci] fix device_map auto change in hf handler

- tests/integration/llm/client.py
Fix awscurl run headers: Remove space because it's string.
> [ci] Fix awscurl run headers

- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/tests.py
> [ci] Add models in text embedding integration

- serving/docker/lmi.Dockerfile
> [docker] update vllm wheel for version required by lmi-dist

- .github/workflows/llm_integration.yml
> [ci] remove precompiled trt tests because of switch from g5 to g6

- tests/integration/llm/prepare.py
- wlm/build.gradle.kts
- wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
- wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
- wlm/src/main/java/ai/djl/serving/wlm/NeuronSmartDefaultUtils.java
- wlm/src/test/java/ai/djl/serving/wlm/NeuronSmartDefaultUtilsTest.java
- wlm/src/test/resources/smart-default-model/2b/config.json
- wlm/src/test/resources/smart-default-model/70b/config.json
- wlm/src/test/resources/smart-default-model/8b/config.json
- wlm/src/test/resources/smart-default-model/empty/config.json
- wlm/src/test/resources/smart-default-model/unit/config.json
Part 2 of the smart defaults for Neuron. Updates:
- rolling batch default to auto
- TP degree heuristically determined based on model config
- max rolling batch size heuristically determined based on model config
Smart defaults are determined by the maximum concurrency for the total instance, so in instances where we are will to make a large tradeoff for latency we will need to override the max batch size and lower it.
> [lmi][neuron] Add smart defaults to LMI Neuron

- serving/docker/lmi.Dockerfile
Built locally and ran sample inference with llama3-8b to test
> [docker][lmi] fix torch and flashattention dependency versions

- serving/docker/partition/sm_neo_quantize.py
Fixes issue caused by: https://github.com/casper-hansen/AutoAWQ/issues/558.
Fixes the following error message:
```
"OptimizationFatalError('Encountered an error during quantization: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat2 in method wrapper_CUDA_bmm)')",
```
Fixed in Neo by always quantizing with device_map=auto.
Relates to https://github.com/deepjavalibrary/djl-serving/pull/2271. That PR fixes this issue by passing the device_map=auto in serving.properties. For non-Neo quantization, this will still be required.
> [Neo][vLLM] Fix quantization failure caused by improperly loaded model.

- .github/workflows/lmi-no-code.yml
Llama3-13b requires accuracy correction with additional env's and needs to be removed as an LCNC target until it is addressed in the underlying neuron framework.
> [ci] llama-2-13b on inf2 requires additional config removing from LCNC

- engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java
- serving/src/main/java/ai/djl/serving/http/HttpRequestHandler.java
- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
- serving/src/main/java/ai/djl/serving/http/Session.java
- serving/src/main/java/ai/djl/serving/util/ConfigManager.java
- serving/src/main/java/ai/djl/serving/util/NettyUtils.java
1. Parse requestId from HTTP header that is present on SageMaker (and SageMaker like) platforms
2. Log requestId details in relevant places on the invocations/predictions route
This is part 1 of the requestId logging changes. It only touches the java side
- This is the best we can to on the Java side, and should be sufficient. 
Part 2 will focus on the python side
> [serving] add request id logging on invocations/predictions path

- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
vllm 0.6.0 uses msgspec for sampling params after 0.6.0 which means that we can no longer pull available params out of dictionary keys.
> [python] Update vllm rolling batcher sampling params for 0.6.0 support

- engines/python/setup/djl_python/neuron_utils/model_loader.py
- serving/docker/pytorch-inf2.Dockerfile
- wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
- wlm/src/main/java/ai/djl/serving/wlm/NeuronSmartDefaultUtils.java
- wlm/src/test/java/ai/djl/serving/wlm/NeuronSmartDefaultUtilsTest.java
Update docker to latest nightly vllm for LMI Neuron
> [docker][neuron] Version bumps for vllm 0.6.0

- serving/docker/partition/partition.py
- serving/docker/partition/sm_neo_quantize.py
This PR adds additional pass-through options to configure awq & fp8 quantization.
For **AWQ**, we add the following options. These map to the options [defined here](https://github.com/casper-hansen/AutoAWQ/blob/eab1a4accf56bd01b3050b091fb74cfb42bf3c6e/examples/cli.py#L16).
- `option.awq_zero_point`: toggles zero point quantization
- `option.awq_block_size`: (existing field) group/block size for awq quantization
- `option.awq_weight_bit_width`: bit width for quantization. currently only 4 is supported.
- `option.awq_mm_version`: awq matmul implementation
- `option.awq_ignore_layers`: layers to ignore during quantization
For **FP8**, we add the following options. These are [defined here](https://github.com/neuralmagic/AutoFP8/blob/2cd265ffbcf73cfcca4c11b42673d93c5d508476/auto_fp8/config.py#L …
> [Neo][vLLM] Accept quant options for awq, fp8

- serving/docker/partition/partition.py
Fixed: The calib_size property was not being properly parsed as an int, causing a quantization failure when passing this field.
> [neo] Fix calib_size dtype bug

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
> [python] Update lmi-list generation params after upgrading to vllm 0.5.5

- serving/docker/lmi.Dockerfile
> [docker] Update vllm to 0.6.1.post2

- serving/docker/tensorrt-llm.Dockerfile
Bumps up transformers version in the master branch
After this is approved, I will then cherry-pick to 0.30 and 0.29 branches
For this to be approved, I will have to validate that llama 3.1 is indeed compatible with this version of transformers.
> bump up transformers version for llama 3.1 support

- engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
I am not sure why we were not doing this before - seems like we just missed it.
With the planned updates on lmi-dist, not passing in the batch size is going to cause issues with the vllm warmup phase as it uses batch size, max model len, and max prefill tokens to structure the warmup. Without passing in the batch size here, we default to the vllm 256 (which is conviently our default), but we don't respect any overrides on the vllm side.
We do this for neuron already, need to have this for gpu as well.
> [fix][vllm][lmi] pass batch size to vllm engine args

- serving/docker/tensorrt-llm.Dockerfile
Bumps up Dockerfile to TRTLLM v0.12.
Important information
This bump up is different from earlier ones - there are some things that I could not test yet due to some technical issues with installing tensorrt_llm for breaking changes that require new binaries. It seemed to be missing a binary I could not provide. Hence, due to this change, our nightly container is prematurely sent to v12, so it may have some bugs for around a day or so - I will fix all remaining issues and test as quickly as possible.
To clarify, the bugs left are related to how the code for tp_size, pp_size, etc. is written. It should work regardless, but I just need to double check.
I have found that the other breaking changes including use_custom_all_reduce and max_output_len are non-blocking pending changes (they do not …
> [TRTLLM] Bump up dockerfile

- engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
> [vllm] Validate speculative model config

- engines/python/setup/djl_python/output_formatter.py
- engines/python/setup/djl_python/request_io.py
When exception occurs in inference, we catch it and set the last token as dummy token. So atleast one token should be set, even if exception occurred. 
But to check whether last_token_index is set or not, we check `if _last_token_index` will be false when `last_token_index=0`. 
This PR reverts the yesterday's PR. 
Tested it manually in my ec2 machine
> [python] fix last token fetch logic

- engines/python/setup/djl_python/arg_parser.py
- engines/python/setup/djl_python_engine.py
- engines/python/src/main/java/ai/djl/python/engine/Connection.java
- engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
This PR enables specification of the log level in djl_python_engine.
For now, we only switch between info/debug based on whether debug logging is enabled on the java side.
While we could allow for more log levels here (in pyenv), we rely on certain info level logs from python to execute the engine successfully on the java side.
This also slightly adjusts the format of the python log message to indicate the level we are logging at
> [python] allow debug logging in python engine

- serving/docker/pytorch-inf2.Dockerfile
- serving/docker/scripts/install_inferentia2.sh
Update to Neuron 2.20.0 SDK for LMI Neuron
> [docker] bump neuron version to 2.20.0 SDK

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
Ensure 'sampling_params' is not in LMI_DIST_GENERATION_PARAMS. This could happen with the old code due to the use of the delegation pattern for lmi_dist RequestParams.
> [lmi] Ensure 'sampling_params' is not in LMI_DIST_GENERATION_PARAMS

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
> [fix][lmi] Pass max_num_seqs param to lmi_dist

- engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_neuron_scheduler.py
- engines/python/setup/djl_python/transformers_neuronx_scheduler/slot.py
- tests/integration/tests.py
Fixing error with default behavior when do_sample is true but neither top_p / top_k are set. Fix added for defaulting the prefill/decode bool to None inside the NiaveRollingBatcher to support the updates to Optimum modeling. Additionally, removing stale model tests.
> [fix] optimum token selector do sample defaults

- .github/workflows/docker-nightly-publish.yml
- .github/workflows/serving-publish.yml
- buildSrc/src/main/kotlin/ai/djl/javaBase.gradle.kts
- gradle/libs.versions.toml
- serving/docker/Dockerfile
- serving/docker/aarch64.Dockerfile
- serving/docker/lmi.Dockerfile
- serving/docker/pytorch-gpu.Dockerfile
- serving/docker/pytorch-inf2.Dockerfile
- serving/docker/scripts/install_djl_serving.sh
- serving/docker/tensorrt-llm.Dockerfile
This PR aims to move towards decoupling the DJL library from DJL Serving by:
1. Separating version dependencies between DJL and DJL Serving in the Dockerfiles and Gradle build files.
2. Introducing the serving_publish.yml workflow in the DJL-Serving repository to manage releases independently.
We also remove the Maven publishing logic in the serving_publish workflow as it is no longer needed. 
3. Decoupling DJL version and DJL-Serving versioned publish artifacts for docker container builds in djl serving installation script 
- aarch64 in nightly publish needs to grab env variables again because it's on a separate runner
> Decouple djl and serving in dockerfiles and gradle and add serving publish

- engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
Given the fact that the bonus token was thrown away in previous versions of lmi_dist, the true number of speculative tokens was effectively off by 1 from how it was configured. Now that we correctly handle bonus token rather than throwing it away, the new version will have the same behavior with speculative_length 4 that the previous versions had with speculative_length 5 (but with better performance!). Thus, we change the default to 4.
We need a followup PR to update the documentation accordingly.
> [lmi] Change speculative_length default to 4

- engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_neuron_scheduler.py
Removing attention mask from prepare inputs - it is now handled by the optimum modeling prepare decode and prepare prefill functions which homogenize the model inputs to the generic forward call of input ids, cache ids, seq ids.  This should fix the new failures in the LMI Neuron CI where OptimumForCausalLM forward is getting an unexpected keyword argument 'attention_mask'.
> [fix] forward compatibility for transformers_neuronx_scheduler

- engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py
- engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
- engines/python/src/main/java/ai/djl/python/engine/Connection.java
- engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
- engines/python/src/main/java/ai/djl/python/engine/PyModel.java
- engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
- wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
This adds pipeline-parallel support to lmi-dist rolling batch, whether multi-node or not. It also updates logic on the java side for how to handle pipeline parallel degree and tensor parallel degree. Finally, it switches to a passive worker mode when using MPI, where the frontend only sends inference messages to rank 0 after model load--trtllm already worked this way, but it's extra important when running with pipeline parallelism to not synchronize the worker processes after each iteration.
> [lmi][lmi-dist] Add pipeline-parallel support to lmi-dist, and use_passive_workers by default

- serving/docker/lmi.Dockerfile
the docker build kept installing vllm 0.6.2 instead of the patch build from my fork. could not figure out why and in the end it was just a typo. this now installs the correct vllm patch with support for MLlama. i validated it works and will raise the pr for tests
> [docker] fix typo vllm_version -> vllm_wheel

- engines/python/setup/djl_python/neuron_utils/model_loader.py
- engines/python/setup/djl_python/properties_manager/tnx_properties.py
- engines/python/setup/djl_python/tests/test_properties_manager.py
- engines/python/setup/setup.py
Add neuron sdk config changes to tnx properties, and enable sharded model save / load.
> [neuron] update tnx properties for 2.20.0 SDK

- engines/python/setup/djl_python/huggingface.py
We should rely on the engine provided tokenizer in rolling-batch use-cases instead of creating our own.
> [lmi] use engine provided tokenizer for rolling_batch use-cases

- engines/python/setup/djl_python/neuron_utils/neuron_smart_default_utils.py
- engines/python/setup/djl_python/tests/neuron_test_scripts/test_neuron_smart_default_utils.py
- engines/python/setup/djl_python/transformers_neuronx.py
- tests/integration/llm/prepare.py
- tests/integration/tests.py
Add smart default logic to python only path, specifically AOT compilation.
This knowingly duplicates the logic applied in the wlm -> https://github.com/deepjavalibrary/djl-serving/blob/master/wlm/src/main/java/ai/djl/serving/wlm/NeuronSmartDefaultUtils.java . The reason for this is that when running AOT compilation the model servers default configuration modules are never called. This means that we are finding divergent behavior when defaulting  values while partitioning when compared to runtime compilation through the model server.
> [neuron] add smart defaults for aot partition path

- tests/integration/launch_container.sh
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/tests.py
There are a few changes in this PR, mostly related to adding new tests
1. Add multimodal tests for vllm backend (previously we only ran them for lmi-dist)
- remove paligemma test - this model does not contain a chat template, and we only support multi-modal requests via chat api. It used to work until transformers removed default chat template behavior
3. Add pixtral tests for both lmi-dist and vllm
- Note that succes of these tests depends on this PR https://github.com/deepjavalibrary/djl-serving/pull/2468/files
4. Add Mllama-11b test for vllm
- This doesn't work with lmi-dist currently
5. Add a variety of pipeline parallel tests for lmi-dist
- tp1, pp1, 4 workers
- tp1, pp2, 2 workers
- tp2, pp1 2 workers
- pp4
- tp2 pp2
- tp2 pp2 + spec dec
6. Mount aws env vars in launch_container …
> [ci][tests] adding new multimodal and pipeline parallel tests

- engines/python/setup/djl_python/neuron_utils/neuron_smart_default_utils.py
- engines/python/setup/djl_python/tests/neuron_test_scripts/test_transformers_neuronx.py
Removed smart default test for n_positions from handler as it was moved to the smart default class. Added an exception for 0 value divisors coming out of model size heuristics.
> [fix] neuron unit test smart default handler and error handling

- engines/python/setup/djl_python/output_formatter.py
- engines/python/setup/djl_python/request.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/utils.py
- engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java
With further testing, we found that pull request #2466 was incomplete. This adds the rest of what was needed.
I ran with this `model.py` script to cause exceptions to be thrown randomly, as well as a variant that overrides `postprocess_results` to not set `code` or `error`, to ensure that `@stop_on_any_exception` works as expected.
I also verified that it does not change the behavior unless enabling the feature flag.
model.py:
``` python
import djl_python.rolling_batch.lmi_dist_rolling_batch
_update_request_cache_with_output = djl_python.rolling_batch.lmi_dist_rolling_batch.update_request_cache_with_output
_ctr = 0
def update_request_cache_with_output(*args, **kwargs):
global _ctr
_ctr += 1
if _ctr % 20 == 0:
raise RuntimeError("Uh oh")
return _update_request_cache_with_output(*args, …
```
> [python] Fix backport of rolling batch non-streaming non-200 error code support

- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- engines/python/setup/djl_python/tests/rolling_batch/fake_rolling_batch.py
I was too hasty with https://github.com/deepjavalibrary/djl-serving/pull/2473. While the huggingface model config is not needed in most cases, we are currently relying on it to select the correct image token to use in multi modal use-cases.
We pull this model config directly from the engine, since at least in the case vllm/lmi-dist, there is already logic implemented there to properly pull the model config (especially in cases like mistral where you have to do a bunch of checks and parsing to get it into hf format).
This will fix the ci errors related to multi-modal. I ran all those test cases against this change and it is working. For the previous PR, i only tested pixtral well it seems.
> [lmi] expose method on RollingBatch to retrieve huggingface model config

- tests/integration/tests.py
Fixing a typo. I want to make some changes to how we specify args in the tests here, but will do that in a follow up PR since that impacts all tests.
> [fix] fix typo in t5 integration test

- serving/src/main/java/ai/djl/serving/http/AdapterManagementRequestHandler.java
- wlm/src/main/java/ai/djl/serving/wlm/Adapter.java
- wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
- wlm/src/main/java/ai/djl/serving/wlm/PyAdapter.java
- wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java
Currently adapter management API requests run together with inference request, see https://github.com/deepjavalibrary/djl-serving/blob/master/wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java#L90. The requirement is to run adapter management API requests without delay. So this PR add adapter requests to jobQueue to run.
> [lora] Add adapter config jobs to job queue

- engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java
This is a forward port of PR #2481 
Example using awscurl below.
Before:
```
timestamp: 1729797995533
input: {"inputs": "list all the names which start with the letter r","parameters":{"max_new_tokens":10,"seed":2,"do_sample":true}}
output: > POST //invocations HTTP/1.1
>
> Accept: */*
> User-Agent: awscurl/1.0.0
> Host: 127.0.0.1:8094
> Content-Type: application/json
>
< HTTP/1.1 200 OK
<
< Content-Type: application/json
< x-request-id: f5c33cdf-2313-4f81-895b-ac8c0c9eb91d
< Pragma: no-cache
< Cache-Control: no-cache; no-store, must-revalidate, private
< Expires: Thu, 01 Jan 1970 00:00:00 UTC
< transfer-encoding: chunked
< connection: keep-alive
<
{"code":424,"message":"Batch inference failed","properties":{},"content":{"keys":[],"values":[]},"cancelled":false}
```
After:
```
timestamp: …
```
> [fix] Propagate RollingBatch predict output code to request outputs

- serving/docs/configurations_model.md
- serving/docs/lmi/README.md
- serving/docs/lmi/announcements/breaking_changes.md
- serving/docs/lmi/conceptual_guide/lmi_engine.md
- serving/docs/lmi/tutorials/seq_scheduler_tutorial.md
- serving/docs/lmi/tutorials/trtllm_manual_convert_tutorial.md
- serving/docs/lmi/user_guides/chat_input_output_schema.md
- serving/docs/lmi/user_guides/hf_accelerate.md
- serving/docs/lmi/user_guides/lmi-dist_user_guide.md
- serving/docs/lmi/user_guides/starting-guide.md
- serving/docs/lmi/user_guides/trt_llm_user_guide.md
- serving/docs/lmi/user_guides/vision_language_models.md
- serving/docs/lmi/user_guides/vllm_user_guide.md
Changes:
- Move all usages of `engine=MPI` to `engine=Python, option.mpi_mode=true`
- updates to the LMI-Dist breaking changes doc
- Removes the hardcoded list of supported models in lmi-dist/vllm in favor of a link to vllm's docs.
This is the first PR related to updating LMI docs for v12. There will be additional PRs that address:
- TensorRT-LLM update
- Neuron update
Additionally, after these release we need to do the following:
- Update the deployment guide with guidance for v12+
- Move configuration usages to either all Environment variables, or all serving.properties. We should still describe that both configuration mechanisms are supported, but there's no need to duplicate these configurations everywhere.
> [lmi][v12][docs] update lmi documentation for v12

- engines/python/setup/djl_python/neuron_utils/model_loader.py
Before neuron sdk 2.18 version, we need to load the safetensors model using huggingface on CPU and save it a presharded version, then  load the model using NeuronAutoModel. After 2.18 sdk version, it is not needed anymore. 
Link: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/libraries/transformers-neuronx/transformers-neuronx-developer-guide.html#checkpoint-support-and-automatic-model-selection
```
Both regular and sharded variants of checkpoints are supported. It is no longer recommended to use the save_pretrained_split function which was used in older Transformers Neuron examples.
```
In our code, although, we have been loading the safetensors format in cpu and loading them, but `split_model_path` is not used anywhere when using safetensors format.
> [python] remove huggingface load and save for tnx

- engines/python/setup/djl_python/neuron_utils/model_loader.py
- engines/python/setup/djl_python/neuron_utils/neuron_smart_default_utils.py
- engines/python/setup/djl_python/properties_manager/tnx_properties.py
- engines/python/setup/djl_python/transformers_neuronx.py
> The saving and loading of presharded weights is only available when on_device_embedding is true.
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/libraries/transformers-neuronx/transformers-neuronx-developer-guide.html#serialization-support
Since neuron 2.20 artifacts, we need to enable on_device_embedding for pre-sharded weights. So enabling this smart default, so our UX compatibility would not break. This should also fix the neo neuron CI failures https://github.com/deepjavalibrary/lmi-distro/actions/runs/11484522981/job/31962540314
> [python] add on_device_embedding=True to save and load preshareded weights

- engines/python/setup/djl_python/neuron_utils/model_loader.py
- engines/python/setup/djl_python/properties_manager/tnx_properties.py
- engines/python/setup/djl_python/tests/test_properties_manager.py
Legacy partition is, two fold process. First, is to load the model using HF model and then split and save them. Second step is to load the split model and compile and save them. 
This is not needed anymore, from neuron 2.18. We dont need to support these anymore, as we moved to neuron 2.20.
> [python] remove legacy partition for neuron

- serving/docker/lmi.Dockerfile
> [docker] Use lmi-dist 13.0.0 nightly wheel

- serving/docker/lmi.Dockerfile
This fixes an issue with our pip install, that while broken did not reveal itself in our integ tests (things still executed, but there could have been subtle issues we were not aware of).
In particular, the way we had things setup resulted in torch 2.4.0 being installed with cu121 rather than cu124 as intended. I don't know exactly why this happened, but it does happen because we have split the pip install across multiple steps and did not ensure the torch constraint across all of them.
Additionally, we noticed that there are pydantic version configs between djl and vllm that did not reveal themselves earlier.
This PR is only going to 0.30.0 dlc. On the main branch we need to do this via a requirements file. We also need to get rid of Auto Fp8 in favor of llm compressor as auto fp8 is …
> fix lmi pip installs

- wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
Set properties load_on_devices=0 for Lora case, in order to make sure vllm rolling batch has one worker as well.
For vllm rollng batch, setting maxWorkers=1 is not enough, multiple workers will still be launched. Because devices is set to [0] for MPI engine, but not for Python engine. See https://github.com/deepjavalibrary/djl-serving/blob/v0.29.0/wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java#L1011-L1012.
Therefore, for LoRA case, need to set load_on_devices=0 to avoid launching multiple worker threads for vllm rolling batch.
> [lora] Set properties for Lora

- serving/src/main/java/ai/djl/serving/workflow/Workflow.java
Fix workflow close order
Right now we close WorkerPoolConfig first, then close WorkflowFunction.
But WorkflowFunction like AdapterWorkflowFunction is dependent on WorkerPoolConfig, see https://github.com/deepjavalibrary/djl-serving/blob/master/serving/src/main/java/ai/djl/serving/workflow/function/AdapterWorkflowFunction.java#L104-L105
If WorkerPoolConfig close first, the dependent adapters can't be closed properly.
> [fix] Fix workflow close order

- engines/python/setup/djl_python_engine.py
During testing, I found 2 cases that should be caught as OOM and send 507 status code.
Currently we only catch exceptions thrown as torch.OutOfMemoryError and MemoryError as OOM. See: https://github.com/deepjavalibrary/djl-serving/blob/master/engines/python/setup/djl_python_engine.py#L169-L171
But the below 2 cases are thrown as ValueError and RuntimeError:
1)
```
INFO  PyProcess W-495-model1-stdout: [1,0]<stdout>:ERROR::Failed invoke service.invoke_handler()
INFO  PyProcess W-495-model1-stdout: [1,0]<stdout>:Traceback (most recent call last):
INFO  PyProcess W-495-model1-stdout: [1,0]<stdout>:  File "/tmp/.djl.ai/python/0.31.0-SNAPSHOT/djl_python_engine.py", line 161, in run_server
INFO  PyProcess W-495-model1-stdout: [1,0]<stdout>:    outputs = …
```
> [python] Add more OOM handling

- serving/docker/pytorch-inf2.Dockerfile
https://github.com/deepjavalibrary/djl-serving/pull/2456 - This PR uses v0.6.2 version of vllm. It is better to maintain vllm of Lmi container and neuron container to have the same version of VLLM to avoid any discrepancies.
> [docker] upgrade neuron vllm to 0.6.2

- serving/docker/pytorch-inf2.Dockerfile
This pins the hf hub dependency to <0.26 to prevent the breaking change that introduced causing regression. I validated that this change works by building the container and running the impacted tests (neuron unit tests) locally
> [docker][inf2] pin hf hub python dependency

- serving/docker/partition/sm_neo_shard.py
The `MODEL_DIR_NAME` constant is now accessible from the `sagemaker_fast_model_loader_rust` Python module, this allows any changes to the name to be automatically reflected in the AOT sharding script.
> [neo] Get SM Fast Model Loader model dir name from package

- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- serving/src/main/java/ai/djl/serving/http/AdapterManagementRequestHandler.java
- serving/src/main/java/ai/djl/serving/http/DescribeAdapterResponse.java
- serving/src/main/java/ai/djl/serving/http/list/ListAdaptersResponse.java
- serving/src/test/java/ai/djl/serving/ModelServerTest.java
- wlm/src/main/java/ai/djl/serving/wlm/Adapter.java
Add an additional `load` option to the register adapter API and update adapter API.
The reason is for this change is to keep consistent with other model servers like vllm and lorax. vllm load_lora_adapter API don't load adapter weights, the adapter weights is only loaded when running inference using one particular adapter.
Discussed with Hosting team, making default to `true`.
Example:
```
curl -X POST "http://localhost:8080/models/model/adapters?name=eng_alpaca&load=false&src=/opt/ml/model/adapters/eng_alpaca"
```
> [lora] Add load option to LoRA adapter API

- serving/docs/adapters_api.md
> [lora] Add load option to API doc

- serving/docker/partition/sm_neo_shard.py
- serving/docker/partition/sm_neo_trt_llm_partition.py
This PR adds the generation of a `serving.properties` file to the output artifacts of AOT sharding jobs, so the `option.load_format` and `option.tensor_parallel_degree` values can be propagated when loading the artifacts for runtime
> [neo] Generate serving.properties file during sharding jobs

- serving/docker/partition/sm_neo_shard.py
This PR allows customers to pass in values for the LMI options
- `option.gpu_memory_utilization` 
- `option.enforce_eager` 
- `option.max_rolling_batch_size `
- `option.max_model_len`
during Neo AOT sharding jobs. Changing the values of these options can potentially allow a customer to shard a model on an instance which would result in OOM when using default values. Note that the customized options need to be set to the same values when loading back the artifacts during runtime; the generated `serving.properties` in the output artifacts will ensure this parity.
> [neo] Allow setting GPU memory-related LMI options in sharding jobs

- .github/workflows/continuous.yml
Currently, if one of the windows/mac/linux checks fails, we short circuit and cancel all of them. 
this change allows each one to run to completion so that we can understand where an issue lies.
See https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
> [ci] don't shor-circuit continuous pr check if 1 job in the matrix fails

- serving/docker/tensorrt-llm.Dockerfile
release container should be using the release wheel, not nightly
> [trt][docker] pin trt version to release version, not nightly

- serving/build.gradle.kts
- serving/src/main/java/ai/djl/serving/ServerInitializer.java
- serving/src/main/java/ai/djl/serving/http/ClusterRequestHandler.java
- serving/src/test/java/ai/djl/serving/http/ClusterRequestHandlerTest.java
- serving/src/test/java/ai/djl/serving/http/package-info.java
For multinode communication with > 2 nodes, it was possible to get into a race condition where two different channels try to run ssh keygen at the same time because both would fail the file-exists check. In this case, one of the keygen would be stuck asking if it should overwrite the previous file
```
~/workspace/djl/djl-serving   master  ssh-keygen -q -t rsa -N "" -f rsa_test
~/workspace/djl/djl-serving   master a ssh-keygen -q -t rsa -N "" -f rsa_test
rsa_test already exists.
Overwrite (y/n)?
```
This would cause the worker node to not be able to join the cluster and the leader node to be stuck waiting for all the workers.
With this change, we move to a single shareable ClusterRequestHandler which is used by all channels, and a `synchronize` before the file check to ensure we do …
> Create a single shareable ClusterRequestHandler for all channels to prevent ssh-keygen race conditions. Add unit tests for the ClusterRequestHandler

- serving/docker/partition/sm_neo_shard.py
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- pass Lora config to arg list  in Neo sharding script
- also add tinyllama fast model loading for related integ code
> add Lora config to arg list in Neo sharding script& its integ test change

- serving/docker/lmi.Dockerfile
Update lmi nightly wheel now that it has updated the build with vllm (custom wheel) and pytorch (2.5.1) deps
> [docker][lmi] update back to lmi nightly wheel

- serving/docker/partition/sm_neo_shard.py
> neo shard script: remove  `del engine` as engine doesn't exist any more

- engines/python/setup/djl_python/outputs.py
- serving/docs/lmi/user_guides/lmi_input_output_schema.md
The python output default error message is "prediction failure".
But the python handler was also used for register model, I got the following error message when failing to register model in MME case, which could be confusing for customers. So changing to "invoke handler failure". Please also suggest better message if you have one.
```
{
"code": 500,
"type": "EngineException",
"message": "Failed to initialize model: prediction failure"
}
```
> [python] Update output default error message

- serving/docker/lmi.Dockerfile
hosting has a strict cuda version check on the label, it needs to 12.2 to use the proper driver. this was fixed in 0.30.0, but seems like we missed it on the main branch
> [sm][docker] use the correct verified cuda version in docker file

- engines/python/setup/djl_python/tests/neuron_test_scripts/test_neuron_tnx_rolling_batch.py
EDIT: Even tiny models have higher context length. So, we trained model and tokenizer to have smaller context length 4k on runtime. I trained the model offline and uploaded it to s3. So the previous fix is not needed. 
---
This should fix the tnx unit tests in integration tests failures. This is due to transformers getting upgraded to 4.45.2. This does not affect our handlers. This only affects, `train_new_from_iterator` in transformers. 
Raised PR in transformers to fix it. https://github.com/huggingface/transformers/pull/34661
> [test] fix transformers neuronx integration test failure

- serving/docker/pytorch-inf2.Dockerfile
https://github.com/deepjavalibrary/djl-serving/pull/2518 - Replacing nightly with vllm 0.6.2
> [0.30.0-dlc] upgrade neuron vllm to 0.6.2

- serving/docker/pytorch-inf2.Dockerfile
> [docker] update neuron artifacts to 2.20.1 (#2577)

- engines/python/setup/djl_python/input_parser.py
- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
Two changes in this PR:
1. Add stricter validation on the input schema for default payload format (validating that inputs is of type str
If you passed in a list or dict to `inputs` before, you would get something like this in the logs:
```
INFO  PyProcess W-161-926d3f85ed178e0-stdout: [1,0]<stdout>:INFO::[RequestId=6b6324e5-588b-469f-a10b-64db2f221273] parsed and scheduled for inference
INFO  PyProcess W-161-926d3f85ed178e0-stdout: [1,0]<stdout>:ERROR::Rolling batch inference error. There are 1 requests impacted. Dumping the impacted requestIds
INFO  PyProcess W-161-926d3f85ed178e0-stdout: [1,0]<stdout>:Traceback (most recent call last):
INFO  PyProcess W-161-926d3f85ed178e0-stdout: [1,0]<stdout>:  File "/tmp/.djl.ai/python/0.31.0-SNAPSHOT/djl_python/rolling_batch/rolling_batch.py", line …
```
> [lmi] validate inputs field is of type string for request

- engines/python/setup/djl_python/input_parser.py
- serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
> [cherry-pick][lmi] validate inputs field is of type string for request (#2583)

- serving/docker/lmi.Dockerfile
- serving/docker/requirements-lmi.txt
- serving/docker/scripts/install_djl_serving.sh
This refactors the the lmi.Dockerfile primarily to order the layers in such a way that the more "static" layers are up towards the beginning, and the more "dynamic" layers are towards the bottom. After a release, the most likely components of the container to change are:
- DJL Serving
- OS patches
previously, these were done before any of the python installs, meaning that if we patched/updated a container with a new djl_serving deb, everything from that point on would need to be rebuilt. Moving the djl and os patching towards the bottom should allow for all of the previous layers to be mostly static (caching/build/pull implications).
Additionally, I have refactored the python dependency installation into a requirements file. The requirements file is easier to parse in my opinion (version …
> Refactor LMI dockerfile

- engines/python/setup/djl_python/input_parser.py
> [0.31.0-dlc] Log adapter name in inference

- engines/python/setup/djl_python/input_parser.py
- engines/python/setup/djl_python/properties_manager/properties.py
Parse adapters from input based on enable_lora config, not based on checking adapter_registry is empty or not. Because adapter_registry might be empty if user has not registered any adapters.
> [0.31.0-dlc] Parse adapters iff enable_lora is true

- wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
- wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
Improve logging for exec shell command
> [serving] Improve logging for exec shell command

- .github/workflows/sagemaker_llm_benchmark.yml
- tests/integration/benchmark/ir-llm/config/lmi-dist/config.yml
- tests/integration/benchmark/ir-llm/config/trtllm/config.yml
This PR includes:
- extend workflow and aws client session timeout
- add one runner to parallel lmi-dist and trtllm benchmark
- fix typos
Test:
- https://github.com/deepjavalibrary/djl-serving/actions/runs/12001588530
- Cloudwatch dashboards
1. SM_LLM_benchmark_LMI_Llama-405b-fp8-series 
2. SM_LLM_benchmark_LMI_Llama-70b-series
3. SM_LLM_benchmark_LMI_Llama-8b-series
4. SM_LLM_benchmark_TRTLLM_Llama-405b-fp8-series
5. SM_LLM_benchmark_TRTLLM_Llama-70b-series
6. SM_LLM_benchmark_TRTLLM_Llama-8b-series
> Fixed sagemaker_llm_benchmark workflow configuration

- engines/python/setup/djl_python/neuron_utils/neuron_smart_default_utils.py
- tests/integration/llm/client.py
This PR aims to fixes the Neo failures for this model configuration. https://github.com/deepjavalibrary/djl-serving/blob/255408edc13d1a01903b6206bcabeca04291312a/tests/integration/llm/prepare.py#L1345 
- During partition, since no rolling_batch option is specified, the default setting of disable is used, and the model is compiled accordingly.
- During inference, Java side, has LMI smart default capability, which assigns the rolling batch option to auto.
Since compiled configuration is different from inference configuration, the hash values of the neff files are different, hence it fails.
- In this PR, we are setting rolling batch as auto in smart defaults, so when partitioning, the default becomes `auto` for `option.rolling_batch`
- We recently added validations that input should be …
> [python] add rolling batch as auto for neuron smart default

- engines/python/setup/djl_python/properties_manager/properties.py
- engines/python/setup/djl_python/tests/test_properties_manager.py
In Java side, Smart defaults, always sets rolling batch as auto when user does not provide one. We would want to do the same defaults in python side. This would unify the UX configurations for partition/neo use cases as well.
> [python] making rolling batch default as auto

- engines/python/setup/djl_python/input_parser.py
Neuronx unit tests cases are failing because of this. `enable_lora` is only available in lmi_dist and vllm as of now. Lora is not supported in neuron yet.
> [python][fix] check whether config has enable_lora attribute

- serving/docker/partition/sm_neo_shard.py
Change the default value of `enforce_eager` to false during Fast Model Loader AOT sharding, to [match LMI-Dist's runtime default](https://github.com/deepjavalibrary/djl-serving/blob/6a29680b1267939cdcb05049293a161967c213ce/engines/python/setup/djl_python/properties_manager/lmi_dist_rb_properties.py#L37). This will help GPU memory usage parity between AOT and runtime.
> [neo] Correct enforce_eager default for LMI sharding

- serving/docker/lmi.Dockerfile
- serving/docker/requirements-lmi.txt
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/tests.py
> [serving] Updates onnxruntime to 1.20.0 and add integration tests

- serving/docs/lmi/user_guides/output_formatter_schema.md
> [doc] modify the code for output formatter schema

- serving/docker/deepspeed.Dockerfile
- serving/docker/pytorch-inf2.Dockerfile
- serving/docker/tensorrt-llm.Dockerfile
Test failure run is here https://github.com/deepjavalibrary/djl-serving/actions/runs/12247196620/job/34164824528.
I validated stable diffusion works with this change:
```
python llm/prepare.py stable-diffusion stable-diffusion-2-1-base
./launch_container.sh deepjavalibrary/djl-serving:deepspeed ./models/ deepspeed
+ false
+ [[ deepjavalibrary/djl-serving:deepspeed …
```
> [docker] pin huggingface-hub to 0.25.1

- engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
There was a missing return in the utility method that formats the request for vllm/lmi-dist.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] Have you [manually built the docker image](https://github.com/deepjavalibrary/djl-serving/blob/master/serving/docker/README.md#build-docker-image) and verify the change?
- [x ] Have you run related tests? Check [how to set up the test environment here](https://github.com/deepjavalibrary/djl-serving/blob/master/.github/workflows/integration_execute.yml#L72); One example would be `pytest tests.py -k "TestCorrectnessLmiDist"  -m "lmi_dist"`
Please describe the Unit or Integration tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be …
> [fix] return prompt from get_prompt_inputs utility method

- engines/python/setup/djl_python/seq_scheduler/lm_block.py
- engines/python/setup/setup.py
While working on https://github.com/deepjavalibrary/djl-serving/pull/2639, I noticed an issue with upgrading the transformers version for unit tests:
```
======================================================================
ERROR: test_contrastive_scheduler (djl_python.tests.test_scheduler_bloom.TestSchedulerBloom.test_contrastive_scheduler)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/runner/work/djl-serving/djl-serving/engines/python/setup/djl_python/tests/test_scheduler_bloom.py", line 80, in test_contrastive_scheduler
scheduler.add_request(input_ids_0, request_ids)
File "/home/runner/work/djl-serving/djl-serving/engines/python/setup/djl_python/seq_scheduler/seq_batch_scheduler.py", line 116, in add_request …
```
> [fix] fix issue with BloomBlock due to transformers upgrade

- .github/workflows/docker_publish.yml
- .github/workflows/nightly.yml
add new github workflow for the new nightly workflow so we can start testing runs .
in order for developer to start a new run, github requires yml files to be in the mainline 
> add new github workflow files for the new nightly workflow

- .github/workflows/docker-nightly-publish.yml
This change migrates the docker build process for all containers to self-hosted runners. We have been seeing issues with github-hosted runners and docker push failures. There is not much to go off of for those failures https://github.com/deepjavalibrary/djl-serving/actions/runs/12393618923/job/34595251621. It just says `denied: ` with no reason/explanation.
For whatever reason, this does not occur on self-hosted runners. So to unblock ourselves for the time being, we'll use those. 
Example run with these changes: https://github.com/deepjavalibrary/djl-serving/actions/runs/12400236498
Please …
> do not fail-fast for docker publish

- .github/workflows/docker-nightly-publish.yml
* Enable selections in docker image build by using arch as input arg
* refactor the code to use matrix 
- If this change is a backward incompatible change, why must this change be made?  N/A
a run with building all images: https://github.com/deepjavalibrary/djl-serving/actions/runs/12423622213
a run with some images: [12423485871](https://github.com/deepjavalibrary/djl-serving/actions/runs/12423485871)
> Enable selections in docker image build workflow

- .github/workflows/docker_publish.yml
- .github/workflows/integration.yml
- .github/workflows/nightly.yml
- serving/docker/scripts/push_image_from_ECR.sh
The current nightly pipeline only publishes updated nightly images if all integration tests pass. This change enables publishing of nightly containers when the relevant tests succeed, rather than requiring all tests across all containers.
Test Case 1: Forcing all tests to succeed will result in all images being published:
https://github.com/deepjavalibrary/djl-serving/actions/runs/12658537776
Test Case 2: Forcing all tests to fail will result in no images being published: …
> enable nightly publishes per container based on test suite results

- serving/docker/scripts/push_image_from_ECR.sh
The image retagging doesn't occur because of an echo. Removing it.
> fix ecr push script to tag image after pull and before push

- serving/docker/pytorch-inf2.Dockerfile
- serving/docker/scripts/install_inferentia2.sh
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html#trn1-packages
- Bumps the neuron container to 2.21 SDK. 
- Updating Optimum neuronx tp 0.27 (latest)
- Installing NXDI, Optimum-Neuron and TnX with no **dependencies**. The main reason is, NXDI and TnX is dependent on transfromers version 4.45.2 but Optimum-neuron's latest version is dependent on 4.43. Since last version, we have been using updated version of 4.45 but we have not faced any problems with optimum. Soon, we might be deprecating optimum-neuronx since, neuron-vllm is expanding it's model coverage.
Docker version update
Manually built the docker container https://github.com/deepjavalibrary/djl-serving/actions/runs/12679289973
> [docker] bump neuron sdk to 2.21

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- serving/docs/lmi/user_guides/lmi_input_output_schema.md
This change removes the need for `do_sample` to be set explicitly for sampling to occur. Previously, sampling parameters would be ignored unless do_sample was set to true. While that behavior did follow the transformers behavior, it is no longer what users expect.
We will still respect do_sample: false as a greedy sampling indicator.
I also removed the .keys() from this method as it's unnecessary. 
> [lmi][vllm] do not require do_sample to enable sampling

- .github/workflows/docker_publish.yml
- .github/workflows/integration.yml
This fixes an issue with the nightly pipeline. Two workflows are currently failing due to not finding awscli in apt. This changes the installation of awscli from apt to python via pip.
I'll scan the other workflows and make the same change as necessary - getting this one out now to restore failures in container CI.
> [fix][ci] install awscli via pip due to issues with using apt

- engines/python/setup/djl_python/input_parser.py
This change imports the vllm chat processing only when required. This will fix the trtllm integ tests failures.
Sample failure https://github.com/deepjavalibrary/djl-serving/actions/runs/12950279922/job/36124428030
```
[INFO ] 2025-01-24 15:45:48 PyProcess - W-10627-test-stdout: [1,3]<stdout>:Traceback (most recent call last):
[INFO ] 2025-01-24 15:45:48 PyProcess - W-10627-test-stdout: [1,3]<stdout>:  File "/tmp/.djl.ai/python/0.32.0-SNAPSHOT/djl_python_engine.py", line 204, in main
[INFO ] 2025-01-24 15:45:48 PyProcess - W-10627-test-stdout: [1,3]<stdout>:    model_service = load_model_service(args.model_dir, entry_point,
[INFO ] 2025-01-24 15:45:48 PyProcess - W-10627-test-stdout: [1,3]<stdout>:  File "/tmp/.djl.ai/python/0.32.0-SNAPSHOT/djl_python/service_loader.py", line 48, in …
```
> [fix][trtllm] only import vllm chat processing when required

- engines/python/setup/djl_python/properties_manager/tnx_properties.py
- engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
- engines/python/setup/djl_python/transformers_neuronx.py
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/tests.py
> [python] Support NxDI with Vllm

- awscurl/build.gradle.kts
- This fixes the `serving.publish` CI failures. https://github.com/deepjavalibrary/djl-serving/actions/workflows/serving-publish.yml. 
- We recently changed awscurl executable build to be async. i.e we changed from exec to providers.exec. Here `result.get()`, we are forcing the execution and retrieving the result of the shell command.
CI after this PR: https://github.com/deepjavalibrary/djl-serving/actions/workflows/serving-publish.yml
> [ci] enforce execution of awscurl executable file

- serving/docker/partition/partition.py
- serving/docker/partition/properties_manager.py
- serving/docker/partition/utils.py
> [python] remove deepspeed related AOT code

- engines/python/setup/djl_python/transformers_neuronx.py
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/tests.py
> [python] add aot config for nxdi with vllm

- serving/docker/partition/properties_manager.py
> [python] remove unused get_engine_configs

- .gitignore
- benchmark/build.gradle.kts
- buildSrc/src/main/kotlin/ai/djl/pythonFormatter.gradle.kts
- buildSrc/src/main/kotlin/ai/djl/shellFormatter.gradle.kts
- serving/build.gradle.kts
> [ci] Fixes gradle 8.12 warnings

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- engines/python/setup/djl_python/tests/test_rb_vllm_utils.py
> [python] Update rolling batch params to output delta

- engines/python/setup/djl_python/chat_completions/vllm_chat_utils.py
- engines/python/setup/djl_python/input_parser.py
- engines/python/setup/djl_python/output_formatter.py
- engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
- engines/python/setup/djl_python/request_io.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- engines/python/setup/djl_python/tests/test_rolling_batch.py
- engines/python/setup/setup.py
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/tests.py
> [python] Add tool calling support

- engines/python/setup/djl_python/transformers_neuronx.py
In vllm, for JIT, they store the compiled artifacts in the model directory. Sometimes user's model directory could be readonly. So, this PR changes the user's model directory to /tmp/.djl.ai/neuron-compiled-artifacts
> [python] move the default compile path to /tmp/.djl.ai

- engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
Neuron vllm is still using 0.6.2, so ToolParse imports are failing for neuron test cases. So this PR, moves these to local imports to avoid problems for Neuron containers. 
> [python] move toolparsermanager to local imports

- serving/docker/partition/sm_neo_dispatcher.py
- serving/docker/partition/sm_neo_shard.py
Update the Neo dispatcher to account for different Python executables / venvs required by subprocesses, in accordance with #2690
> Support different Python executables in Neo dispatcher

- tests/integration/tests.py
> [ci] convert nxdi tests to aot compiled

- serving/docker/lmi-container-requirements-common.txt
- serving/docker/partition/partition.py
- serving/docker/partition/sm_neo_quantize.py
Migrates existing FP8 quantization functionality to llmcompressor from AutoFP8. The existing quantization recipe is fp8 weights and activation quantization, with static activation scales. Uses cnn-dailymail for calibration, defaulting to 512 samples at 2048 seq len.
Installed the previous version of llm-compressor (0.3.1) due to an issue with compatibility between llm-compressor (0.4.0) and transformers 2.5.2, which is the current version in djl-serving.
- Update CI tests in lmi-distro to verify these changes.
- Remove AutoFP8 dependency from container.
- Future feature support (prioritization tbd)
- MoE model quantization. (May run with exiting code, but will not ignore the correct layers)
- KV cache quantization with static scales.
- Calibration dataset selection
- AWQ migration (not …
> AutoFP8 to llmcompressor migration for FP8 quantization

- engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
vLLM in EngineArgs, sets max_model_len as block_size if device is neuron. We dont need another check in our side. 
> [python] offload setting block size to neuron

- engines/python/setup/djl_python/chat_completions/vllm_chat_utils.py
- engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
- serving/docker/lmi-container-requirements-common.txt
- serving/docker/requirements-lmi.txt
- serving/docker/requirements-vllm.txt
- serving/docker/scripts/create_virtual_env.sh
- tests/integration/llm/client.py
- tests/integration/tests.py
This changes updates to vllm 0.7.1, which involves shuffling around some dependencies and being less strict with dependency versions. 
Additionally, it updates the chat processing for vllm to be functional. There is still a good amount we need to implement for chat processing, that i'll take up in a follow up PR:
- use the sampling params provided directly from the vllm chat object (to_sampling_params method). this will ensure we use the correct sampling params for chat
- validate function calling and tool usage with this update
- allow user to specify override chat template, and chat format
I have tested this with (single test for each):
- HF non rolling batch
- HF scheduler rolling batch
- vLLM rolling batch
- lmi-dist rolling batch
I also added a chat test for mistral with vllm.
Please …
> fix lmi/vllm virtual envs, update to vllm 0.7.1

- engines/python/setup/djl_python/neuron_utils/model_loader.py
- engines/python/setup/djl_python/transformers_neuronx.py
- tests/integration/tests.py
- Moving nxdi logic to a separate model loader. Initially I wanted to avoid introducing another model loader, but the default model loader is TNX Model loader. It does not cause any errors now, but there are some code and initialization done, that are not necessary. Keeping the execution clean would be better for the long run. 
- Removed vllm 8B test. Running AOT with 8B is stuck for some reason, but JIT compilation works. Still figuring out. Will add it back once I am able to figure it out. 
> [python] move nxdi logic to model loader

- serving/docker/partition/sm_neo_dispatcher.py
- serving/docker/requirements-vllm.txt
Use the vllm python venv for llm-compressor quantization. The vllm venv is compatible with llm-compressor 0.4.0 because it has transformers==4.48.2. 0.4.0 was auto installed in vllm venv. I made this version explicit to avoid confusion.
The lmi-dist venv does not work because it has llm-compressor==0.3.0 installed, and quantization fails with this version. Attempting to upgrade to 0.3.1 fails due to a dependency conflict between llm-compressor==0.3.1 and vllm==0.6.3.post1 (lmi-dist).
I also performed further local validation of the container with **llama-3.1-8b**. Quantized and served with the following serving.properties:
Case 1:
```
option.rolling_batch=lmi-dist
option.quantize=fp8
```
- Note that we still input `option.quantize=fp8`, but the output serving.properties will be …
> Use VLLM python venv for quantization + make llm compressor version explicit in vllm venv

- engines/python/setup/djl_python/chat_completions/vllm_chat_utils.py
- engines/python/setup/djl_python/output_formatter.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
> [tool] Fix tool calling output format

- engines/python/setup/djl_python/output_formatter.py
> [tool] Fix tool calling output formatter

- engines/python/setup/djl_python/chat_completions/vllm_chat_utils.py
- engines/python/setup/djl_python/output_formatter.py
- engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/tests.py
> [python] Support reasoning content

- serving/docker/partition/partition.py
- serving/docker/partition/sm_neo_dispatcher.py
- tests/integration/llm/prepare.py
Various fixes for neo fp8 CI:
- Update llm/prepare.py to properly pass in option for FP8 quantization.
- Do tokenization from FP8 on our side, like we were doing before with AutoFP8. Delegating this to llmcompressor leads to unneeded tokenization that **leads to timeout in CI**.
- Use lmi-dist-venv to run awq quantization, due to hf transformers version incompatibility.
- Repeated local tests with Llama-3.1-8b as in #2701
> Neo Quantization Fixes

- .github/workflows/integration.yml
The reason for correctness test failure for neuron is, awscurl requires java and java is not installed in Deep Learning AMI Neuron. 
So installing java, if it is not installed only if neuron devices exists. For GPU instances, nothing should happen. We are suppressing output and errors. 
> [ci] install java for neuron conatiners

- engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
This PR removes the generation_config parameter from vllm properties. This is an engine argument and can be leveraged via pass-through. 
I validated this for GPU - when specifying OPTION_GENERATION_CONFIG=auto , vllm will pick up generation_config.json if present.
I added some logging to test:
Without sampling params in the payload:
```
INFO  PyProcess W-3507-08a20b291e447c9-stdout: INFO::default sampling params are default_sampling_params={'temperature': 0.36, 'top_p': 0.9}
INFO  PyProcess W-3507-08a20b291e447c9-stdout: INFO::using sampling params sampling_params=SamplingParams(n=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.36, top_p=0.9, top_k=-1, min_p=0.0, seed=None, stop=[], stop_token_ids=[], bad_words=[], include_stop_str_in_output=False, …
```
> [vllm] leverage passthrough for generation_config engine argument

- serving/docker/requirements-vllm.txt
Installs the wheel for flashinfer 0.2.0.post2 - vllm 0.7.1 uses post1, but there is not official torch 2.5 wheel for that version. I have tested 0.2.0.post2 locally with Llama and it functions well.
Before this, my test with Llama and FlashInfer backend failed completely. 
> [vllm] add flashinfer wheel for 0.2.0.post2

- serving/docker/pytorch-inf2.Dockerfile
- serving/docker/scripts/install_inferentia2.sh
Upgrade neuron to 2.21.1. 
Container build is successful https://github.com/deepjavalibrary/djl-serving/actions/runs/13293442868
> [docker] Bump up neuron to 2.21.1

- serving/docker/lmi.Dockerfile
- serving/docker/scripts/patch_libpmix2.sh
- serving/docker/tensorrt-llm.Dockerfile
Addresses https://ubuntu.com/security/CVE-2023-41915 in affected images. Will need to subsequently cherry-pick to release branches.
> [docker] Add CVE patch for libpmix2 in affected images

- serving/docker/lmi.Dockerfile
- serving/docker/scripts/patch_libpmix2.sh
- serving/docker/tensorrt-llm.Dockerfile
Addresses https://ubuntu.com/security/CVE-2023-41915 in affected images.
> [0.32.0-dlc][docker] Add CVE patch for libpmix2 in affected images (#2750)

- serving/docker/requirements-vllm.txt
Install ninja to fix the error below when running name tool calling.
```
INFO  PyProcess W-194-8d7f663aaab4e5d-stdout: Traceback (most recent call last):
INFO  PyProcess W-194-8d7f663aaab4e5d-stdout:   File "/tmp/.djl.ai/python/0.33.0-SNAPSHOT/djl_python/rolling_batch/rolling_batch.py", line 47, in try_catch_handling
INFO  PyProcess W-194-8d7f663aaab4e5d-stdout:     return func(self, *args, **kwargs)
INFO  PyProcess W-194-8d7f663aaab4e5d-stdout:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
INFO  PyProcess W-194-8d7f663aaab4e5d-stdout:   File "/tmp/.djl.ai/python/0.33.0-SNAPSHOT/djl_python/rolling_batch/vllm_rolling_batch.py", line 185, in inference
INFO  PyProcess W-194-8d7f663aaab4e5d-stdout:     self.engine.add_request(request_id=request_id,
INFO …
```
> [docker] Install ninja in lmi container

- engines/python/setup/djl_python/python_async_engine.py
- serving/docker/lmi-container-requirements-common.txt
Use uvloop instead of asyncio for the event loop. I've tested this locally and uvloop can get significantly faster than asyncio when streaming responses for many concurrent requests. In my local testing, it's never slower than asyncio.
> [python] use uvloop instead of asyncio for event loop

- engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
- engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py
- engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/tests.py
Fixes a hang caused by requests that are longer than `max_model_len` in vLLM and lmi-dist handlers. The main fix is here:
https://github.com/a-ys/djl-serving-1/blob/4a8e75869ead48f79c279edc3078d796c0afa163/engines/python/setup/djl_python/rolling_batch/rolling_batch_vllm_utils.py#L57-L58
**Cause**:
vLLM sends a response with the ignored sequence on too long request. Without this check, djl-serving doesn't process the response, waiting for prefill to complete. However, the vLLM engine has already ignored and removed the request from the queue, leaving djl-serving to wait forever for the prefill that won't come.
In addition, we add a check to try throw an error in this case, rather than returning an empty string to the client: https://github.com/a-ys/djl-serving-1/blob/4a8e75869ead48f79c279ed …
> Fix too long requests hang in vLLM & lmi-dist

- benchmark/src/main/resources/log4j2.xml
- prometheus/src/test/resources/log4j2.xml
- serving/src/main/conf/log4j2-access.xml
- serving/src/main/conf/log4j2-console.xml
- serving/src/main/conf/log4j2-plain.xml
- serving/src/main/conf/log4j2.xml
- serving/src/main/resources/log4j2.xml
`status` in log4j configuration file is deprecated https://logging.apache.org/log4j/2.x/manual/configuration.html#configuration-attribute-status. 
> remove status from log4j configuration of status logger

- .github/workflows/integration.yml
Integration tests have been failing for the CPU test suites - github is not able to select the proper instance for ubuntu-latest. We have made any changes to the workflows that could cause these failures, so I believe something has changed on the github side that is due to specifying the same label same times in the runs-on criteria.
For now, the easiest option is to move to self-hosted cpu runners. The syntax to implement conditional, variable length criteria for runs-on is tough to get right and parse, and is quite error prone.
Please also list any relevant details for your test …
> [ci] use self-hosted cpu instances in integ tests

- serving/docker/requirements-vllm.txt
xgrammar is a supported backend for guided decoding, but does not get installed when vllm is installed. Some models use xgrammar as the backend for guided decoding, but those models/requests fail at the moment. Installing xgrammar fixes those issues.
> [vllm] install xgrammar to support structured outputs for some models

- wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
> [lmi] add logging when unable to fetch huggingface config for model

- engines/python/setup/djl_python/lmi_vllm/request_response_utils.py
- engines/python/setup/djl_python/lmi_vllm/vllm_async_service.py
The previous logic for converting token text to ids was incorrect for the tgi style schema. This changes fixes those issues by forcing the completion request to return token ids. For non-streaming requests, we do have to convert each token id to the token text because that information is not provided in the response. For streaming, no tokenization is required.
> [vllm] fix handling of token ids for TGI style responses

- engines/python/setup/djl_python/properties_manager/vllm_rb_properties.py
- Bug fix (non-breaking change which fixes an issue)
- Nightly pipeline: https://github.com/deepjavalibrary/djl-serving/actions/runs/14890506033
The full set of integration tests are run. The tests passed except for the Neuron ones.
> [vllm] Update vllm_rb_properties.py to accommodate vllm-0.8.5 changes

- tests/integration/llm/prepare.py
- tests/integration/tests.py
This fixes some issues in the TestGPU test suite. Couple of issues:
- TestGPU matches with TestGPUHandlerPerformance suite, which incorrectly gets included as the release criteria for the GPU base container. I removed that test suite and moved the actual tests to more relevant suites (vllm and trtllm)
- The handler performance tests were still running with the rolling batch mode, and due to some changes in https://github.com/deepjavalibrary/djl-serving/commit/f4ce3b6a05a7aec22767237645248b21c2336457 that results in both async and rolling batch mode being enabled. For now, I updated the tests here to use async mode (based on the defaults set in the previously mentioned PR). There still needs to be some work to fix the RB/Async flows, and the ideal state should be completely removing …
> [tests][lmi] use async mode for performance tests

- tests/integration/llm/prepare.py
- tests/integration/tests.py
Add vllm_async_handler as entrypoint to VLLM async integration tests
> [fix] Add vllm_async_handler as entrypoint to VLLM async integration tests

- buildSrc/src/main/kotlin/ai/djl/javaBase.gradle.kts
- engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
- engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
- tests/integration/tests.py
- Add additional flag for server to detect if worker has gone down unexpectedly, e.g. segmentation fault from the underlying engine, and trigger process restart accordingly
- Tested behavior by sending SIGSEGV to `mpirun` process to simulate crash, verifying successful restart upon subsequent requests
> [fix] Add handling for abrupt process termination (#2857)

- .github/workflows/integration.yml
- engines/python/setup/djl_python/async_utils.py
- engines/python/setup/djl_python/lmi_vllm/vllm_async_service.py
- engines/python/setup/djl_python/session_manager.py
- engines/python/setup/djl_python/session_utils.py
- engines/python/src/test/java/ai/djl/python/engine/PySessionsTests.java
- serving/docs/stateful_sessions.md
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/tests.py
- wlm/src/main/java/ai/djl/serving/wlm/LmiConfigRecommender.java
This PR add support for session based sticky routing, all requests from the same session are routed to the same instance.
- API implemented following https://docs.aws.amazon.com/sagemaker/latest/dg/stateful-sessions.html
- Add `option.enable_stateful_sessions` (default to true).
- Set maxWorkers=1 if stateful sessions enabled, this is to avoid multiple workers creating different session_id and causing session_id mismatch during inference.
- Added integration test
- Updated unit test `PySessionsTests.java`
- Added documentation `stateful_sessions.md`
- Added sample notebook https://github.com/deepjavalibrary/djl-demo/pull/573
Please describe the Unit or Integration tests that you ran to verify your …
> [0.34.0-dlc][python] Support session based sticky routing in async mode

- .github/workflows/integration.yml
- engines/python/setup/djl_python/async_utils.py
- engines/python/setup/djl_python/huggingface.py
- engines/python/setup/djl_python/input_parser.py
- engines/python/setup/djl_python/lmi_vllm/request_response_utils.py
- engines/python/setup/djl_python/lmi_vllm/vllm_async_service.py
- engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
- tests/integration/llm/client.py
- tests/integration/llm/prepare.py
- tests/integration/tests.py
- Add support for adapters (LoRA) management in async-mode vLLM handler, adapted from existing `huggingface.py` handler
- Add integration tests for async vLLM LoRA
- Temporarily disable irrelevant integration tests to save time/compute and prevent blocking vLLM image release
- Improve robustness of error handling in test client
> [python] Support adapters in async vLLM handler
