deepjavalibrary/djl-serving

engines/python/src/main/java/ai/djl/python/engine/Connection.java
engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
engines/python/src/main/resources/ai/djl/python/scripts/djl_python_engine.py
engines/python/src/main/resources/ai/djl/python/scripts/inputs.py
engines/python/src/main/resources/ai/djl/python/scripts/outputs.py
engines/python/src/main/resources/ai/djl/python/scripts/pair_list.py
engines/python/src/test/resources/accumulate/model.py
serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/src/main/java/ai/djl/serving/http/RequestParser.java
serving/src/main/java/ai/djl/serving/models/ModelManager.java
serving/src/main/java/ai/djl/serving/util/NettyUtils.java
wlm/src/main/java/ai/djl/serving/wlm/BatchAggregator.java
wlm/src/main/java/ai/djl/serving/wlm/Job.java
wlm/src/main/java/ai/djl/serving/wlm/PermanentBatchAggregator.java

Update for input/output api change

---

engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
engines/python/src/main/java/ai/djl/python/engine/PyModel.java

[python] Allow set python executable path

---

engines/python/src/test/resources/resnet18/model.py

[python] Fix resnet18 model GPU bug

---

serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
serving/src/main/java/ai/djl/serving/models/ModelManager.java
wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
wlm/src/main/java/ai/djl/serving/wlm/util/WlmConfigManager.java

[serving] Add autoscale for inferentia

---

engines/python/setup/djl_python/arg_parser.py
engines/python/setup/djl_python/service_loader.py
engines/python/setup/djl_python/test_model.py
engines/python/setup/djl_python/ts_service_loader.py
engines/python/setup/djl_python_engine.py
engines/python/src/main/java/ai/djl/python/engine/Connection.java
engines/python/src/main/java/ai/djl/python/engine/PyModel.java
engines/python/src/test/resources/resnet18/model.py
serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java

[python] Add support to load torchserve model

---

engines/python/src/main/java/ai/djl/python/engine/PyModel.java
engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/util/NeuronUtils.java
serving/src/test/java/ai/djl/serving/NeuronUtilsTest.java

[serving] auto detect number of neuron cores

---

serving/docker/Dockerfile
serving/docker/README.md
serving/docker/inf1.Dockerfile

Add dockerfile for inferentia

---

engines/python/src/main/java/ai/djl/python/engine/PyModel.java

[python] support nested folder in model archive file

---

.github/CODEOWNERS

Add initial codeowners

---

README.md

Upgrade DJL version from 0.13.0 to 0.14.0

---

engines/python/build.gradle
gradle.properties
serving/build.gradle

[serving] Reduces netty dependencies

---

.github/workflows/codeql-analysis-java.yml

[ci] workaround codeql build issue

---

engines/python/build.gradle
engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
gradle.properties

Upgrade to djl 0.15.0

---

serving/build.gradle
serving/src/main/java/ai/djl/serving/models/ModelManager.java
serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java
serving/src/main/java/ai/djl/serving/util/MutableClassLoader.java
serving/src/test/java/ai/djl/serving/plugins/DependencyManagerTest.java
serving/src/test/java/ai/djl/serving/plugins/package-info.java

[serving] Install engine dependency ondemand

---

serving/src/main/java/ai/djl/serving/util/ConfigManager.java
wlm/src/main/java/ai/djl/serving/wlm/util/WlmConfigManager.java

[serving] Refactor debug flag

---

.github/CODEOWNERS

Add djl-admin as codeowners

---

central/package-lock.json

Update nodejs package version

---

engines/python/build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Upgrade netty to 4.1.72.Final

---

serving/src/main/java/ai/djl/serving/ModelServer.java

Load all model by default when model store is specified

---

serving/build.gradle
serving/src/main/java/ai/djl/serving/workflow/BadWorkflowException.java
serving/src/main/java/ai/djl/serving/workflow/Workflow.java
serving/src/main/java/ai/djl/serving/workflow/WorkflowDefinition.java
serving/src/main/java/ai/djl/serving/workflow/WorkflowExecutionException.java
serving/src/main/java/ai/djl/serving/workflow/WorkflowExpression.java
serving/src/main/java/ai/djl/serving/workflow/function/IdentityWF.java
serving/src/main/java/ai/djl/serving/workflow/function/ModelWorkflowFunction.java
serving/src/main/java/ai/djl/serving/workflow/function/WorkflowFunction.java
serving/src/main/java/ai/djl/serving/workflow/function/package-info.java
serving/src/test/java/ai/djl/serving/WorkflowTest.java
serving/src/test/java/ai/djl/serving/workflow/function/OtherIdentityWF.java
serving/src/test/java/ai/djl/serving/workflow/function/package-info.java
serving/src/test/resources/workflows/basic.json
serving/src/test/resources/workflows/basic.yaml
serving/src/test/resources/workflows/criteria.json
serving/src/test/resources/workflows/functions.json
serving/src/test/resources/workflows/globalPerf.json
serving/src/test/resources/workflows/localPerf.json
wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java

This adds support for parsing a workflow from a json or yaml file.
In addition, it refactors the workflow to support the WorkflowFunctions. This
includes creating the executor, helping constructs, and supporting model
execution as a WorkflowFunction.
It also makes the WorkloadManager autoCloseable for easier testing.

Workflow file parsing

---

serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/models/ModelManager.java

[serving] Detect engine when load model from URL

---

engines/python/README.md

fixing broken url in python engine readme file

fixing broken url

---

engines/python/src/main/java/ai/djl/python/engine/PyNDManager.java
gradle.properties

Bump up version to 0.16.0

---

serving/src/main/java/ai/djl/serving/ModelServer.java

Throws error when model directory path is invalid.

error message when model path is invalid

---

serving/docker/inf1.Dockerfile

Update inferentia docker image to use PyTorch 1.10.0

---

README.md
serving/docker/Dockerfile
serving/docker/README.md
serving/docker/inf1.Dockerfile

Upgrade to DJL 0.16.0

---

gradle.properties
gradle/wrapper/gradle-wrapper.properties
tools/conf/pmd.xml

Update dependencies version

---

serving/src/main/java/ai/djl/serving/util/ConfigManager.java

[serving] Fixes startup NPE bug

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Removes redundant logging

---

engines/python/src/main/java/ai/djl/python/engine/Connection.java
engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
engines/python/src/main/java/ai/djl/python/engine/PyModel.java
engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
engines/python/src/test/resources/accumulate/model.py

[python] configure model loading/prediction timeout

---

gradle.properties
serving/build.gradle

[serving] Upgrade dependency version

---

serving/src/main/java/ai/djl/serving/ModelServer.java

[serving] Avoid load MXNet unnecessarily

---

engines/python/src/main/java/ai/djl/python/engine/Metric.java
engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
engines/python/src/test/resources/accumulate/model.py
engines/python/src/test/resources/echo/model.py

Add metric unit test

---

serving/src/main/java/ai/djl/serving/ModelServer.java

[serving] Install engine plugin if needed

---

README.md

[docs] Add install djl instruction for Windows

---

README.md
engines/python/README.md
serving/docker/Dockerfile
serving/docker/README.md
serving/docker/inf1.Dockerfile

[docs] Upgrade to DJL 0.17.0

---

engines/python/src/main/java/ai/djl/python/engine/PyEnv.java

[python] Improves pip installation logging

---

serving/docker/Dockerfile

[serving] Fixes log4j in docker file

---

serving/src/main/java/ai/djl/serving/Arguments.java
serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java
serving/src/test/java/ai/djl/serving/plugins/DependencyManagerTest.java

Allows user install native library to avoid network access at runtime

[serving] Add install dependency in commandline

---

gradle.properties

bump up djlserving version

---

.github/workflows/pyunit.yml
engines/python/setup/djl_python/inputs.py
engines/python/setup/djl_python/outputs.py
engines/python/setup/djl_python/test_model.py
engines/python/setup/djl_python/tests/test_input_output.py
engines/python/setup/setup.py

Add python unit tests and package improvements

add python test

---

.github/workflows/client-test.yml
engines/python/setup/djl_python/outputs.py
engines/python/setup/setup.py
tests/python/model.py
tests/test_client.py

Add integration tests for DJL-Serving

add client tests

---

.github/workflows/client-test.yml
tests/binary/prepare.py
tests/test_binary.py
tests/test_client.py

Add tests for binary mode testing

add pytest for binary mode

---

wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
wlm/src/main/java/ai/djl/serving/wlm/util/WlmConfigManager.java

If model has a property "defaultGPUWorkers", then take this property's value for min and max default workers.

Adding model property check for max workers

---

engines/python/setup/djl_python/inputs.py
engines/python/setup/djl_python/tests/test_input_output.py
engines/python/setup/setup.py

[python] Reformat python code

---

gradle/wrapper/gradle-wrapper.properties
serving/build.gradle

[serving] Fix selfsign certificate issue for JDK 15+

---

.github/workflows/continuous.yml
build.gradle
serving/src/main/java/ai/djl/serving/models/ModelManager.java
serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
serving/src/test/java/ai/djl/serving/translator/TestTranslator.java
serving/src/test/java/ai/djl/serving/translator/package-info.java

Add test translator for testing plugin functionalities

add Test Translator plugin

---

serving/docker/deepspeed.Dockerfile

Add DeepSpeed docker image for large model supporting

add DeepSpeed docker image

---

.github/workflows/nightly-publish.yml

Add simple CI/CD workflow for testing purpose

add cicd publish

---

.github/workflows/nightly-publish.yml

Add two new instances for CI on GitHub Actions. Graviton and Inferentia

[Action] add two new instances

---

serving/docker/aarch64.Dockerfile
serving/docker/scripts/install_djl_serving.sh
serving/docker/scripts/install_inferentia.sh
serving/docker/scripts/install_python.sh

[Docker] create aarch64 docker

---

serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java

[serving] Fixes install dependency bug if folder not exists

---

serving/docker/aarch64.Dockerfile
serving/docker/inf1.Dockerfile
serving/docker/scripts/install_djl_serving.sh

[Docker] fix download issue

---

serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/inf1.Dockerfile

Fix deepspeed installation instruction to follow general standard

[Docker] fix deepspeed installation

---

.github/workflows/docker-nightly-build.yml
serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/docker-compose.yml
serving/docker/inf1.Dockerfile

Create CPU full package on Docker. Support multi-stage build

[Docker] Support full package installation

---

.github/workflows/docker-nightly-build.yml

Change the order for permission granting

[Docker] change the order

---

serving/docker/Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/inf1.Dockerfile
serving/docker/pytorch-cu113.Dockerfile

Clean pip cache to reduce space. Also use runtime instead of devel

[Docker] clean up pip cache

---

benchmark/src/main/java/ai/djl/benchmark/NDListGenerator.java
benchmark/src/test/java/ai/djl/benchmark/NDListGeneratorTest.java

[djl-bench] Add .npz output

---

benchmark/build.gradle
serving/docker/README.md
tests/integration/test_client.sh

[Docker][Integration] add test client script for curl

---

.github/workflows/continuous.yml

Add mac and windows to continuous.yml

---

.github/workflows/integration.yml
tests/integration/download_models.sh

add inferentia tests

---

serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java

[serving] Support nested folder in model archieve file

---

serving/docker/scripts/install_inferentia.sh

[docker] Fix install inferential docker script

---

.github/workflows/integration.yml

fix the container

---

.github/workflows/integration.yml

Add gpu and inferentia tests

---

.github/workflows/integration.yml
tests/integration/download_models.sh

Add gpu and inf1 test

---

.github/workflows/integration.yml

https://github.com/deepjavalibrary/djl/pull/1763/files - This should fix Tensorflow error.

Adding more engine tests

---

serving/docker/deepspeed.Dockerfile

Add specialized jar for deepspeed

install deepspeed specialized engine

---

engines/python/setup/djl_python/arg_parser.py
engines/python/setup/djl_python/encode_decode.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/inputs.py
engines/python/setup/djl_python/outputs.py
engines/python/setup/djl_python/service_loader.py
engines/python/setup/djl_python/test_model.py
engines/python/setup/djl_python/ts_service_loader.py
engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
engines/python/src/main/java/ai/djl/python/engine/PyModel.java
engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
engines/python/src/test/resources/echo/serving.properties
engines/python/src/test/resources/huggingface/requirements.txt
engines/python/src/test/resources/huggingface/serving.properties

[python] Support serve huggingface transformers model

---

serving/docker/deepspeed.Dockerfile
serving/docker/deepspeed.config.properties

Always load on GPU0 instead of loading on all devices

[DeepSpeed] workaround for sagemaker configs

---

.github/workflows/client-test.yml
tests/java-client/build.gradle

[tests] Use local java engine to test java client

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-cu113.Dockerfile
serving/docker/pytorch-inf1.Dockerfile

[docker] Add -XX:+UseContainerSupport option

---

serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java

[serving] Fixes insecure Xml parsing

---

.github/workflows/nightly-docker-ecr-sync.yml
serving/docker/scripts/pull_and_retag.sh

Migrate docker image to ECR repository

add docker image migration process

---

.github/workflows/nightly-docker-ecr-sync.yml

[Docker] Add AWSCLI install for the job

---

.github/workflows/nightly-docker-ecr-sync.yml

Handle empty string input in github action

[Docker] handle empty string

---

serving/build.gradle
serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/pytorch-cu113.Dockerfile
serving/docker/pytorch-inf1.Dockerfile
serving/src/main/java/ai/djl/serving/util/ConfigManager.java

[serving] Allows user override OMP_NUM_THREADS

---

engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
engines/python/src/main/java/ai/djl/python/engine/PyModel.java
serving/src/main/java/ai/djl/serving/util/ConfigManager.java

This PR is to fix https://github.com/deepjavalibrary/djl/discussions/1848
The customer run into the get environment security issue. This PR put the environment call into a utility function and catch the exception.

Catch security exception in get environment call

---

engines/java/src/main/java/ai/djl/java/engine/JavaEngine.java
serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
serving/src/test/resources/identity/serving.properties
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Respect per model minWorkers setting

---

.github/workflows/client-test.yml
.github/workflows/pyunit.yml

Remove test on push. Only allow PR testing

reduce test numbers

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-cu113.Dockerfile
serving/docker/pytorch-inf1.Dockerfile
serving/src/main/java/ai/djl/serving/util/ConfigManager.java

[serving] Disable UseContainerSupport for SageMaker

---

serving/src/main/java/ai/djl/serving/util/NettyUtils.java

[serving] print non-200 response to debug log

---

serving/src/main/java/ai/djl/serving/util/ConfigManager.java
wlm/src/main/java/ai/djl/serving/wlm/util/WlmConfigManager.java

[wlm] Fix WlmConfigManager bug

---

engines/python/README.md
serving/src/main/java/ai/djl/serving/http/ConfigurableHttpRequestHandler.java
serving/src/main/java/ai/djl/serving/plugins/FolderScanPluginManager.java
serving/src/main/java/ai/djl/serving/plugins/PluginMetaData.java
serving/src/main/java/ai/djl/serving/util/ConfigManager.java
serving/src/main/java/ai/djl/serving/workflow/Workflow.java

[serving] Update logging levels for some logs

---

.github/workflows/client-test.yml

Build a client test for windows system

add windows client test

---

serving/docker/Dockerfile

[ONNXRuntime] support 1.12.1

---

serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java

[serving] Sets per model job_queue_size when register model

---

central/src/main/java/ai/djl/serving/central/handler/RequestHandlerWrapper.java
plugins/static-file-plugin/src/main/java/ai/djl/serving/plugins/staticfile/HttpStaticClasspathResourceHandler.java
serving/src/main/java/ai/djl/serving/http/ConfigurableHttpRequestHandler.java
serving/src/main/java/ai/djl/serving/workflow/Workflow.java

[serving] Updates logging level for some logs

---

tools/gradle/check.gradle

[spotbug] add workaround for DJLServing

---

serving/docker/Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-cu113.Dockerfile
serving/docker/pytorch-inf1.Dockerfile
serving/docker/scripts/install_djl_serving.sh
serving/docker/scripts/patch_oss_dlc.sh

In compliance of all necessary licenses, we equipped the license builder created by DLC team to patch the licences after build

[Docker] add DLC license builder for packages we use

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-cu113.Dockerfile
serving/docker/pytorch-inf1.Dockerfile

[docker] Limit JVM memory usage in docker

---

.github/workflows/integration.yml
serving/docker/deepspeed.Dockerfile

[Nightly] fix deepspeed and nightly failing

---

serving/docker/deepspeed.Dockerfile

Fix docker container build failure

[docker] minor fix in dockerfile

---

gradle/wrapper/gradle-wrapper.properties
tools/gradle/check.gradle

[ci] Upgrade gradle to 7.5.1 and support JDK18

---

.github/workflows/integration.yml

dpkg lock happened a few times during the run

wait dpkg lock issue for integration tests

---

engines/python/setup/djl_python/inputs.py
engines/python/setup/djl_python/tests/test_input_output.py

Print input string, simple function

print input through string

---

build.gradle
serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java

[serving] Upgrades to minimum JDK version to 11

---

plugins/management-console/webapp/package.json

ejs dpendencies is causing critical CVE and patch with latest

[Frontend] fix CVE and add frontend test

---

serving/docker/scripts/install_inferentia.sh

required to install by inferentia team

[inf][Docker] required by inferentia team

---

.github/workflows/docker-nightly-publish.yml
serving/docker/docker-compose.yml
serving/docker/pytorch-cu113.Dockerfile
serving/docker/scripts/pull_and_retag.sh

Add support for Parallelformers on DJLServing

[Docker] add parallelformers docker image

---

serving/docker/pytorch-cu113.Dockerfile

Fix broken config and add OSS patches

[Docker] Add OSS patch to Parallelformers

---

serving/docker/scripts/pull_and_retag.sh

fix sync script

---

.github/workflows/nightly-docker-ecr-sync.yml

Cleanup docker in the system after use

[Sync ECR] clean up after run

---

serving/docker/deepspeed.Dockerfile

[Docker] update deepspeed

---

serving/src/main/conf/log4j2.xml

[serving] Adding logger name to log

---

engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
engines/python/src/main/java/ai/djl/python/engine/PyProcess.java

[python] PyPredictor should only throw TranslateException

---

serving/src/main/java/ai/djl/serving/util/NeuronUtils.java

[serving] Use IMDSV2 for NeuronUtils to detect neuron cores

---

benchmark/src/test/java/ai/djl/benchmark/BenchmarkTest.java

[benchmar] Adds missing assertion for unit test

---

engines/java/src/main/java/ai/djl/java/engine/JavaNDManager.java
engines/python/src/main/java/ai/djl/python/engine/PyNDManager.java

Fixes compile error for API changes

---

serving/src/main/java/ai/djl/serving/http/RequestParser.java

[serving] Improve input content-type handling

---

engines/python/setup/djl_python/arg_parser.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/inputs.py
engines/python/setup/djl_python/outputs.py
engines/python/setup/djl_python/pair_list.py
engines/python/setup/djl_python/service_loader.py
engines/python/setup/djl_python/tests/test_input_output.py
engines/python/setup/djl_python/ts_service_loader.py
engines/python/setup/djl_python_engine.py
engines/python/setup/setup.py
engines/python/src/main/java/ai/djl/python/engine/Connection.java
engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
engines/python/src/test/resources/accumulate/model.py
engines/python/src/test/resources/echo/model.py
engines/python/src/test/resources/resnet18/model.py

1. avoid utf-8 encode error if output key is not str
2. Fixed PyProcess restart bug
3. Improved python exception handling
4. Fixed existing python code error

[serving] Fixes python process restart failure issue

---

serving/build.gradle
serving/docker/Dockerfile

Add onnxruntime to default while building snapshot. And docker options

[Docker] workaround on integration tests

---

serving/docker/Dockerfile

[Docker] minor fix

---

serving/docker/Dockerfile

Use bash to execute if command

[Docker] fix dependencies

---

serving/.gitignore
serving/build.gradle
serving/src/main/conf/config.properties
serving/src/main/conf/log4j2.xml
serving/src/main/java/ai/djl/serving/util/ConfigManager.java

1. Update log output pattern
2. Use docker log4j2.xml in gradle run
3. Increase max request size

[serving] Updates logging configuration

---

engines/python/setup/djl_python/pair_list.py
engines/python/src/main/java/ai/djl/python/engine/Connection.java
engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
engines/python/src/test/resources/echo/model.py
serving/src/main/java/ai/djl/serving/util/NettyUtils.java

1. Allows empty string for input
2. Improve error message from exception

[python] Adds unittest for restart python process

---

plugins/management-console/webapp/vue.config.js
serving/build.gradle

[console] Add management console to distribution package

---

build.gradle
plugins/management-console/src/main/java/ai/djl/serving/console/ConsoleRequestHandler.java
serving/build.gradle
serving/docker/Dockerfile
serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java
serving/src/main/java/ai/djl/serving/util/ConfigManager.java

[serving] Support install SNAPSHOT version of engine

---

serving/src/main/java/ai/djl/serving/util/ConfigManager.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
serving/src/test/resources/identity/serving.properties
wlm/src/main/java/ai/djl/serving/wlm/WorkerPool.java

[serving] Adds per model job queue size configuration

---

serving/docker/deepspeed.Dockerfile

[deepspeed] Adds SentencePiece to DeepSpeed docker

---

serving/docker/scripts/install_djl_serving.sh

Update installation script

---

serving/docker/scripts/install_djl_serving.sh

cp with -r to copy the whole folder

fixing script error

---

README.md
benchmark/README.md
benchmark/snapcraft/snapcraft.yaml
engines/java/README.md
engines/python/README.md
serving/docker/README.md
serving/src/test/java/ai/djl/serving/plugins/DependencyManagerTest.java
wlm/README.md

Upgrade to DJL 0.19.0

---

engines/java/README.md

[docs] Update javadoc link

---

plugins/management-console/src/main/java/ai/djl/serving/console/ConsoleRequestHandler.java
plugins/management-console/webapp/src/api/configAPI.js
plugins/management-console/webapp/src/env.js
plugins/management-console/webapp/src/view/AddModel.vue
plugins/management-console/webapp/src/view/Main.vue
plugins/management-console/webapp/vue.config.js

0.19.0 Latest version before release

Adds restart feature to management console

---

serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-cu113.Dockerfile

Accelerate library is built by huggingface to allow low memory loading options on models:
```
low_cpu_mem_usage=True
```

[Docker][DeepSpeed] use accelerate to reduce memory cost

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/pytorch-cu113.Dockerfile

Bump up torch version for 0.19.0

[Docker] bump up torch version

---

serving/docker/pytorch-cu113.Dockerfile

[docker] Fix pytorch-cu113 docker file

---

.github/workflows/integration.yml
serving/docker/scripts/docker_name_builder.sh
tests/integration/download_models.sh

Support versioning for integration test and allow test on ONNX model for AARCH

[Docker] support integration test on release images

---

serving/docker/aarch64.Dockerfile

[Docker] make aarch defaults in pytorch

---

plugins/management-console/docs/console_zh.md
serving/docker/dockerd-entrypoint.sh

Submit docs and modify dockerd-entrypoint.sh to restart

Add management console document

---

.github/workflows/integration.yml

Fix the mis-added arch in the code

[Docker] fix arg in code

---

serving/docker/aarch64.Dockerfile

[aarch64] Remove unsupported engine

---

serving/docker/scripts/install_djl_serving.sh

[Docker] mkdirs for Inferentia for bug fixing

---

serving/docker/pytorch-cu113.Dockerfile
serving/docker/scripts/install_djl_serving.sh

[docker] Fixed pytorch-cu113 docker build

---

serving/docker/pytorch-cu113.Dockerfile

[Docker] change copy script location

---

serving/docker/deepspeed.Dockerfile

Support DeepSpeed and Transformers on Bloom model for DJLServing

[Docker] upgrade deepspeed and transformers

---

serving/docker/pytorch-cu113.Dockerfile

Use latest huggingface library for more models support

update huggingface version

---

serving/src/test/java/ai/djl/serving/ModelServerTest.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] clean cache directory on model unload

---

engines/python/src/main/java/ai/djl/python/engine/PyProcess.java

[python] Fixes logging issue

---

serving/docker/pytorch-cu113.Dockerfile

For supporting INT8 and other necessary CUDA libraries

[Docker] switch base image to devel

---

serving/docker/deepspeed.Dockerfile
serving/docker/scripts/security_patch.sh

Fix the security issue in the docker image

apply CVE patches into the docker

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-cu113.Dockerfile
serving/docker/pytorch-inf1.Dockerfile
serving/docker/scripts/security_patch.sh

[Docker] add label patching for DLC

---

serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java
serving/src/test/java/ai/djl/serving/plugins/DependencyManagerTest.java

[serving] Fixes install XGBoost engine bug

---

serving/src/main/java/ai/djl/serving/ModelServer.java

[serving] Improve logging message

---

engines/python/build.gradle
engines/python/setup/djl_python/arg_parser.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/service_loader.py
engines/python/setup/djl_python_engine.py
engines/python/src/main/java/ai/djl/python/engine/Connection.java
engines/python/src/main/java/ai/djl/python/engine/DsEngineProvider.java
engines/python/src/main/java/ai/djl/python/engine/DsNDManager.java
engines/python/src/main/java/ai/djl/python/engine/PyEngine.java
engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
engines/python/src/main/java/ai/djl/python/engine/PyModel.java
engines/python/src/main/java/ai/djl/python/engine/PyNDArray.java
engines/python/src/main/java/ai/djl/python/engine/PyNDManager.java
engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
engines/python/src/main/resources/META-INF/services/ai.djl.engine.EngineProvider
engines/python/src/test/java/ai/djl/python/engine/DsEngineTest.java
engines/python/src/test/resources/resnet18/model.py
serving/docker/Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/scripts/install_djl_serving.sh
serving/docker/scripts/install_inferentia.sh
serving/docker/scripts/install_python.sh
serving/docker/scripts/patch_oss_dlc.sh

[docker] Update deepspeed docker file

---

serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java

[serving] Loads model from root of model_store directory

---

engines/python/build.gradle
engines/python/setup/djl_python/arg_parser.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/service_loader.py
engines/python/setup/djl_python_engine.py
engines/python/src/main/java/ai/djl/python/engine/Connection.java
engines/python/src/main/java/ai/djl/python/engine/DsEngineProvider.java
engines/python/src/main/java/ai/djl/python/engine/DsNDManager.java
engines/python/src/main/java/ai/djl/python/engine/PyEngine.java
engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
engines/python/src/main/java/ai/djl/python/engine/PyModel.java
engines/python/src/main/java/ai/djl/python/engine/PyNDArray.java
engines/python/src/main/java/ai/djl/python/engine/PyNDManager.java
engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
engines/python/src/main/resources/META-INF/services/ai.djl.engine.EngineProvider
engines/python/src/test/java/ai/djl/python/engine/DsEngineTest.java
engines/python/src/test/resources/resnet18/model.py

- Refactor python code to support mpi mode
- [python] Adds large model inference support with MPI mode
- Add option.tensor_parallel_degree in serving.properties

[python] Adds large model inference support with MPI mode

---

engines/python/src/main/java/ai/djl/python/engine/DsEngineProvider.java
engines/python/src/main/resources/META-INF/services/ai.djl.engine.EngineProvider

[python] Remove DsEngineProvider alias

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-cu113.Dockerfile
serving/docker/pytorch-inf1.Dockerfile

Add label tagging for telemetry

[Docker] add tagging labels

---

serving/docs/configurations.md

[doc] Update DJL Serving doc

---

serving/docker/deepspeed.Dockerfile

[Docker] Fix Accelerate version

---

engines/python/src/main/java/ai/djl/python/engine/Connection.java
engines/python/src/main/java/ai/djl/python/engine/DsEngineProvider.java
engines/python/src/main/java/ai/djl/python/engine/PyEngine.java
engines/python/src/main/java/ai/djl/python/engine/PyEngineProvider.java
engines/python/src/main/java/ai/djl/python/engine/PyModel.java
serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/util/ConfigManager.java

Auto set CUDA_VISIBLE_DEVICES when user provide TENSOR_PARALLEL_DEGREE and a valid device id

start supporting multi-gpu in python mode

---

benchmark/build.gradle

[benchmark] Adds HuggingFace model zoo to djl-bench

---

serving/docs/packaging.md

[doc] Add DJL Serving packaging doc

---

benchmark/README.md

[djl-bench] Update README to upgrade Java version to 11

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-cu113.Dockerfile
serving/docker/pytorch-inf1.Dockerfile
serving/docker/scripts/install_inferentia.sh
serving/docker/scripts/install_python.sh
serving/docker/scripts/install_s5cmd.sh
serving/docker/scripts/security_patch.sh

Add S5CMD into DJLServing DLC's and also some patch update and fixes on existing offerings

[DLC] update docker with s5cmd

---

serving/docker/scripts/security_patch.sh

Fix shell script in or switching

fix shell script

---

serving/docker/scripts/install_s5cmd.sh

fix tar file unzip location

---

central/package.json

[central] workaround webpack-cli 5.0.0 build issue

---

benchmark/src/main/java/ai/djl/benchmark/AbstractBenchmark.java
benchmark/src/main/java/ai/djl/benchmark/Arguments.java
benchmark/src/main/java/ai/djl/benchmark/Benchmark.java
benchmark/src/main/java/ai/djl/benchmark/MultithreadedBenchmark.java
benchmark/src/test/java/ai/djl/benchmark/BenchmarkTest.java

[benchmark] Make warmup iteration configurable

---

benchmark/README.md

[benchmar] Update benchmark README

---

engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
engines/python/src/main/java/ai/djl/python/engine/PyModel.java

Add S3 download capabiltiy to Python engine

support download model from s3

---

README.md
serving/docs/configurations.md

[doc] Update configurations document

---

serving/build.gradle
serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-cu113.Dockerfile
serving/docker/pytorch-inf1.Dockerfile
serving/docker/scripts/install_djl_serving.sh
serving/docker/scripts/telemetry.sh

[Docker] build dlc telemetry

---

gradle.properties

Upgrade dependencies version

---

plugins/management-console/src/main/java/ai/djl/serving/console/ConsoleRequestHandler.java
serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java
serving/src/main/java/ai/djl/serving/util/ConfigManager.java

[serving] Uses Engine.getDjlVersion() for consistency

---

serving/src/main/java/ai/djl/serving/util/NeuronUtils.java

[serving] Refactor NeuronUtils

---

.github/workflows/integration.yml
serving/docker/scripts/telemetry.sh
tests/integration/launch_container.sh
tests/integration/test_telemetry.sh

add telemetry collection testing

---

.github/workflows/llm_integration.yml
tests/integration/deepspeed/README.md
tests/integration/deepspeed/client.py
tests/integration/deepspeed/deepspeed-model.py
tests/integration/deepspeed/prepare.py

Add multi-gpu tests on the large model inference

[Docker][G5] add test artifacts

---

serving/docker/scripts/telemetry.sh
tests/integration/launch_container.sh

By default, IMDSV2 is not accessible from the network

fix the telemetry inaccessible issues

---

serving/docker/scripts/telemetry.sh

fall back to imds v1

---

.github/workflows/llm_integration.yml
engines/python/src/main/java/ai/djl/python/engine/PyModel.java
tests/integration/deepspeed/client.py
tests/integration/deepspeed/deepspeed-model.py
tests/integration/deepspeed/prepare.py
tests/integration/launch_container.sh

Applying patch fixes for G5 integration tests

G5 test patch fixes

---

.github/workflows/llm_integration.yml
engines/python/setup/djl_python/inputs.py
tests/integration/deepspeed/README.md
tests/integration/deepspeed/client.py
tests/integration/deepspeed/deepspeed-model.py
tests/integration/deepspeed/prepare.py
tests/test_client.py

[G5][Docker] add gptj model

---

.github/workflows/docker-nightly-publish.yml
.github/workflows/integration.yml
serving/docker/README.md
serving/docker/docker-compose.yml
serving/docker/pytorch-cu117.Dockerfile
serving/docker/scripts/pull_and_retag.sh
serving/docker/scripts/security_patch.sh
tests/integration/download_models.sh
tests/integration/launch_container.sh

Upgrade pytorch to cu117 and 1.13.0

[Docker] upgrade cu117

---

.github/workflows/llm_integration.yml
tests/integration/deepspeed/client.py
tests/integration/deepspeed/deepspeed-model.py
tests/integration/deepspeed/prepare.py

[Docker][G5] add bloom 7b1 support

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/pytorch-cu117.Dockerfile
serving/docker/pytorch-inf1.Dockerfile
serving/docker/scripts/telemetry.sh
tests/integration/test_telemetry.sh

update telemetry to follow DLC standard

---

.github/workflows/docker-nightly-publish.yml
serving/docker/docker-compose.yml
serving/docker/paddle-cu112.Dockerfile

[Docker] add paddlepaddle docker build script

---

serving/docker/docker-compose.yml

fix on the tag

---

tests/integration/test_telemetry.sh

Support case like 0.20.0~SNAPSHOT instead of 0.20.0

[Docker] fix regex

---

serving/docs/configurations.md

[docs] Update serving configurations document

---

.github/workflows/llm_integration.yml
engines/python/setup/djl_python/huggingface.py
serving/docker/pytorch-cu117.Dockerfile
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Add LLM huggingface handler tests

[Docker][G5] add huggingface tests

---

engines/python/setup/djl_python/huggingface.py
tests/integration/llm/client.py

[Handler] fix python grammer

---

serving/src/main/java/ai/djl/serving/ModelServer.java

[serving] Fixes tensor_parallel_degree parsing bug

---

serving/docker/scripts/telemetry.sh

Fix telemetry on instance ID logging and other info

fix telemetry

---

engines/python/setup/djl_python/huggingface.py

Fix a few bugs related to handler problems

fix mapping issues

---

engines/python/setup/djl_python/huggingface.py
tests/integration/llm/client.py
tests/integration/llm/prepare.py

[G5] final fixes

---

serving/src/main/java/ai/djl/serving/ModelServer.java

[serving] Support tensor_parallel_degree for commandline

---

.github/workflows/llm_integration.yml

Use default serve command to enable autoscaling

use default serve command

---

serving/docker/pytorch-inf1.Dockerfile
serving/docker/scripts/install_inferentia.sh

[Docker] upgrade inferentia docker image

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/deepspeed-model.py
tests/integration/llm/prepare.py

Unset min length for hf generation

[Docker] unset min length

---

serving/docker/scripts/install_inferentia.sh
tests/integration/download_models.sh

[Inf] update model

---

serving/src/main/java/ai/djl/serving/util/ConfigManager.java
serving/src/test/resources/config.properties

[serving] Remove unused setLoadOnDevice()

---

.github/workflows/integration.yml

fix on the test failure

---

tests/integration/llm/prepare.py

tFix handler usage on DeepSpeed tests

[DeepSpeed] fix handler usage

---

engines/python/setup/djl_python/deepspeed.py

[DeepSpeed] fix the get class error

---

engines/python/setup/djl_python/deepspeed.py
tests/integration/launch_container.sh

Support faster failing if container died

[CI] support faster failing

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Fix logging bucket problems, fix the worker checking on DeepSpeed

[Docker] fix a few things

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Add OPT 13B model to the test set

[Docker] add opt 13b option

---

engines/python/setup/djl_python/stable-diffusion.py
serving/docker/deepspeed.Dockerfile

Minor updates to handler and dockerfile to support stable diffusion with our customer wheel.
Tests will be added once we update the wheel in the docker file to point to the updated one with fixes.

Update SD handler to work with custom wheel

---

engines/python/src/test/resources/resnet18/model.py

[python] use jitscript model if available

---

serving/docker/aarch64.Dockerfile

[docker] Fixes aarch64 docker file

---

.github/workflows/llm_integration.yml

fix action test for stable-diffusion

---

tests/integration/llm/client.py

remove bracket

---

.github/workflows/llm_integration.yml

[ci] Avoid run integration test as root

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/deepspeed-model.py
tests/integration/llm/prepare.py
tests/test_binary.py
tests/test_client.py

[tests] Reformat python code

---

serving/docker/scripts/install_djl_serving.sh

Remove snakeyaml dependencies in past release

[Backport][Docker] backport snakeyaml disabling in last release

---

serving/docker/deepspeed.Dockerfile

Use patch-fixed 1.12.1 torch wheel

[Backport] use torch wheel that has patched fixes

---

engines/python/src/main/java/ai/djl/python/engine/PyModel.java

[Backport] backport SageMaker change to 0.20.0

---

engines/python/src/main/java/ai/djl/python/engine/PyModel.java

Use temp directory instead of /tmp path

[Backport] use temp directory

---

engines/python/src/main/java/ai/djl/python/engine/PyModel.java

Fix by using Java temp directory

use temp directory instead of /tmp

---

tests/integration/llm/deepspeed-model.py

Fix model_id understanding on the deespeed raw

[Backport] fix issue on model_id for deepspeed raw test

---

serving/docker/Dockerfile
serving/docker/scripts/install_djl_serving.sh

Remove tensorflow from Docker images to mitigate CVE issues

[Backport] remove all tensorflow in 0.19.0

---

.github/workflows/integration.yml

Remove tensorflow integration test since it is gone

[Backport] remove tensorflow tests

---

serving/docker/scripts/security_patch.sh

CRITICAL CVE reported by ECR scan https://ubuntu.com/security/notices/USN-5787-1

Patch CVE for libksba8

---

serving/docker/scripts/security_patch.sh

CRITICAL CVE reported by ECR scan https://ubuntu.com/security/notices/USN-5787-1

Patch CVE for libksba8 0.20.0-deepspeed

---

engines/java/src/main/java/ai/djl/java/engine/JavaEngine.java
engines/python/src/main/java/ai/djl/python/engine/PyEngine.java
engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
plugins/kserve/src/test/java/ai/djl/serving/kserve/KServeTensorTest.java

[engines] Update Engine implementation

---

benchmark/src/main/java/ai/djl/benchmark/AbstractBenchmark.java
benchmark/src/main/java/ai/djl/benchmark/Arguments.java
benchmark/src/main/java/ai/djl/benchmark/MultithreadedBenchmark.java
benchmark/src/main/java/ai/djl/benchmark/WlmBenchmark.java
engines/python/src/main/java/ai/djl/python/engine/CodecUtils.java
gradle/wrapper/gradle-wrapper.properties
plugins/kserve/src/main/java/ai/djl/serving/kserve/KServeRequestHandler.java
plugins/kserve/src/test/java/ai/djl/serving/kserve/KServeTensorTest.java
serving/src/main/java/ai/djl/serving/util/OpenSslKey.java

Upgrade gradle to 7.6 and fixes pmd issues

---

.github/workflows/docker-nightly-publish.yml
serving/docker/docker-compose.yml
serving/docker/fastertransformer.Dockerfile

Add FasterTransformer docker image. Use c6i instance for faster build from source.

[Docker] add faster transformer docker image

---

serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java

[serving] Rollback model if failed start work in synchronous mode

---

serving/docker/fastertransformer.Dockerfile

To copy all libraries to the system lib

[Docker] update faster transformer image

---

serving/src/main/java/ai/djl/serving/util/NettyUtils.java

[serving] Treat empty HTTP parameter as absent

---

plugins/management-console/webapp/src/view/Inference.vue

1. Add json/urlencoded/text/raw/form-data type support
2. Auto detect upload file content-type
3. Fix remove form-data bug

[console] Improves inference content-type handling

---

plugins/management-console/webapp/src/common/http.js
plugins/management-console/webapp/src/view/AddModel.vue
plugins/management-console/webapp/src/view/UpdateModel.vue

[console] Improves register model UI

---

plugins/management-console/webapp/src/view/Inference.vue

[console] Fixes inference UI bug

---

serving/docs/configuration.md
serving/docs/configurations.md

[docs] Updates serving configuration document

---

engines/python/setup/djl_python/deepspeed.py

[deepspeed] Fixed gpt-neox model name typo

---

engines/python/src/main/java/ai/djl/python/engine/PyModel.java

[python] Improves s5cmd error handling

---

tests/integration/llm/prepare.py

[test] Fixes prepare.py typo

---

serving/docker/fastertransformer.Dockerfile

Update the container to the latest version

update fastertransformer docker

---

serving/src/main/java/ai/djl/serving/util/ConfigManager.java

[serving] Fixes wrong onnx configuration

---

serving/build.gradle
serving/docs/console.md
serving/docs/modes.md
serving/src/test/java/ai/djl/serving/ModelServerTest.java
serving/src/test/resources/identity/serving.properties
wlm/src/main/java/ai/djl/serving/wlm/PermanentBatchAggregator.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java

[serving] Emits medel inference metrics to log file

---

plugins/management-console/webapp/src/view/AddModel.vue
plugins/management-console/webapp/src/view/UpdateModel.vue

[console] Fixes broken vue tags

---

engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
engines/python/src/test/resources/echo/serving.properties
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java

Set model status to failure after exceed retry threshold

---

plugins/management-console/webapp/src/view/AddModel.vue
plugins/management-console/webapp/src/view/UpdateModel.vue
serving/docs/management_api.md
serving/docs/workflows.md
serving/src/main/conf/config.properties
serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/http/DescribeWorkflowResponse.java
serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
serving/src/main/java/ai/djl/serving/util/ConfigManager.java
serving/src/main/java/ai/djl/serving/workflow/WorkflowDefinition.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
serving/src/test/java/ai/djl/serving/WorkflowTest.java
serving/src/test/resources/workflows/globalPerf.json
serving/src/test/resources/workflows/localPerf.json
wlm/src/main/java/ai/djl/serving/wlm/BatchAggregator.java
wlm/src/main/java/ai/djl/serving/wlm/Job.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
wlm/src/main/java/ai/djl/serving/wlm/PermanentBatchAggregator.java
wlm/src/main/java/ai/djl/serving/wlm/TemporaryBatchAggregator.java
wlm/src/main/java/ai/djl/serving/wlm/util/WlmConfigManager.java
wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java

[console] Adds unit suffixes to maxBatchDelay and maxIdelTime

---

engines/python/setup/djl_python/huggingface.py
tests/integration/llm/client.py

Kwargs after entering pipeline becomes:
```
{kwargs: {'device_map': 'auto'}, 'tokenizer':'xxx'}
```

[Handler] fix kwargs

---

plugins/management-console/webapp/src/view/UpdateModel.vue
serving/docs/management_api.md
serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerPool.java

[serving] Makes batch per model setting

---

serving/docker/fastertransformer.Dockerfile

Update fastertransformer to the latest cu117

[FT][Docker] update fastertransformer to cu117

---

serving/src/main/java/ai/djl/serving/ModelServer.java

[serving] Support model.pt and model.onnx file name

---

serving/docker/fastertransformer.Dockerfile
serving/docker/scripts/install_python.sh

Add python 3.9 since DLC by default install python 3.9

add python3.9 for fastertransformer

---

serving/docker/fastertransformer.Dockerfile
serving/docker/scripts/install_python.sh

Adding missing zlib and pythondev

[FT][Docker]add missing zlib deps

---

serving/docs/configurations.md
serving/docs/modes.md
serving/src/main/java/ai/djl/serving/ModelServer.java

[docs] Adds dynamic batching settings to document

---

plugins/management-console/webapp/src/view/UpdateModel.vue
serving/src/main/java/ai/djl/serving/http/DescribeWorkflowResponse.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerPool.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java

[serving] Keep failure worker status for 1 minutes

---

README.md
benchmark/README.md
benchmark/build.gradle
benchmark/snapcraft/snapcraft.yaml
benchmark/src/main/java/ai/djl/benchmark/Benchmark.java
engines/python/src/main/java/ai/djl/python/engine/DsEngineProvider.java
engines/python/src/main/resources/META-INF/services/ai.djl.engine.EngineProvider
plugins/management-console/webapp/src/view/Dependency.vue
serving/docs/configurations.md
serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java
serving/src/main/puml/architecture.puml
serving/src/test/java/ai/djl/serving/ModelServerTest.java

[serving] Adds FasterTransformer engine alias

---

serving/docker/fastertransformer.Dockerfile

Install ft wheel  and sentencepiece in container

Install ft wheel in container

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/fastertransformer-model.py
tests/integration/llm/prepare.py

Add an intial fastertransformer t5 integration test to test the workflow. Will add more tests after this.

Add fastertransformer t5 integration test

---

serving/src/main/java/ai/djl/serving/ModelServer.java

[serving] Support FasterFansformer to run in mpi mode

---

serving/docs/plugin_management.md

[docs] Improves plugin README

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/fastertransformer-model.py
tests/integration/llm/prepare.py

Add FT integration tests for gpt2, opt and bloom models

[FT][LLM tests]Add FT integration tests for gpt2, opt and bloom models

---

serving/docs/management_api.md

[docs] Fixes managment_api.md broken list

---

serving/src/main/java/ai/djl/serving/ModelServer.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Detects engine to avoid uncessarily download MXNet engine

---

.github/workflows/llm_integration.yml
tests/integration/llm/README.md
tests/integration/llm/client.py
tests/integration/llm/fastertransformer-model.py
tests/integration/llm/prepare.py

[LLM Integration] add flant5 model

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile
serving/docker/paddle-cu112.Dockerfile
serving/docker/pytorch-cu117.Dockerfile
serving/docker/pytorch-inf1.Dockerfile

[docker] Adds SageMaker mme lable

---

plugins/management-console/webapp/src/common/http.js
serving/src/main/java/ai/djl/serving/http/BadRequestException.java
serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/src/main/java/ai/djl/serving/http/LoadModelRequest.java
serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
serving/src/main/java/ai/djl/serving/models/ModelManager.java
serving/src/main/java/ai/djl/serving/util/NettyUtils.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java

[serving] Adds SageMaker MME support

---

tests/integration/llm/prepare.py

Switch the model to fp32 and gain performance + accuracy

switch to fp32

---

serving/docker/deepspeed.Dockerfile

fix pip install for ds wheel

---

tests/integration/llm/deepspeed-model.py

Update using the most recent loading mechanism

update to use tensor parallel

---

serving/docker/pytorch-cu117.Dockerfile

Update the version to match deepspeed container

update the transformer container versions

---

benchmark/README.md
benchmark/snapcraft/snapcraft.yaml

[djl-bench] Updates djl-bench version to 0.21.0

---

.github/workflows/llm_integration.yml
engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/stable-diffusion.py
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Support Stable Diffusion depth in the model server

adding stable diffusion depth model

---

tests/integration/llm/prepare.py

add fp16 check

---

serving/docs/configurations.md
serving/docs/modes.md
serving/src/main/java/ai/djl/serving/ModelServer.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Makes load_on_devices per model setting

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py

Fixing the current master pipeline

fix the bytesio location

---

serving/docs/modes.md
serving/src/main/java/ai/djl/serving/util/ConfigManager.java
serving/src/main/java/ai/djl/serving/util/NettyUtils.java
wlm/build.gradle
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
wlm/src/main/java/ai/djl/serving/wlm/util/WlmConfigManager.java
wlm/src/main/java/ai/djl/serving/wlm/util/WlmOutOfMemoryException.java
wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java

[serving] Check available memory before loading model

---

tests/integration/llm/client.py

bump up for T5 model memory

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Uses MemAvailable to check CPU memory

---

serving/docker/fastertransformer.Dockerfile

update fastertransformer build from source code

update the build code

---

serving/docker/scripts/pull_and_retag.sh

Add fastertransformer image in the sync list

add fastertransformer in sync list

---

tests/integration/launch_container.sh

[test] Use -u djl only for UID is 1000

---

.github/workflows/llm_integration.yml

The docker container scilent dead

fix test failure

---

tests/integration/launch_container.sh
tests/integration/llm/client.py

Apply more memory on T5-XXL model

add more memory for testing

---

build.gradle
engines/python/build.gradle
serving/docker/partition/partition.py
serving/docker/partition/properties_manager.py
serving/docker/partition/run_partition.py
tests/integration/llm/client.py
tests/integration/llm/deepspeed-model.py
tests/integration/llm/fastertransformer-model.py
tests/integration/llm/prepare.py

Reformat python source code

---

.github/workflows/llm_inf2_integration.yml

Adding a new workflow to test [transformers-neuronx](https://github.com/aws-neuron/transformers-neuronx) LLM on inf2
- If this change is a backward incompatible change, why must this change be made? N/A
- Interesting edge cases to note here N/A

Adding new workflow to test transformers-neuronx LLM on inf2

---

serving/docker/fastertransformer.Dockerfile

Add FT license file to root dir

Add FT license file to root dir

---

serving/docker/fastertransformer.Dockerfile
serving/docker/scripts/security_patch.sh

Adds security patching for fastertransformer image on DLC branch

Add security patching for fastertransformers image

---

serving/src/main/conf/log4j2.xml
serving/src/main/resources/log4j2.xml

[serving] Adds color hightlight for console logging

---

.github/workflows/llm_inf2_integration.yml
serving/docker/pytorch-inf2.Dockerfile
tests/integration/download_models.sh

[docker] Adds java support for inf2

---

serving/docker/fastertransformer.Dockerfile
serving/docker/partition/partition.py
serving/docker/partition/properties_manager.py
serving/docker/partition/utils.py

sample model.py for FT
```
import os
import fastertransformer
import torch
import logging
import sys
from djl_python import Input
from djl_python import Output
def get_model(properties):
model_name = properties.get('model_id') or properties.get('model_dir')
tensor_parallel = properties.get('tensor_parallel_degree')
pipeline_parallel = properties.get('pipeline_paralell_degree', 1)
dtype = properties.get('dtype')
return fastertransformer.init_inference(model_name, tensor_parallel, pipeline_parallel, dtype)
def partition(inputs: Input):
properties = inputs.get_properties()
model_name = properties.get('model_id') or properties.get('model_dir')
tensor_parallel = properties.get('tensor_parallel_degree')
pipeline_parallel = properties.get('pipeline_paralell_degree', 1)
save_mp_checkpoint_path = …
```

FT AOT support

---

engines/python/setup/djl_python/fastertransformer.py

Add fastertramsformer default handler
Tested locally by passing as model.py

Add fastertramsformer default handler

---

build.gradle
engines/python/setup/djl_python/fastertransformer.py
serving/docker/partition/partition.py
serving/docker/partition/properties_manager.py

[python] Format python code

---

engines/python/setup/djl_python/np_util.py
engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
engines/python/src/test/resources/resnet18/processing.py

[python] Adds hybrid pre/post process unit test

---

engines/python/setup/djl_python/transformer-neuronx.py
engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
engines/python/src/main/java/ai/djl/python/engine/PyModel.java
engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
serving/docker/scripts/install_inferentia2.sh

add Inferentia2 handler

---

serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/util/NeuronUtils.java

Add Inf2 autoscaling for LLM models

add neuron auto-scaling

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

Bypass NC core allocation for INf2 instance

bypass nc core allocation

---

serving/docs/plugin_management.md

Plugins readme fix

---

.github/workflows/llm_inf2_integration.yml
engines/python/setup/djl_python/transformer-neuronx.py
tests/integration/launch_container.sh
tests/integration/llm/client.py
tests/integration/llm/prepare.py

add inf2 handler test

---

.github/workflows/llm_integration.yml
serving/docker/partition/partition.py
serving/docker/partition/properties_manager.py

https://pypi.org/project/dummy_test/#files

Bugfix requirements.txt download

---

.github/workflows/llm_integration.yml
tests/integration/llm/fastertransformer-model.py
tests/integration/llm/prepare.py

ft raw aot test

---

engines/python/setup/djl_python/fastertransformer.py
engines/python/setup/djl_python/transformer-neuronx.py
engines/python/src/main/java/ai/djl/python/engine/Connection.java
serving/src/main/java/ai/djl/serving/util/NeuronUtils.java
serving/src/test/java/ai/djl/serving/NeuronUtilsTest.java
tests/integration/llm/prepare.py

auto-scale by neuron cores

---

serving/src/main/java/ai/djl/serving/util/NeuronUtils.java
serving/src/test/java/ai/djl/serving/util/NeuronUtilsTest.java
serving/src/test/java/ai/djl/serving/util/package-info.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[inf2] Cache inferentia instance type and add unit test back

---

serving/src/main/java/ai/djl/serving/util/NeuronUtils.java

[inf2] Fixes NeuronUtils.getNeuronCores() bug

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[inf2] Should not pass neuron device to PyTorch engine

---

tests/integration/llm/client.py

change the worker to 3

---

engines/python/setup/djl_python/transformer-neuronx.py

Use batch encoding with padding for this case.
Tested on inf2.48xlarge

fix encoding for inf2

---

serving/docker/scripts/pull_and_retag.sh

add pytorch inf2

---

.github/workflows/docker-nightly-publish.yml

Bring more time for copying container

[Sync] give extra timeout time

---

gradle.properties

Upgrade version to 0.22.0

---

benchmark/build.gradle
serving/build.gradle

[ci] Upgrades gradle to 8.0.2

---

benchmark/build.gradle
gradle/wrapper/gradle-wrapper.properties
plugins/kserve/build.gradle
plugins/management-console/build.gradle
plugins/plugin-management-plugin/build.gradle
serving/build.gradle

[ci] Uses recommended way to create task in build.gradle

---

.github/workflows/nightly-docker-ecr-sync.yml

give ecr sync more time

---

.github/workflows/llm_integration.yml

[ci[ Clean up models directory after integration tests

---

engines/python/setup/djl_python/transformers-neuronx.py

add pad token if not set

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Add ft handler tests. 
Testing: ran workflow here https://github.com/deepjavalibrary/djl-serving/actions/runs/4389136546/jobs/7686414699

Add ft handler tests

---

.github/workflows/llm_integration.yml
engines/python/setup/djl_python/fastertransformer.py
serving/docker/partition/utils.py
tests/integration/llm/prepare.py

AOT support in FT default handler and test cases. Constructed a new FT docker image with a local debian and tested the test cases in EC2.

AOT Support in FT default handler and test cases

---

serving/docs/modes.md

[docs] Fix serving doc

---

serving/build.gradle

Include Kserve plugins to distribution

---

engines/python/setup/djl_python/outputs.py
engines/python/setup/djl_python_engine.py
engines/python/src/main/java/ai/djl/python/engine/Connection.java
engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
engines/python/src/test/resources/echo/model.py
plugins/kserve/src/main/java/ai/djl/serving/kserve/KServeRequestHandler.java
serving/src/main/java/ai/djl/serving/ServerInitializer.java
serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/src/main/java/ai/djl/serving/util/NettyUtils.java
tests/integration/llm/prepare.py

[serving] Adds chunked encoding support

---

.github/workflows/llm_integration.yml

[Fix] Kill docker process in actions post test

---

engines/python/src/test/resources/echo/model.py

[python] Fixes typo in unit test

---

serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/workflow/WorkflowDefinition.java

Load external dependencies for workflows

---

.github/workflows/llm_integration.yml

[CI/CD]Clean up models dir on-fail step

---

engines/python/src/main/java/ai/djl/python/engine/PyModel.java

[python] Passing arguments to model.py

---

wlm/src/main/java/ai/djl/serving/wlm/WorkerPool.java

[serving] Fixes GPU auto scaling bug

---

serving/docker/pytorch-cu117.Dockerfile

update pytorch docker to py3.9

update pytorch docker to py3.9

---

engines/python/src/main/java/ai/djl/python/engine/PyModel.java
engines/python/src/test/resources/huggingface/serving.properties

[python] Infer default entryPoint if not provided

---

engines/python/setup/djl_python/outputs.py
engines/python/setup/djl_python/tests/test_input_output.py
engines/python/setup/djl_python_engine.py

Add finalize function for Output object to callback

add finalize callback function

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Detect triton engine

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Add HF and DeepSpeed streaming integration tests.

Add HF and DeepSpeed streaming integration tests

---

serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/util/NeuronUtils.java
serving/src/test/java/ai/djl/serving/util/NeuronUtilsTest.java

[serving] Fixes NeuronUtils for SageMaker

---

serving/src/test/java/ai/djl/serving/translator/EchoTranslator.java

[serving] Fixes test compile error due to merge conflict

---

engines/python/src/main/java/ai/djl/python/engine/PyProcess.java

[python] Fixes python startup race condition

---

serving/docker/partition/properties_manager.py

Add default handler for AOT

---

serving/docker/pytorch-inf2.Dockerfile

Use a tagged version other than always upstream

use transformer neuronx tag

---

tests/integration/llm/client.py

Fixes response json format to be backwards compatible for text-generation use case in the default handlers.

Update client in llm tests for updated response format

---

engines/python/src/main/java/ai/djl/python/engine/Connection.java

[python] Fixes visible neuron cores environment variable

---

benchmark/src/main/java/ai/djl/benchmark/WlmBenchmark.java
serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
serving/src/main/java/ai/djl/serving/models/ModelManager.java
serving/src/main/java/ai/djl/serving/util/ConfigManager.java
serving/src/main/java/ai/djl/serving/workflow/WorkflowDefinition.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
serving/src/test/java/ai/djl/serving/WorkflowTest.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerPool.java
wlm/src/main/java/ai/djl/serving/wlm/util/WlmConfigManager.java
wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java
wlm/src/test/java/ai/djl/serving/wlm/WorkLoadManagerTest.java

[serving] Refactor per model configuration initialization

---

engines/python/src/main/java/ai/djl/python/engine/PyModel.java
serving/src/main/java/ai/djl/serving/http/DescribeWorkflowResponse.java
serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java
serving/src/main/java/ai/djl/serving/models/ModelManager.java
serving/src/main/java/ai/djl/serving/workflow/Workflow.java
serving/src/main/java/ai/djl/serving/workflow/WorkflowDefinition.java
serving/src/main/java/ai/djl/serving/workflow/function/ModelWorkflowFunction.java
wlm/src/main/java/ai/djl/serving/wlm/BatchAggregator.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java
wlm/src/test/java/ai/djl/serving/wlm/ModelInfoTest.java

- [serving] Refactor per model configuration initialization
- [serving] Avoid download from s3 multiple time

[serving] Avoid download from s3 multiple time

---

serving/docker/deepspeed.Dockerfile

Updating DeepSpeed wheel to latest

[ci] bump up deepspeed version

---

gradle.properties
serving/build.gradle
serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java

[serving] Avoid compile time dependency on log4j

---

engines/python/setup/djl_python/deepspeed.py

This PR covers 2 things:
- Support text2text-generation task in the DeepSpeed default handler
- Remove restriction on model type. With DeepSpeed's new AutoTP functionality, models that do not support kernel injection can be used with the injection policy being determined by DeepSpeed at runtime. What this means for us is we can support many more model types without having to determine and hard code the injection policy for all model types. See https://www.deepspeed.ai/tutorials/automatic-tensor-parallelism/ for more details.
Tested this on g5.12xl with flant5-xxl model using tp2
Below is a comparison between accelerate and deepspeed for this model. 4 requests with batch sizes (1,2,4,8):
```
DeepSpeed
Time for inference with batch size 1 is 3.2054641246795654s
Time for inference with batch …
```

Support text2text-generation task in deepspeed

---

serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile

install git in all published container

install git in 0.21.0 dlc

---

serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java
serving/src/main/java/ai/djl/serving/util/MutableClassLoader.java
serving/src/main/java/ai/djl/serving/workflow/WorkflowDefinition.java

[serving] Adds deps folder to classpath in MutableClassLoader constructor

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/fastertransformer.py
tests/integration/llm/client.py

Unified the the handler experience

update fastertransformer to follow huggingface parameters

---

plugins/cache/src/main/java/ai/djl/serving/ddbcache/DdbCacheEngine.java

Change billing model to pay per request

---

.github/workflows/docker-nightly-publish.yml
.github/workflows/llm_integration.yml
serving/docker/docker-compose.yml
serving/docker/fastertransformer.Dockerfile
serving/docker/pytorch-cu117.Dockerfile
serving/docker/scripts/install_aitemplate.sh
serving/docker/scripts/install_python.sh
serving/docker/scripts/pull_and_retag.sh

remove transfromers default build. User should use DeepSpeed/FasterTransformer image instead (200mb diff).

clean up docker build script and remove transformers docker image build

---

engines/python/setup/djl_python/fastertransformer.py

The GPT model pipeline_generate output has one more redundant []. Fix in this PR

make output consistent

---

serving/docker/partition/partition.py
serving/docker/partition/properties_manager.py
serving/docker/partition/utils.py

[AOT] Upload sharded checkpoints to S3

---

README.md
benchmark/README.md
benchmark/snapcraft/snapcraft.yaml
engines/python/README.md
serving/docker/README.md
serving/src/test/java/ai/djl/serving/plugins/DependencyManagerTest.java
wlm/README.md

[serving] Upgrade to DJL 0.22.0

---

tests/integration/llm/client.py

fix memory format in fastertransformer test

[CI] fix the memory format

---

.github/workflows/llm_integration.yml

- Started using tempfile directory to download files from S3 to local directory in docker (https://docs.python.org/3/library/tempfile.html#tempfile.mkdtemp). This changes the directory name in the verify str for FT. Fixed the CI grep string in this PR.

[CI] Fix FT verify string for partitions

---

benchmark/snapcraft/snapcraft.yaml
gradle.properties
serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile
serving/docker/pytorch-cu117.Dockerfile
serving/docker/pytorch-inf1.Dockerfile
serving/docker/pytorch-inf2.Dockerfile

[serving] Update DJL version to 0.22.1

---

serving/docker/deepspeed.Dockerfile

Update DeepSpeed default dependencies version

[Docker] update a few versions

---

serving/docker/deepspeed.Dockerfile

downgrade diffuser

---

serving/docker/partition/partition.py
serving/docker/partition/properties_manager.py
serving/docker/partition/utils.py

[AOT] Entrypoint download from url

---

.github/workflows/docker-nightly-publish.yml
.github/workflows/integration.yml
serving/docker/README.md
serving/docker/docker-compose.yml
serving/docker/fastertransformer.Dockerfile
serving/docker/pytorch-cu118.Dockerfile
serving/docker/scripts/pull_and_retag.sh
serving/docker/scripts/security_patch.sh
tests/integration/download_models.sh
tests/integration/launch_container.sh

Upgrade everything to pytorch 2.0 and cu118

[Docker] upgrade to pytorch 2.0 and cu118

---

engines/python/setup/djl_python/streaming_utils.py

1. Fixes incorrect results issue for gpt models(more generally for models where pad token is set to eos token) for inputs with unequal sequence length. If pad token and eos token are the same, attention_mask should be set to 1 for padded tokens according to [link](https://github.com/huggingface/transformers/blob/fe1f5a639d93c9272856c670cff3b0e1a10d5b2b/src/transformers/generation/utils.py#L606-L612).
2. Added a check to validate supported models architectures

[python][streaming]Batching fix and validate model architecture

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/huggingface.py

skip special tokens by default

---

serving/docker/deepspeed.Dockerfile

Upgrade transformers to 4.28.1 with LLAMA model

fix a few version bugs

---

plugins/cache/src/main/java/ai/djl/serving/ddbcache/DdbCacheEngine.java
plugins/cache/src/test/java/ai/djl/serving/ddbcache/DdbCacheEngineTest.java
serving/docker/Dockerfile
serving/src/main/java/ai/djl/serving/cache/MemoryCacheEngine.java
serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/src/main/java/ai/djl/serving/http/RequestParser.java
serving/src/main/java/ai/djl/serving/util/NettyUtils.java

[serving] Read x-synchronus and x-starting-token from input payload

---

serving/docker/pytorch-cu118.Dockerfile

fix torch vision version mismatch

add torchvision

---

serving/docker/deepspeed.Dockerfile

Downgrade huggingface to its eariler version

downgrade huggingface

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/inputs.py
serving/src/main/java/ai/djl/serving/http/RequestParser.java

[serving] Keep original content-type header

---

.github/workflows/llm_inf2_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Add inf2 integration test for streaming.
Test log - https://github.com/deepjavalibrary/djl-serving/actions/runs/4737750171/jobs/8410900025

Add inf2 streaming integration test

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Override inferred options in criteria

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/transformers-neuronx.py

Correctly handle enable streaming property
Tested locally.

Correctly handle enable streaming property

---

serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/plugins/FolderScanPluginManager.java

[serving] Stop modle server if plugin init failed

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py

Add HuggingFace no code model tests

add no code model tests

---

engines/python/setup/djl_python/streaming_utils.py

Do best effort model type validation to fix configs without arch list, for e.g cerebras gpt

[python][streaming]Do best effort model type validation to fix configs without arch list

---

.github/workflows/llm_integration.yml
serving/src/main/java/ai/djl/serving/models/ModelManager.java

[serving] Fixes huggingface integration test

---

serving/src/main/java/ai/djl/serving/util/NettyUtils.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
serving/src/test/java/ai/djl/serving/translator/EchoTranslator.java
serving/src/test/resources/echo/serving.properties
wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerPool.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerState.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java

[wlm] Throttles request if all workers are busy

---

serving/docs/streaming_config.md

Add a doc to use streaming in djl-serving

[docs] Adds streaming configuration document

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/inputs.py
engines/python/setup/djl_python/streaming_utils.py
serving/docker/partition/partition.py
tests/integration/llm/client.py

fixes the issue in the client tests with gpu mem mismatch.
formats python code.

fix client tests and format python code

---

engines/python/src/main/java/ai/djl/python/engine/PyEnv.java

[python] prints out error message if pip install failed

---

gradle.properties
serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile
serving/docker/pytorch-cu118.Dockerfile
serving/docker/pytorch-inf1.Dockerfile
serving/docker/pytorch-inf2.Dockerfile

update to djl 0.23.0

---

plugins/kserve/src/main/java/ai/djl/serving/kserve/KServeTensor.java
plugins/kserve/src/test/java/ai/djl/serving/kserve/KServeTensorTest.java

[kserve] Fixes unit test for extra data type

---

serving/docker/pytorch-inf2.Dockerfile

install fixed version for transformers and accelerate

---

.github/workflows/llm_inf2_integration.yml
.github/workflows/llm_integration.yml

Add numpy in the requests library

add numpy fix

---

.github/workflows/llm_integration.yml
serving/docker/dockerd-entrypoint.sh
serving/docker/partition/partition.py
serving/docker/partition/properties_manager.py
tests/integration/launch_container.sh
tests/integration/llm/client.py
tests/integration/llm/prepare.py

[0.22.1 dlc] Merge the AOT Sagemaker changes and test cases

---

serving/docker/pytorch-inf2.Dockerfile
serving/docker/scripts/install_inferentia2.sh

Cherrypicking the commit to 0.22.1

[INF2][DLC][CherryPick 681] Update Neuron to 2.10 (#681)

---

.github/workflows/llm_inf2_integration.yml
engines/python/setup/djl_python/stable_diffusion_inf2.py
engines/python/setup/djl_python/transformers-neuronx.py
serving/docker/pytorch-inf2.Dockerfile
tests/integration/llm/client.py
tests/integration/llm/prepare.py
tests/integration/lmic_test_builder.py

Add SD 2.1 support on INF2 inference

add stable diffusion support on INF2

---

.github/workflows/llm_inf2_integration.yml

[CI] add small fixes

---

.github/workflows/docker-publish-hf.yml
.github/workflows/hf_tgi_integration.yml

Add HuggingFace TGI docker build pipeline
DLC PR: https://github.com/aws/deep-learning-containers/pull/2910

Add HuggingFace TGI publish and test pipeline

---

serving/docker/README.md

Add shared memory arg to docker launch command in README

---

.github/workflows/docker-publish-hf.yml

Update github-slug-action to v4.4.1

---

.github/workflows/llm_integration.yml
tests/integration/llm/prepare.py

Change the bucket for different object

---

plugins/cache/src/main/java/ai/djl/serving/ddbcache/DdbCacheEngine.java
serving/src/main/java/ai/djl/serving/cache/MemoryCacheEngine.java

[api] Update ChunkedBytesSupplier API

---

plugins/management-console/src/main/java/ai/djl/serving/console/ConsoleRequestHandler.java

Fixes: https://github.com/deepjavalibrary/djl/issues/2589

[console] Fixes log file charset issue

---

.github/workflows/llm_inf2_integration.yml
engines/python/setup/djl_python/streaming_utils.py
engines/python/setup/djl_python/transformers-neuronx.py
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Add NeuonX new features for token generation

add neuronx new feature for generation

---

engines/python/setup/djl_python/stable_diffusion_inf2.py

Back port this feature to 0.21.1

[Cherry pick] adding clip model support

---

engines/python/setup/djl_python/stable_diffusion_inf2.py

CLIP model now is supported by INF2

[INF2] adding clip model support

---

plugins/cache/build.gradle
plugins/cache/src/main/java/ai/djl/serving/ddbcache/DdbCachePlugin.java
serving/src/main/java/ai/djl/serving/ModelServer.java

[plugin] Include djl s3 extension in djl-serving distribution

---

.github/workflows/llm_inf2_integration.yml
engines/python/setup/djl_python/stable_diffusion_inf2.py
tests/integration/llm/prepare.py

Add BF16 support for the model

[cherry-pick] add bf16 support (#700)

---

serving/src/main/java/ai/djl/serving/ModelServer.java
serving/src/main/java/ai/djl/serving/TempLocalRepositoryFactory.java

[serving] Workaround LocalRepository detection issue

---

engines/python/setup/djl_python/streaming_utils.py

Add support for streaming Seq2Seq models. Tested with t5 large model.

Add support for streaming Seq2Seq models

---

.github/workflows/llm_integration.yml
engines/python/src/main/java/ai/djl/python/engine/Connection.java
tests/integration/llm/client.py

fix the device mapping issue if visible devices is set

---

tests/integration/llm/client.py
tests/integration/llm/prepare.py

Make the test to produce more memory rooms

[INF2] give better room for more tokens

---

tests/integration/llm/prepare.py

minor fix to bump up n positions

bump up n positions

---

serving/src/main/java/ai/djl/serving/workflow/WorkflowDefinition.java
serving/src/main/java/ai/djl/serving/workflow/function/FunctionsApply.java
serving/src/test/resources/workflows/basic.json
serving/src/test/resources/workflows/local/serving.properties
serving/src/test/resources/workflows/localPerf.json
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[workflow] Support load model from workflow directory

---

engines/python/setup/djl_python/huggingface.py

Add support for se2seq model loading in HF handler. Currently it only supports `AutoModelForCausalLM` for non-pipeline path.

Add support for se2seq model loading in HF handler

---

serving/src/test/java/ai/djl/serving/ModelServerTest.java
serving/src/test/resources/emptyStore.config.properties

Adds unit test for initializing all models from empty model store.

Add unit test for empty model store initialization

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py

Fixes the LLM workflow tests on no code use-case: https://github.com/deepjavalibrary/djl-serving/actions/runs/4985774337

Fix no code tests in lmi test suite

---

engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/transformers-neuronx.py
tests/integration/llm/client.py
tests/integration/llm/prepare.py

[test] Reformat python code

---

engines/python/setup/djl_python/transformers-neuronx.py
tests/integration/llm/client.py

[test] Refactor client.py

---

.github/workflows/docker-nightly-publish.yml
serving/docker/fastertransformer.Dockerfile

Update fastertransformers to consume from S3

update fastertransformers build instruction

---

tests/integration/llm/prepare.py

[test] Update tranformser-neuxornx gpt-j-b mode options

---

engines/python/src/main/java/ai/djl/python/engine/PyEnv.java

[python] Support pip install in offline mode

---

engines/python/src/main/java/ai/djl/python/engine/PyEnv.java

[python] Add --no-index to pip install in offline mode

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/huggingface.py
serving/docker/fastertransformer.Dockerfile

Add LLAMA compatible changes support.
fix #677

adding llama model support

---

serving/docker/fastertransformer.Dockerfile

Update fastertransformers dependencies

[FT] change the dependencies so

---

serving/docker/fastertransformer.Dockerfile

[docker] Uses the same convention as tritonserver

---

engines/python/setup/djl_python/fastertransformer.py

[python] Fixes typo in fastertransformer handler

---

engines/python/setup/djl_python/encode_decode.py

[python] Adds text/plain content-type support

---

serving/src/test/java/ai/djl/serving/ModelServerTest.java

[serving] Avoid unit-test hang

---

engines/python/setup/djl_python/scheduler/batch.py
engines/python/setup/djl_python/scheduler/contrastive_batch.py
engines/python/setup/djl_python/scheduler/contrastive_seq_batch_scheduler.py
engines/python/setup/djl_python/scheduler/search_config.py
engines/python/setup/djl_python/scheduler/seq_batch_scheduler.py
engines/python/setup/djl_python/scheduler/seq_batcher.py

These are the skeleton classes for the scheduler. @KexinFeng and I will create the subsequent PR implementing this functions along with their unit test cases.

Skeleton structure for sequence batch scheduler

---

engines/python/setup/djl_python_engine.py
engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
engines/python/src/test/java/ai/djl/python/engine/DsEngineTest.java
engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
serving/src/main/java/ai/djl/serving/util/NettyUtils.java

[python] Handle torch.cuda.OutOfMemoryError

---

engines/python/src/main/java/ai/djl/python/engine/PyModel.java
serving/src/main/java/ai/djl/serving/util/ConfigManager.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerPool.java

[serving] Improves model loading logging

---

plugins/cache/src/main/java/ai/djl/serving/cache/DdbCacheEngine.java

[cache] Rename evn var DDB_TABLE_NAME to SERVING_DDB_TABLE_NAME

---

serving/src/main/java/ai/djl/serving/models/ModelManager.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerPool.java
wlm/src/main/java/ai/djl/serving/wlm/util/WlmConfigManager.java

[serving] Sets default minWorkers to 1 for GPU python model

---

.github/workflows/sagemaker-integration.yml
tests/integration/llm/sagemaker-endpoint-tests.py

Adding Sagemaker AOT integration tests. 
Will add pythia-12b test in a separate PR. HF download failed in my local test, so will upload the file to s3 and specify s3 uri in model_id.

SM AOT Tests

---

serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile

Pin bitsandbytes version to 0.38.1

[docker] Pin bitsandbytes version to 0.38.1

---

serving/docker/fastertransformer.Dockerfile

[fix] Fix bitsandbytes pip install

---

wlm/src/main/java/ai/djl/serving/wlm/WorkerPool.java

[serving] Fixes log message

---

serving/docker/fastertransformer.Dockerfile

Add triton wheel to the commits

add triton components in the nightly

---

wlm/src/main/java/ai/djl/serving/wlm/LmiUtils.java

[wlm] Adds more logs to LMI engine detection

---

serving/src/main/java/ai/djl/serving/ModelServer.java

1. Load HF model even alrady downloaded
2. Use random name to avoid conflict
3. Avoid use hash as model name

[serving] Uses predictable model name for HF model

---

serving/src/main/java/ai/djl/serving/models/ModelManager.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Adds parallel loading support for Python engine

---

plugins/management-console/webapp/src/view/Inference.vue

[console] file are not required in form data

---

engines/python/setup/djl_python/encode_decode.py
engines/python/setup/djl_python/huggingface.py

[python] Support non-gpu models for huggingface

---

.github/workflows/llm_integration.yml

Option to run only the lmi tests needed

---

engines/python/setup/djl_python/np_util.py

Remove hardcoded version in Assertion error

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/np_util.py
engines/python/setup/djl_python/streaming_utils.py
engines/python/setup/djl_python/transformers-neuronx.py
engines/python/setup/djl_python_engine.py

[python] Add application/jsonlines as content-type for streaming

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/huggingface.py

[python] Fixes trust_remote_code issue

---

serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile

Support einops for Falcon models

ad einops for supporting falcon models

---

tests/integration/llm/client.py
tests/integration/llm/prepare.py

Add stream generation on batch 2

fix the stream generation

---

engines/python/setup/djl_python/transformers-neuronx.py

[python] Fixes typo in transformers-neuronx.py

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/fastertransformer.py
engines/python/setup/djl_python/streaming_utils.py

[python] Adds content-type response for DeepSpeed and FasterTransformer handler

---

engines/python/setup/djl_python/huggingface.py
engines/python/src/main/java/ai/djl/python/engine/Connection.java

[python] Fixes device id mismatch issue for mutlple GPU case

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/streaming_utils.py
engines/python/setup/djl_python/transformers-neuronx.py

Use huggingface streamer for inputs

add stream generation for huggingface streamer

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/streaming_utils.py
engines/python/setup/djl_python/transformers-neuronx.py

[python] Fixes device mismatch issue for streaming token

---

serving/docker/deepspeed.Dockerfile

Add 0.22.1 changes for DeepSpeed container

[Backport] backport with version upgrade on 0.22.1

---

serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile
serving/docker/pytorch-inf2.Dockerfile

Install safetensors to support this format

add safetensors

---

serving/docker/deepspeed.Dockerfile

Upgrade DeepSpeed to the latest 0.9.2

upgrade deepspeed

---

engines/python/setup/djl_python/deepspeed.py

Fix input_data and device order for streaming. This should fix:
https://github.com/deepjavalibrary/djl-serving/actions/runs/5190145348/jobs/9356247259#step:14:34

Fix input_data and device order for streaming

---

engines/python/setup/djl_python/huggingface.py

When device map is set, user shoudl not set device for a pipeline.

fix huggingface device bugs

---

engines/python/setup/djl_python/huggingface.py

[HF] typo fix

---

serving/docs/management_api.md

[docs] Updates management api document

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/streaming_utils.py

[python] Fixes invlid device issue

---

wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java

[wlm] Fixes WorkerThread name

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/fastertransformer-model.py
tests/integration/llm/prepare.py

Update FasterTransformer GPU memory expectation

update gpu memory consumption and adding GPTNeoX, GPTJ

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/streaming_utils.py

[python] Fixes streaming token device mismatch bug

---

serving/docker/partition/properties_manager.py

[partition] Improves partition error message

---

engines/python/build.gradle
engines/python/src/main/java/ai/djl/python/engine/PyEnv.java

[python] Extract .py files recursively

---

engines/python/setup/djl_python/outputs.py

return self after addition

---

.github/workflows/llm_integration.yml
tests/integration/llm/prepare.py

[CI] Remove duplicated tests for AOT

---

.github/workflows/llm_integration.yml

The job stuck at job not found issue

fix workflow

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py

[CI] Fix Remove models in step

---

serving/docker/partition/properties_manager.py

[partition] Adding back S3Url for backward compatibility in pysdk

---

engines/python/setup/djl_python/transformers-neuronx.py
serving/docker/pytorch-inf2.Dockerfile
serving/docker/scripts/install_inferentia2.sh

Add neuronx 2.11.0 support

---

engines/python/setup/djl_python/scheduler/search_config.py
engines/python/setup/djl_python/scheduler/seq_batch_scheduler.py
engines/python/setup/djl_python/scheduler/seq_batcher.py
engines/python/setup/djl_python/scheduler/seq_batcher_impl.py
engines/python/setup/djl_python/scheduler/step_generation.py
engines/python/setup/djl_python/tests/efficiency_benchmark.py
engines/python/setup/djl_python/tests/test_scheduler.py

Sampling seqBatcher design

---

engines/python/setup/djl_python/scheduler/seq_batch_scheduler.py
engines/python/setup/djl_python/scheduler/seq_batcher.py
engines/python/setup/djl_python/scheduler/seq_batcher_impl.py
engines/python/setup/djl_python/scheduler/step_generation.py

Max_seqbatcher_number_threshold_api

---

serving/docker/fastertransformer.Dockerfile
serving/docker/pytorch-inf2.Dockerfile

Update FT and TNX containers to add pinned protobuf dependency for llama support

[docker] add protobuf to FT and TNX

---

engines/python/setup/djl_python/deepspeed.py
engines/python/src/main/java/ai/djl/python/engine/PyModel.java
engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java
engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
engines/python/src/test/resources/rolling_batch/model.py
engines/python/src/test/resources/rolling_batch/serving.properties

[python] Adds rolling batch support

---

engines/python/setup/djl_python/scheduler/search_config.py
engines/python/setup/djl_python/scheduler/seq_batch_scheduler.py
engines/python/setup/djl_python/scheduler/seq_batcher.py
engines/python/setup/djl_python/tests/efficiency_benchmark.py
engines/python/setup/djl_python/tests/test_scheduler.py

This succeeds the previous PR #841

Max new length

---

engines/python/setup/djl_python/scheduler/seq_batch_scheduler.py

fix the type of max_seq_len

---

engines/python/setup/djl_python/huggingface.py

fix T5 model not support INT8 issue on handler

---

serving/docker/scripts/install_djl_serving.sh

Update netty for cve

---

engines/python/setup/djl_python/scheduler/seq_batch_scheduler.py
engines/python/setup/djl_python/scheduler/seq_batcher.py
engines/python/setup/djl_python/scheduler/seq_batcher_impl.py
engines/python/setup/djl_python/scheduler/utils.py
engines/python/setup/djl_python/tests/test_scheduler.py

Compute kv cache utility function

---

.github/workflows/rolling_batch_integration.yml
engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
tests/integration/llm/prepare.py
tests/integration/rb_client.py

Rolling batch integration tests

---

engines/python/setup/djl_python/fastertransformer.py
engines/python/setup/djl_python/huggingface.py
serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile

add 4 bits loading for huggingface

add 4 bits loading

---

.github/workflows/lmi_dist_integration.yml
serving/docker/deepspeed.Dockerfile

Add LMI Distribute library testing pipeline

add lmi dist tests pipeline

---

.github/workflows/lmi_dist_integration.yml

add workflow dispatch

---

.github/workflows/lmi_dist_integration.yml

Install the latest nightly wheel for testing

[LMI Dist] install the latest nightly wheel

---

.github/workflows/lmi_dist_integration.yml
serving/docker/deepspeed.Dockerfile
serving/docker/scripts/install_flash_attn.sh

add flash attention installation and a few bug fixing

---

.github/workflows/docker-nightly-publish.yml

make DeepSpeed build in CPU runner to run faster

add deepspeed cpu build in the pipeline

---

serving/src/test/java/ai/djl/serving/ModelServerTest.java

1. Fixes cu118 test case failure for MXNet
2. Fixes multi-GPU throttle test case failure

[serving] Fixes unittest in multi-GPU case

---

.github/workflows/lmi_dist_integration.yml
tests/integration/llm/client.py

Fix a few pipeline issues

---

.github/workflows/docker-nightly-publish.yml
engines/python/setup/djl_python/huggingface.py
serving/docker/scripts/install_flash_attn.sh

Extend the time for DeepSpeed container building

[CI] give longer time for building DeepSpeed container

---

engines/python/setup/djl_python/huggingface.py
engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java

Non streaming for rolling batch

---

engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py

Fix Kwargs in AutoConfig

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[wlm] Fixes MPI engine workers detection

---

engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

Fix lmi-dist batch handling

---

engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java
engines/python/src/test/resources/rolling_batch/model.py

[python] Increase default max_rolling_batch_size to 32

---

engines/python/src/main/java/ai/djl/python/engine/Connection.java
engines/python/src/main/java/ai/djl/python/engine/PyProcess.java

[python] Allows mpi model load multiple times on the same GPU

---

engines/python/setup/djl_python/scheduler/seq_batch_scheduler.py
engines/python/setup/djl_python/scheduler/seq_batcher.py
engines/python/setup/djl_python/scheduler/seq_batcher_impl.py
engines/python/setup/djl_python/scheduler/step_generation.py
engines/python/setup/djl_python/scheduler/utils.py
engines/python/setup/djl_python/tests/test_scheduler.py

1. Using torch.multinomial function to pick from topK samples and added fixed torch seed.
2. Reformatted the file. 
3. Ran the unit test with no problems.

Uses multinomial to choose from topK samples and improve topP sampling

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/fastertransformer.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
engines/python/setup/djl_python/tests/test_scheduler_bloom.py
engines/python/setup/djl_python/transformers-neuronx.py
tests/integration/rb_client.py

Reformat python code

---

tests/integration/llm/prepare.py

Fix rolling batch type

---

engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java
engines/python/src/test/resources/echo/model.py
engines/python/src/test/resources/oom/model.py
engines/python/src/test/resources/oom/serving.properties

Add oom unit tests for load and invoke

Add oom unit tests for load and invoke

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

[python] Use lmi-dist api to get batch class

---

.github/workflows/rolling_batch_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Add integration test for lmi-dist AutoModel

---

engines/python/setup/djl_python/streaming_utils.py

Fix skip_special_tokens flag

---

engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java

This reverts commit cfb23d85f6423fbd4d7dd93d9b9358fdad9e494f.

Revert "Non streaming for rolling batch (#881)"

---

serving/docker/fastertransformer.Dockerfile

Upgrade FT container on HF versions

[FasterTransformer] upgrade fastertransfomers HF versions

---

engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java

Assign random seed for lmi dist

---

.github/workflows/rolling_batch_integration.yml
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/rolling_batch/rolling_batch.py
tests/integration/llm/client.py

[python] JSON format for rolling batch

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py

[python] Fixes rolling batch error handling case

---

.github/workflows/lmic_performance.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py
tests/integration/profiles/bloom_7b1.json
tests/integration/profiles/gpt_j_6b.json
tests/integration/profiles/gpt_neox_20b.json
tests/integration/profiles/llama_13b.json

Add open-llama-13b to performance testing, and update the performance pipeline. Lowered the test counts to 10, and removed p99 as it loses meaning on lower number of tests.

[ci/cd] Add llama to performance testing

---

engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java

[python] A temporary workaround for rolling batch

---

engines/python/setup/djl_python/huggingface.py

[python] Fixes huggingface logging bug

---

engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java
wlm/src/main/java/ai/djl/serving/wlm/BatchAggregator.java

[serving] Adds batch size metric

---

serving/docs/out_of_memory_management.md

OOM management doc

---

tests/integration/llm/client.py
tests/integration/llm/prepare.py

Brief description of what this PR is about:
Changes to lmi dist integ test. Tested locally with `prepare.py` and `client.py`

lmi_dist model tests updates

---

.github/workflows/rolling_batch_integration.yml
tests/integration/llm/prepare.py

Adding gpt-neox-20b-quantized to workflow

---

serving/docs/configuration.md
serving/docs/modes.md

[docs] Updates model configuration document

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

1. seed should be positive
2. default parameters should be None

[python] Fix repeated output for rolling batch

---

engines/python/setup/djl_python/scheduler/seq_batch_scheduler.py
engines/python/setup/djl_python/tests/test_scheduler.py

[Fix] bug_fix_for_empty_tensor_input

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py

[python] Fixes logging bug

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

[python] Add null check for prefill batch

---

serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile

Updating bitsandbytes to latest on ft and ds docker images.

[docker] bump bitsandbytes versions

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/scheduler/seq_batch_scheduler.py

[python] Send error message in json format

---

serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile

upgrade based on the bitsandbytes

bump up bitsandbytes on its fixes

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Add lora tests for fastertransformer

---

serving/docs/configurations.md

[docs] Adds s5cmd feature in document

---

engines/python/setup/djl_python/huggingface.py

fix some boolean kwargs and bug in load_in_4_bit

Fix boolean kwargs and typo in load_in_4_bit assignment

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

Support revision on huggingface models

add revision as part of the model inputs

---

tests/integration/llm/prepare.py

Add Falcon 7B model test with revision

add revision in test

---

serving/src/main/java/ai/djl/serving/ModelServer.java

Add revision check for the model id

add model revision environment variable

---

serving/docs/configurations.md

[docs] Adds document about venv per model

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/huggingface.py

Fix some issues with remote code for lora

---

README.md
benchmark/README.md
engines/python/README.md
serving/docker/README.md
wlm/README.md

Update docs to djl 0.23.0

---

serving/docker/deepspeed.Dockerfile

[docker] [0.23.0-dlc] Update release version and wheels

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

[0.23.0-dlc] [cherrypick] Allow overriding truncate parameter in request (#953)

---

tests/integration/llm/sagemaker-endpoint-tests.py

Add support for testing candidate release images in sagemaker tests

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[wlm] Allows set defatul options with environment variable

---

benchmark/snapcraft/snapcraft.yaml

[serving] Update djlbench snapcraft version to 0.23.0

---

engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
engines/python/src/main/java/ai/djl/python/engine/PyModel.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

Enable MPI model by environment variable

---

engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java

Add built-in json formatter

---

serving/docs/modes.md

[docs] Update rolling batch document

---

.github/workflows/llm_inf2_integration.yml
engines/python/setup/djl_python/transformers-neuronx.py
serving/docker/pytorch-inf2.Dockerfile
tests/integration/launch_container.sh
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Handler update to add in ability to use GPT-NeoX models, and experimentally use Llama models. Can currently be run when building from source on the github master, but there are errors in GPT-NeoX which will be resolved for 2.12 release.

[serving] Update tnx handler for 2.12 supported models

---

serving/docker/pytorch-inf2.Dockerfile
tests/integration/llm/client.py

[fix] TNX add use_sample for llama, freeze docker DJL version

---

.github/workflows/llm_inf2_integration.yml

[ci] Use smaller instance for inf2 bloom test

---

engines/python/setup/djl_python/transformers-neuronx.py
serving/docker/scripts/install_inferentia2.sh
tests/integration/llm/sagemaker-endpoint-tests.py

Bump version in inf2 install script for docker, and run python formatter

[docker] Update install inf2 script dependencies

---

engines/python/setup/djl_python/transformers-neuronx.py
serving/docker/scripts/install_inferentia2.sh
tests/integration/llm/client.py
tests/integration/llm/prepare.py

[docker] Update install inf2 script dependencies (#976)

---

gradle.properties

Bump up DJL version to 0.24.0

---

serving/src/main/java/ai/djl/serving/util/ConfigManager.java

[serving] Print out CUDA and Neuron device information

---

engines/python/src/main/java/ai/djl/python/engine/Connection.java

This can prevent mpi sub process kill each other

[python] Clean up dangling process in java

---

serving/src/main/conf/log4j2-console.xml
serving/src/main/conf/log4j2-plain.xml

[serving] Fixes console log configuration

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

[python] Refactor lmi_dist rolling batch

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py

[python] Fixes json output formatter

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile
serving/docker/pytorch-cu118.Dockerfile
serving/docker/pytorch-inf2.Dockerfile

[docker] Upgrade to DJL 0.24.0

---

tests/integration/llm/prepare.py

Set jsonlines formatter for lmi-dist rolling batch test

---

tests/integration/llm/prepare.py

Fix the rolling batch integration test

---

serving/docker/fastertransformer.Dockerfile

* Install FasterTransformer libs with llama support in FT docker
* Install dependency pip packages - `bfloat16` and `tiktoken`

Install FasterTransformer libs with llama support

---

engines/python/setup/djl_python/fastertransformer.py

Add trust_remote_code to ft handler

---

engines/python/src/main/java/ai/djl/python/engine/PyModel.java
engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java
serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
wlm/src/main/java/ai/djl/serving/wlm/WorkLoadManager.java

[serving] Improves PyProcess lifecycle logging

---

engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java

[python] Adds pid to python process log

---

engines/python/setup/djl_python/fastertransformer.py

Was looking at the code and this seemed like a bug as were are not updating offset for each item in the batch.

Fix batch offset computation in FT handler

---

engines/python/setup/djl_python/inputs.py
engines/python/src/main/java/ai/djl/python/engine/PyPredictor.java
engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java

[python] Includes individual headers for server side batching

---

serving/docs/modes.md

[docs] Updates rolling batch document

---

serving/src/main/java/ai/djl/serving/plugins/DependencyManager.java

[serving] Install commong-loggings dependency for XGBoost engine

---

engines/python/setup/djl_python/inputs.py

[python] Fixes batch header key issue

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/inputs.py
engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py
engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java

RollingBatch error handling and reset from Java and Python

add error handling for rolling batch

---

.github/workflows/integration.yml
serving/docker/deepspeed.Dockerfile

Test fix for integration tests for previously released containers.

[ci] fix djl_bench snapshot dep and pydantic version mismatch

---

serving/src/main/conf/log4j2-access.xml
serving/src/main/conf/log4j2-plain.xml

[serving] Allows print access log to console

---

engines/python/setup/djl_python/inputs.py

fix the error typing

---

serving/src/main/java/ai/djl/serving/models/ModelManager.java

[serving] Adds unregister model log

---

engines/python/setup/djl_python/huggingface.py
engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java
serving/src/main/java/ai/djl/serving/http/InferenceRequestHandler.java
serving/src/main/java/ai/djl/serving/util/NettyUtils.java

[serving] Return proper HTTP status code for each batch

---

engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py

Fix VLLM inference bug
```
engine=Python
option.model_id=openlm-research/open_llama_7b
option.trust_remote_code=true
option.tensor_parallel_degree=2
option.rolling_batch=vllm
```

fix vllm inference error

---

plugins/cache/README.md
plugins/cache/src/main/java/ai/djl/serving/cache/S3CacheEngine.java
plugins/kserve/README.md
plugins/management-console/README.md
plugins/plugin-management-plugin/README.md
plugins/static-file-plugin/README.md
serving/docs/cache.md
serving/docs/plugin_management.md
serving/docs/streaming.md
serving/docs/streaming_config.md

This adds docs for the use of streaming. It also makes some updates to the plugin docs.

Adds streaming docs

---

engines/python/src/main/java/ai/djl/python/engine/PyEnv.java
engines/python/src/main/java/ai/djl/python/engine/PyModel.java

Allows set TENSOR_PARALLEL_DEGREE=max

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py

Fix the error and reset handling

add some fix to the error messages

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Add FT llama integration test.
Test run - https://github.com/deepjavalibrary/djl-serving/actions/runs/5942084769/job/16114358047

Add FT llama integration test

---

benchmark/build.gradle
gradle/wrapper/gradle-wrapper.properties
serving/build.gradle

[ci] Upgrades gradle to 8.3

---

benchmark/src/main/java/ai/djl/benchmark/NDListGenerator.java
benchmark/src/test/java/ai/djl/benchmark/NDListGeneratorTest.java
engines/python/src/test/java/ai/djl/python/engine/PyEngineTest.java

[benchmark] Adds safetensors support

---

.github/workflows/rolling_batch_integration.yml
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Add two new tests for MPT and StarCoder

add mpt and starcoder tests

---

serving/docs/configurations.md

[docs] Updates TENSOR_PARALLEL_DEGREE description

---

engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py

fix logging bug in vllm

---

engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py

Use serious logic to ensure all result are captured

[VLLM] use more complex logic to ensure all result are captured

---

engines/python/setup/djl_python/huggingface.py

[python] Fixes tokenizer bug when using hugging pipeline

---

engines/python/src/main/java/ai/djl/python/engine/Connection.java
engines/python/src/main/java/ai/djl/python/engine/PyModel.java
engines/python/src/main/java/ai/djl/python/engine/PyProcess.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

Fixes OOM checker bug

---

serving/docs/configurations.md

[docs] Document Python engine alias

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile
serving/docker/pytorch-cu118.Dockerfile
serving/docker/pytorch-inf2.Dockerfile

Adding labels with djl version in them for sagemaker telemetry.

[docker] add version labels for sagemaker

---

engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py

Add options to set batched tokens

[VLLM] add option to set batched tokens

---

engines/python/setup/djl_python/rolling_batch/rolling_batch.py
engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
engines/python/setup/djl_python/tests/run_rolling_batch_alone.py

Standalone script to test rolling batch

[rollingbatch] add standalone script to run

---

engines/python/setup/djl_python/transformers-neuronx.py
serving/docker/pytorch-inf2.Dockerfile
serving/docker/scripts/install_inferentia2.sh

Upgrade Neuron dependencies to 2.13.1 with compiler optimization

update inf2 dependencies to 2.13.1

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

Change rolling batch generations order

---

serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile

Upgrade HuggingFace dependencies for the container

[DeepSpeed] upgrade dependencies

---

serving/docker/pytorch-inf2.Dockerfile

[docker] Upgrades to inf2 2.13.2 version

---

engines/python/src/main/java/ai/djl/python/engine/RollingBatch.java

Apply fixes to 0.23.0 on rolling batch

[Cherrypick 0.23.0][python] Avoid holding the lock while running inference (#1045)

---

engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py

cherry pick a few vLLM bug fixes and stuff.

[0.23.0 cherry pick] #1034 #1035 #1036 #1041 vLLM changes

---

engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/transformers-neuronx.py

add revision checker for config in handler

add revision to handler

---

engines/python/setup/djl_python/transformers-neuronx.py

prevent looking for revision and remote code checker for saved local files

[INF2] disable checker for saved model

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

Upgrade lmi_dist

---

tools/conf/pmd.xml

[ci] Fixes PMD warning

---

serving/src/main/java/ai/djl/serving/models/ModelManager.java

[serving] Make sure extracting jni from jar file in deps folder

---

build.gradle
serving/build.gradle

[ci] Fixes gradle deprecation warnings

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Fixes wrong device mapping for non-tp mode

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

Reverts deepjavalibrary/djl-serving#1060

Revert "Upgrade lmi_dist"

---

.github/workflows/rolling_batch_integration.yml

[CherryPick] use tag for test and not hardcode

---

.github/workflows/rolling_batch_integration.yml

CI bug fixes for rolling batch

[RollingBatch][CI] use tag for test and not hardcode

---

engines/python/setup/djl_python/streaming_utils.py

The current device mapping have some issues. With the update from Transformer, they had a strict check of input data device

[Handler] fix device mapping issues

---

engines/python/setup/djl_python/stable_diffusion_inf2.py
serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile
serving/docker/pytorch-cu118.Dockerfile
serving/docker/pytorch-inf2.Dockerfile

[docker] Change default OMP_NUM_THREADS back to 1 for GPU

---

.github/workflows/rolling_batch_integration.yml
tests/integration/launch_container.sh
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Add VLLM tests for rolling batch

[CI] add vllm tests

---

engines/python/setup/djl_python/stable_diffusion_inf2.py
engines/python/setup/djl_python/transformers-neuronx.py
tests/integration/llm/client.py

[Handler] add dynamic batching to transformers neuronx

---

serving/src/main/conf/log4j2-access.xml
serving/src/main/conf/log4j2-console.xml
serving/src/main/conf/log4j2-plain.xml
serving/src/main/conf/log4j2.xml

[serving] Fixes log rotation issue

---

engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
engines/python/setup/djl_python/transformers_neuronx.py
serving/docker/pytorch-inf2.Dockerfile
tests/integration/launch_container.sh

allow `max_new_tokens` to be used on vLLM. Also changed a few Neuron behavior for compilation

[handler] fix a few issues

---

engines/python/setup/djl_python/transformers_neuronx.py
serving/docker/pytorch-inf2.Dockerfile
serving/docker/scripts/install_inferentia2.sh

[Neuron] upgrade to Neuron 2.14.0 SDK

---

serving/docker/pytorch-inf2.Dockerfile
tests/integration/llm/prepare.py

grant write permission to the folder

[INF2] grant write permission

---

tests/integration/llm/prepare.py

[vLLM] add pyarrow dependency

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/huggingface.py

Formalize DeepSpeed model inputs

[Handler] formalize all engines with same settings

---

.github/workflows/rolling_batch_integration.yml

Add no code CI testing on RollingBatch

add no code testing for rollingbatch

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/optimum_neuron_scheduler.py
engines/python/setup/djl_python/transformers_neuronx_scheduler/token_selector.py
serving/docker/partition/utils.py
serving/docker/pytorch-inf2.Dockerfile

Fix several bugs in huggingface and deepspeed handler. This should fix the CI issues

fix some bugs in handler

---

engines/python/setup/djl_python/huggingface.py

Add unmerged lora support in HF handler. Handler expects extra `adapters` parameter to be passed to it.
E.g request: 
```
curl -X POST http://127.0.0.1:8080/invocations \
-H "Content-Type: application/json" \
-H "X-Amzn-SageMaker-Target-Model: base-1.tar.gz" \
-d '{"inputs": ["How is the weather"], "adapters": ["adapter_1"], "parameters": {"max_new_tokens": 25}}'
```
Added two new functions which can be called to load and unload adapters
1. register_adapter
2. unregister_adapter

Add unmerged lora support in HF handler

---

engines/python/setup/djl_python/huggingface.py

I incorrectly set adapter arg outside of the if loop.

Fix setting adapters arg

---

engines/python/src/main/java/ai/djl/python/engine/PyProcess.java

Small cleanup following #1095.

Cleans some unused pieces of PyProcess

---

engines/python/src/test/resources/adaptecho/adapters/myBuiltinAdapter/adapter.txt
serving/src/main/java/ai/djl/serving/http/AdapterManagementRequestHandler.java
serving/src/main/java/ai/djl/serving/workflow/function/AdapterWorkflowFunction.java
serving/src/test/java/ai/djl/serving/ModelServerTest.java
wlm/src/main/java/ai/djl/serving/wlm/Adapter.java
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java
wlm/src/main/java/ai/djl/serving/wlm/WorkerThread.java

This enables support for automatically adding a directory of adapters. It will
be read on the first load and utilize the existing registration flow.

Creates adapters by directory

---

serving/docker/pytorch-inf2.Dockerfile

[CI] fix the inf2 container build failure

---

serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile

Use custom peft wheel to support unmerged lora inference.

Use custom peft wheel

---

engines/python/setup/djl_python/deepspeed.py
engines/python/setup/djl_python_engine.py

fix deepspeed bugs and have better logging

---

engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py

Bug fix on the integer parsing

[vLLM] capture max_rolling_batch settting issues

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py
tests/integration/llm/unmerged_lora.py

This correctness test uses a custom model.py file that does:
* This test tests peft apis for loading and deleting adapters.
* It also generates unmerged lora result and merged result for the same input. The results are logged to the console. The results are almost same except for minor differences at one or two words.
outputs from unmerged lora: 
`
'Below is an instruction that describes a task. Write a response that appropriately completes the \n request.### Instruction: Tell me about Alpacas ### Response: Alpacas are small, cute animals that are native to South America. They are related to camels and llamas, and are known for their soft, luxurious fleece. Alpacas are raised for their fleece, which is used to make clothing and other products.'
`
outputs from merged lora: 
`
'Below is an …

Unmerged lora correctness test

---

engines/python/setup/djl_python/transformers_neuronx.py

Add -O1 optimization flag per Neuron instructions

[INF2][Handler] added optimization level per Neuron instruction

---

engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
engines/python/setup/djl_python/transformers_neuronx.py
tests/integration/llm/client.py
tests/integration/llm/prepare.py
tests/integration/llm/unmerged_lora.py

Add INT8 quantization for Neuron, also fix the optimzation level with recent SDK release

[Handler] add neuron int8 quantization

---

engines/python/setup/djl_python/transformers_neuronx.py

[INF2][Handler] fix none type check

---

engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py
serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile
serving/docker/pytorch-inf2.Dockerfile

Upgrade dependencies version to latest

[Docker] upgrade dependencies version

---

.github/workflows/llm_integration.yml

Add dependency on stop-runners for lora correctness test

---

engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py
tests/integration/llm/prepare.py

[Handler] bump up vllm version and fix some bugs

---

serving/docker/scripts/install_inferentia2.sh

Remove header installation in INF2

[Backport][0.22.1][INF2] remove header installation

---

serving/docker/scripts/install_inferentia2.sh

Remove header installation in INF2

[Backport][0.23.0] remove INF2 header installation

---

.github/workflows/rolling_batch_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Add rolling batch gptq integration test

---

.github/workflows/docker-nightly-publish.yml

CPU space is not enough for 0.22.1 build

[0.22.1][DeepSpeed] make deepspeed run on cpu runner

---

engines/python/setup/djl_python/rolling_batch/vllm_rolling_batch.py

Support AWQ quantization on vLLM

[vLLM][Handler] add quantization option for vLLM

---

engines/python/setup/djl_python/transformers_neuronx.py

Remove all type conversion since it is handled by neuron model loading script.

[INF2][Handler] remove type conversion in Neuron

---

tests/integration/llm/prepare.py

Add extra timeout time for neuron solution

[CI][Neuron] add extra timeout time for gpt neox

---

tests/integration/launch_container.sh

Let INF2 instance sleep longer than GPU

[CI] allow inf2 instance to sleep longer

---

.github/workflows/llm_inf2_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Switch the model to smaller pythia 2.8b

[INF2][CI] switch the model to pythia

---

.github/workflows/instant_benchmark.yml
tests/integration/instant_benchmark.py

Add instant benchmark support for DJLServing. More detail coming soon

Instant benchmark

---

serving/src/test/java/ai/djl/serving/ModelServerTest.java
serving/src/test/resources/zoomodel/serving.properties
wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Allow model_id point to djl model zoo

---

README.md
benchmark/README.md
engines/python/README.md
serving/docker/Dockerfile
serving/docker/README.md
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile
serving/docker/pytorch-cu118.Dockerfile
serving/docker/pytorch-inf2.Dockerfile
wlm/README.md

Updates docs and docker files (release version and wheels) for 0.24.0 release

[0.24.0 branch] Release 0.24.0 changes

---

.github/workflows/instant_benchmark.yml
tests/integration/instant_benchmark.py

Start testing and see if everything works, stay tuned!

Instance Benchmark Rev2

---

engines/python/setup/djl_python/deepspeed.py

[feat] Modify deepspeed handler to support smoothQuant.

---

tests/integration/instant_benchmark.py

Remove EOF or emptylines in the file

[IB] remove empty lines

---

engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py

Disable circular import for handler

[Handler] disable circular import

---

engines/python/setup/djl_python/deepspeed.py

Add error message for quantization when using checkpoint loading.

Add error message for quantization when using checkpoint loading.

---

serving/docker/deepspeed.Dockerfile

Update vllm wheel name

---

serving/docker/deepspeed.Dockerfile
tests/integration/llm/prepare.py

Installing official vLLM into container

installing official vLLM into container

---

.github/workflows/llm_integration.yml
serving/docker/deepspeed.Dockerfile
tests/integration/launch_container.sh
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Adding smoothquant integ tests

---

engines/python/setup/djl_python/huggingface.py
engines/python/setup/djl_python/rolling_batch/scheduler_rolling_batch.py

The dependencies installation has issues

[Handler] disable flash attention as default as of now

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Adding llama2 w/ SmoothQuant ci test
CI test: https://github.com/deepjavalibrary/djl-serving/actions/runs/6461571512

Adding llama2 w/ SmoothQuant ci test

---

.github/workflows/docker-nightly-publish.yml

Giving extra disk space for building

[Docker] free disk space for docker build

---

engines/python/setup/djl_python/transformers_neuronx.py

Allow max rolling batch to be set on Neuron

[INF2] add neuron batch size default and support rolling batch configs

---

engines/python/setup/djl_python/huggingface.py

Enable auto on the following models

[LMI][Handler] add more model support coverage

---

.github/workflows/llm_integration.yml
tests/integration/llm/client.py
tests/integration/llm/prepare.py

Change CI testing to use standard llama

[CI] change xgen to standard llama model

---

engines/python/setup/djl_python/huggingface.py

[bugfix] parsing waiting steps to integer

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[bug fix] add entrypoint camel case recovery

---

tests/integration/llm/prepare.py
tests/integration/lmic_test_builder.py
tests/integration/profiles/gpt_j_6b.json
tests/integration/profiles/gpt_neox_20b.json
tests/integration/profiles/llama_13b.json

Added benchmark for smoothquant
Tested on ec2 instance.

Add CI performance test for deepspeed smoothquant.

---

engines/python/setup/djl_python/transformers_neuronx.py
tests/integration/llm/client.py

This will be useful for efficient bucket selection

Add context length estimate for Neuron handler

---

engines/python/setup/djl_python/transformers_neuronx.py

Allow low CPU memory loading of split model directly

[INF2] allow neuron to load split model directly

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

Fix lmi_dist garbage output issue

---

engines/python/setup/djl_python/rolling_batch/lmi_dist_rolling_batch.py

Backports https://github.com/deepjavalibrary/djl-serving/pull/1187 to 0.24.0

[0.24.0] Fix lmi_dist garbage output issue

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

Identify max in the memory checking section

add memory checking in place to identify max

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[Cherrypick][0.24.0] add memory checking in place to identify max (#1191)

---

wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java

[serving] Auto detect XGBoost engine with .xgb extension

---

serving/docs/adapters.md
serving/docs/adapters_api.md
serving/docs/management_api.md

Adds documentation for adapters

---

serving/docker/Dockerfile
serving/docker/aarch64.Dockerfile
serving/docker/deepspeed.Dockerfile
serving/docker/fastertransformer.Dockerfile
serving/docker/pytorch-cu118.Dockerfile
serving/docker/pytorch-inf2.Dockerfile

Update the container labels to match the current version of DJL.

[telemetry] update nightly containers label to djl 0.25.0

---

.github/workflows/llm_optimization_integration.yml

Test run: https://github.com/deepjavalibrary/djl-serving/actions/runs/6579107619/job/17874407446

Check logs for aiccl usage in integ test

---

build.gradle
engines/python/build.gradle

[ci] Fixes missing publish tasks

---

serving/src/main/java/ai/djl/serving/workflow/function/WlmWorkflowFunction.java

[serving] Fixes large concurrent clients performance issue

---

serving/src/main/java/ai/djl/serving/http/AdapterManagementRequestHandler.java
serving/src/main/java/ai/djl/serving/http/ManagementRequestHandler.java

[serving] Revert management URI matching regex
